### ISSUE TITLE
Unhandled exceptions while using elastic-apm-node

### ISSUE THREAD

**Issue by mohit3081989** [elastic/apm-agent-nodejs#1007]
**Describe the bug**
Since I have started using elastic-apm-node, it has started throwing unhandled errors which is causing unnecessary alerts and node process to crash, error is  :
```
SyntaxError: Value expected to be an array/object but is not
     at JSON.parse (<anonymous>)
     at ServerResponse.res.end (/usr/src/app/node_modules/swagger-express-validator/index.js:147:20)
     at write (/usr/src/app/node_modules/finalhandler/index.js:297:9)
     at send (/usr/src/app/node_modules/finalhandler/index.js:301:5)
     at Immediate.<anonymous> (/usr/src/app/node_modules/finalhandler/index.js:133:5)
     at Immediate.<anonymous> (/usr/src/app/node_modules/elastic-apm-node/lib/instrumentation/modules/finalhandler.js:24:20)
     at Immediate.<anonymous> (/usr/src/app/node_modules/express/lib/router/index.js:635:15)
     at Shim.applySegment (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:1387:20)
     at Immediate.wrapper [as _onImmediate] (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:2022:17)
     at runCallback (timers.js:796:20)
     at tryOnImmediate (timers.js:752:5)
     at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**To Reproduce**
1. Use this config 
node : 8.9.0
elastic-apm-node : 2.9.0
apm-server : 6.5.1
```
export ELASTIC_APM_ENABLED=true
export ELASTIC_APM_SERVER_URL="http://elastic-search-apm.urbanclap.infra:8200"
export ELASTIC_APM_SERVICE_NAME="$SERVICE_ID-$ENV"
export ELASTIC_APM_ASYNC_HOOKS=false 
export ELASTIC_APM_CAPTURE_BODY="off"
export ELASTIC_APM_TRANSACTION_SAMPLE_RATE=0.1
export ELASTIC_APM_CAPTURE_EXCEPTIONS=false
export ELASTIC_APM_CAPTURE_ERROR_LOG_STACK_TRACES="never"
export ELASTIC_APM_CAPTURE_SPAN_STACK_TRACES=false
export ELASTIC_APM_SOURCE_LINES_SPAN_APP_FRAMES=0
export ELASTIC_APM_SOURCE_LINES_SPAN_LIBRARY_FRAMES=0
export ELASTIC_APM_SOURCE_LINES_ERROR_APP_FRAMES=0
export ELASTIC_APM_SOURCE_LINES_ERROR_LIBRARY_FRAMES=0
export ELASTIC_APM_ERROR_MESSAGE_MAX_LENGTH="1kb"
export ELASTIC_APM_STACK_TRACE_LIMIT=0
export ELASTIC_APM_TRANSACTION_MAX_SPANS=100
export ELASTIC_APM_API_REQUEST_TIME="10s"
export ELASTIC_APM_API_REQUEST_SIZE="768kb"
export ELASTIC_APM_METRICS_INTERVAL="30s"
```

**Expected behavior**
There should not be any unhandled exceptions thrown from the library to the service using it. 

**Environment (please complete the following information)**
- OS: [ubuntu: 16.04]
- Node.js version:  8.9.0
- APM Server version: 2.9.0
- Agent version: 6.5.1

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by Qard** [comment]
From the stack trace, it looks like you're using it together with the New Relic agent, which is not recommended. It can interfere with our instrumentation, causing problems like this. Have you tried running without the New Relic agent?

**Comment by mohit3081989** [comment]
Hi Stephen,

We didn't try with newrelic disabled. We run newrelic on production and we
just wanted to try how elastic-apm works as well. Why is it the case that
newrelic is causing elastic-apm library to throw these errors ? Could you
please explain a bit more about this?

We haven't faced this problem with all the production microservices, it's
working all fine for others on which we took it live. So, I am bit
suspicious that newrelic could be the reason for it.

FYI, all of my microservices use exactly same framework for using newrelic
and elastic-apm.

Thanks,

**Comment by Qard** [comment]
We both patch similar functions and if any are patched not-quite-right, it _may_ cause the other agent to not recognize what it is trying to patch. Unfortunately JavaScript does not currently have a way to achieve instrumentation without potentially observable side effects. This can sometimes result in situations like this where unexpected behavior occurs. We try as much as possible to code defensively, checking everything is as we expect before doing anything and trying not to interfere with each other but both agents are in active development so it's a bit of a moving target. For this reason, most APM vendors recommend not to run their agent together with other agents.

Generally the types of errors that sneak through are very, very edge-case things that only surface in very specific scenarios that are easy to miss. In this particular case, it appears that `swagger-express-validator` is _also_ patching the `res.end(...)` method, but is _expecting_ to receive a data argument, even though it's supposed to be optional. I'm not sure if the code leading into it actually received that data and dropped it somewhere, but the `finalhandler` instrumentation in our agent should definitely be passing that through, if it received it.

**Comment by watson** [comment]
@mohit3081989 could you share a code example of how you're using `swagger-express-validator`? That way we might be able to reproduce it

**Comment by shashanksah** [comment]
Hi Watson,
I am from Mohit's team. Below is the code for swagger:
`var validator = require('swagger-express-validator');
var expandSchemaRef = require('expand-swagger-refs').expanded;

validator({
  schema: expandSchemaRef(schema),
  validateRequest: true,
  validateResponse: true,
  requestValidationFn: function(req, data, errors) {
    let logData = {…};
    Logger.error(logData);
    throw new UCError({ err_message: errors.map(function(e) {return `${e.dataPath} ${e.message}`}).join(",") });
  },
  responseValidationFn: function(req, data, errors) {
    let logData = {…};
    Logger.error(logData);
    throw new UCError({ err_message: errors.map(function(e) {return `${e.dataPath} ${e.message}`}).join(",") });
  }
})`

Thanks,
Shashank

**Comment by shashanksah** [comment]
Hi @watson ,
When migrating one of our service to elastic APM after switching off new relic, we were still getting this error. So, new relic does not seems to be causing this issue. We are currently using version 2.9.0, Is there any fix which went after this which can resolve this issue?
This is a big blocker for our launch, any help will be great.

Thanks

**Comment by shashanksah** [comment]
With the current debugging I have the following information:
1) This issue is occurring when there is an error thrown by the service.
2) If elastic APM is disabled, then the error is handled by the below function:
    app.use(method_url, function(err, req, res, next) {
      res.status(500).json({ err_type: ERROR_TYPE,
        err_message: ERROR_MESSAGE });
    });
3) If elastic APM is enabled, then the above function does not receives any call, instead an error is being thrown by swagger-express-validator. This error is thrown because it tries to JSON parse the below html code:
<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>[object Object]</pre>\n</body>\n</html>\n
4) I upgraded our elastic APM version to 2.11.5 and swagger version in our openapi repo to 1.0.0 from 0.0.9 . Now I am not getting this error, but the response of the API call has been changed to the HTML code mentioned in point 3.

**Comment by watson** [comment]
I think I finally managed to track down the issue. It doesn't seem to be related to your swagger packages - at least I was able to reproduce it without using those.

I'm hoping to land #1111 soon which fixes it.

That being said, the swagger middleware you use does seem to be changing the internals of the HTTP request objects in a very significant and potentially hazardous way. So I can't rule out that the package will not mess with our ability to instrument your application in some way, potentially making it incompatible with the Node.js agent.

**Comment by shashanksah** [comment]
Hi Watson,

Thanks for the info. But question still remains the same, why we didn't face any issue when instrumentation was done by NewRelic. We have been using NewRelic for long time but it never cause internal crash of server.
Also can you elaborate a bit on :
> the swagger middleware you use does seem to be changing the internals of the HTTP request objects in a very significant and potentially hazardous way

And

> I can't rule out that the package will not mess with our ability to instrument your application in some way, potentially making it incompatible with the Node.js agent.

What's the potential problem you see we have with Swagger middleware we are using ?

**Comment by watson** [comment]
> But question still remains the same, why we didn't face any issue when instrumentation was done by NewRelic. We have been using NewRelic for long time but it never cause internal crash of server.

The issue I found was not the crash, but the wrong return value you described in [bullet no 4 above](https://github.com/elastic/apm-agent-nodejs/issues/1007#issuecomment-498353430), once you had upgraded to v2.11.5. This issue only occurred if setting `captureExceptions: false` while also providing a custom Express error handler, and was unique to our agent. As far as I understood, after upgrading to this version the crash went away, right?

I'd still like to discover the source of the crash but just haven't been able to reproduce it yet.

Regarding the swagger module, I'll let my colleague @Qard jump in with more details as he spent quite a long time reading its source code last week while I was focused on reproducing the bug.

**Comment by watson** [comment]
For me to be able to reproduce the crash in v2.9.0, it would help a lot if you could share an example app that crashes as you described.

Alternatively, If it's not possible for you to reproduce it in an example app, I need the following in order to build one my self:

- Your `package-lock.json`
- Your Express routing file(s), so I can see exactly the order in which the swagger validator is loaded together with your normal error handler, etc
- Your swagger schema used by the validator
- A `curl` command that fails reliably with the given swagger schema

**Comment by watson** [comment]
We've fixed the bug with the wrong return value that was discussed above in version 2.15.6 that was just released.

If the crash still happens please reply with the information listed in https://github.com/elastic/apm-agent-nodejs/issues/1007#issuecomment-498590766 and I'll re-open this issue
