### ISSUE TITLE
Rename uncaught to handled

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#101]
The meaning of the `uncaught` property on errors should be flipped and renamed to `handled`. This is more programming language neutral.

**Comment by Qard** [comment]
Not sure why merging #140 didn't close this. Closing manually. 😕

**Comment by watson** [comment]
I think it's because it's still not in master. Let's reopen but put the issue in the "Waiting for 6.2" column in the GitHub project 😃
