### ISSUE TITLE
Drop support for Node.js 6 + 11

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1014]
Checklist

- [x] Remove unsupported versions from package.json `engines` field (should be: `^8.6.0 || 10 || 12`)
- [ ] Mention minimum required version in docs to be v8.6.0
- [x] Remove forced upgrade of npm from Travis and Jenkins
- [x] Remove Node.js 6 and 11 tests from Travis and Jenkins
- [x] Bump the AppVeyor version of Node.js to be v10

**Comment by watson** [comment]
According to npm stats, only 10% of Node.js users are still on version 6: https://twitter.com/seldo/status/1115689379878465542

**Comment by watson** [comment]
If we could wait until 2019-06-01, we could drop support for Node.js 11 at the same time

**Comment by watson** [comment]
We should consider a not supporting very old versions of Node.js 8. E.g. the spread operator wasn't supported until Node.js 8.6.0. And there are other examples like that.

**Comment by Qard** [comment]
commitlint just dropped support for 6.x in a minor so now our tests on 6.x are all failing. We should really get this dropped right away...

**Comment by watson** [comment]
I haven't ticked off "Mention minimum required version in docs to be v8.6.0" because we haven't done this for older node versions previously. Instead we rely on the `engines` field in `package.json` and the more generic text in https://www.elastic.co/guide/en/apm/agent/nodejs/current/supported-technologies.html#supported-technologies

For now, I think this is ok. If we want to improve this we can just do it in a separate issue/PR
