### ISSUE TITLE
Add inject/extract traceparent API

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1015]
It's currently possible to get the `traceparent` value, but we leave it up to the user to know the name of the header/key. To allow us to change this name easily and to make it easier for users to use the correct key, we need a better API.

For inspiration, the OpenTracing API uses the concept of extract and inject for serialization and de-serialization respectively. The OT serialization looks like this:

```js
var clientSpan = ...;
...
// Inject clientSpan into a text carrier.
var headersCarrier = {}
Tracer.inject(clientSpan.context(), Tracer.FORMAT_HTTP_HEADERS, headersCarrier)
// Incorporate the textCarrier into the outbound HTTP request header map.
Object.assign(outboundHTTPReq.headers, headersCarrier)
// ... send the httpReq
```

And the de-serialization like this:

```js
// Use the inbound HTTP request's headers as a text map carrier.
var headersCarrier = inboundHTTPReq.headers
var wireCtx = Tracer.extract(Tracer.FORMAT_HTTP_HEADERS, headersCarrier)
var serverSpan = Tracer.startSpan('...', { childOf: wireCtx })
```

With respect to the HTTP format, this means that the user doesn't need to know about the name of the HTTP header. When it comes to a binary or just pure text format this doesn't have any particular benefit over just a simple function that returns or takes a string or buffer that contains the serialized trace context.

**Comment by alvarolobato** [comment]
@elastic/apm-agent-devs are other agents doing things in this line?

**Comment by axw** [comment]
Not quite. I'll explain what I do below as food for thought. I don't have immediate plans to change this, though it will evolve a little as we work on https://github.com/elastic/apm/issues/71.

In the Go agent, there's a common "apmhttp" module which all other HTTP-related modules rely on for trace context injection/extraction. The API looks like this:

```go
const TraceparentHeader = "Elastic-Apm-Traceparent"
func ParseTraceparentHeader(h string) (apm.TraceContext, error) {...}
func FormatTraceparentHeader(c apm.TraceContext) string {...}

// StartTransaction will extract trace-context headers and use them to start a transaction.
// Internally, it uses the TraceparentHeader constant, and ParseTraceparentHeader function.
func StartTransaction(tracer *apm.Tracer, name string, req *http.Request) (*apm.Transaction, *http.Request) {...}
```

The user could just refer to the `TraceparentHeader` constant, passing that into `ParseTraceparentHeader`; but that doesn't take into account `tracestate` or work with our proposal to use either/both "traceparent"/"elastic-apm-traceparent".

The `StartTransaction` function wraps all of this up into a function which takes an HTTP request, starts a transaction, and returns a copy of the HTTP request with the transaction associated. Header extraction is encapsulated. This works well for Go, which has just one core HTTP library which 99% of servers use; I don't know how well that translates to all of the other languages.

The story is the same for HTTP clients: there's just one library, and we have a function which instruments it and encapsulates all of the header-related logic.

The encapsulated logic could be extracted into a "carrier" type of API, but I'm not convinced it would make for a better experience for Go developers.

**Comment by felixbarny** [comment]
The Java agent is doing it a bit differently from OT and the go agent. The user basically only has to provide a function to [write a header](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-inject-trace-headers) (for example `(name, value) -> request.addHeader(name, value)`) and to [read a header](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-start-transaction-with-remote-parent-header) (for example `key -> request.getHeader(key)`).

The advantage is that this is agnostic of the actual header name and that this mechanism is garbage free. There is no intermediate TextMap representation, or similar. The readers are rather directly read from and written to the underlying request object.

**Comment by astorm** [comment]
With the advent of the W3C TraceContext specification gaining traction both with Elastic and the OpenTelemetry project (OpenTelemetry is the successor to OpenTracing), it feels like there's less of a need for a formal API for header extraction/injection. 

Closing for now, but more than happy to keep the conversation going.
