### ISSUE TITLE
how to avoid GET unknown route when using Eggjs

### ISSUE THREAD

**Issue by wjeek** [elastic/apm-agent-nodejs#1038]
how to avoid GET unknown route when using Eggjs. i have just writen apm.start()

**Comment by Qard** [comment]
There was another user recently wanting to use the agent with the eggjs router. The solution there was to just use the new patch registry feature. Have a look at https://github.com/elastic/apm-agent-nodejs/issues/878 and let me know if that works for you. I'm not sure yet if we want to add the eggjs router to our core instrumentation, as it seems to have very low download counts compared to our other instrumented frameworks, and there's a maintenance cost associated with supporting a new framework officially. However, it _does_ seem like we're seeing multiple people asking about it, so we _may_ reconsider in the future. 🤔

**Comment by yuxizhe** [comment]
maybe you can use this option `usePathAsTransactionName` temporarily

 [https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#use-path-as-transaction-name](url)

#907

**Comment by watson** [comment]
We'll close this issue for now due to lack of activity. Please just add a comment if this has not be resolved 🙂

**Comment by wjeek** [comment]
thx resolved

> maybe you can use this option `usePathAsTransactionName` temporarily
> 
> https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#use-path-as-transaction-name
> 
> #907
