### ISSUE TITLE
`log.param_message` should be set even when there are no placeholders

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-agent-nodejs#104]
At the moment we don't send up `param_message` if there are no placeholders.
It's useful to have the `param_message` always be around, even when it has no placeholders.  It allows people to make aggregations in Elasticsearch across the `param_message` in a consistent way instead of having to use a script to fall back to `message` when `param_message` is missing.

**Comment by watson** [comment]
As opposed to Python, we differentiate between calling `captureError` with a [string](https://www.elastic.co/guide/en/apm/agent/nodejs/1.x/agent-api.html#message-strings) (in which case it's not possible to use params at all) and the [special parameterized object](https://www.elastic.co/guide/en/apm/agent/nodejs/1.x/agent-api.html#parameterized-error-object).

Here's where we detect and use the special parameterized object:

https://github.com/elastic/apm-agent-nodejs/blob/419dcf551b45e80659bb456be474f21998e2040b/lib/parsers.js#L21-L29

This sounds to me more like an implementation detail of Elasticsearch, in which case I think this is better handled by the APM Server, similar to how properties have their default values filled out if missing.

**Comment by watson** [comment]
Closing this issue for now due to inactivity. Please reopen if it should still be considered 😃
