### ISSUE TITLE
Invalid patch handler type: number

### ISSUE THREAD

**Issue by kevindoveton** [elastic/apm-agent-nodejs#1048]
**Describe the bug**
When using webpack to bundle a node application, a message is logged "invalid patch handler type: number" and no instrumentations are recorded. I believe that this error is logged on `line 80, lib/instrumentation/index.js`. I also believe that it is related to 
 https://github.com/webpack/webpack/issues/1554

**To Reproduce**
1. Create a webpack nodejs project
2. add default configuration
3. note error

**Expected behavior**
Insturmentation is loaded

**Environment (please complete the following information)**
- OS: [e.g. Linux]: Mac
- Node.js version: 8.11.3
- APM Server version: 
- Agent version: 2.11

**How are you starting the agent? (please tick one of the boxes)**
- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [x] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by kevindoveton** [comment]
is it possible to change the `require.resolve` to `require`

**Comment by watson** [comment]
Thanks for opening an issue on this. This was previously discussed in #955, but let's keep this issue open since the #955 covered multiple topics. This particular webpack issue is being fixed in #957

**Comment by kevindoveton** [comment]
Ah sorry, I was searching for that explicit error in the issues. Thanks for the prompt response.

**Comment by watson** [comment]
This fix has just been merged into master and will be part of our next release
