### ISSUE TITLE
Allow monitoring event loop delay and active event handlers

### ISSUE THREAD

**Issue by SimonSimCity** [elastic/apm-agent-nodejs#1053]
As proposed in https://discuss.elastic.co/t/node-js-monitoring/149094, I want to ask for the measuring of performance metrics which might be even more important than CPU:

* event loop delay
* active event handlers

On both of these values the administrator can sometimes better decide if his application is collapsing on the mass of events waiting for execution.

The package https://github.com/RuntimeTools/appmetrics referenced to in the thread linked above also has some GC metrics and additional things which might be neat to have in this package.

**Comment by watson** [comment]
Thanks for the suggestion! I'm happy to announce that this is already under development. You can follow along in the PR here: #1021

I'll go ahead and close this issue if you don't mind 🙂
