### ISSUE TITLE
Add full url to context.request.url in APM Server payload

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#106]
We should find a way to assemble a full URL (https://example.com:8080/path?query=params) from a combination of `req.url`, http headers and socket information.

The full url should be added to the APM Server payload as the property `context.request.url.full`.

If a full URL cannot be assembled because we for instance are missing the domain, the `full` property should not be set.

This is where we currently process the URL from requests:

https://github.com/elastic/apm-agent-nodejs/blob/66f54d115f015412fce7d7c9a0c7de68d45acbec/lib/parsers.js#L88-L132

**Comment by Qard** [comment]
PR is: #166
