### ISSUE TITLE
APM agent disabling application middleware (express-slash)

### ISSUE THREAD

**Issue by tomdaniels** [elastic/apm-agent-nodejs#1067]
**Describe the bug**
[express-slash](https://www.npmjs.com/package/express-slash) middleware not compatible with `elastic-apm-node` module.

If you define a route (say: `/foo`), for any request that is `/foo/`, this middleware will 301 redirect to `/foo`. _Assuming there is no `/foo/` defined._

**To Reproduce**
1. Clone this server: https://github.com/tomdaniels/apm-express-slash

2. Request `/foo/`.
sh: `curl localhost:300/foo/`
stoud: `Moved Permanently. Redirecting to /foo`

3. Navigate to `./config/default.js`

4. Update line 10: `ELASTIC_APM_ENABLED: true,`

5. Repeat step 2

**Expected behavior**
The app should still 301 redirect to `/foo`

**Environment (please complete the following information)**
- OS: MacOS Mojave
- Node.js version: 10.15.0 (tried some 8.x and 9.x with no luck as well (nvm))
- APM Server version: 6.7
- Agent version: 2.10.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by watson** [comment]
Thanks for reporting this bug and for the detailed steps of how to reproduce it. I've been able to reproduce it and is looking into fixing it...

**Comment by watson** [comment]
I managed to track down the problem and have created a PR that fixes this issue: #1070

As soon as the tests pass and the PR is reviewed and merged, we'll publish a new version of the agent to npm.

Thanks again for letting us know about this bug and sorry for the inconvenience.

**Comment by tomdaniels** [comment]
Thanks @watson for your help, I've tested the changes and seems to be resolved.

**Comment by watson** [comment]
We've just released v2.11.2, which includes the fix for this bug. Once again, thanks for reporting this ❤️
