### ISSUE TITLE
CPU metrics mismatch

### ISSUE THREAD

**Issue by pruthvi-1012** [elastic/apm-agent-nodejs#1068]
**Describe the bug**
APM agent often pushes 0% process and system CPU usage, it should have at least some value greater than zero as the process is still running. Even comparing the stats on the container itself does not match the CPU usage provided by APM. 

**To Reproduce**
1. Deploy APM enabled node application to a container (Linux). 
2. Compare container stats to APM data
3. Compare process metrics within the container to APM data
4. Screenshot of this comparison attached.

**Expected behavior**
APM agent should push correct CPU metrics instead of 0%

**Environment (please complete the following information)**
- OS: Linux
- Node.js version: 8.10.0
- APM Server version: 6.7.0
- Agent version: 2.6.0, 2.11.1

**How are you starting the agent? (please tick one of the boxes)**
- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Screenshot

![metrics-comapre](https://user-images.githubusercontent.com/9096457/57602907-af23f880-75a3-11e9-8630-509abcec5363.png)

**Comment by watson** [comment]
Thanks for reporting this bug. I'm able to reproduce it and we'll look into what's going on.

**Comment by vivek-sheth** [comment]
@watson thank you for confirming the bug. When can we expect this bug to be fixed?

**Comment by watson** [comment]
@vivek-sheth We still haven't found the source of the bug. The entire team has been attending an internal company conference last week, so we haven't had much time to look into this yet.

**Comment by watson** [comment]
This issue has now been fixed and released as part of v2.11.5. Thanks for your patience 😊

**Comment by vivek-sheth** [comment]
Thank you @watson for fixing it. 👍
