### ISSUE TITLE
Use v8.getHeapStatistics over os.totalmem/freemem

### ISSUE THREAD

**Issue by backflip** [elastic/apm-agent-nodejs#1077]
**Is your feature request related to a problem? Please describe.**
It seems like `os.totalmem()` doesn't really tell me how much memory my Node process is allowed to use (setting `--max-old-space-size` does not affect it). Same for `os.freemem()`.

**Describe the solution you'd like**
Would it be reasonable to replace it with `v8.getHeapStatistics().heap_size_limit` (which is properly affected by setting `--max-old-space-size`) and `v8.getHeapStatistics().used_heap_size`, respectively?

**Describe alternatives you've considered**
Custom metrics would be an alternative [as soon as they are available](https://github.com/elastic/apm-agent-nodejs/issues/867).

**Comment by watson** [comment]
Great minds think alike 😄 There's [a PR](https://github.com/elastic/apm-agent-nodejs/pull/1021) open adding the memory metrics you mentioned. You can see the new heap related metrics here:

https://github.com/elastic/apm-agent-nodejs/pull/1021/files#diff-f4a2093d1bf303e6e6894f7bcc66d3eeR69

Btw, I think both are good metrics to collect right? It's nice to know both the OS level memory metrics _and_ how much memory is available to the runtime.

**Comment by backflip** [comment]
Argh, sorry, missed that one when searching the code base. Looking forward to it!
