### ISSUE TITLE
Allow configuring captured body length

### ISSUE THREAD

**Issue by eigengrau** [elastic/apm-agent-nodejs#1078]
It would be convenient if the length at which the captured request body is truncated were configurable, akin to `ELASTIC_APM_ERROR_MESSAGE_MAX_LENGTH`.

**Comment by watson** [comment]
Good idea. Out of curiosity, what is your current use-case? Do you want it to be larger or smaller than the current configured value?

**Comment by eigengrau** [comment]
> Out of curiosity, what is your current use-case? Do you want it to be larger or smaller than the current configured value?

I was looking into debugging chatty webhooks, such as Amazon Alexa or Actions-on-Google, which deliver JSON payloads of around 4 KB.

**Comment by kevindoveton** [comment]
I'd love to take this one on if it's open to community PRs?

**Comment by trentm** [comment]
This can be done via the [`logFieldMaxLength`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#long-field-max-length) config var added in v3.21.0 (2021/09/15).
