### ISSUE TITLE
Logger not defined in generic span 

### ISSUE THREAD

**Issue by vokaltomas** [elastic/apm-agent-nodejs#1079]
**Describe the bug**
Logger instance is not defined inside generic-span for certain call

**To Reproduce**
1. Create span with <https://github.com/elastic/apm-agent-nodejs-opentracing>
2. Then call addTag

**Expected behavior**
This is caused by incorrect implementation on lines 68 and 84 where there should be:  
`this._agent.logger.warn` instead of `this.logger.warn` 

**Environment (please complete the following information)**
- OS: All
- Node.js version: 11.2
- APM Server version: 7.0.0
- Agent version: 2.11.1

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**
Can you please also fix implementation of apm opentracing extension to call non-deprecated method on span?  
<https://github.com/elastic/apm-agent-nodejs-opentracing/blob/fa358dc5cca8624765544c4c168780e967048b8e/lib/span.js#L82>

**Comment by watson** [comment]
Thanks for reporting this bug. It has been fixed in the latest version (v2.11.3) which was just released.
