### ISSUE TITLE
HapiJS update to new package paths

### ISSUE THREAD

**Issue by bgardner87** [elastic/apm-agent-nodejs#1097]
**Is your feature request related to a problem? Please describe.**
HapiJS moved their packages to '@hapi/hapi' instead of just 'hapi' and new versions are published there. The agent needs updated to support newer hapijs installs.

**Describe the solution you'd like**
Update the agent to support both old and new versions and paths

**Describe alternatives you've considered**
I'm not sure there are alternatives...

**Additional context**
Creating the issue so I can get a fix and PR started :)

**Comment by watson** [comment]
Added in #1246
