### ISSUE TITLE
feat(instrumentation): add memcached

### ISSUE THREAD

**Issue by mikefaut** [elastic/apm-agent-nodejs#1131]
**Is your feature request related to a problem? Please describe.**
There currently isn't support for memcached.

**Describe the solution you'd like**
A memcached handler could be added to /lib/instrumentation/modules

**Describe alternatives you've considered**
Currently I overwrite/wrap the memcached requests with a span.

**Additional context**
The code I use is below, which I use to wrap the set and get functions. 
```
function wrapFunctionWithAPMSpan(func, name) {
    return (...args) => {
        let span = apm.startSpan(name)
        return func(...args).then((result) => {
            span.end()
            return result
        }).catch((err) => {
            span.end()
            throw (err)
        })
    }
}
```

**Comment by watson** [comment]
Hi @mikefaut, thanks for opening this issue 😃

I would love to see automatic instrumentation of memcached in the agent as well 👍 Our roadmap is currently pretty full, but hopefully, we can get to it soon.

**Comment by mikefaut** [comment]
Are there any caveats for implementing this? I might look at doing it when/if I get a chance. I'd probably use the redis instrumentation as a template.

**Comment by watson** [comment]
I don't think so, but it depends a little on the internals of the memcached module. Some modules have obvious hooks where it's easy to get notified when for instance a new query starts and when it ends, and what type of query it is, while others make it a lot harder.

**Comment by watson** [comment]
The API to add automatic instrumentation for new modules is public btw, so you can easily try it out without having to modify the module source code. You just need to call the [`agent.addPatch`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-add-patch) function with a patch function.

We'll happily help you through the PR process as well.

**Comment by mikefaut** [comment]
I wrote a patch for this. I'll still need to do a bit of testing but I could use some feedback. What is the process for PRs? Are there some docs? Also do you have ideas on how I can do version testing?

**Comment by watson** [comment]
That's great to hear. We have documented our contribution guidelines in the [`CONTRIBUTING.md`](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md) file. I suggest you take a look at that. In there's also a specific section for adding support for new modules:
https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#adding-support-for-new-modules

Point number 6 in the list is a bit outdated as the `test/.jenkins_tav.yml` file have been moved to a different folder, so you can skip that for now.

If you like to get some feedback on the code before completing all the steps listen in the guide first, feel free to just open a PR with only the code. Then we can add the feedback there.
