### ISSUE TITLE
Run Jenkins tests against Node.js RC+nightly

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1135]
### Checklist

- [ ] Create an "extra branch" on the pipeline (similar to how the TAV tests are set up) that runs after the TAV tests which runs our normal test suite against Node.js release candidates and Node.js nightly builds.
- [ ] Set up a daily cron job to run our entire test suite against `master` and ensure the new "extra branch" only runs during the cron job and not during normal builds.

We already do all of this on Travis.

- Here's an example of how one of those cron jobs look like: https://travis-ci.org/elastic/apm-agent-nodejs/builds/546393842
- Here's the configuration for those builds: https://github.com/elastic/apm-agent-nodejs/blob/d33d45e16af18ab051c15daf47dac6ddc86f2e62/.travis.yml#L219-L335

**Comment by kuisathaverat** [comment]
This would be a new job that launches the regular CI process and a new one that tests the Node.js nightly versions

**Comment by watson** [comment]
Potential issue: Since we're not using nvm but Docker, I think we might have to either maintain our own Docker images or switch to using nvm - or some combination of the two.

**Comment by kuisathaverat** [comment]
we build our own for the TAV test so we can make the same using the nvm as base images
