### ISSUE TITLE
Don't add traceparent header to requests to the intake API

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1136]

**Comment by watson** [comment]
@graphaelli is the Go agent enabled for the APM Server by default on new on-prem deployments or in the cloud? Just trying to assess how high a priority we should give this 😅

**Comment by graphaelli** [comment]
It is not enabled by default in either case and I expect it is rarely enabled outside of Elastic, lowest priority is appropriate imo.  In the meantime, is there a way to configure exclusions for trace context propagation manually?

**Comment by watson** [comment]
Unfortunately, it's currently not possible to block certain domains. But it's been discussed before. This is where the check should be made:

https://github.com/elastic/apm-agent-nodejs/blob/2ae2295584657e8ced87db4a90d5d894e2a09cea/lib/instrumentation/http-shared.js#L128-L130

Today we have one rule inside the `shouldPropagateTraceContext` function which is just checking to see if the request is signed with an AWS signature. Updating it to check for a list of hosts would be fairly trivial. And including the APM Server host in this list should be simple as well.
