### ISSUE TITLE
Log stack trace for uncaught exceptions to STDERR

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1141]
Today the stack trace for an uncaught exception isn't logged to STDERR when it's being sent to the APM Server. This makes it impossible to see what's wrong during development without setting `captureExceptions: false` temporarily.

**Comment by smhmayboudi** [comment]
Hi, thanks in advance for all your efforts. I think instead of using the `console.error`, `agent.logger.error` should be used.
https://github.com/elastic/apm-agent-nodejs/blob/c56f894138c81f0b07146f86c3ba7139bb68a59c/lib/agent.js#L411

**Comment by watson** [comment]
We chose to use `console.error` instead of the logger to ensure that uncaught exceptions would always be written to STDERR. This is to make sure that the exception is written to STDERR even in cases where a custom logger is provided that logs to a different destination - for instance, a file.
