### ISSUE TITLE
apm.start{serverUrl} strips away sub-path and only uses proto+host

### ISSUE THREAD

**Issue by StianOvrevage** [elastic/apm-agent-nodejs#115]
First of all, great work on APM, can't wait to feed it some data!

But I have one issue: The agent mangles the URL given to send data to.

Configure `serverUrl: 'https://my.site.com/apm/` and it will use `https://my.site.com/`. This breaks the very definition of "URL" as well as many (including mine) common reverse-proxying setups.

**Comment by watson** [comment]
@StianOvrevage Thanks for bringing this to our attention. That should of course be allowed. I've made a PR that will add this capability. As soon as it's merged we'll publish a new version of the agent 😃

**Comment by watson** [comment]
@StianOvrevage If you install v0.9.0 of the agent it should now be possible to use a sub-path in `serverUrl`. Once again, thanks for letting us know about this use-case 😃

**Comment by StianOvrevage** [comment]
Awesome sauce, @watson!

**Comment by StianOvrevage** [comment]
Speaking of use-case; just gonna ask here and not create an issue if it's really far fetched.

I'm trying to also add apm-agent-nodejs to a serverless(TM) project which gets deployed to AWS Lambda. It works when running locally on my laptop. However on AWS it never produces data because of the extreme short-livedness of the Lambda functions. I have added `apm.endTransaction()` and `apm._instrumentation._agent._instrumentation._queue._flush()` which seems to send every event to APM pretty instantly when running locally. However, on AWS it produces nothing and the AWS logs doesn't show anything useful.

Is this a possible use-case or is this completely off?

**Comment by watson** [comment]
@StianOvrevage That's a really good question. And you'll probably not be the only one to ask it. I don't have a solution for you unfortunately, but I think it would make sense to gather some feedback and experience, so could I get you to open a separate issue with it anyway?

Regarding your hack to call `_flush` directly, you can just set the [`maxQueueSize`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#max-queue-size) config option to `0` which will flush instantly as well.
