### ISSUE TITLE
No need to run TAV tests all the time in Jenkins

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1152]
Today the TAV tests run all the time on Jenkins which ties up a lot of resources. This is not needed as we have some degree of knowledge of when we don't need to run them.

The TAV tests only need to run under the following circumstances:
- Only run on PR builds and not on commits to regular branches like `master` etc (unless it's a "cron" job as described in #1135, in which case we want to run it on `master`)
- The PR branch being build doesn't start with `greenkeeper/`

**Comment by watson** [comment]
cc @elastic/observablt-robots

**Comment by kuisathaverat** [comment]
it'd check changes on modules to trigger only the TAV test needed for PRs, on scheduled builds it would launch 'em all

**Comment by watson** [comment]
The approach you're describing sounds like the one proposed in #378.

Checking for changes to modules requires a few other things to be in place first, so I was thinking this was too big of a feature to add if we wanted it quickly. So it would be easier, for now, to simply implement my proposed solution. If you want to implement the solution described in #378, we need to first have a chat about how exactly we need this to work before proceeding.

> [...] on scheduled builds it would launch 'em all

Does that mean that TAV tests currently will not run on scheduled builds but only on PRs and when we push to `master`? We don't want them to run on new branch commits, but we do need them to run on scheduled builds (basically as described in the description).

**Comment by kuisathaverat** [comment]
>Does that mean that TAV tests currently will not run on scheduled builds but only on PRs and when we push to master? 

currently a build it is scheduled for every branch, this build executes the current pipeline that launches the TAV test, 'em all.
https://github.com/elastic/apm-agent-nodejs/blob/master/Jenkinsfile#L24

>We don't want them to run on new branch commits, but we do need them to run on scheduled builds (basically as described in the description).

this is what you are requesting in the issue, isn't it?

**Comment by watson** [comment]
Maybe I misunderstood what "scheduled builds" mean. We need to run a build automatically on `master` once a day as described in #1135 where the TAV tests are included. If that's what a scheduled build is, then we need to run them during those. But not on PR branches - only on `master`.

> this is what you are requesting in the issue, isn't it?

Yes

**Comment by v1v** [comment]
This particular issue has been addressed with https://github.com/elastic/apm-agent-nodejs/pull/1181
