### ISSUE TITLE
Document how to use Distributed Tracing with custom protocols

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1155]
Today Distributed Tracing is automatically supported with HTTP/HTTPS. But if the user uses another protocol such as TCP, UDP, WebSocket, or Protocol Buffers, they need to manually encode the `traceparent` header onto the message, manually decode it on the other end, and manually start a new Transaction as a child of that `traceparent`.

I think this is such a common need that we should dedicate a page to it in the documentation.

Here are a few posts asking about this in the Discuss forum:
- https://discuss.elastic.co/t/full-trace-with-custom-integration/185996
- https://discuss.elastic.co/t/highly-custom-distributed-tracing/187206

**Comment by watson** [comment]
@bmorelli25 how would you like to go about this? Should I create a draft for you to review, or can you go with what is described in the Discuss posts?

**Comment by bmorelli25** [comment]
There's a lot of good information in this issue and the first discuss post. I think I can put something together and have you review it.

I don't think there's a distributed tracing section in the Node.js docs, so will need to figure out where this lives.

**Comment by watson** [comment]
If creating a distributed tracing section makes sense let's do that :)

**Comment by watson** [comment]
Related: https://discuss.elastic.co/t/highly-custom-distributed-tracing/187206/7?u=wa7son
