### ISSUE TITLE
Lint commit messages as separate build on Jenkins

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1157]
Today Jenkins will lint the commits in the PR for each stage of the build before running the actual tests. Instead, this should be done just once as a separate build stage just as it's done on Travis. This way it doesn't hinder the actual tests from running even if the commit message is invalid.

cc @elastic/observablt-robots

**Comment by kuisathaverat** [comment]
PR https://github.com/elastic/apm-agent-nodejs/pull/1172
