### ISSUE TITLE
Change default flushInterval

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#117]
The [`flushInterval`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#flush-interval) config option defaults to 60 seconds today. That's too long and is a left over from the Opbeat agent where all requests from all Opbeat users was sent to one single endpoint. A better default would probably be something like 30 seconds.

When changing the default, remember to update the documentation as well.

**Comment by watson** [comment]
Hi @elastic/apm, what do you think would be a reasonable default queue flush interval? Is 30 seconds good, or should we go even lower? I think we have similar config options in all the backend agents, so maybe it would make sense to align as well? (the use-case for frontend agents are completely different).

**Comment by mikker** [comment]
@beni has gone all the way down to 10 and I have followed (AFAIR). I think that's totally reasonable now that everyone has their own server (and can change it back up if need be)

**Comment by watson** [comment]
Oh, I checked the Python docs and they still said 60. Maybe I looked at the wrong version of the docs

**Comment by beniwohli** [comment]
I didn't make the change yet, but I was suggesting 10s when we discussed it a couple of weeks ago.

**Comment by watson** [comment]
This was solved in #186
