### ISSUE TITLE
Research integration with logging libraries

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1187]
Related to elastic/apm-dev#279

**Comment by Qard** [comment]
Some popular loggers:
- [loglevel](https://www.npmjs.com/package/loglevel)
- [winston](https://www.npmjs.com/package/winston)
- [fancy-log](https://www.npmjs.com/package/fancy-log)
- [morgan](https://www.npmjs.com/package/morgan)
- [bunyan](https://www.npmjs.com/package/bunyan)
- [consola](https://www.npmjs.com/package/consola)
- [pino](https://www.npmjs.com/package/pino)
- [console-log-level](https://www.npmjs.com/package/console-log-level)

**Comment by Qard** [comment]
We've decided to start integrating with some of the top logging libraries. Closing the research task now.

**Comment by Qard** [comment]
fancy-log actually has _more_ used-by results on Github than winston, apparently. 😮
