### ISSUE TITLE
Limit the max amount of timer metrics

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-nodejs#1249]
We missed a bullet point from elastic/apm-agent-nodejs#1064 in the implementation (https://github.com/elastic/apm-agent-nodejs/pull/1219):

- [ ] [Limit the max amount of timers](https://docs.google.com/document/d/1-_LuC9zhmva0VvLgtI0KcHuLzNztPHbcM0ZdlcPUl64#heading=h.tzyh7loxf2is)

**Comment by Qard** [comment]
Yep, that was intentional. We'll need to make a PR to measured, the metrics library we depend on, and I didn't have time to make that and wait to get it landed if we wanted this feature to be available for 7.3. That's an immediate next task, so we can just use this issue to track that. 👍
