### ISSUE TITLE
Improve user-agent header

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1253]
The user agent was updated recently (#1238) from:

```
{package-name}/{package-version}
```

to:

```
{agent-name}/{package-version}
```

Following [discussion](https://github.com/elastic/apm/issues/88#issuecomment-517313900), we're updating it once more to get the package-name back into the header:

```
{agent-name}/{package-version} {package-name}/{package-version}
```

I propose also that we call the agent-name `elasticapm-nodejs` instead of `elasticapm-node` while we're at it. The duplicate `package-version` is intentional ([see discussion](https://github.com/elastic/apm/issues/88#issuecomment-517512118)).

**Comment by trentm** [comment]
The user-agent was spec'd to be `$repoName/$version ($serviceName $serviceVersion)` at https://github.com/elastic/apm/blob/main/specs/agents/transport.md#user-agent

And that was implemented in https://github.com/elastic/apm-agent-nodejs/pull/2402 a while back.
