### ISSUE TITLE
Run commit message linting in parallel with regular tests on Jenkins

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1259]
Linting of commit messages was moved to a separate build in #1172, but it's running before any of the other tests, which I guess means it will not run the regular tests until linter finishes successfully (please correct me if I'm wrong).

There's no reason why we want to hold up the regular tests waiting for the linter to finish, so we should just run it all in parallel.

ping @elastic/observablt-robots

**Comment by v1v** [comment]
Even though it sounds a good approach, from the resources point of view, aka the number of workers required to run in the parallel is a kind of a waste of time/ money as they do run in the cloud.

In other words, if the linting is prescriptive I'd suggest running at the very beginning as other steps will be required to be evaluated again, later on, therefore the number of parallel resources to be used for a non-well-prepared commit should be reduced. What benefits do I see:
- Forcing contributors to use the mandatory git commit message to be able to even build the project in the CI.
- Reduce the number of workers in parallel for a bad commit.
- Reduce the waiting time in the queue in case there are a bunch of other pipelines/builds in the queue. IIRC, we got up to 300 workers in parallel.
- A bit smart way to use the resources without wasting money

I do understand it's worth the feedback about the requirement of having quick feedback, but I see also the above cons.

Another option  might be moving the commit linting at the very end as a warning, therefore if the only issue is the commit message, then the owner of the repo could potentially edit the git log to change it accordingly or even forget about it and use the GitHub UI squash and merge feature to ensure the commit message fulfill the linting requirements. Although it might require some further analysis.

**Comment by watson** [comment]
The commit message linting errors are nice for us to know, but it's more critical to know the actual test errors. Waiting sometimes days for the user to fix the commit message before we can see the actual errors puts an extra workload on the reviewer.

We also have the option to change the name of the commit when we merge directly from the GitHub UI, so the commit linting errors are just something we need to be aware of but not something we want to block the other tests.

Here you can see on Travis how we run them all at the same time:

![image](https://user-images.githubusercontent.com/10602/62548007-72943000-b866-11e9-9d0b-f34fbe350476.png)

**Comment by v1v** [comment]
Makes sense! thanks for the clarification :)

As far as I see in Travis is not a blocker but a warning? Is that right? If so, what do you think if we move the linting validation stage at the very end of the Jenkins pipeline? If so:
- Should it be set the linting stage as unstable and therefore the GH check will be set similar too?
- Or should it be set the linting stage as a failure and therefore the GH check will be set similar too?
- Or should it be set as an unstable pipeline and therefore the GH checks, aka the commit linting and the pr-merge one, will be set similar too?

**Comment by watson** [comment]
No, it's a blocker in Travis as well - if you ask because you looked on Travis just now and saw that it was running even through the next stage had already completed, that's because I just restarted the linting build on master because it had timed out for some reason 🤷‍♂ 

I'd like it to mark the GH check as a failure so that we don't miss it. But I'm ok with it technically just being unstable in Jenkins so it doesn't block the other tests if that's what you mean?

**Comment by v1v** [comment]
Cool, then I've got all the details that I need, I'll work on it during this week. Thanks again
