### ISSUE TITLE
Deprecate genericSpan._context in next major

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1294]
Currently, the OT bridge accesses the [`_context`](https://github.com/elastic/apm-agent-nodejs/blob/55e45e189fc082c3b2db5e61598def8e5704054d/lib/instrumentation/generic-span.js#L13) property on `GenericSpan` objects. This means that it's de facto a public property. Let's grab the opportunity to refactor this when we land the next major.

**Comment by watson** [comment]
I'm not sure what the best approach is here. Technically we can just agree that this is "removed" in v3.0.0 and not use it in the OpenTracing bridge once we upgrade to that version. This doesn't require any code changes as the property is already prefixed with an underscore. Or we can actively rename the property to something else to make sure we don't forget to stop using it. But that also just seems a bit silly, as it begs the question: What should we rename it to? `__context`?!?

Maybe the right approach is simply to update the OT bridge now to not use it and be done with it. That way we don't forget once we upgrade the OT bridge to support the new version of the agent 🤔

**Comment by Qard** [comment]
I'd say just update the OT bridge. There shouldn't be anyone _else_ using that property currently, but if there is, changing it would break them. I think it's probably better to just change our one outside use of it and continue considering it private the way we always have. 🤷‍♂

**Comment by watson** [comment]
This was fixed in https://github.com/elastic/apm-agent-nodejs-opentracing/pull/10 and released in v2.0.0 of the `elastic-apm-node-opentracing` module.
