### ISSUE TITLE
Lambda instrumentation should not expect lowercase headers

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-nodejs#1315]
**Describe the bug**

The `apm.lambda` instrumentation expects to find the trace header lower-cased:

https://github.com/elastic/apm-agent-nodejs/blob/d866894a810e5dedee1a857781712efb7beeb251/lib/lambda.js#L78

At least when testing with the local API Gateway (using `sam local start-api`), the headers are not lower-cased. In fact the gateway seems to transform them, so "foo: bar" becomes "Foo: bar".

I haven't found a formal definition of what the headers are _supposed_ to look like, but I've come across these pages which suggest that the headers aren't expected to be lower-cased:
 - https://docs.aws.amazon.com/lambda/latest/dg/with-on-demand-https.html (see example event)
 - https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html ("Header names and query parameters are processed in a case-sensitive way" -- seems to conflict with `sam local start-api`, but that could just be a bug in the local API Gateway code.)
 - https://github.com/serverless/serverless/issues/2765#issuecomment-331158257

**To Reproduce**
1. Install the SAM CLI: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html
2. Create a new SAM app: `sam init -r nodejs10.x -n foo`
3. Modify foo/hello-world/app.js so that the response body includes the event:

```js
response = {
    'statusCode': 200,
    'body': JSON.stringify({
        message: 'hello world',
        input: event
    })
}
```

4. Start the local API Gateway: `cd foo && sam local start-api`
5. Send an HTTP request: `curl -H "Elastic-Apm-Traceparent: foobar" http://localhost:3000/hello`

You should see in the response that the headers contain the key `Elastic-Apm-Traceparent`, rather than `elastic-apm-traceparent`.

(I originally instrumented the app with the agent, and found that it was not honouring incoming elastic-apm-traceparent headers from the RUM agent. The above is a simplification.)

**Expected behavior**
When instrumenting the app with the agent, transactions should honour the incoming header regardless of what case it was sent to the API Gateway.

**Environment (please complete the following information)**
- OS: Linux
- Node.js version: 10.16.0
- APM Server version: 7.3.0
- Agent version: 2.16.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by Qard** [comment]
Hmm, I guess the headers don't actually _come_ from HTTP then. Node.js lowercases all headers automatically, so AWS must be doing something weird to bypass HTTP headers and maybe send them in the body instead? 🤔

**Comment by axw** [comment]
> Hmm, I guess the headers don't actually come from HTTP then

Are you referring to the Node.js HTTP module? I don't know for sure, but I don't think so. I'm pretty sure the Lambda just receives a blob of JSON.

Lambdas can be invoked in response to a variety of event sources, not all of which are HTTP-based. I'm not sure where the Node.js runtime code lives, or if it's even available for inspection; the Go runtime uses a mechanism which is independent of the event source, and I imagine that's the case for all of the standard runtimes.

FWIW, I also found https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html which suggests the headers are lower-cased when coming through ALB.

**Comment by Qard** [comment]
Yes, Node.js http lowercases headers automatically, but I guess it's not using _actual_ headers and is instead receiving them some _other_ way. Not really any way to know, as the lambda runtime is closed source, so all we can really do is poke at it from the inside and see how it behaves. 😞

**Comment by watson** [comment]
@axw forgot to ask, did you find this bug because some of our agents don't use all-lowercase header names? They are all supposed to do that (though we are of course supposed to handle it even if they are not)

**Comment by axw** [comment]
@watson I found it while testing with the RUM agent, which does lower-case the header. It was the API Gateway (SAM local testing tool) that was modifying the header case.
