### ISSUE TITLE
APM Server transport error (ECONNRESET): socket hang up

### ISSUE THREAD

**Issue by jayadeepsureify** [elastic/apm-agent-nodejs#1320]
**Describe the bug**
While connecting NodeJS Agent from express app to the APM server. Observing the "APM Server transport error (ECONNRESET): socket hang up"
**To Reproduce**
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**

**Environment (please complete the following information)**
- OS: [e.g. Linux] - centos 6.9
- Node.js version: v8.10.0
- APM Server version: 7.3.1
- Agent version: 2.16.1

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    var apm = require('elastic-apm-node').start({
      // Override service name from package.json
      // Allowed characters: a-z, A-Z, 0-9, -, _, and space
      serviceName: 'localdev',
    
      // Use if APM Server requires a token
      secretToken: '...',
      verifyServerCert: false,
      serverTimeout: '5s',
    
      // Set custom APM Server URL (default: http://localhost:8200)
      serverUrl: 'https://sample.com:8200'
    });
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by watson** [comment]
Are you receiving any data in the APM index in Elasticsearch?

**Comment by jayadeepsureify** [comment]
The issue was while agents are connecting to APM server on the command line it was prompting. I don't find new data about agents in Elasticsearch But I can see startup indices of APM in Elasticsearch.

**Comment by watson** [comment]
Ah, is the APM agent in a CLI tool in this case and not a continuously running application/service?

If so, does this error happen when the program exits?

**Comment by jayadeepsureify** [comment]
usign APM node modules in express.js and launching by PM2. In pm2 logs found the error regarding APM. But our Application is running continously without exit.

**Comment by watson** [comment]
Thanks for the details.

The error means that the TCP socket to the APM Server was unexpectedly closed. This socket is used to send data from the agent to the APM Server and might be closed unexpectedly from time to time for instance due to network issues, or if the APM Server is restarted, or if a proxy in between the agent and the APM Server decides to close its socket.

If you just get a few of these messages from time to time, but data is generally flowing fine to the APM Server and onwards to Elasticsearch, then I wouldn't worry too much about it. But if this is happening all the time and especially if no data is getting through it's obviously a sign that something more fundamental is wrong.

Since you say that no data is making it to the ES index, it would probably be a good idea to check the following:

1. Is the `serverUrl` configured correctly to point to your APM Server?
1. Is the APM Server running and accepting traffic on the configured port (default 8200)? _You can learn more about debugging the APM Server in the [troubleshooting section](https://www.elastic.co/guide/en/apm/server/current/common-problems.html)_

**Comment by jayadeepsureify** [comment]
I checked above configuration in Agent side, It is perfect. Actually, I am running the express code using PM2, not by a native node(node index.js). Is that the problem from the agent side?

**Comment by watson** [comment]
It shouldn't be a problem that you run your app using pm2. Have you checked the logs of your APM Server to see if the connection actually makes it all the way from the agent to the APM Server? It could be that there's some network routing issue.

If the socket is closed by the APM Server it might write in the logs why it's doing it.

**Comment by jayadeepsureify** [comment]
can you tell where need to check the logs I am using latest version of Elastic Stack on top of Centos 7.

**Comment by watson** [comment]
Could I get you to try and curl the root of the APM Server from the same host as where your application is running? That way we can see if there's access between the two hosts.

Here's is how I expect it to look:

```
$ curl -i http://example.com:8200
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 05 Sep 2019 10:46:23 GMT
Content-Length: 124

{
  "build_date": "2019-08-22T09:36:45Z",
  "build_sha": "0effb08d637e80f85933182ac0454dd35e88c348",
  "version": "7.3.1"
}
```

**Comment by jayadeepsureify** [comment]
Thanks for the troubleshooting steps it helped to fix the issue...

**Comment by JannikZed** [comment]
Hey guys,
I'm facing the same issue really often. We are using elastic cloud on Kubernetes. Everything in version 7.9.3
We have the APM nodejs client running in a serverless environment and see a lot of the requests fail with `APM Server transport error (ECONNRESET): Client network socket disconnected before secure TLS connection was established`
We have a python django app as well with a running APM client and I can't see these issue happening there. So my question is: how can I better debug this issue? Maybe it is a miss-match of session timeouts of our kubernetes ingress, APM server and APM client.

**Comment by bradleydamato** [comment]
> Hey guys, I'm facing the same issue really often. We are using elastic cloud on Kubernetes. Everything in version 7.9.3 We have the APM nodejs client running in a serverless environment and see a lot of the requests fail with `APM Server transport error (ECONNRESET): Client network socket disconnected before secure TLS connection was established` We have a python django app as well with a running APM client and I can't see these issue happening there. So my question is: how can I better debug this issue? Maybe it is a miss-match of session timeouts of our kubernetes ingress, APM server and APM client.

@JannikZed did you ever figure this out?

**Comment by JannikZed** [comment]
Unfortunately not :( I think it just happened with clients running in
Lambdas, but I’m also not sure about that.
We finally stopped using elastic APM.
