### ISSUE TITLE
Add serviceInstanceName config option

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1322]
For details see elastic/apm#141

**Comment by curtisjohnson1** [comment]
Hi @watson, I'm happy to pick this one up.

**Comment by watson** [comment]
Thanks for offering to take this one @curtisjohnson1. I just checked with a colleague and we're currently waiting for https://github.com/elastic/kibana/issues/43765#issuecomment-527188147 to be resolved before we can say for certain that we want to implement it this way. I'll update this issue once we have a resolution. Until then it's probably best to wait implementing it so you don't waste any time.

**Comment by curtisjohnson1** [comment]
No problem, I'll leave it for now until the above issue is resolved. Thanks for getting back to me so quickly.
