### ISSUE TITLE
lambda: provide a hook for injecting trace-context into Lambda payloads

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-nodejs#1329]
**Is your feature request related to a problem? Please describe.**

At the moment, if you use the AWS SDK to invoke a Lambda, there's no automatic trace-context propagation. This is (in my opinion) the correct default, due to a couple of reasons:

 - there's no way to pass metadata aside from ClientContext, which could be dangerous to manipulate
 - injecting automatically into a well-defined location in the payload is possible, but could change application behaviour

However, it means that users must manually inject trace-context into the payload, and to do that they must first explicitly create a span.

**Describe the solution you'd like**

Instrument methods at the AWS SDK level, rather than HTTP, using the AWS SDK-provided [middleware](https://github.com/aws/aws-sdk-js-v3#middleware).

Users could then register their own middleware to for Invoke and InvokeAsync methods to inject the span's traceparent into the Lambda payload. We should also provide a simple function that would register middleware under the covers, purely for modifying the payload like so:

```js
apm.registerLambdaInjector(function(payload) {
    payload.headers = {...payload.headers, ...{'elastic-apm-traceparent': apm.currentTraceparent}}
})
```

**Comment by axw** [comment]
Middleware is only part of the v3 SDK, which is in developer preview. Not sure if there's something similar for v2, a brief look says no. It may not be necessary though.

**Comment by axw** [comment]
The v2 AWS SDK has a top level "events" property which can be used to subscribe to events for all the things. We could use this. I prototyped a module which will create spans for all AWS SDK operations:

https://github.com/elastic/apm-agent-nodejs/compare/master...axw:aws-sdk-module?expand=1

The span name is hacked specifically for Lambda, so that it looks like `Lambda.Invoke: <function>`. Maybe there's a better way, but we might end up having to create service-specific logic for the names.

In addition, if a user sets `agent.lambda.injectHeaders` to a function accepting a Lambda payload and a headers object, then it will be called with the decoded payload, and if it returns truthy then the payload will be encoded back to JSON and stored back in the request.

There's still HTTP spans being created, which I'm not sure are adding much value. Maybe we want to suppress them somehow?

![image](https://user-images.githubusercontent.com/843579/64397488-03dc0980-d094-11e9-8459-1dc5ab7714bd.png)

(There's no downstream transaction for the Lambda request because I don't have my IAM permissions set up right.)

**Comment by astorm** [comment]
We're doing some backlog cleanup -- in the time since this issue was opened, is appears that lambda support was pulled back and a working group has formed to develop a long term solution.  See https://github.com/elastic/apm-agent-nodejs/issues/827 

We're going to close this out in favor of the central Lambda Issue over in the `apm` repo. https://github.com/elastic/apm/issues/352. If this was premature (i.e. there's more conversation to have here) please don't hesitate to let us know.
