### ISSUE TITLE
lambda: automatically wrap lambda handler

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-nodejs#1336]
**Is your feature request related to a problem? Please describe.**

Currently in order to instrument AWS Lambda, you must explicitly wrap the handler, e.g.

```js
const apm = require('elastic-apm-node').start({...})

exports.handler = apm.lambda(function handler (payload, context, callback) {
  callback(null, `Hello, ${payload.name}!`)
})
```

This is unlike other technologies, such as HTTP servers, where we automatically patch the server.

**Describe the solution you'd like**

Ideally, requiring `elastic-apm-node` would automatically patch what's needed, so that the `apm.lambda` call becomes unnecessary.

One option would be to define a setter for the main module's exports, so that when the handler is defined it can be intercepted and wrapped. The name of the handler property can be obtained through the `_HANDLER` environment variable, according to https://docs.aws.amazon.com/lambda/latest/dg/lambda-environment-variables.html.

**Describe alternatives you've considered**

Patch the Lambda runtime I guess? This is not documented, and could change. It would be safer to just patch the user-provided handler

**Comment by Qard** [comment]
Unfortunately that's not really possible. By the time our agent is loaded the top-level module object has already been constructed and exists in the file scope where we don't have the ability to change it anymore

**Comment by axw** [comment]
I added the following to the bottom of `elastic-apm-node/index.js`, and it worked for me:

```js
Object.defineProperty(require.cache["/var/task/index.js"].exports, 'handler', {
    set: function(x) {
        this._handler = module.exports.lambda(x)
    },
    get: function() {
        return this._handler
    }
})
```

**Comment by Qard** [comment]
You can have names other than "handler" so we'd need something that can dynamically dispatch. You can do that with a `Proxy`, but then a user could also overwrite the `module.exports` object completely, like this:

```js
module.exports = {
  aLambda(...) {},
  anotherLambda(...) {}
}
```

That last case is impossible to handle and, unfortunately, quite common. There's also the possibility of re-assignment which might double-wrap, but I think we can detect that.

We could do a `Proxy` based auto-patching thing, which I think could be a good approach, but we would need to document that it doesn't work when overwritting `module.exports`.

**Comment by Qard** [comment]
The "handler" name is only a default. It's quite common to have differently named functions or even export multiple functions in the same file and just deploy the same code with different settings to do different things. We'd need something that can dynamically dispatch which is possible with a `Proxy` but we can only _augment_ the `exports` object not _replace_ it as it won't change in module scope. A user could also overwrite the `module.exports` object completely, which even a `Proxy` could not handle:

```js
module.exports = {
  aLambda(...) {},
  anotherLambda(...) {}
}
```

We'd also need to consider the possibility of re-assignment which might double-wrap, but I think we can detect that.

There _is_ an environment variable indicating the current function name, so we could use that with your `defineProperty(...)` idea, but that breaks down in some of the local dev lambda environments as they don't all include that and some even start _all_ the functions in the same process.

**Comment by axw** [comment]
> The "handler" name is only a default.

That code above was just meant to show the mechanics. We would have to use `_HANDLER` to do it properly. I wasn't thinking we'd replace `exports`, but just define a property.

> There is an environment variable indicating the current function name, so we could use that with your defineProperty(...) idea, but that breaks down in some of the local dev lambda environments as they don't all include that and some even start all the functions in the same process.

Hmm, OK. Which ones were you thinking of?

Although the https://github.com/lambci/docker-lambda README refers to a different name, AWS_LAMBDA_FUNCTION_HANDLER, I just ran a quick test and it does expose _HANDLER to the code.

https://github.com/ashiina/lambda-local apparently uses the handler name for AWS_LAMBDA_FUNCTION_NAME. I haven't tested if it sets _HANDLER also, but doesn't look like it from a quick glance. We could send a PR to change it.

**Comment by AlexanderWert** [comment]
Resolved in https://github.com/elastic/apm-agent-nodejs/pull/2577
