### ISSUE TITLE
Add/update instrumentation for @koa/router

### ISSUE THREAD

**Issue by lfk** [elastic/apm-agent-nodejs#1343]
**Is your feature request related to a problem? Please describe.**

The `koa-router` module seems to have become unmaintained as of late, resulting in a fork being made and placed under the "official" `@koa` namespace. See [this ticket](https://github.com/ZijianHe/koa-router/issues/513) for details.

Due to how this module shims middleware, moving to `@koa/router` would cause breakage.

**Describe the solution you'd like**

Please consider including `@koa/router` in the instrumentation `MODULES` set.
Given how modules are required in the loader, there is sadly no straightforward way to link multiple entries to the same source file; symlinking might be dangerous, not sure how that'd work out cross-platform?

**Describe alternatives you've considered**

Made a quick attempt at using `agent.addPatch(...)` as suggested in #878. Had to tweak the validation logic in `lib/instrumentation/modules/koa-router.js` as well, as the `(!semver.satisfies(version, '>=5.2.0 <8'))` rejects `@koa/router`, which is at major version 8.

Would not consider this a permanent solution, regardless.

**Edit:** More details about the workaround, fixed typo.

**Comment by watson** [comment]
Thanks for opening this issue. This can be fixed in the same manner as we fixed the rename of `hapi` to `@hapi/hapi` in #1246. 

While looking into if this was possible, I ended up actually writing the implementation so it should be ready in #1346 😅

**Comment by lfk** [comment]
Oh wow, never have I seen a ticket addressed so swiftly. Big kudos!

**Comment by watson** [comment]
This has now been released in v2.17.0
