### ISSUE TITLE
Http tests fail randomly on Jenkins for Node.js 6

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1350]
The `test/instrumentation/modules/http/aborted-requests-enabled.js` test often fail for Node.js 6 on Jenkins.

Here's a few examples:

- https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1340/9/pipeline/114#step-300-log-1850
- https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1344/10/pipeline/124#step-306-log-1850
- https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1344/8/pipeline/116#step-298-log-1850

**Comment by watson** [comment]
In case we lose the history, here's a screenshot of the logs:

![image](https://user-images.githubusercontent.com/10602/64954452-ea05a800-d885-11e9-9b1d-76486f573e26.png)

**Comment by trentm** [comment]
Node.js 6 is no longer supported. 8.6.0 is the min in v3 of this module.
