### ISSUE TITLE
Issue using setLabel (data missing?)

### ISSUE THREAD

**Issue by jooj123** [elastic/apm-agent-nodejs#1364]
**Describe the bug**

I have been using the `setLabel` to set a label on the current transaction in an express controller.
https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-set-label

Its been working fine for a number of weeks - but all of a sudden data has dropped. 
See here for the last 7 days of data:

![Screen Shot 2019-09-19 at 6 08 45 pm](https://user-images.githubusercontent.com/1309297/65225475-91920d00-db08-11e9-85af-95bf1cde8b20.png)

We did notice messages like this when trace enabled:
```
error while getting callsite source context: ENOENT: no such file or directory, open '/Users/martin.jujou/Documents/projects/fe-server-search-listings/build/server/webpack:/node_modules/@domain-group/fe-build/lib/fe-server/server.js'
Sending error to Elastic APM { id: 'c7748797b9aaeb10c21820ba8b0cd33b' }
intercepted http.ClientRequest response event { id: 'f39f58246ca9eb50' }
intercepted http.IncomingMessage end event { id: 'f39f58246ca9eb50' }
recovering from wrong currentTransaction { wrong: undefined,
  correct: 'f39f58246ca9eb50',
  trace: '375aef07b13bebe496b1da50baa45072' }
```

"recovering from wrong currentTransaction" doesn't sound right ?

and not sure whats with "error while getting callsite source context: ENOENT: no such file or directory.. " We dont have that when elastic APM is disabled..

**To Reproduce**

Its on our closed source system - but basically we have a:
`apm.setLabel('aggregator', 'internal');`

On a controller - we have noticed that we have put more traffic to this endpoint (which included far more redis calls via `ioredis` client) from Sept 16th onwards - and it seems data has started to drop off (and completely at around Sept 17th ~ 10pm syd time)
We know that particular controller is definitely getting traffic and entering that `apm.setLabel('aggregator', 'internal');` 

If we remove "context.tags.aggregator:internal" from the search we can see traffic at the endpoint `/:listingSlug` (which is where the label is set)

I have checked the index and seems to be searchable:
![Screen Shot 2019-09-19 at 6 19 06 pm](https://user-images.githubusercontent.com/1309297/65226330-03b72180-db0a-11e9-9d03-5a4f3d5996de.png)

**Expected behavior**

Not sure why there is a data drop off.

**Environment (please complete the following information)**

- OS: node:10.15.3-alpine
- Node.js version: 10.15.0
- APM Server version: 6.7.0
- Agent version: 2.16.2

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by Qard** [comment]
Closing as this issue is being handled elsewhere. Feel free to leave a comment if you prefer I reopen it.

**Comment by jooj123** [comment]
Its fine to close 

Yeah for reference this turned out to be an elastic field type issue - we were REDACTING fields with a filter and one of the fields expected IP type - but due to the REDACTING with value "[REDEACTED]" it was a string) which caused serious data issues

**Comment by Qard** [comment]
Thanks for sharing the solution here. Might help if anyone else encounters it. 👍
