### ISSUE TITLE
Add support for mongodb v3.3+

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1368]
Version 3.3.0 of the `mongodb` module stopped using the `mongodb-core` module as the underlying tech for talking to MongoDB ([see release notes](https://github.com/mongodb/node-mongodb-native/releases/tag/v3.3.0)). That module is the one we currently instrument instead of the more high level `mongodb` module.

This approach previously meant that we could support a wide range of high-level clients by just instrumenting ONE module as at least one popular high-level client besides `mongodb` used `mongodb-core` directly. Now that client (`mongojs`) also depends on `mongodb`, so it's no longer actually necessary to instrument the more low-level module.

We currently claim support for the following high-level clients:
- [mongodb](https://www.npmjs.com/package/mongodb): `>=2.0.0` - doesn't use `mongodb-core` since v3.3.0
- [mongojs](https://www.npmjs.com/package/mongojs): `>=1.0.0` - latest version v2.6.0 depends on `mongodb@^2.2.31`
- [mongoose](https://www.npmjs.com/package/mongoose): `>=4.0.0` - latest version v5.7.1 depends on `mongodb@3.3.2`

I propose that we simply start instrumenting `mongodb` directly. For simplicity, we could start this instrumentation from v3.3.0 an upwards, or we could completely drop support for `mongodb-core` and also add support for older versions of `mongodb`. If we fully dropped support for all versions of `mongodb-core` it would be a breaking change as support for older versions of `mongojs` depend on it.

**Comment by gumold** [comment]
Dropping support for mongodb-core would be manageable for most of the apm user if it's part of v3 of this agent to reduce non backward compatibility.

I think to manage the current problem for v2, as you propose, selectively handling mongodb and mongojs is a better idea.

**Comment by Qard** [comment]
`mongojs` seems to have _just_ bumped to `mongodb` 3.x in master, and is not yet in a released version. All versions should work up to at least the current 2.6.0. Maybe we should update the docs to say supported up to 2.7.0 even though we don't know yet if the next release will be a major or minor? 🤔

**Comment by watson** [comment]
That was over a year ago. There hasn't been any development in `master` since 4th of July 2018, so I doubt it will ever get released. But good idea 👍
