### ISSUE TITLE
Update docs to show no support for newer versions of mongodb and mongoose

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1369]
### mongodb

Our docs currently claim support for the `mongodb` module v2.0.0 and above. As described in #1368 we no longer support v3.3.0 and above, so until we do, our docs should be updated to reflect that.

### mongoose

Our docs currently claim support for the `mongoose` module v4.0.0 and above. As described in #1368 we no longer support v5.7.0 and above, so until we do, our docs should be updated to reflect that.

**Comment by ernanirst** [comment]
@watson Looking at the `mongoose` tags, it seems that the last version to include `mongodb-core` was v5.6.13. So, would be fair to say the `mongoose` is supported between v4.0.0 and v5.6.13?

**Comment by Qard** [comment]
Yes, that should be accurate.
