### ISSUE TITLE
Support disabling logger or default to noop logger

### ISSUE THREAD

**Issue by jsumners** [elastic/apm-agent-nodejs#1392]
My organization has its own logging format (mostly similar to Pino's output). But I cannot boot our logger before this library due to issues. We also have log shippers and destinations that expect that specific format to be adhered to. So to prevent this module from writing incompatible logs I have to:

```js
const apm = require('elastic-apm-node').start({
  logger: Object.create(require('abstract-logging'))
});
```

At a very minimum, I'd like to see `logger: false` as a supported option to disable the logger. A more complete solution would be to use `abstract-logging` yourself internally and you'll automatically gain compatibility with the list of loggers in https://github.com/elastic/apm-agent-nodejs/issues/1187#issuecomment-514103468. Note: this is what we do in Fastify -- https://github.com/fastify/fastify/blob/0e39b83c3bde8a9cb6531ad2dbe960be75199e1d/lib/logger.js#L84-L88

**Comment by Qard** [comment]
The equivalent of `logger: false` would be `logLevel: 'silent'`. The `logger` option should only be used when you _want_ to receive the logs.

As for supporting `abstract-logging`, that could be an interesting possibility, but it sounds like it might be unnecessary for your particular needs right now. 🤔

**Comment by jsumners** [comment]
“Silent” is not documented as a possibility — https://github.com/elastic/apm-agent-nodejs/blob/master/docs/configuration.asciidoc#loglevel

Using `abstract-logging` internally to the module would solve this for me because I could ignore customizing the logger and let the noop logger do its thing.

**Comment by Qard** [comment]
Ah, right..."silent" was just a test thing. Try "fatal", there shouldn't be anything on that log level so it should be effectively silent.

**Comment by jsumners** [comment]
Yes, that does seem to be a way to get it solved for now. But it isn't a foolproof solution. There is no guarantee that `logger.fatal` will not be used in the future. It would really be nice to have the ability to disable the logger completely by `logger: false`.

**Comment by Qard** [comment]
We don't _intend_ on it ever logging anything by default, so that should not change.

**Comment by Qard** [comment]
It basically _is_ a guarantee. _We_ control all the code where the logger is used, and we _do not_ intend to ever log _anything_ by default as there are many users that _require_ process output to have a specific format with no extra output mixed in.

I feel the `logger: false` style also makes the use of the `logLevel` config confusing. I think it'd be better to just land the pino refactor in the next major. Leading up to that, what we _could_ do is add _our own_ "silent" option for 3.x that just swaps out the existing logger for a null logger. 🤔

**Comment by trentm** [comment]
In [v3.10.0](https://www.elastic.co/guide/en/apm/agent/nodejs/current/release-notes-3.x.html#release-notes-3.10.0) of the agent support was added for an "off" [logLevel](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#log-level) in #1908
