### ISSUE TITLE
Commit message linting not working on Jenkins

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1407]
@elastic/observablt-robots As discovered in #1403, commit message linting was accidentally removed in #1325. We should re-add it to Jenkins.

**Comment by v1v** [comment]
> .ci/scripts/lint-commits.sh is not required anymore as it runs within the npm run lint context.`

Is this incorrect?

**Comment by watson** [comment]
Ah yes, good point. It's weird then that it's not catching lint errors 🤔

**Comment by watson** [comment]
Oh wait... commit linting isn't part of `npm run lint` (that's only code linting). For commit linting you need to run `npm run lint:commit`
