### ISSUE TITLE
Preserve client's real IP

### ISSUE THREAD

**Issue by AE777F63** [elastic/apm-agent-nodejs#1459]
client.ip appears to be based on req.socket.remoteAddress, which is not very useful if the server is running behind a proxy. It would be nice to have client's real IP as well.

https://github.com/elastic/apm-agent-nodejs/blob/v3.1.0/lib/parsers.js#L100
https://github.com/elastic/apm-server/pull/2588
https://expressjs.com/en/api.html#req.ip

**Comment by axw** [comment]
@AE777F63 this came up in discussions just last week, and the conclusion was that agents will continue to send the (direct) peer address, as well as the HTTP headers.

The server may later grow the ability to optionally extract the originating client IP from headers; we would need to make this configurable, to handle header trust issues. If this is important to you, would you please create a feature request at https://github.com/elastic/apm-server?

**Comment by Qard** [comment]
Closing for now. If/when APM Server supports it, we can re-open.

**Comment by AE777F63** [comment]
OK, I'll do that. In case anyone interested, here's a quick-and-dirty way to have this:

```
// patch APM
const parsers = require('elastic-apm-node/lib/parsers');
const _ = require('lodash');
const patch = (object, method, wrapper) => object[method] = _.partial(wrapper, object[method]);
patch(parsers, 'getContextFromRequest', function (wrapped, req, ...args) {
    const context = wrapped.call(this, req, ...args);
    context.socket.remote_address = req.ip;
    return context;
});

// configure the express app
app.set("trust proxy", true);
```
