### ISSUE TITLE
Add simple head based transaction sampling

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#148]
Currently the agent sends up all information about all transactions to the APM Server. In Elastic 6.2 we should allow for "head based random sampling" - i.e. where only a configurable percentage of the total transactions are sampled. The non-sampled transactions will still be sent to the APM Server, but without any spans and without any context.

The config option should be called `transactionSampleRate` and default to 100% - i.e. everything is collected.

It's preferable if we can find a way to disable the [wrapping of callbacks](https://github.com/elastic/apm-agent-nodejs/blob/826efc9f7affca4369fe0dc21070427fcb3879d6/lib/instrumentation/index.js#L110-L125) when a transaction isn't sampled. This means that there's certain things we cannot do as easily as we'll not have an active transaction available during for instance the request/response life cycle. This can mean that setting the name and result for HTTP based transactions can be difficult and might require a bit of refactoring.

Note that this feature will need to go into the [elastic-6.2 branch](https://github.com/elastic/apm-agent-nodejs/tree/elastic-6.2) as it can't be released until Elastic 6.2 version is released.

**Comment by Qard** [comment]
PR is: #154
