### ISSUE TITLE
Populate span.db.link/span.db.instance

### ISSUE THREAD

**Issue by AE777F63** [elastic/apm-agent-nodejs#1482]
**Is your feature request related to a problem? Please describe.**
The name/URL of the database is not stored in "db" events.

**Describe the solution you'd like**
span.db.link and span.db.instance should be set accordingly.

**Describe alternatives you've considered**
Using filters; this cannot be done reliably if more than one database is used (in mongodb case, at least), since the underlying database object cannot be obtained from within the filter.

As a side note, it would be nice to have exposed, monkey-patch-able methods that would allow users to access the underlying context and extend the reports if need be, e.g.
```
          span = agent.startSpan(ns + '.' + name, 'db', 'mongodb', 'query')
```
could become something like
```
          span = _startSpan(this, name);
          module.exports._startSpan (context, name) {
              return agent.startSpan(context.ns + '.' + name, 'db', 'mongodb', 'query');
          }
```
Same applies for http-shared.js:traceOutgointRequest.
This is obviously not as good as having the fields you need supported by the agent natively, and to some extent this approach is limited by apm-server's schema, but still.

**Additional context**
https://github.com/elastic/apm-server/blob/056276511a1f8327992302267b010ac4e9c04511/docs/data/elasticsearch/generated/spans.json#L194
https://github.com/elastic/apm-server/issues/2478

**Comment by Qard** [comment]
I'm not sure I understand what you are asking for. What are these `link` and `instance` fields for? Are you trying to get the hostname of the database or something like that? Can you elaborate, please?

**Comment by AE777F63** [comment]
Yes, basically I want the hostname of the database. If I understand the schema correctly, db.link is the hostname and db.instance is the name of the database.

**Comment by Qard** [comment]
You can already set that data with `span.setDbContext(...)`. It's just a matter of modifying the existing instrumentation to get their corresponding equivalents of "link" and "instance" then just add them to the object it's _already_ supplying when it calls `span.setDbContext(...)`. Each database already has it's own place that is called.

It doesn't really make sense to request this generically as the _capability_ already exists. What we _need_ is just to know what specific database do you _want_ it for?

**Comment by AE777F63** [comment]
> You can already set that data with span.setDbContext(...)
As a user, I can't do that, since I don't have a good place to put this in the code (and putting setDbContext after every call to the database is less than ideal), if that's what you meant. From within APM - yes, sure.

> It's just a matter of modifying the existing instrumentation to get their corresponding equivalents of "link" and "instance" then just add them to the object it's already supplying when it calls span.setDbContext(...)
Yes, that's basically what I'd like to have.

> What we need is just to know what specific database do you want it for?
For mongo and postgres, although I imagine this is relevant for other databases as well.

**Comment by axw** [comment]
> db.link is the hostname

`db.link` is meant to hold the database link name, e.g. https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_5005.htm

We'll be adding a new field for capturing the destination address, which we would ideally populate with the database hostname: https://github.com/elastic/apm/issues/115

**Comment by Qard** [comment]
@AE777F63 Yep, agreed that asking the user to put that in their code is not user-friendly. I just meant that we already "support" this in the sense that nothing needs to change in the core code, we just need to update our instrumentation modules, which should be relatively easy but each database will need to be handled differently, so we should have separate tasks to add it to each. I can start with mongo and postgres to make sure we cover your case first, then get to the others later. :)

**Comment by AE777F63** [comment]
> I can start with mongo and postgres to make sure we cover your case first, then get to the others later.

Cool, thanks. Although given what @axw said, I suppose db.link is not really relevant for mongo, right? Not sure about postgres.

**Comment by trentm** [comment]
`span.db.instance` was added for mongodb, mongodb-core, mysql, mysql2, pg, `@elastic/elasticsearch` in #2882  

I'm closing this now. We can add separate issues for other specific cases.
