### ISSUE TITLE
add configuration option to specify a certificate authority file ( SSL )

### ISSUE THREAD

**Issue by lreuven** [elastic/apm-agent-nodejs#1508]
**Is your feature request related to a problem? Please describe.**
nodejs agents and are required to disable SSL verification as described [here](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#validate-server-cert). The key statement is

Disabling validation is normally required if using self-signed certificates.

**Describe the solution you'd like**
Implement an option to define a configuration option to specify a certificate authority file.
**Describe alternatives you've considered**

**Additional context**
https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

**Comment by jasonslater2000** [comment]
any progress on adding support for specifying a Cert Authority file?

**Comment by axw** [comment]
@jasonslater2000 I've made a start on it in https://github.com/elastic/apm-nodejs-http-client/pull/102. There's more to be done in this repo, which I hope to get to in the next week or so.

In the mean time, ICYMI: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file may be useful
