### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by itsmed** [elastic/apm-agent-nodejs#151]
Having had a quick chat with @watson and @Qard we said we should add a CONTRIBUTING.md file. A question I didn't think to ask at the time is if we ask community members to sign the Elastic [Contributor License Agreement](https://www.elastic.co/contributor-agreement/), as we do with [Elasticsearch](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) and other projects. Thoughts @watson, @Qard ?

**Comment by watson** [comment]
@itsmed yes we do. The bot will also ask the contributer to sign it if he hasn't already

**Comment by watson** [comment]
Maybe we can reuse some of the stuff that was just added to to the APM Server in elastic/apm-server#590
