### ISSUE TITLE
Since 7.4.2 missing 90% of requests?

### ISSUE THREAD

**Issue by bradennapier** [elastic/apm-agent-nodejs#1510]
So this is a pretty hard thing to figure out what happened here.  Since I upgraded to 7.4.2 I am suddenly missing 90% of my transactions.  I see the `apm-server` has no major changes and there are no updates to this agent since then but it is not clear where those requests have suddenly gone to!

![image](https://user-images.githubusercontent.com/15365418/68248735-6a759900-ffeb-11e9-834a-4841eb965902.png)

It works out to almost EXACTLY 90% of requests missing with the only change being i updated my elastic cloud to 7.4.2 across ElasticSearch, APM Server, and Kibana.

Note that the missing time here was due to trying to remove the 7.4.2 index to see if there was something weird with that index when it was initially created since i noticed the difference here.

A couple points:

---

* My `ELASTIC_APM_TRANSACTION_SAMPLE_RATE` is `0.1` 

When looking at our datadog instance metrics and comparing it to ES, previously it was exactly 90% less than datadog (sample rate of 0.1), but now it is 90% less than 0.1 - so it seems like it is double-applying the filtering or something?

* I have another custom index which does not display any changes in index counts and its data is correct to what shows in our sql database so it appears that is correct

* I have already attempted to restart both the entire deployment (rolling restart) as well as the instances running the apm agent.

* While I have the `ELASTIC_APM_LOG_LEVEL` set to `error`, it does not appear to be logging any problems at this time.

* Based on recomendations from earlier posts (as we have far too many requests for APM to handle in our application), we apply a custom filter using `apm.addFilter` - this has not changed since it has been working flawlessly.  I can't find any case where these values may be suddenly handled differently though.

```js
/**
 * Filter to only send sampled results to the APM Server
 */
apm.addFilter(payload => {
  if (!payload) {
    return false;
  }
  if (typeof payload.sampled === 'boolean' && !payload.sampled) {
    /*
      When this occurs the data result looks similar to below.
      Returning here when not sampling works as expected and does
      not produce any errors.

      {
        "id": "566594a22f516683",
        "trace_id": "fc9d048d55f21ffbebb1a2d44648b7d3",
        "name": "GET /endpoint",
        "type": "request",
        "duration": 94.044,
        "timestamp": 1569358244043041,
        "result": "HTTP 2xx",
        "sampled": false,
        "sync": false,
        "span_count": {
          "started": 0
        }
      }
    */
    return false;
  }

  if (
    typeof payload.transaction?.sampled === 'boolean' &&
    !payload.transaction.sampled
  ) {
    /*
      When an error occurs, the `transaction.sampled` is where
      the data is, but regardless, if this filter ever returns
      undefined it will cause the app to crash completely.
    */
    return false;
  }

  return payload;
});
```

**Comment by bradennapier** [comment]
Interesting and possible solution.  In the past I tried setting the transaction sample rate to 0.01 in the central config for apm when metrics were breaking apm (before we introduced the filters mentioned above).

This never worked and did nothing.  

It appears that as of 7.4.2 upgrade suddenly the central config does start working and thus it was changing to this value I didn't know was still configured in elastic apm

https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#central-config

**Comment by bradennapier** [comment]
Yep - needless to say this was it. 

Should probably have a note somewhere that the central config will start working with 7.4.2 and people should be mindful of this fact

![image](https://user-images.githubusercontent.com/15365418/68251437-1f5e8480-fff1-11e9-89bd-c7fb52865fb6.png)

**Comment by axw** [comment]
@bradennapier sorry for the late reply. Glad to see you tracked it down.

Which version did you upgrade from? Central config was added in 7.3.0, and is mentioned in the [APM Server 7.3.0 release notes](https://www.elastic.co/guide/en/apm/server/current/release-notes-7.3.0.html)

Is there a particular reason why you've set `ELASTIC_APM_LOG_LEVEL` to `error`, rather than sticking with the default of `info`? Is it too noisy? I ask because at info level you should see log messages when config is updated due to central config, so it may have been more obvious.

**Comment by bradennapier** [comment]
yeah it gives me ten thousand + messages per minute lol

**Comment by axw** [comment]
> yeah it gives me ten thousand + messages per minute lol

That seems like a bug to me.

Since you've resolved the issue, I'll close this. I've created https://github.com/elastic/apm-agent-nodejs/issues/1519 to review the agent's log levels - any additional/specific details you can provide there would be appreciated.
