### ISSUE TITLE
Review info-level logging

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-nodejs#1519]
The agent logs at "info" level by default. According to https://github.com/elastic/apm-agent-nodejs/issues/1510#issuecomment-553486590, it is currently too noisy, leading to (in this case) changing it to "error" level, which means some useful log messages being suppressed. We should review the logging, bumping any noisy logs to debug level.

**Comment by watson** [comment]
This is a possible duplicate of #375

**Comment by axw** [comment]
Agreed - closing, thanks for the pointer.
