### ISSUE TITLE
Add support for Lambda

### ISSUE THREAD

**Issue by rubenfonseca** [elastic/apm-agent-nodejs#1521]
elastic-apm removed support for Lambda (see https://github.com/elastic/apm-agent-nodejs/issues/1511). I would like one day to bring that back.

**Additional context**
Looking on how datadog does it, it seems they rely on xray to generate the metrics, and then have some kind of transformer that eats xray events and outputs datadog events. Could something similar be used with elastic?

**Comment by lreuven** [comment]
Thanks for the feedback it's on our roadmap, we will fix it :) 
 have look at [this issue](https://github.com/elastic/apm-agent-nodejs/issues/827), there some additional ideas and alternatives to xray approach.

**Comment by astorm** [comment]
We're doing some backlog cleanup and are going to close out this issue in favor of the central Lambda Issue over in the `apm` repo. https://github.com/elastic/apm/issues/352

If this was premature please don't hesitate to reopen or comment as needed.
