### ISSUE TITLE
Transaction not recorded

### ISSUE THREAD

**Issue by dedekrnwan** [elastic/apm-agent-nodejs#1551]
**Describe the bug**
Transaction not recorded while i am hit some endpoint, but the apm-server get metric data.

**To Reproduce**

I have start apm-server connection in the first file named `server.ts` 

```
const apm = elasticApmNode.start({
	serviceName: 'Elk Stack',
	serverUrl: '${process.env.APM_SERVER_HOST}',
	captureBody: 'all',
});
```

Creating express route using decorators, implement routing using `app.use()`

```
router.route('${route.path}')[route.method]([...middlewares.before, handler, ...middlewares.after, ...middlewares.error])
 app.use('${uses}${prefix}', router);
```

**Expected behavior**

APM page like this
![image](https://user-images.githubusercontent.com/25242055/69618667-dab48f00-106c-11ea-96c5-1ab28c58d31e.png)

The Transaction Data should be like this (example using loopback 2)

![image](https://user-images.githubusercontent.com/25242055/69619311-fbc9af80-106d-11ea-99d0-ee63d4ea5dd8.png)

**Environment (please complete the following information)**

- OS: Linux (Docker in Windows)
- Node.js version: 8
- APM Server version: 7.4.0
- Agent version: 3.2.0
- Express version: 4.17.1

**How are you starting the agent? (please tick one of the boxes)**

- [v] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by lreuven** [comment]
Hi,
can you check if you can connect to the APM server?  did you add  secretToken: '<apm_token>' as well?
Any message in the log file? 
have a look [here](https://www.elastic.co/guide/en/apm/agent/nodejs/3.x/troubleshooting.html) for additional troubleshooting info.

**Comment by dedekrnwan** [comment]
@lreuven The agent has been connected correctly to apm-server checked from kibana:
![image](https://user-images.githubusercontent.com/25242055/69627380-10fa0a80-107d-11ea-9689-577d063f3180.png)

And there's nothing message show up, and i didn't adding any apm_token

**Comment by lreuven** [comment]
can you add the log message from the agent?

**Comment by dedekrnwan** [comment]
@lreuven I got log like this 
`start trace { trans: 'd6843df5b2ac4e4b',
  parent: undefined,
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'unnamed',
  type: null,
  subtype: null,
  action: null }
start span { span: '5c0dc97d247e9f06',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SQL',
  type: 'db',
  subtype: 'postgresql',
  action: 'query' }
intercepted call to pg.Client.prototype.query { id: 'd6843df5b2ac4e4b',
  sql: 'SELECT count(*) AS "count" FROM "user" AS "User" WHERE "User"."email" = \'dekur98@gmail.com\';' }
intercepted end of pg.Client.prototype.query { id: 'd6843df5b2ac4e4b' }
ended span { span: '5c0dc97d247e9f06',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SELECT FROM "user"',
  type: 'db',
  subtype: 'postgresql',
  action: 'query' }
encoding span { span: '5c0dc97d247e9f06',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SELECT FROM "user"',
  type: 'db' }
start span { span: 'cadb98d643cdd7ab',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SQL',
  type: 'db',
  subtype: 'postgresql',
  action: 'query' }
intercepted call to pg.Client.prototype.query { id: 'd6843df5b2ac4e4b',
  sql: 'SELECT count(*) AS "count" FROM "user" AS "User" WHERE "User"."username" = \'dekur98\';' }
sending span { span: '5c0dc97d247e9f06',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SELECT FROM "user"',
  type: 'db' }
intercepted end of pg.Client.prototype.query { id: 'd6843df5b2ac4e4b' }
ended span { span: 'cadb98d643cdd7ab',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SELECT FROM "user"',
  type: 'db',
  subtype: 'postgresql',
  action: 'query' }
encoding span { span: 'cadb98d643cdd7ab',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SELECT FROM "user"',
  type: 'db' }
start span { span: 'e8a77e62a76743bf',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SQL',
  type: 'db',
  subtype: 'postgresql',
  action: 'query' }
intercepted call to pg.Client.prototype.query { id: 'd6843df5b2ac4e4b',
  sql: 'INSERT INTO "user" ("id","name","username","email","password","birthdate","phone","createdDate","updatedDate") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8) RETURNING *;' }
sending span { span: 'cadb98d643cdd7ab',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'SELECT FROM "user"',
  type: 'db' }
intercepted end of pg.Client.prototype.query { id: 'd6843df5b2ac4e4b' }
ended span { span: 'e8a77e62a76743bf',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'INSERT INTO "user"',
  type: 'db',
  subtype: 'postgresql',
  action: 'query' }
encoding span { span: 'e8a77e62a76743bf',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'INSERT INTO "user"',
  type: 'db' }
sending span { span: 'e8a77e62a76743bf',
  parent: 'd6843df5b2ac4e4b',
  trace: 'd1cbe0d3aa266c683b17a011cf703717',
  name: 'INSERT INTO "user"',
  type: 'db' }
{"level":30,"time":1574773732604,"pid":27,"hostname":"fd9ca6011af0","flag":"Ok","message":"Register successfully","data":{"token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNTc0NzczNzMyLCJleHAiOjE1NzQ4MTY5MzIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QvIiwiaXNzIjoiVHlwZXNjcmlwdCIsInN1YiI6Im5vcmVwbHlAdHMuY29tIn0.ZzjkFyzLVT3pULX0pX4VUaE4vKYVLwz3GdzJxbsMjDgQx-4qqI7d-9IymTZpYl-XQGT0ZNMTC9z8gqKJCAvKVw"},"code":200,"v":1}
{"level":30,"time":1574773732610,"pid":27,"hostname":"fd9ca6011af0","req":{"id":1,"method":"POST","url":"/auth/register","headers":{"host":"localhost:3001","user-agent":"insomnia/7.0.3","content-type":"application/json","accept":"*/*","content-length":"163"},"remoteAddress":"::ffff:172.21.0.1","remotePort":44954},"res":{"statusCode":200,"headers":{"x-dns-prefetch-control":"off","x-frame-options":"SAMEORIGIN","strict-transport-security":"max-age=15552000; includeSubDomains","x-download-options":"noopen","x-content-type-options":"nosniff","x-xss-protection":"1; mode=block","access-control-allow-origin":"*","content-type":"application/json; charset=utf-8","content-length":"349","etag":"W/\"15d-Ht/skSELBQlpx8E2hR6QoCu18qs\""}},"responseTime":272,"msg":"request completed","v":1}
`

while i am hit some endpoint.

and i got this in my `apm` index from agent :
`{
  "_index": "apm-7.4.0-metric-000001",
  "_type": "_doc",
  "_id": "mw_Vp24BOZ2-kTsEGYPT",
  "_version": 1,
  "_score": null,
  "_source": {
    "container": {
      "id": "fd9ca6011af080011f1e60d9432be72a6b846c1e7bd2dd4005cf2620dce08154"
    },
    "observer": {
      "hostname": "ad7004a30fc6",
      "id": "7b1f211d-49cb-4b5d-b3db-9d0ab91ce260",
      "ephemeral_id": "02c23276-2c72-4fb2-b1e3-66d98402fc2f",
      "type": "apm-server",
      "version": "7.4.0",
      "version_major": 7
    },
    "agent": {
      "name": "nodejs",
      "version": "3.2.0"
    },
    "process": {
      "args": [
        "/usr/local/bin/node",
        "/var/www/app"
      ],
      "pid": 27,
      "title": "node",
      "ppid": 17
    },
    "@timestamp": "2019-11-26T13:09:40.142Z",
    "system": {
      "process": {
        "memory": {
          "rss": {
            "bytes": 66547712
          },
          "size": 708710400
        },
        "cpu": {
          "total": {
            "norm": {
              "pct": 0.010763538513286243
            }
          },
          "system": {
            "norm": {
              "pct": 0.001849983181971073
            }
          },
          "user": {
            "norm": {
              "pct": 0.00891355533131517
            }
          }
        }
      },
      "memory": {
        "actual": {
          "free": 361095168
        },
        "total": 2096140288
      },
      "cpu": {
        "total": {
          "norm": {
            "pct": 0.03279515640766902
          }
        }
      }
    },
    "ecs": {
      "version": "1.1.0"
    },
    "service": {
      "environment": "production",
      "name": "Elk Stack",
      "runtime": {
        "name": "node",
        "version": "8.16.2"
      },
      "language": {
        "name": "javascript"
      },
      "version": "1.0.0"
    },
    "host": {
      "hostname": "fd9ca6011af0",
      "os": {
        "platform": "linux"
      },
      "ip": "172.21.0.6",
      "name": "fd9ca6011af0",
      "architecture": "x64"
    },
    "nodejs": {
      "handles": {
        "active": 7
      },
      "memory": {
        "heap": {
          "used": {
            "bytes": 34477928
          },
          "allocated": {
            "bytes": 38674432
          }
        }
      },
      "eventloop": {
        "delay": {
          "avg": {
            "ms": 0.38864147018030515
          },
          "ns": 0
        }
      },
      "requests": {
        "active": 3
      }
    },
    "processor": {
      "name": "metric",
      "event": "metric"
    },
    "labels": {
      "hostname": "fd9ca6011af0",
      "env": "production"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-11-26T13:09:40.142Z"
    ]
  },
  "sort": [
    1574773780142
  ]
}`

**Comment by lreuven** [comment]
I meant the node agent logs :)

**Comment by dedekrnwan** [comment]
You meant from my node js services ?
`
agent configured correctly { pid: 27,
  ppid: 17,
  arch: 'x64',
  platform: 'linux',
  node: 'v8.16.2',
  agent: '3.2.0',
  ancestors: 
   [ '/var/www/app/node_modules/elastic-apm-node/index.js',
     '/var/www/app/dist/src/lib/server.js',
     [length]: 2 ],
  startTrace:
   [ 'at Agent.start (/var/www/app/node_modules/elastic-apm-node/lib/agent.js:154:11)',
     'at Object.<anonymous> (/var/www/app/dist/src/lib/server.js:19:40)',
     'at Module._compile (module.js:653:30)',
     'at Object.Module._extensions..js (module.js:664:10)',
     'at Module.load (module.js:566:32)',
     'at tryModuleLoad (module.js:506:12)',
     'at Function.Module._load (module.js:498:3)',
     'at Function.Module.runMain (module.js:694:10)',
     'at startup (bootstrap_node.js:204:16)',
     'at bootstrap_node.js:625:3',
     [length]: 10 ],
  main: undefined,
  dependencies: undefined,
  conf: 
   Config {
     ignoreUrlStr: [ [length]: 0 ],
     ignoreUrlRegExp: [ [length]: 0 ],
     ignoreUserAgentStr: [ [length]: 0 ],
     ignoreUserAgentRegExp: [ [length]: 0 ],
     abortedErrorThreshold: 25,
     active: true,
     addPatch: undefined,
     apiRequestSize: 786432,
     apiRequestTime: 10,
     asyncHooks: true,
     breakdownMetrics: true,
     captureBody: 'all',
     captureErrorLogStackTraces: 'messages',
     captureExceptions: true,
     captureHeaders: true,
     captureSpanStackTraces: true,
     centralConfig: true,
     containerId: undefined,
     disableInstrumentations: [ [length]: 0 ],
     environment: 'production',
     errorMessageMaxLength: 2048,
     errorOnAbortedRequests: false,
     filterHttpHeaders: true,
     globalLabels: undefined,
     instrument: true,
     instrumentIncomingHTTPRequests: true,
     kubernetesNamespace: undefined,
     kubernetesNodeName: undefined,
     kubernetesPodName: undefined,
     kubernetesPodUID: undefined,
     logLevel: 'trace',
     logUncaughtExceptions: false,
     metricsInterval: 30,
     metricsLimit: 1000,
     serviceNodeName: undefined,
     serverTimeout: 30,
     sourceLinesErrorAppFrames: 5,
     sourceLinesErrorLibraryFrames: 5,
     sourceLinesSpanAppFrames: 0,
     sourceLinesSpanLibraryFrames: 0,
     stackTraceLimit: 50,
     transactionMaxSpans: 500,
     transactionSampleRate: 1,
     usePathAsTransactionName: false,
     verifyServerCert: true,
     serviceName: 'Elk Stack',
     serverUrl: 'http://apm-server:8200',
     serviceVersion: '1.0.0',
     logger:
      { trace:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        debug:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        info:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        warn:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        error:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        fatal:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } } },
     transport:
      { [Function: httpTransport]
        [length]: 2,
        [name]: 'httpTransport',
        [prototype]: httpTransport { [constructor]: [Circular] } },
     serverHost: 'apm-server:8200',
     serverPort: 8200 } }
adding hook to Node.js module loader`

I got this log after connection the node js agent to apm-server

**Comment by dedekrnwan** [comment]
I have fixing this case, i put apm-server connection to the first of my server.ts. `import 'localenv'` is the suspect of this case. thanks for the response in this case.
