### ISSUE TITLE
Unexpected APM Server response when polling config not a compatible Kibana version

### ISSUE THREAD

**Issue by kevcodez** [elastic/apm-agent-nodejs#1561]
We are using Elastic Cloud 7.5. When booting up our Node.JS application that uses the APM agent, we get the following error

> APM Server transport error (503): Unexpected APM Server response when polling config                                                                                                                                                              12:12:14
not a compatible Kibana version: min version 7.5.0, configured version 7.4.1

Do we need to configure something or does this library need an update?

**Comment by lreuven** [comment]
Thanks for reporting the issue,
which apm server version do you use?

**Comment by kevcodez** [comment]
@lreuven 7.5.0

**Comment by axw** [comment]
@kevcodez did you upgrade an existing 7.4.1 cluster to 7.5.0? I'm assuming so. I just tested this, and reproduced the issue. I've filed a bug against the server: https://github.com/elastic/apm-server/issues/3022

Assuming it's the same scenario as yours, you can fix the issue by hitting "Force Restart" on the APM tab in the Elastic Cloud UI.

**Comment by kevcodez** [comment]
@axw I did. Thanks for the hint, I will try that.

**Comment by lreuven** [comment]
@kevcodez any update? 
if there is no update in the coming 3 days we will close the issue.
Thanks for your help.

**Comment by kevcodez** [comment]
Forcing a restart fixed it. Sorry for the late response.
