### ISSUE TITLE
Shipping Logs to Elastic Cloud

### ISSUE THREAD

**Issue by matthew1534** [elastic/apm-agent-nodejs#1563]
Can this module be used to ship logs to Elastic Cloud something similar to the [logzio-nodejs](https://github.com/logzio/logzio-nodejs) module? If not, is there some other way this can be done?

Background: we are on Google Cloud Platform but cannot use Google Stackdriver for any logging due to it potentially storing/transferring logs outside of the EU so we cannot use the [Filebeat Google Cloud Module](https://www.elastic.co/guide/en/beats/filebeat/7.5/filebeat-module-googlecloud.html) to ship the logs to Elastic Cloud (and we would rather not have a non-serverless product i.e. VM, running just to ship the logs if possible). We are using Google's serverless products which seem to so far work well with this module - thanks! :)

_Apologies if this isn't the right place to post this_

Many thanks, Matthew

**Comment by axw** [comment]
The APM agents aren't designed for sending logs - only traces and metrics at the moment. I'll close this issue. I'd recommend opening a topic at https://discuss.elastic.co/c/logs

It sounds to me like GCP support for Functionbeat (https://github.com/elastic/beats/issues/14362) might be what you need.

In the mean time, maybe you could use something like https://www.npmjs.com/package/winston-elasticsearch or https://github.com/pinojs/pino-elasticsearch? Elastic Cloud gives you direct access to Elasticsearch, so you can index logs directly using the Elasticsearch REST API.
