### ISSUE TITLE
Agent doesn't report GraphQLError

### ISSUE THREAD

**Issue by lreuven** [elastic/apm-agent-nodejs#1590]
> it seems that the agent gets a bit confused because that object appears not to be a native Error type, and so the agent represents it as a log message rather than an exception

thanks @axw 

if you call apm.captureError(err.originalError), that does have a stack trace. 

have a look at : 
https://discuss.elastic.co/t/capturing-stack-traces-from-graphqlerrors-in-apollo-server/212563/1

**Comment by brianstebar2** [comment]
Thanks for opening this ticket!  Let me know if there's any more information I can provide that'd be useful.

**Comment by lreuven** [comment]
it's in our backlog but  it might take some time till we fix it

**Comment by brianstebar2** [comment]
@lreuven: If there's anything I can do to accelerate the process, please let me know.  We're trying to avoid needing to implement a separate solution for capturing stack traces, and this functionality is entirely broken within the agent for Apollo.

As a side note: does Elastic not provide SLAs regarding customer-reported defects?  I've seen similar SLAs provided by other SaaS vendors (either where I've been a customer or an employee).   I'd be surprised if a software company of Elastic's size didn't follow such a practice.

**Comment by lreuven** [comment]
@brianstebar2 regarding SLAs, please take a look over https://www.elastic.co/guide/en/cloud/current/ec-get-help.html. We aim to fix bugs as soon as we can, but we can't provide a guaranteed time frame. Critical issues will be prioritized higher, but this needs to happen through the support channel.
If you'd like to accelerate the process further, we would welcome any contributions you have, whether they're code fixes or additional analysis.

**Comment by watson** [comment]
Released in v3.5.0
