### ISSUE TITLE
Add support for numeric and boolean labels

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-nodejs#1598]
**Is your feature request related to a problem? Please describe.**

Since APM Server 6.7, labels can have numerical or boolean values. We should add support for these in the agent's API, which currently supports only string values (non-string values are stringified).

**Describe the solution you'd like**

[`setLabel`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/transaction-api.html#transaction-set-label) and [`addLabels`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/transaction-api.html#transaction-add-labels) should accept numeric and boolean values, and should not stringify them.

Just changing the behaviour would be a breaking change (particularly because they would end up as different Elasticsearch field types, causing indexing to fail), so that change would have to be done with a major version bump.

**Describe alternatives you've considered**

If waiting for a major version bump is too much, then we could add parameters to the functions that instruct them to not stringify values. Those parameters would be removed in a future major version, and the behaviour would be switched so stringification is not applied by default.

**Additional context**
https://www.elastic.co/guide/en/apm/get-started/current/metadata.html#labels-fields

**Comment by ddolcimascolo** [comment]
Ah! I've just been hit by this :disappointed:  
Any plan to allow numeric/booleans labels in the near future ?

**Comment by ddolcimascolo** [comment]
Hopefully this can be integrated in a minor release soon! https://github.com/elastic/apm-agent-nodejs/pull/1909
