### ISSUE TITLE
Duplicate Span for all Request

### ISSUE THREAD

**Issue by arunp-motorq** [elastic/apm-agent-nodejs#1606]
**Describe the bug**

Am using elastic apm agent in my express js app. For all the request I see exactly 2x the number of spans. All settings are default. All these spans are calls to a NoSQL database ( Azure cosmos db). I checked for multiple request and all of them had 100% duplicate spans

**To Reproduce**

Steps to reproduce the behavior: 
1. Using the default config . 
2. Using the latest stable version of npm - 3.3.0 

**Expected behavior**

**Environment (please complete the following information)**

- OS: Windows 
- Node.js version: 10.
- APM Server version:  7.5
- Agent version: 3.3.0

**How are you starting the agent? (please tick one of the boxes)**

- [*] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

**Comment by lreuven** [comment]
Can you provide some additional info /code examples?
we can't reproduce the issue

**Comment by trentm** [comment]
@arunp-motorq Please re-open this ticket if you are able to repro and provide some code examples.
