### ISSUE TITLE
Daily schedule job can not show the downstream job link

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-nodejs#1607]
```
[2020-01-28T04:05:45.513Z] [INFO] Can not determine redirect link!!!
Cannot invoke method resultIsWorseOrEqualTo() on null object
```

<img width="1128" alt="Screenshot 2020-01-28 at 10 11 59" src="https://user-images.githubusercontent.com/5400788/73250181-a8332980-41b6-11ea-8fbd-5fa75f23b4f9.png">

**Comment by v1v** [comment]
This is now solved:
- https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-schedule-daily/detail/apm-agent-nodejs-schedule-daily/152/pipeline/29

In a nutshell, the build step in the CI Jenkinsfile is overridden and the `wait: false` argument returns a null object that was not handled correctly.
