### ISSUE TITLE
Edit an ended span

### ISSUE THREAD

**Issue by jremerich** [elastic/apm-agent-nodejs#1608]
Hi!

The agent sends all queries executed on Postgres very well, but in some cases I'd like to edit the span adding labels and changing the name, but as the agent has ended the span I don't abble to set this properties.

How can I do this?

Thanks!

**Comment by trentm** [comment]
@jremerich Hi. I realize this answer is coming *years* later.  

In general, after a span has ended it may have already been sent on to APM server and won't be looked at again, so any modifications to the Span object will not change anything. There is, however, a [`apm.addSpanFilter(...)`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-add-span-filter) Agent API that can be used to specify a function that can modify the serialized Span data before it is sent to APM server. On the off chance this is at all still relevant to you, hopefully that API is helpful.

**Comment by jremerich** [comment]
Nice to know this!

I'm using a span that wraps the query execution as workarround.. But your instruction looks better.

Thanks for your reply!!
