### ISSUE TITLE
node app cratch when [zlib binding closed]

### ISSUE THREAD

**Issue by rambo-panda** [elastic/apm-agent-nodejs#1625]
**Describe the bug**

```
AssertionError [ERR_ASSERTION]: zlib binding closed
    at processChunk (zlib.js:541:5)
    at Gzip._transform (zlib.js:444:3)
    at Gzip.Transform._read (_stream_transform.js:190:10)
    at Gzip.Readable.read (_stream_readable.js:452:10)
    at flow (_stream_readable.js:922:34)
    at pipeOnDrainFunctionResult (_stream_readable.js:734:7)
    at cleanup (_stream_readable.js:660:7)
    at ClientRequest.onunpipe (_stream_readable.js:621:9)
    at ClientRequest.emit (events.js:182:13)
    at Gzip.Readable.unpipe (_stream_readable.js:762:12)
    at unpipe (_stream_readable.js:711:9)
    at ClientRequest.onclose (_stream_readable.js:699:5)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at Socket.socketCloseListener (_http_client.js:348:9)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:606:12)
```
This is the logs  caught:
```
APM Server transport error (503): Unexpected APM Server response
APM Server accepted 0 events in the last request
Error: queue is full
```

**Environment (please complete the following information)**

- OS: [e.g. Linux] CentOS Linux release 7.5.1804 (Core)
- Node.js version: v10.13.0
- APM Server version: 7.4
- Agent version: 3.3.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
   {
    "active": true,
    "serverUrl": "http://10.6.0.167:8200",
    "serviceName": "test",
    "captureBody": "all",
    "logEvel": "error,",
    "metricsInterval": 0,
    "captureErrorLogStackTraces": "always",
    "transactionSampleRateedit": 0.5,
    "globalLabels": { "env": "production"}
   }
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    {
       "dependencies": {
        "elastic-apm-node": "3.3.0",
        "koa": "2.5.2"
        }
    }
    ```
  </details>

**Comment by lreuven** [comment]
Hi,
When the APM Server's queue has reached the maximum size, APM Server returns an HTTP 503 status with the message "Queue is full".
this might happen for a few reasons, have a look [here](https://www.elastic.co/guide/en/apm/server/master/common-problems.html#queue-full) - it should cover it.
let us know if it reproduces after the changes.

**Comment by rambo-panda** [comment]
Yes
shortly after receiving the "queue is full" alarm, I also received a hard disk alarm :cry:

By the way, how to avoid `AssertionError [ERR_ASSERTION]: zlib binding closed` problems?

I initially suspect it is the problem here
```js
// elastic-apm-http-client/index.js
function destroyStream (stream) {
 ...
    if (typeof stream.destroy === 'function') {
      // Manually close the stream instead of calling `close()` as that would
      // have emitted 'close' again when calling `destroy()`
      if (stream._handle && typeof stream._handle.close === 'function') {
        stream._handle.close()
        stream._handle = null
      }

      stream.destroy()
    } else if (typeof stream.close === 'function') {
      stream.close()
    }
  } 
...
}
```

**Comment by rambo-panda** [comment]
may I ask you a question?

I see a lot of uses like this in your code:
```js
  var zlib
  try { zlib = require('zlib') } catch (err) { }
```
why add protection to nodejs internal modules?

**Comment by lreuven** [comment]
Did you manage to work out the full disk issue?

**Comment by lreuven** [comment]
Hi 
closing this issue, if it reproduces - let us know.
