### ISSUE TITLE
Add config option to set a max number of spans a transaction can have

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#163]
By default all spans that happen during a transaction should be recorded and sent to the APM Server. But the user should be able to configure the agent with a max number of spans that an individual transaction can have. If that number if reached, any subsequent spans should be dropped, but the transaction should still be sent to the APM Server (just without the dropped spans).

We should keep track of how many spans are dropped per transaction and add the count using the following JSON to the transaction in the APM Server intake API payload:

```json
"span_count": {
  "dropped": {
    "total": <number-of-dropped-spans>
  }
}
```

The config option should be called `transactionMaxSpans`.

Target branch: `master`

Related PR on APM Server: elastic/apm-server#448

### To do

- [ ] Implement code
- [ ] Add tests
- [ ] Update docs

**Comment by Qard** [comment]
PR is: #170

**Comment by Qard** [comment]
Additional PR for count reporting is: 172
