### ISSUE TITLE
Need a guide to handling outgoing graphQL request

### ISSUE THREAD

**Issue by pawsong** [elastic/apm-agent-nodejs#1631]
**Is your feature request related to a problem? Please describe.**
We are considering using elastic APM to monitor our next.js + apollo app. The app fires multiple graphql requests but the requests are recorded on APM server as plain http requests.

**Describe the solution you'd like**
Want to see at least the graphql query names on Kibana.

**Describe alternatives you've considered**
Tried to monkey patch this library.

https://github.com/elastic/apm-agent-nodejs/blob/c56f894138c81f0b07146f86c3ba7139bb68a59c/lib/instrumentation/http-shared.js#L173

**Additional context**
<img width="1174" alt="스크린샷 2020-02-15 오후 12 23 32" src="https://user-images.githubusercontent.com/2945463/74581049-187edf00-4fee-11ea-916d-a2e3eb11815a.png">

**Comment by watson** [comment]
Which library are you using to make the outgoing GraphQL requests?

This agent currently supports the instrumenting GraphQL requests made by the [graphql](https://www.npmjs.com/package/graphql) module (see the patch code in https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/graphql.js).

**Comment by lreuven** [comment]
@pawsong any additional details? 
please note that we will close the issue if there are not additional details.

**Comment by pawsong** [comment]
@lreuven We could track the request detail after we installed apm on graphql api server. The issue can be closed. Thanks
