### ISSUE TITLE
Show metrics on kibana

### ISSUE THREAD

**Issue by pawsong** [elastic/apm-agent-nodejs#1635]
**Is your feature request related to a problem? Please describe.**
I tried to find event loop metric graph on Kibana APM section, but had no luck. And found the metric graph is hard-coded per agent type like this:

https://github.com/elastic/kibana/blob/06bee6051258009cca6c0c92fa1362c56823e734/x-pack/legacy/plugins/apm/server/lib/metrics/get_metrics_chart_data_by_agent.ts#L30

There is no specified metric graphs except java.

**Describe the solution you'd like**
Want to see nodejs specific metrics on Kibana

**Comment by lreuven** [comment]
Hi,
Have a look at this repo : https://github.com/elastic/apm-contrib/tree/master/apm-agent-nodejs/dashboards .
Feel free to enrich and contribute back :)
