### ISSUE TITLE
Don't use dummy transaction name if it's unknown

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#167]
For reference see elastic/apm-server#425

**Comment by watson** [comment]
@roncohen If we don't change anything we'll be backwards compatible with older versions of the APM Server, but if we stop sending up "unnamed" as we do today in case there's no name, the agent will stop working with older APM Servers. How should we deal with this?

**Comment by roncohen** [comment]
@watson i don't have a strong preference either way

**Comment by watson** [comment]
It would be nice if we had a way to check which version of the APM Server we were running. Or maybe if we had a config option where the user could specify the version. That way we can tailor the request to the right version and not break backwards compatibility

@elastic/apm-agent-devs do any of you have experience with or thoughts on this?

**Comment by mikker** [comment]
Every time we've talked about having the apm-version visible from the outside, @beniwohli has mentioned that this might be a security risk.

Every time there's a crack in a specific Wordpress version the web is thoroughly scanned for websites running that version. We might make ourselves vulnerable to stuff like that.

**Comment by beniwohli** [comment]
We have versioned APIs, why not bump the version number if the API changes?

We would need to agree on which side maintains backwards compatibility with older api versions (for totally unbiased reasons, I think the server is the right place, doing it in the agents multiplies the necessary work by the number of agents).

**Comment by jahtalab** [comment]
I also think that we should use the API version number, using apm-server version doesn't make sense IMO.

If I remember correctly when we had this discussion before, we decided that apm-server would deprecate one API version in a major `apm-server` version and remove it in the next major version.

**Comment by watson** [comment]
Now that 6.3 we can technically implement this in the Node.js agent as well. But as mentioned that would break compatibility with 6.2. So unless someone have a good solution on how to deal with this, I vote that we just close this issue and keep sending up `unnamed` in cases where we don't have a transaction name.

**Comment by Qard** [comment]
Yeah, I think it's best we keep sending it for awhile to give people plenty of time to update apm-server instances.
