### ISSUE TITLE
require vs import

### ISSUE THREAD

**Issue by sibelius** [elastic/apm-agent-nodejs#1671]
**Describe the bug**

Not sure if this is a bug or it is by design

Can I use apm using `import` syntax?, like this:

```jsx
import apm from 'elastic-apm-node';
```

or I need to use `require`?

`const apm = require('elastic-apm-node').start()`

**Comment by watson** [comment]
Yes, you can read about how to use the agent with Babel, TypeScript or ES Modules here:
https://www.elastic.co/guide/en/apm/agent/nodejs/current/es-modules.html
