### ISSUE TITLE
Implement transaction_ignore_urls

### ISSUE THREAD

**Issue by lreuven** [elastic/apm-agent-nodejs#1689]
See [elastic/apm#144](https://github.com/elastic/apm/issues/144)

**Comment by trentm** [comment]
IIUC, this needs the kibana changes under https://github.com/elastic/kibana/tree/master/x-pack/plugins/apm/common/agent_configuration/

**Comment by trentm** [comment]
kibana changes:
- master: https://github.com/elastic/kibana/pull/85655
- 7.x: https://github.com/elastic/kibana/pull/85798
