### ISSUE TITLE
ApiKey authentication

### ISSUE THREAD

**Issue by hpinhal** [elastic/apm-agent-nodejs#1693]
**Describe the solution you'd like**
Support for ApiKey-based agent authentication.

The GO agent already supports this feature. [Source](https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html#config-api-key)

Willing to help if needed.

**Comment by lreuven** [comment]
Hi,
we will be happy with the contribution,
will review once you submit the PR
thanks

**Comment by gergof** [comment]
I will take care of this issue. I already opened a PR in the apm-nodejs-http-client repo to resolve this and I will open a PR here as well.
https://github.com/elastic/apm-nodejs-http-client/pull/110
