### ISSUE TITLE
[Discussion] Codecov vs. alternatives

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-nodejs#1705]
Hi all,

This issue is being filed to discuss how coverage reports should work for this project. Right now, I believe codecov is still configured. Some of the other agent projects have migrated to using Cobetura instead. (https://github.com/elastic/apm-agent-ruby/pull/736 and https://github.com/elastic/apm-agent-python/pull/735)

Is a migration to Cobetura something that is of interest for this project as well? Or are we happy with the way things are currently? Let us (@elastic/observablt-robots ) know. Thanks!

**Comment by watson** [comment]
I haven't personally had any issue with using codecov. What's the benefit of using Cobetura?

**Comment by cachedout** [comment]
Hi @watson Some teams have reported problems with CodeCov, such as incorrect results. (@beniwohli can likely impart more specifics than I could on this point.)

If you don't have any issue with CodeCov, however, there is likely not a compelling reason to change.
