### ISSUE TITLE
Compatibility with Node.js v14

### ISSUE THREAD

**Issue by aayani** [elastic/apm-agent-nodejs#1723]
The package doesn't seem to be working with the new version of Node. Any chance for a near update?

**Comment by lreuven** [comment]
Hi,
thanks for the feedback.
@vigneshshanmugam can you have a look?

**Comment by sibelius** [comment]
check the latest version

**Comment by vigneshshanmugam** [comment]
The latest version `3.6.0` supports Node.js  v14

**Comment by aayani** [comment]
Great job guys
