### ISSUE TITLE
Add public function to flush transaction queue

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#173]
The agent maintains an in-memory queue of recorded transactions which is sent to the APM server and emptied periodically. Currently [a private function exists](https://github.com/elastic/apm-agent-nodejs/blob/a3506ff59c4b01c14a5d97416ae03edb6e3494df/lib/instrumentation/queue.js#L51-L55) which the agent uses internally to flush the queue.

It would make sense to make this function public, so that users of the agent can call it as well - e.g.  before shutdown of the process (the agent could also hook into the process shutdown procedure to automate this task, but that's a separate issue).

This would also make our test suite better as it's never a good idea to use private functions in a test, which we currently do all over the place to force a flush of the queue during testing.

Suggestions for function name:

- `agent.flush()`
- `agent.flushQueue()`
- `agent.flushTransactionQueue()` - If we later include other things than transactions in the queue, this might be a bad name

### To-do

- [ ] Implement code
- [ ] Make tests
- [ ] Update agent API documentation

**Comment by watson** [comment]
@elastic/apm-agent-devs if you don't have this feature already, maybe consider something similar

**Comment by Qard** [comment]
PR is: #187
