### ISSUE TITLE
Expose Typescript Types

### ISSUE THREAD

**Issue by byronferguson** [elastic/apm-agent-nodejs#1737]
**Is your feature request related to a problem? Please describe.**
While trying to build a good wrapper for this library to use within NestJS I don't have access to all of the appropriate typings.

**Describe the solution you'd like**
I would like the types be exported out of the package to be made available for accurate/detailed typing within 3rd party libraries.

**Describe alternatives you've considered**
Copy-paste of the source code into my own project isn't a valid sustainable solution.

**Comment by watson** [comment]
I'm not that familiar with how this would be done as I haven't used TypeScript much. Do you have an example of another package that does this?

**Comment by ffknob** [comment]
> I'm not that familiar with how this would be done as I haven't used TypeScript much. Do you have an example of another package that does this?

I'm also no Typescript specialist, but I wonder if it's not just exporting everything from `index.d.ts`. At least I did it here (in my `node_modules/elastic-apm-node/index.d.ts`) and now I'm able to:

```
import {
    Transaction,
    LabelValue,
    CaptureErrorCallback,
    UserObject,
    CaptureErrorOptions,
    TransactionOptions,
    SpanOptions,
    Span
} from 'elastic-apm-node';
```

Anyway, i've opened a PR for this, but again, not sure how bad things could get with this approach.

https://github.com/elastic/apm-agent-nodejs/pull/1775

**Comment by ffknob** [comment]
A possible workaround until thos types are exported:

1. Copy `node_modules/elastic-apm-node/index.d.ts` to `src/types/apm.d.ts`
2. Include the following in the `compilerOptions` of your `tsoconfig.json`: 

```
    "typeRoots": [
      "./src/types",
      "./node_modules/@types"
    ],
```
3. Edit `src/types/apm.d.ts` and remove the `export = Agent` line
4. Edit `src/types/apm.d.ts` and `export` each type from there
5. Create a `src/types/index.d.ts` file with this:

```
/// <reference path="apm.d.ts" />
```
6. Try to import something from APM in one of your `.ts` files:

```
import {
    Transaction,
    LabelValue,
    CaptureErrorCallback,
    UserObject,
    CaptureErrorOptions,
    TransactionOptions,
    SpanOptions,
    Span,
    Agent
} from '../shared/types/apm'; // TODO: in the future maybe from 'elastic-apm-node';

Make sense?
```

**Comment by walez** [comment]
Please any update on this? not exposing the type makes it very difficult to mock apm on typescript projects

**Comment by opravil-jan** [comment]
Hi,

what can I do to make this PR be merged, please?

Thanks

**Comment by MateiNenciu** [comment]
Yes, works perfect for me now. Thanks !

**Comment by trentm** [comment]
@MateiNenciu thanks!
