### ISSUE TITLE
Automatically flush transaction queue on process exit

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#174]
By default the in-memory transaction queue is sent to the APM Server every minute. When the Node.js process is terminated, any transactions that is still in the queue is lost. We should look into if it would make sense to automatically sent the remaining transactions to the APM Server when the process exits.

**Comment by Qard** [comment]
I think this is an "it depends" situation. We're already intercepting `uncaughtException` events to report errors, it's possible we could just delay `process.exit(...)` and report _anything_ in the queue.

The question is, could there be scenarios where delaying the exit is unsafe? What about differences between kill codes? Holding the process open on `SIGHUP` is probably fine, but what would be expected with `SIGINT`, `SIGKILL` or `SIGTERM`?

**Comment by watson** [comment]
At some point I'd like to send the collected metrics to a different thread synchronously so that we don't have this problem. This will also fix the `uncaughtException` issue you mention.

But you're right that it's an "it depends" situation. In those situation the right answer is often to not deal with it and let the user handle it instead. So maybe that's the answer here as well? We have an API that allows the user to implement this feature them selfs. So maybe all we need to do for now is just mention in our docs that the user needs to do this them selfs?

**Comment by watson** [comment]
Let's just write good documentation on how the users can do this them selfs. We'll close this issue and open another to write the documentation
