### ISSUE TITLE
Use lower default value for flushInterval config option

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#175]
The [`flushInterval`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#flush-interval) config option currently defaults to 60 seconds. This is too long and we should decide on a better default.

**Comment by watson** [comment]
All the backend agents might consider to use the same new default interval /cc @elastic/apm-agent-devs

**Comment by beniwohli** [comment]
I vote for 10 seconds

**Comment by mikker** [comment]
10

**Comment by watson** [comment]
Thanks 😃

**Comment by Qard** [comment]
PR is: #186
