### ISSUE TITLE
TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by grahamrhay** [elastic/apm-agent-nodejs#1769]
**Describe the bug**

Seeing an error when making a request using a proxy:

```
TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: http://127.0.0.1:3128http://foo.com/...
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at exports.parseUrl (.../node_modules/elastic-apm-node/lib/parsers.js:247:10)
    at exports.getHTTPDestination (.../node_modules/elastic-apm-node/lib/instrumentation/context.js:14:48)
    at IncomingMessage.onEnd (.../node_modules/elastic-apm-node/lib/instrumentation/http-shared.js:212:38)
    at IncomingMessage.elasticAPMCallbackWrapper (.../node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  input: 'http://127.0.0.1:3128http://foo.com/...',
  code: 'ERR_INVALID_URL'
}
```

The proxy url appears to have been prepended to the actual url?

Request options:

```
{"uri":"http://foo.com/...","method":"POST","json":true,"body":{},"proxy":"http://127.0.0.1:3128","timeout":15000}
```

**To Reproduce**

Make a request using a proxy

**Expected behavior**

Not a crash (unhandled error took down the process)

**Environment (please complete the following information)**

- OS: Debian 9
- Node.js version: v12.16.3
- APM Server version: 7.6.1
- Agent version: 3.5

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Using env vars for config

**Comment by watson** [comment]
Thanks for reporting this bug. I can see how this could happen, unfortunately: The agent doesn't take into account that the `path` segment of the HTTP request can contain the domain name as well, which can be the case with some proxies.

The agent uses the module `http-request-to-url` to extract destination URL from the request object. I'm working on finding a good solution to this problem: https://github.com/Qard/http-request-to-url/issues/1

**Comment by gabe0x02** [comment]
Looks like I've run into this issue while trying add APM to our service.  Any chance the #1771 will get merged?

**Comment by gabe0x02** [comment]
Or failing that, any ideas for a work around?   My proxied request is throwing and exception in the apm module which is not being handled and causing my process to just exit:
```
Sending error to Elastic APM { id: 'a8df8c4fb111dc9f73933570342aafa3' }
Process exited with status 1
State changed from up to crashed
```
<img width="1233" alt="Screen Shot 2020-07-15 at 1 34 40 PM" src="https://user-images.githubusercontent.com/154245/87593461-574db980-c6a0-11ea-9087-e6dc4baa802a.png">
