### ISSUE TITLE
GraphQL tests fail

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-nodejs#1776]
**Describe the bug**

Since May 28th some graphQL tests are failing without any code change or any CI change, we tested it locally and it fails also with the same failure, we testes Node.js 12.17.0 (26-May-2020 ), Node.js 12.10.0(Sep 2019), and Node.js 12.18.0 (02-Jun-2020) We tracked one of the tests and the calls it makes, and should not fail and we do not have a proper explanation for that

The test call (test/instrumentation/modules/apollo-server-express.js:198)
```
test('POST /graphql - sub-query', function (t) {
  resetAgent(done(t, 'books'))
```

The done function (test/instrumentation/modules/apollo-server-express.js:261)
```
function done (t, query) {
  return function (data, cb) {
    t.strictEqual(data.transactions.length, 1)
    t.strictEqual(data.spans.length, 1)
    var trans = data.transactions[0]
    var span = data.spans[0]
    t.strictEqual(trans.name, query + ' (/graphql)')
```

and the test failed with

```
node_tests_1     |     operator: equal
node_tests_1     |     expected: 'books (/graphql)'
node_tests_1     |     actual:   'POST /graphql'
```

What bothers me it is the  'POST /graphql' is the test name but not the query parameter passed ('books') Why the transaction name changed of format without changes in code.

**To Reproduce**

Steps to reproduce the behavior: 
1. nvm install 12.18.0
2. npm install
3. node test/test.js

```
TAP version 13
# POST /graphql
ok 1 have active transaction
ok 2 should be strictly equal
ok 3 should be strictly equal
ok 4 should be strictly equal
not ok 5 should be strictly equal
  ---
    operator: equal
    expected: 'hello (/graphql)'
    actual:   'POST /graphql'
    at: <anonymous> (/Users/inifc/src/apm-agent-nodejs/test/instrumentation/modules/apollo-server-express.js:269:7)
    stack: |-
      Error: should be strictly equal
          at Test.assert [as _assert] (/Users/inifc/src/apm-agent-nodejs/node_modules/tape/lib/test.js:260:54)
          at Test.bound [as _assert] (/Users/inifc/src/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
          at Test.strictEqual (/Users/inifc/src/apm-agent-nodejs/node_modules/tape/lib/test.js:424:10)
          at Test.bound [as strictEqual] (/Users/inifc/src/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
          at /Users/inifc/src/apm-agent-nodejs/test/instrumentation/modules/apollo-server-express.js:269:7
          at Object._write (/Users/inifc/src/apm-agent-nodejs/test/_mock_http_client.js:27:50)
          at Object.sendSpan (/Users/inifc/src/apm-agent-nodejs/test/_mock_http_client.js:31:12)
          at /Users/inifc/src/apm-agent-nodejs/lib/instrumentation/index.js:240:46
          at done (/Users/inifc/src/apm-agent-nodejs/lib/instrumentation/span.js:168:5)
          at /Users/inifc/src/apm-agent-nodejs/lib/instrumentation/span.js:131:16
          at /Users/inifc/src/apm-agent-nodejs/node_modules/async-value-promise/index.js:30:27
          at AsyncValue.set (/Users/inifc/src/apm-agent-nodejs/node_modules/async-value/index.js:30:7)
          at AsyncValuePromise.resolve (/Users/inifc/src/apm-agent-nodejs/node_modules/async-value-promise/index.js:60:18)
          at /Users/inifc/src/apm-agent-nodejs/lib/instrumentation/span.js:115:39
          at /Users/inifc/src/apm-agent-nodejs/node_modules/after-all-results/index.js:20:25
          at processTicksAndRejections (internal/process/task_queues.js:79:11)

```

**Expected behavior**

the test should pass

**Environment (please complete the following information)**

- OS: Linux, MacOS
- Node.js version: 12.10.0 ,12.17.0, 12.18.0 
- APM Server version: NONE
- Agent version: master branch

**How are you starting the agent? (please tick one of the boxes)**

- ~[ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)~
- ~[ ] Requiring `elastic-apm-node/start` from within the source code~
- ~[ ] Starting node with `-r elastic-apm-node/start`~

**Comment by kuisathaverat** [comment]
@watson Do you have any idea what it could be related to?

**Comment by watson** [comment]
Update: I think it's related to a new release of `apollo-server-core` (version 2.14.0) which broke our instrumentation
