### ISSUE TITLE
Support knex >= 0.21.0

### ISSUE THREAD

**Issue by amd032** [elastic/apm-agent-nodejs#1786]
I have found this line in the code
https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/knex.js#L10

It was written 8 months ago. 
Knex released version at that time was 0.20.0, now latest knex is 0.21.1

Could you check if it's really needed to block latest knex? Maybe it's already compatible with your product?

**Comment by vigneshshanmugam** [comment]
@amd032 Do you want to give a PR?

**Comment by amd032** [comment]
I wasn't aware I can :)
If you want me to provide a branch and PR, I sure can do it.

**Comment by JCMais** [comment]
@amd032 just in case you don't have the time to create the PR please let me know as I should be able to.

**Comment by amd032** [comment]
@JCMais thanks, please do the change. I have quite busy time now.
