### ISSUE TITLE
Calling registerMetric() throws when active: false

### ISSUE THREAD

**Issue by MartinKolarik** [elastic/apm-agent-nodejs#1799]
**Describe the bug**

The exception is the same as in #1257.

**Environment (please complete the following information)**
- OS: Windows 10
- Node.js version: 14
- APM Server version: N/A
- Agent version: 3.6.1

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by MartinKolarik** [comment]
Just an update - this bug is still present in the current version.

**Comment by astorm** [comment]
Thanks for re-bringing this to our attention @MartinKolarik -- we're better staffed these days :)

We've got a PR going to get this issue fixed: https://github.com/elastic/apm-agent-nodejs/pull/2290  -- If you have a moment and could test out the PR branch and confirm that it solves your issue we'd appreciate it (no worries if not though).

**Comment by MartinKolarik** [comment]
Yes, #2290 fixes it, thanks!

**Comment by trentm** [comment]
elastic-apm-node@3.21.0 is now published with this fix.
