### ISSUE TITLE
Redis support > 2.0.0

### ISSUE THREAD

**Issue by ashrafuzzaman** [elastic/apm-agent-nodejs#1806]
**Is your feature request related to a problem? Please describe.**
I have been having issues running APM with asyncHooks to true. After a lot of investigation, I found that redis version was the cause of that issue. apm only supports redis 2 and the latest version is > 3. It is frustrating that with any other version of redis the 
asyncHooks does not work and without asyncHooks it is not reliable.

**Describe the solution you'd like**
Support the latest version of Redis plugin.

**Describe alternatives you've considered**
The aulternative is to stuck with redis 2.0, but I fear in a project where a lot of engineers work. People will not know, not to upgrade redis client to a later version.

**Comment by trentm** [comment]
@ashrafuzzaman Sorry for the delay in responding. Thank you for the ticket!

In version 3.7.0 of the agent (on 2020/8/10) support for instrumenting redis@3 was added. You'll want version 3.8.0 (released on 2020/11/09) which fixed a bug in v3.7.0 that accidentally broke redis@2 instrumentation. The current latest version of the APM agent should support redis@2 and redis@3.

Please let us know if that isn't the case for you.
