### ISSUE TITLE
'npm run lint:commit' fails in clone without a local commit

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#1808]
**Describe the bug**

Running `npm run lint:commit` fails in "master" in a git clone that hasn't made any local commits. This is also run by `npm test` so is a slight stumbling block for newbies (such as myself) trying out the test suite. @Qard already open an upstream bug on commitlint >1y ago (https://github.com/conventional-changelog/commitlint/issues/589). Would you be interested in a PR something like the following to work around it here?

```
--- a/test/lint-commits.sh
+++ b/test/lint-commits.sh
@@ -16,8 +16,10 @@ elif [[ -z "$CI" ]]; then
   GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

   if [[ "$GIT_BRANCH" == "master" ]]; then
-    # If on master, just test the latest commit
-    commitlint --edit
+    # If on master, just test the latest local commit, if there is one.
+    # Remove the '-f ...' guard if/when conventional-changelog/commitlint#589

+    # is fixed.
+    [[ ! -f .git/COMMIT_EDITMSG ]] || commitlint --edit
   else
     # If on a branch, test all commits between this branch and master
     commitlint --from=master
```

**To Reproduce**

1. Make a new fresh clone: `git clone git@github.com:elastic/apm-agent-nodejs.git`
2. Install deps: `cd apm-agent-nodejs; npm install`
3. Run either `npm run lint:commit` or `npm test`:

```
$ npm test
...
> test/lint-commits.sh

+ [[ -n '' ]]
+ [[ -z '' ]]
++ git rev-parse --abbrev-ref HEAD
+ GIT_BRANCH=master
+ [[ master == \m\a\s\t\e\r ]]
+ commitlint --edit
/home/trentm/elastic/apm-agent-nodejs/node_modules/@commitlint/cli/lib/cli.js:124
	throw err;
	^

[Error: ENOENT: no such file or directory, open '/home/trentm/elastic/apm-agent-nodejs/.git/COMMIT_EDITMSG'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/trentm/elastic/apm-agent-nodejs/.git/COMMIT_EDITMSG'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elastic-apm-node@3.7.0 lint:commit: `test/lint-commits.sh`
npm ERR! Exit status 1
...
npm ERR! Test failed.  See above for more details.
```

**Expected behavior**

The lint passes, the test suite passes (at least this step).

**Environment (please complete the following information)**

- OS: Linux and macos
- Node.js version: v14.8.0, v10.20.1
- APM Server version: N/A
- Agent version: latest master (commit 6e487e962d5b488aa6a448a9e64bec9d25fc0915)

**How are you starting the agent? (please tick one of the boxes)**

N/A

**Comment by trentm** [comment]
THis was made obsolete by #1901

**Comment by gkatsanos** [comment]
@trentm how is #1901 fixing this one ? I'm a little confused.

**Comment by trentm** [comment]
@gkatsanos It used to be that running `npm run lint:commit` in this repo on a local branch could fail (if that branch didn't yet have any commits). With #1901 we dropped `npm run lint:commit` completely from this repo -- we are no longer linting commit message format.

**Comment by gkatsanos** [comment]
> @gkatsanos It used to be that running `npm run lint:commit` in this repo on a local branch could fail (if that branch didn't yet have any commits). With #1901 we dropped `npm run lint:commit` completely from this repo -- we are no longer linting commit message format.

Our issue is when we use the - - edit flag on a new local clone of the repo, a file is not found (COMMIT_MSG or something). We use a pre commit hook with `--edit`

**Comment by trentm** [comment]
> Our issue is when we use the `--edit` flag on a new local clone of the repo

@gkatsanos I am confused. Do you mean of *this* repo (apm-agent-nodejs.git)? And the `--edit` flag to what command?  AFAIK this repo isn't using `commitlint` anymore.

**Comment by gkatsanos** [comment]
Indeed, my apologies, I was referring to commitlint.

**Comment by trentm** [comment]
Thanks for clarifying.
