### ISSUE TITLE
[META 319] Align sanitize_field_names option + central config

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-nodejs#1811]
See elastic/apm#319

**Comment by trentm** [comment]
Should this point to https://github.com/elastic/apm/pull/334 now and be on the 7.11 milestone?

**Comment by felixbarny** [comment]
that's correct

**Comment by trentm** [comment]
From @AlexanderWert on #1871:
"Note that the implementation of this also includes adding the option to [Kibana](https://github.com/elastic/kibana/blob/master/x-pack/plugins/apm/common/agent_configuration/setting_definitions/general_settings.ts)."

**Comment by astorm** [comment]
https://github.com/elastic/apm-agent-nodejs/pull/1898. implements this functionality, and closes this out.
