### ISSUE TITLE
Add outcome to transactions and spans

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-nodejs#1814]
see https://github.com/elastic/apm/pull/299

**Comment by astorm** [comment]
Hamid's PR https://github.com/elastic/apm-agent-nodejs/pull/1824. gives transactions and spans an outcome property.  Spans that represent outgoing HTTP transactions  will have their outcome set.  The Transaction

Remaining work/questions

- Are there spans other than those representing an HTTP transactions that represent work with an outcome?  

- Or should we attempt to set outcome on a span if _any_ error occurred during the span of time it represents?

- We need an agent level API for setting the transaction outcome manually?

- Do we want/need to tackle an agent level API for setting the span outcome manually -- what would that even look like given that a span can represent any arbitrary unit of time? (would you always be setting the outcome of the current span? Or would you be walking the span tree to find the span object you wanted? etc.)

**Comment by astorm** [comment]
Merged https://github.com/elastic/apm-agent-nodejs/pull/1968 should bring this to a close.
