### ISSUE TITLE
Collect cloud metadata

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-nodejs#1815]
see https://github.com/elastic/apm/pull/290

see also _current_ spec doc: https://github.com/elastic/apm/blob/3f224a9cbacb196bbb196b0868d9fa90a0bbaf6c/specs/agents/metadata.md#cloud-provider-metadata

**Comment by JCMais** [comment]
How would someone go about implementing this?

From what I can see the metadata itself will need to be added to https://github.com/elastic/apm-agent-nodejs/blob/cde2dde8c896e3f6f8313fa3db66da88106d6397/lib/config.js#L239-L249 (which means adding it to the apm-nodejs-http-client package)

`net.createConnection()` is probably the fastest way to check if the metadata server exists, if it does a connection can be made to retrieve the information. This is basically what was done on the reference implementation: https://github.com/basepi/apm-agent-python/blob/f13110156e57eec99134a7f9342243416b969698/elasticapm/utils/cloud.py#L79-L115

But the biggest "issue" so far, is that the config generation is synchronous. An alternative would be to create the cloud metadata fetcher as a function that accepts a callback and then pass that to `ElasticAPMHttpClient`. Writing to the stream could then be deferred until the callback has been called: https://github.com/elastic/apm-nodejs-http-client/blob/1526dedc26392bd92f20b5079f848c7e77567e7c/index.js#L496-L500

**Comment by felixbarny** [comment]
That sounds like a good plan and is in line with what the spec says:

> Any intake API requests to the APM server should be delayed until this metadata is available.

Any events that are created before the metadata is ready would be buffered in the meantime.

**Comment by JCMais** [comment]
I've started working on this at https://github.com/elastic/apm-agent-nodejs/pull/1816

**Comment by astorm** [comment]
With https://github.com/elastic/apm-agent-nodejs/pull/1937 and https://github.com/elastic/apm-nodejs-http-client/pull/129 landed this work is done, and we be available after the next http client and agent release.
