### ISSUE TITLE
create span using apm.startSpan vs transaction.startSpan

### ISSUE THREAD

**Issue by sinoohe** [elastic/apm-agent-nodejs#1819]
Is there any difference between creating a span using `apm.startSpan` and `transaction.startSpan`?
I'm using a custom framework and there are many routes that are working together simultaneously.
should I pass the `transaction` variable in all nested functions as a parameter? or Am I allowed to call `apm.startSpan` in all inner codes? If this is possible how `APM` can understand in which transaction(that are running simultaneously) does this belong to?

**Comment by astorm** [comment]
Hello @sinoohe, nice to meet you.  The current implementation of `apm.startSpan` will associate itself with the _current_ transaction.  

If we look at the `apm.startSpan` function

https://github.com/elastic/apm-agent-nodejs/blob/master/lib/agent.js#L106

we can see it calls though to `this._instrumentation.startSpan.apply(this._instrumentation, arguments)`, whose definition is here

https://github.com/elastic/apm-agent-nodejs/blob/f9ce63af7a091415246b2a3905c676a13cd37423/lib/instrumentation/index.js#L277

Here we can see that `_instrumentation.startSpan` function will look for the current transaction, and then call its `startSpan` function.

Also to whether you're "allowed" to do it or not -- you're allowed to do anything :)  Keep in mind though that `apm.startSpan` will start a span that's associated with the transaction that's current _when `apm.startSpan` is called_.  Depending on how your code is invoked (synchronously, via a setTimeout callback, via a Promise, etc.) that transaction may or may not be the one you think it is.  

If you want to guarantee that the span is associated with a specific transaction, your best/most-straight-forward bet is to call `startSpan` on the actual transaction object.  

Closing this question out as answered, but if you need more help don't hesitate to let us know.
