### ISSUE TITLE
AWS X-Ray integration in Kibana via HTTP Link

### ISSUE THREAD

**Issue by EUinUkraine** [elastic/apm-agent-nodejs#1820]
**Is your feature request related to a problem? Please describe.**
I'm trying to build e2e trace for AWS Native web-stack
ReacrJS+Apolllo GraphQL
Cloudfront+S3 for ReactJS and AWS API Gateway + NodeJS Lambda for GraphQL.  
I successfully added RUM integration to ReactJS 
and
I have difficulties to report Native Elastic Traces from Lambda via apm-agent-nodejs

**Describe the solution you'd like**
The idea to build HTTP Links to X-Ray for Kibana UI in form: 
https://eu-central-1.console.aws.amazon.com/xray/home?region=eu-central-1#/traces/1-5f6dc9e1-9dc73cd32396bc9ff2b8db9b
https://eu-central-1.console.aws.amazon.com/xray/home?region=eu-central-1#/traces/:AWSTraceId
TraceID is part of AWS HTTP response header `x-amzn-trace-id: Root=1-5f6dc9e1-9dc73cd32396bc9ff2b8db9b` it's easy to add it to Elastic Trace Bage and them build this URL or even upload X-Ray data to Kibana

**Describe alternatives you've considered**
Alternative, Force APM Agent to send All gathered data from Lambda to Elastic before returning results from Lambda 

**Additional context**
Context, I made `ngrok` export of my local APM Server to play around lambdas and got `500 Internal Server Error` for my subSecond Lambda, after changing `apiRequestTime: "1s"` I got some data, but I need to `wait` in a lambda that is ugly.  
Some lambda code 
index.js 
```
const apm = require('elastic-apm-node').start({});
const server = new ApolloServer({})
exports.handler = server.createHandler();
```
```
const apm = require("elastic-apm-node");

 async my(_, __, { }) {
      const transaction = apm.startTransaction("My Query", "graphql");
      const span1 = transaction.startSpan("Are All AS completed");
      if (await isAllASCompleted()) {
        return null;
      }
      span1.end();

      const span2 = transaction.startSpan("Send PrP notification");
      try {
        await sendNotification({);
        span2.end();
      } catch (error) {
        span2.end();
        apm.captureError(error);
      }
    
      const span3 = transaction.startSpan("Get patient data");
      const patient = await PatientModel.get({});
      span3.end();

      transaction.result = "success";
      // end the transaction
     transaction.end();

      await wait();
      return patient;
    },
```

**Comment by trentm** [comment]
@EUinUkraine Lambda and X-Ray aren't currently supported by elastic-apm-node. Please refer to this feature request issue for discussion: https://github.com/elastic/apm/issues/352
