### ISSUE TITLE
unhandledRejection having instrumented pg module and had an error from database

### ISSUE THREAD

**Issue by glasseyes42** [elastic/apm-agent-nodejs#1829]
**Describe the bug**

It seems when instrumenting the node postgres module, if there is for example a syntax error or other database centred error whilst using a checked out connection from a pool (ie, potentially to be used for a transaction) not only does the error propagate through the promise chain back to the expected handlers/try-catch ... but also an unhandled promise rejection occurs. 
Also interesting is that this does not seem to happen with a simple `pool.query` use case. 

**To Reproduce**

Some fairly simple example code that will yield both errors logged out:
```javascript
const apm = require('elastic-apm-node').start();
const { Pool } = require('pg');

const config = {
  host: 'localhost',
  database: 'postgres',
  user: 'postgres',
  password: 'password',
};

const pool = new Pool(config);

(async () => {
  process.on('unhandledRejection', (e) => {
    console.error('unhandled', e);
    // process.exit(1);
  });

  async function withTransaction(operations) {
    const connection = await pool.connect();
    try {
      // await connection.query('BEGIN');
      const result = await operations(connection);
      // await connection.query('COMMIT');
      return result;
    } catch (err) {
      // await connection.query('ROLLBACK');
      throw err;
    } finally {
      connection.release();
    }
  }

  try {
    const trans = apm.startTransaction('dummy transaction');
    await withTransaction(async connection => {
      await connection.query(`select 'not-a-uuid' = '00000000-0000-0000-0000-000000000000'::uuid`);
    });
    // await pool.query(`select 'not-a-uuid' = '00000000-0000-0000-0000-000000000000'::uuid`);
    trans.end();
    console.info('finished');
    process.exit(0);
  } catch (e) {
    console.error('caught error successfully', e);
    // process.exit(0);
  }
})();
```

I've narrowed down in some local hacking of the modules in the dep-tree that [changes made here](https://github.com/elastic/apm-agent-nodejs/blob/4fe301d66a1ef748a77a0cde7584931e176c618b/lib/instrumentation/modules/pg.js#L106) can show the situation quite elegantly. By adding: 
```javascript
.catch(err => {
  agent.logger.error('patched query error: %o', err);
  throw new Error('something completely different');
})
```
The resulting output of the combined script + change contains: 
- The APM based error from the `.catch` added. (which will be a message along the lines of `invalid input syntax`)
- The outer most catch from the script, with the same `invalid input syntax` based error.
- Finally there is the `unhandledRejection` error which is now with the new error message. This suggests to me that there must somehow end up being two separate promise chains being executed as a result of the same query function call (and subsequently two different error paths).

**Expected behavior**

**Environment (please complete the following information)**

- OS: Demonstrated in MacOS & Linux (docker container)
- Node.js version: Presents in 12 & 14 (versions tested ... would expect lower versions as well)
- APM Server version: N/A - can be demonstrated with or without successful connection to APM server
- Agent version: 3.7.0 (and lower versions)

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`
(has been demonstrated with the second option here as well in an active codebase)

**Additional context**

`pg` module versions tested against: 
- `8.4.1` (upgraded to this thanks to attempting to remove major node version upgrade as a cause)
- active application demonstrating this issue uses `7.4.3`

**Comment by glasseyes42** [comment]
_feels a bit foolish to have basically spotted the issue without realising it_

Got to stuck into the internals of pg/how-everything-worked. The issue is exactly where I've linked [before](https://github.com/elastic/apm-agent-nodejs/blob/4fe301d66a1ef748a77a0cde7584931e176c618b/lib/instrumentation/modules/pg.js#L106) 

Because this isn't actually returned, any outside application error handling is not applicable to catching any error. This new chain missing a catch handler subsequently causes the `unhandledRejection`. Perhaps the cleanest is to stick an empty catch handler here.

**Comment by astorm** [comment]
Thanks for finding and reporting this @glasseyes42 -- with unhandled promise rejections becoming fatal errors in future versions of NodeJS this is definitely something we'll want to address.

To talk out loud a bit about what this code is doing (much of which you've already said) -- it looks like we wrap the `query` method on the `pg.Client`'s prototype

https://github.com/elastic/apm-agent-nodejs/blob/4fe301d66a1ef748a77a0cde7584931e176c618b/lib/instrumentation/modules/pg.js#L44

and if there's not a callback argument provided then we manually call the original method

https://github.com/elastic/apm-agent-nodejs/blob/4fe301d66a1ef748a77a0cde7584931e176c618b/lib/instrumentation/modules/pg.js#L89

and then attempt to make sure our `end` function (which will end the span) gets called.

https://github.com/elastic/apm-agent-nodejs/blob/4fe301d66a1ef748a77a0cde7584931e176c618b/lib/instrumentation/modules/pg.js#L102

In cases where there's not an `on` method available AND if the original method/function returns something promise-like, we pass our `end` callback to the Promise's `then` function without a `catch`. This results in an unhandled promise rejection when there are promise errors

Questions for you @glasseyes42

- When you add an empty `catch`, does the agent still catch the original error?

- When you add an empty `catch`, does the span still end?

- Do you think you'd be up for making a PR to fix this once we decide on a solution?

Question for @watson 

- If you have any memory of adding this line https://github.com/elastic/apm-agent-nodejs/blob/4fe301d66a1ef748a77a0cde7584931e176c618b/lib/instrumentation/modules/pg.js#L106 -- do you think `finally` would be a better choice here than `then`?  I haven't tested, but my hunch is using `finally` would still achieve our goals while side stepping the unhandled rejection.

**Comment by glasseyes42** [comment]
> When you add an empty catch, does the agent still catch the original error?

Assuming you are referring to the agent reporting errors that ultimately appear in the kibana APM view for an application .. I've not noticed anything when checking the debug log output of the apm client reporting such things (regardless of changes made). I did make an effort last week actually to try and find where that code lives but gave up. Hints for locally proving that?

> When you add an empty catch, does the span still end?

No, fair point. I had a check of `.finally` given the other question above, however that _still_ results in an unhandled rejection if used as a drop in replacement for the the current `.then` with no other code changes - and if used in my snippet below it would prevent reporting an error up the chain back to the application code.

I loathe rewriting variables as a coding style. But... this does work as a drop in replacement (written shorthand, would imagine you'd prefer full functions etc):
```javascript
...
} else if (typeof query.then === 'function') {
  query = query.then(end).catch(err => {
    end();
    throw err;
  });
} else {
  agent.logger.debug('ERROR: unknown pg query type: %s %o', typeof query, { id: id })
}
...
```

> Do you think you'd be up for making a PR to fix this once we decide on a solution?

Can do - trying to construct a test for this will be entertaining though I'd imagine

**Comment by glasseyes42** [comment]
Having had more time to think about it than I did when I was writing and testing that this morning - too many things happening at once as usual.

https://github.com/glasseyes42/apm-agent-nodejs/commit/c304b9f8b7bc4192522ab2ddcac11d383b88a397

I have this now running in a live service. No unhandled rejections. Errors are reported correctly and show in the APM view in kibana. Still not totally happy with the solution but it _does work_

**Comment by watson** [comment]
@astorm wrote:

> -- do you think `finally` would be a better choice here than `then`? I haven't tested, but my hunch is using `finally` would still achieve our goals while side stepping the unhandled rejection.

Yes, but unfortunately `Promise.prototype.finally` wasn't added to Node.js until v10, so we can't use it in this major version of the agent. When encountering cases like this, I've added both a `then` and a `catch` to make sure both cases were covered. I'm not sure why I haven't in this case - I can only assume it was an oversight. Once we drop support for Node.js 8 we can use `finally` in all these scenarios 👍

**Comment by astorm** [comment]
> Yes, but unfortunately Promise.prototype.finally wasn't added to Node.js until v10
✅

 @glasseyes42 After getting feedback from @watson it sounds like the missing catch here was unintentional and a _finally_ isn't an option until we finally move on from Node 8.  

i.e. your fix is the way it should be. 😄    

Would you be up for submitting a PR to get this fix into the agent and into a future release?

**Comment by glasseyes42** [comment]
Sure can PR it. Want me to try and tackle a test case for it? Not familiar with tape though

**Comment by astorm** [comment]
> Want me to try and tackle a test case for it?

If you're down for that, go for it :) Our PG tests live here: https://github.com/elastic/apm-agent-nodejs/blob/master/test/instrumentation/modules/pg/pg.js

tape is an implementation of the [Test Anything protocol](https://testanything.org/) for NodeJS.  Here's an example of a simple suite

```
const tape = require('tape')

tape('name of suite', function(t){
    t.test('simple example test', function (t) {
        t.ok(true, 'is true true?')
        t.equals(42, 42, 'does 42 equal 42?')
    
        t.end() // must end tests 
    })
})
```

Basically you pass the `tape` function/module a suite name and callback, and then use the callback's `t` param to setup additional callbacks that run your tests/assertions, and each of these additional callbacks must _end_ the test once you're done.  

To get started I'd add a new `t.test` to the PG tests with a basic set of assertions, and then once those assertions are running start writing your more complex tests (borrowing from anything you see in `pg.js`.  I'm never sure what the right amount of help is -- so I'll stop there. We're happy to advise/answer any additional questions you have.

**Comment by glasseyes42** [comment]
I'll give it a stab tomorrow, will need to give what I'm doing a break and mull over some things anyway.

Plus side, the code I linked earlier has been running just fine 👍

**Comment by glasseyes42** [comment]
PR opened, still working on a valid test case if its still desired.
