### ISSUE TITLE
Ensure only Elasticsearch _search requests have their body captured

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#183]
When a request to Elasticsearch is detected, a db trace is created and the request body is stored as the query on the trace:

https://github.com/elastic/apm-agent-nodejs/blob/9737fc85117ddb017c4cf263d5734e47ff627ed1/lib/instrumentation/modules/elasticsearch.js#L25

We need to ensure that the query is only added to the trace if we're dealing with a `_search` request. Creation of indexes etc. should still result in a trace, but their body should not be captured on the trace.

**Comment by Qard** [comment]
PR is: #185
