### ISSUE TITLE
Extend Mongoose support

### ISSUE THREAD

**Issue by CyberHippo** [elastic/apm-agent-nodejs#1833]
**Is your feature request related to a problem?**

Yes,
I really like your instrumentation agent but some of my apps are using a version of mongoose that is not currently supported (`^5.9.2`). The supported versions are as of now :
```
>=4.0.0 <5.7.0
```
Do you plan on extending the support to newer versions of mongoose ?

**Describe the solution you'd like**

Support for newer versions of [mongoose](https://www.npmjs.com/package/mongoose) (up to `^5.9.2` ideally).

**Describe alternatives you've considered**

For now, since the APM Server supports the OpenTelemetry standards, I am using the [OpenTelemetry node library](https://www.npmjs.com/package/@opentelemetry/node) with the [contrib otel-collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/elasticexporter).
And for mongoose, I am using the plugin from `wdalmut` : [`@wdalmut/opentelemetry-plugin-mongoose`](https://github.com/wdalmut/opentelemetry-plugin-mongoose).
This situation is fine but I am missing the stack trace in the APM Server.

Thank you !

**Comment by astorm** [comment]
Nice to meet you @CyberHippo -- glad that our [Open Telemetry exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/elasticexporter) has been able to temporarily bridge the gap for you.

It's definitely our intention to support more recent versions of mongoose.

To that end -- did you run into any specific issues when trying the agent with Mongoose `^5.9.2`, or is your concern more with [our stated supported](https://github.com/elastic/apm-agent-nodejs/blob/master/docs/supported-technologies.asciidoc#tracing-and-instrumentation) not including the anything more recent than 5.7?  I mainly want to make sure that we're aware of any specific problem that might be missed by our automated version tests.

**Comment by CyberHippo** [comment]
Hi @astorm,

Your [Open Telemetry exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/elasticexporter) works like a charm !

Glad to hear that you plan on supporting more recent versions of mongoose. 

No I did not encounter any issue, the agent starts up and instruments the rest of the app. Only the stack trace and the metrics for the mongoose calls are missing.

**Comment by aleksanderheimrath** [comment]
Same problem and it seems there is no update

**Comment by danielbloq** [comment]
Hey guys, any news on supporting recent versions of mongoose?
Thanks!
