### ISSUE TITLE
Auto filter sensitive header set-cookie not filtered for response headers

### ISSUE THREAD

**Issue by StoraH** [elastic/apm-agent-nodejs#1834]
**Describe the bug**

When filterHttpHeaders is set to true (ELASTIC_APM_FILTER_HTTP_HEADERS) it's expected to redact sensitive cookie and set-cookie information from the request and response headers. This is done in http-headers.js but only the request headers and not the response headers is getting filtered. This is mainly an issue for the set-cookie in the response header.

**To Reproduce**

1. Setup the APM and set ELASTIC_APM_FILTER_HTTP_HEADERS to true (Should be true by default)
2. Do a call that have a set-cookie with a sensitive value in the response. Ex. A login request
3. Check the APM logs and check the response headers and the set-cookie shows up in clear text.

**Expected behavior**

The expected behavior is that the headers with sensitive values should be masked by the string [REDACTED]. Right now to check what is a sensitive value the node package [is-secret](https://www.npmjs.com/package/is-secret) is used. It's a good starting point but to help this along it would be desirable to be able to set additional headers and cookies that contains sensitive information.

Something like this as environment variable could be a solution:

- ELASTIC_APM_SENSETIVE_HTTP_HEADERS = auth,secreat
- ELASTIC_APM_SENSETIVE_HTTP_COOKIES = auth,private_token

**Environment (please complete the following information)**

- OS: OSX
- Node.js version: 12.18.3
- APM Server version: 7.9.2
- Agent version: 3.4.0

**How are you starting the agent? (please tick one of the boxes)**

- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by astorm** [comment]
Thank you for reporting @StoraH and it's nice to meet you.

We're not 100% sure we understand the specific issue you're running into and have a few clarifying questions.

First, the intention of `ELASTIC_APM_FILTER_HTTP_HEADERS` is to control whether certain HTTP headers values are are sent to the APM Server via Transactions, Spans, and Error payloads.  

You mentioned

> Check the APM logs and check the response headers and the set-cookie shows up in clear text.

It's not 100% clear to us where you're seeing the plaintext headers.  When you say APM logs, do you mean in the log files produced by the Elastic Node Agent?  The log files produced the the APM Server?  Or some other log file?

Or do you mean logs in Elastic's log monitoring product?  If this is what you mean, would it be possible to share a screenshot of which section of the UI you're seeing things in? (with the sensitive information redacted, of course :))

If you can clarify the above issue it'd go a long way towards us understanding your issue and being able to either address it in the agent, or get you pointed at the right code repository :)

**Comment by StoraH** [comment]
Hi @astorm nice to meet you as well.

Sorry for being a bit unclear, you know how it is a Friday afternoon. I'm gonna try to keep the problem explanation simple and keep the improvement ideas out for now.

Right now it's only the sensitive **request headers** that gets redacted and not the **response headers**.  For example if you have a login request and the server response with a set-cookie header it will be shown in clear text in the logs.

Here is a screenshot from http-headers.js to highlight the issue 
![http-headers](https://user-images.githubusercontent.com/1011980/97861628-5b135380-1d04-11eb-9ce9-2ef57d45c6e5.jpg)

And a screenshot from our kibana (I know our cookie name doesn't match a sensitive one but that's another problem) 
![apm-transaction-in-kibana](https://user-images.githubusercontent.com/1011980/97861122-93666200-1d03-11eb-92f1-cdbae16fb496.jpg)

Hope this was a bit more clear and let me know if you need anything more :)

**Comment by astorm** [comment]
That's a perfect explanation @StoraH -- the Kiabana screenshot told me everything I needed to know :) I'll be sure to give https://github.com/elastic/apm-agent-nodejs/pull/1835/files a review. Thanks for bringing this to our attention.

**Comment by astorm** [comment]
fixed in https://github.com/elastic/apm-agent-nodejs/pull/1886
