### ISSUE TITLE
Add support for Node.js 15/16

### ISSUE THREAD

**Issue by shimaore** [elastic/apm-agent-nodejs#1840]
**Describe the bug**

```
error elastic-apm-node@3.7.0: The engine "node" is incompatible with this module. Expected version "^8.6.0 || 10 || 12 || 13 || 14". Got "15.0.1"
```

**To Reproduce**

1. Install Node.js latest
2. `yarn add elastic-apm-node`
3. See error

**Expected behavior**

Node.js 15 should be present in package.json's `engines.node`.

**Environment**

- OS: Linux
- Node.js version: 15.0.1
- APM Server version: n/a
- Agent version: 3.7.0 / master

**Comment by akoso** [comment]
Hi, any news on this?

**Comment by trentm** [comment]
It (in #1841) is still on my radar and included in our roadmap. I haven't had a chance to get back to it since the last issue I posted some details on in December.

**Comment by trentm** [comment]
The work for this now is https://github.com/elastic/apm-agent-nodejs/pull/2055, currently our jenkins-based tests are blocked on https://github.com/nodejs/docker-node/pull/1465

**Comment by akoso** [comment]
Can you please release to npm a new version with the node 15/16 support?

**Comment by trentm** [comment]
> Can you please release to npm a new version with the node 15/16 support?

Thanks for the reminder! Working on it. Should have this out tomorrow.

**Comment by trentm** [comment]
elastic-apm-node@3.15.0 published now.
