### ISSUE TITLE
[CI] test:docs command does not work anymore

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-agent-nodejs#1869]
### Steps to reproduce
1. Run `npm run test:docs`, as explained in the TESTING.md doc

#### Expected behaviour
Tests for docs works with exit 0

#### Actual behaviour
Execution failed because an NPM target does not exist:

>missing script: docs

```shell
➜  apm-agent-nodejs git:(master) npm run test:docs

> elastic-apm-node@3.8.0 test:docs /Users/mdelapenya/sourcecode/src/github.com/elastic/apm-agents/apm-agent-nodejs
> ./test/script/docker/run_docs.sh

Sending build context to Docker daemon  748.5kB
Step 1/5 : ARG NODE_VERSION
Step 2/5 : FROM node:${NODE_VERSION}
latest: Pulling from library/node
Digest: sha256:8ebfdeee577821f6c9caf672f3cb99fc2de39a9cb1d09a80a33d157c1452030f
Status: Image is up to date for node:latest
 ---> 6c5fc80a4d2b
Step 3/5 : RUN apt-get update &&     apt-get install -y xsltproc libxml2-utils &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 3321928374ac
Step 4/5 : ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
 ---> Using cache
 ---> bb81998d6580
Step 5/5 : WORKDIR /app
 ---> Using cache
 ---> 550c7e1e542a
Successfully built 550c7e1e542a
Successfully tagged node_docs:latest
npm ERR! missing script: docs

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-11T06_56_55_974Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elastic-apm-node@3.8.0 test:docs: `./test/script/docker/run_docs.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elastic-apm-node@3.8.0 test:docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mdelapenya/.npm/_logs/2020-11-11T06_56_56_153Z-debug.log
```

### Observations
I believe df396efd3c21b62f8b5e12447ce72799059c5704 changed the target name, from `docs` to `docs:build`. But I replaced the target in the `run_docs.sh` script, from:

```shell
docker run \
  -e CI=true \
  -v "$(pwd)":/app \
  --rm node_docs \
  /bin/bash \
  -c 'npm run docs'
```
to
```shell
docker run \
  -e CI=true \
  -v "$(pwd)":/app \
  --rm node_docs \
  /bin/bash \
  -c 'npm run docs:build'
```
And then it failed again because the whole process is dockerised: the caller script (see above) runs inside a docker container, and the target script (`docs/script/build_docs`) calls another script in the cloned docs repo which is using Docker too, so no Docker in Docker capabilities are available.

```shell
Successfully built 550c7e1e542a
Successfully tagged node_docs:latest

> elastic-apm-node@3.8.0 docs:build
> ./docs/scripts/build_docs.sh apm-agent-nodejs ./docs ./build

./build/docs already exists. Not cloning.
Building docs for apm-agent-nodejs...
Index document: ./docs/index.asciidoc
[Errno 2] No such file or directory
Are you sure Docker is installed?
```

@bmorelli25 any guess?

**Comment by bmorelli25** [comment]
I played around with this... I'm sorry, but I don't really know enough about Docker to give any recommendations. You're right that `docs/script/build_docs` is dockerized. Why is `npm run test:docs` needed? `docs:build` and `docs:open` seem to work fine.

**Comment by astorm** [comment]
@mdelapenya Are you still blocked here or did @bmorelli25's answers get you what you needed?

If you're still blocked -- could you give us a little more context on what you're trying to accomplish with `npm run test:docs` that `npm run docs:build` and `npm run docs:open` don't accomplish?

**Comment by mdelapenya** [comment]
I think this can be closed for now
