### ISSUE TITLE
ci: get test fixture syncing working

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#1872]
**Is your feature request related to a problem? Please describe.**

We have a system for automatically PRing repos when our centralized agent test fixtures are updated.  We need to configure this system for our repo in order to pull in the wildcard matching test fixtures. 

**Describe the solution you'd like**

- ~Add the `wildcard_matcher_tests.json` to this repo~ based on other repo's git history, this won't be needed
- Configure the updater at https://github.com/elastic/apm/blob/master/.ci/.jenkins-agents.yml

**Additional Context**

Moves elastic/apm-agent-nodejs#1870 along.

**Comment by trentm** [comment]
From clicking through a bit, that "system" was added in https://github.com/elastic/apm/pull/231
