### ISSUE TITLE
[META 27] Global Availability of ECS Logger

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#1874]
See: https://github.com/elastic/ecs-logging/issues/27

For this issue we need to asses the state of the NodeJS ECS logger 

https://github.com/elastic/ecs-logging-js/

and work with the client team to fill any gaps before making this globally available.

**Comment by trentm** [comment]
I spoke with @delvedor today and my understanding is he feels ecs-logging-js should basically be fine for "GA". We would want to remove the README comment about it being "beta". (We talked about perhaps adding support for "bunyan" to the list, but I'd think that would be optional.)

We should definitely still go through all the bullets listed at https://github.com/elastic/ecs-logging/issues/27

**Comment by trentm** [comment]
1.0.0 releases via https://github.com/elastic/ecs-logging-nodejs/pull/54

changes: https://github.com/elastic/ecs-logging-nodejs/compare/6537f31f...b6986be4
