### ISSUE TITLE
chore: remove conditional parseurl dependency

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#1884]
**Is your feature request related to a problem? Please describe.**

The [`express-utils.js` internal module](https://github.com/elastic/apm-agent-nodejs/blob/34cc2a77820ae5b52f5ffab36f33fbaece8ccaf6/lib/instrumentation/express-utils.js#L13) has a _conditional_ dependency on the `parseurl` library.  This library is not an agent dependency.  However, if `parseurl` is present then the agent will use it instead of it's own home grown URL parsing.

We've had [users report](https://github.com/elastic/apm-agent-nodejs/pull/1823) that this conditional `require` statement combined with the lack of this module being a dependency has caused issues with modern javascript compilers/transpilers.  Systems like webpack or babel see the agent as a dependency, see parseurl as a dependency of the agent, attempt to find parseurl, and blow up when it's not there. 

**Describe the solution you'd like**

We should remove the conditional dependency.  

- We want to use the agent's internal parser and remove the `require('parseurl')` dependency.
- We'll want to ensure sufficient tests to confirm that our parsing behavior matches the behavior of `parseurl` -- adopting the [parseurl test fixtures](https://github.com/pillarjs/parseurl/blob/master/test/test.js) seems to be a reasonable approach here
- Stretch Goal: the `parseurl` package caches results -- some considerations of the perf trade-offs may be appropriate here 

**Describe alternatives you've considered**

Asking users to manually exclude the agent or its dependency-not-really-a-dependency from their compiler configuration.  While this works, often time users don't even realize they're compiling the agent when using the agent with a package like AngularJS.

**Comment by david-luna** [comment]
Hi @astorm

If you don't mind I'd like to take this one :)

**Comment by david-luna** [comment]
Hi @astorm 

seems there is a problem in the [CLA form](https://www.elastic.co/contributor-agreement/) so the PR build is stuck in the verification step.

Any alternative to sign it or anyone I can ping to fix it?

**Comment by trentm** [comment]
@david-luna I'll look into the CLA issue later today. Thanks for taking this issue!

**Comment by trentm** [comment]
> I'll look into the CLA issue later today.

Looks like the CLA check on #3133 sorted itself out. At least I didn't change anything.

**Comment by david-luna** [comment]
Indeed. I'm going to add a better description on the PR and wait for your comments.

Thank you!
