### ISSUE TITLE
drop commitlint

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#1887]
Alan and I are considering dropping the usage of commitlint to lint commit messages according to https://www.conventionalcommits.org/en/v1.0.0/  The main argument for dropping commitlint is that it trips up too many commits (in PRs and to master, examples below) resulting in failing checks and distraction digging into those.

**What do we really want?**

The ideal here (warning: Trent's opinions) is a process that:

- encourages a "good" *final* commit message (i.e. for the commit that lands
  on master and/or release branches),
- encourages "good" changelog content, and
- isn't overburdensome.

"Good" here should be defined in "CONTRIBUTING.md".

What *isn't* a use case for us is automatically generating a changelog.

**Pros of conventional commits:**

- An actual *spec* for partly defining a "good" commit message can be helpful.
- Encouraging clear identification of breaking changes is helpful.

**Pros of using commitlint:**

- If something isn't checked automatically, it is going to get missed sometimes. Turning off commitlint will mean we'll occasionally miss out on some of the "Pros" from the previous section.

**Cons of using commitlint:**

- A common use case is a PR with intermediate commits as the developer iterates to a final change that will be "Squash and Merge"d.
  Opinion: It is onerous to have to comply with commitlint for those commits that are never intended to land on master as is. They have real distraction impact however as PR checks fail. E.g. with https://github.com/elastic/apm-agent-nodejs/pull/1880

    ```
    % npm run lint:commit
    ...
    + commitlint --from=master
    ⧗   input: fixed typo in pull_request types
    ✖   subject may not be empty [subject-empty]
    ✖   type may not be empty [type-empty]

    ✖   found 2 problems, 0 warnings
    ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

    ⧗   input: added pr trigger for auto-labeling workflow
    ✖   subject may not be empty [subject-empty]
    ✖   type may not be empty [type-empty]

    ✖   found 2 problems, 0 warnings
    ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

    ⧗   input: Added GitHub Workflow for auto-labeling
    ✖   subject may not be empty [subject-empty]
    ✖   type may not be empty [type-empty]

    ✖   found 2 problems, 0 warnings
    ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
    ```

  AFAIK there is no way to resolve this without a `git rebase -i` to edit *all* commit messages on the feature branch and then *force push* those changes to the PR's branch. (A force push is typically undesirable because it breaks PR review comments tied to particular commits.)

- A commit message "1.2.3" (as suggested in [release instructions](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#releasing)) passes, but "1.2.3 (#12345)" from using a PR for the release commit [fails](https://github.com/elastic/apm-agent-nodejs/commit/8a5e908b8e9ee83bb1b828a3bef980388ea6e08e):
    ```
    + commitlint --edit
    ⧗   input: 1.2.3 (#12345)
    ✖   subject may not be empty [subject-empty]
    ✖   type may not be empty [type-empty]
    ```

    There are special cases in commitlint that are not obvious to grok.

- Opinion: For what should be a relatively simple thing (apply a [spec](https://www.conventionalcommits.org/en/v1.0.0/#specification) to commit messages) there is a lot of complexity:
    - lots of code and deps:
        ```
        {
          "name": "elastic-apm-node",
          "scripts": {
            "lint:commit": "test/lint-commits.sh",
            ...
          },
          "devDependencies": {
            "@commitlint/cli": "^8.3.5",
            "@commitlint/config-conventional": "^8.3.4",
            "@commitlint/travis-cli": "^8.3.5",
            "commitlint-config-squash-pr": "^1.0.1",
            ...
          },
          "commitlint": {
            "extends": [
              "squash-pr",
              "@commitlint/config-conventional"
            ]
          }
        }
        ```
    - subtleties on commit first-line length:
        https://github.com/elastic/apm-agent-nodejs/pull/764
        https://github.com/elastic/apm-agent-nodejs/issues/1455 (never resolved)
    - CI-specific commit range selection in [lint-commits.sh](https://github.com/elastic/apm-agent-nodejs/blob/289ec42629c7dbc947dc1b430516fb360abb3769/test/lint-commits.sh)
    - Poor first impression: https://github.com/elastic/apm-agent-nodejs/issues/1808

**What's the alternative?**

The audience for commit messages is maintainers. The audience for the changelog is users.

- Let's change to requiring PRs to include a CHANGELOG.md update within reason. Then the usual review process can do the wordsmithing. It was suggested this could also help [the issue to potentially automate the release process](https://github.com/elastic/apm-agent-nodejs/pull/1714/).

It would be nice if GitHub PRs provided a way to explicitly review the final squashed commit message (e.g. as CR tools like Gerrit do), but it doesn't. Nor is the GitHub UI when merging (the big green button) that helpful for writing a "good" commit message.

- We could consider a lightweight process where we specify the commit message in PR comment. E.g. something like the following. We could eventually consider a GitHub check on *this*.

    > **Proposed commit message**
    >
    > ```
    > this is my commit message summary
    >
    > This is my commit message body.
    >
    > BREAKING CHANGE: Zomg this breaks X, Y, and Z.
    >
    > Fixes #123
    > ```

    Lacking that, we will just rely on the person doing the squash/merge to adequately edit a reasonable commit message.

- We should decide here if we want to continue to encourage conventionalcommits `<type>(<scope>):`-like prefixes on commit messages' first line.

**Comment by astorm** [comment]
I'm pro-moving away from these commit lints.  It's a linter that's _easy_ to transgress during a multi-commit PR, but one where it's difficult (rebase, force push) to fix any transgressions.  It's also easy to game and producing a message that passes, but isn't really a good commit message.

It's also worth mentioning that even if we're capable internally of fixing these commits via a rebase, folks making community PRs aren't always as conversant in the mechanics of git and able to fix this for themselves. It feels like requiring this is a barrier to involving folks.

Re: the specifics of our brave new world

- More verbose/user-friendly CHANGELOG entries make sense.  There are small PRs that may not warrant a change-log entry  ("fixed typo in docs"), but generally let's include them whenever we introduce a new feature, fix a bug, etc.  Human reviews should be sufficient to ensure a CHANGELOG exists. 

- Let's get a _Proposed commit message_ section, with a template, added to our [PR template](https://github.com/elastic/apm-agent-nodejs/blob/master/.github/pull_request_template.md).  This should be a sufficient prompt to remind us that this is needed, as well as remind us to actually do it when we squash and commit. 

- Re: `<type>(<scope>):` -- I think having our _Proposed commit message_ start out with something like 

  ```
  feat|fix|chore|etc: ...
  ```
  
  is reasonable, but I don't think we'd lose much if we gave up scope.  The definition of what a scope is remains a little loosey-goosey/arbitrary to me, and therefore of limited value.
