### ISSUE TITLE
Expose Max Db Statement Size as a Config Option

### ISSUE THREAD

**Issue by gingerwizard** [elastic/apm-agent-nodejs#1921]
Currently the `span.context.db.statement` is limited to 10000 characters after which truncation occurs. This limit is easily exceeded on REST API based dbs that use JSON e.g. Elasticsearch. Proposal is to make this configurable similar tothe  truncation limit for error messages.

**Comment by gingerwizard** [comment]
Note is particularly important when debugging requests to Elasticsearch from Kibana.

**Comment by trentm** [comment]
A temporary work around is to apply this patch to one's node_modules/elastic-apm-node/lib/config.js:

```diff
diff --git a/lib/config.js b/lib/config.js
index 38d6408..a5520b0 100644
--- a/lib/config.js
+++ b/lib/config.js
@@ -257,6 +257,8 @@ class Config {
           // Sanitize conf
           truncateKeywordsAt: config.INTAKE_STRING_MAX_SIZE,
           truncateErrorMessagesAt: conf.errorMessageMaxLength,
+          // XXX
+          truncateQueriesAt: 20000,
           // HTTP conf
           secretToken: conf.secretToken,
```

**Comment by trentm** [comment]
^^ proposing this for 7.13. Currently Dale is having "to maintain a fork for tests and any automation" for his es rally work.

**Comment by trentm** [comment]
Notes to self:
- perhaps do this together with changes to db.statement format for ES: https://github.com/elastic/apm-agent-nodejs/issues/2019
- tracing-instrumentation-db.md spec says "We store up to 10000 Unicode characters per database statement." FWIW
- TODO: verify if >10k gets stored in ES docs or if apm-server clips or rejects. I don't (with a quick naive look) see clipping/length limiting in apm-server for this field.

**Comment by trentm** [comment]
@gingerwizard Once we publish an agent release with this change you'll be able to set the truncation limie for `span.context.db.statement` via the `longFieldMaxLength: <number>` config var.  I try to post here again once we have that release.

**Comment by trentm** [comment]
@gingerwizard If it helps for https://github.com/elastic/rally-internal-tracks/issues/119  `elastic-apm-node@3.21.0` has now been released that includes `longFieldMaxLength` to allow you to increase the max size for `span.context.db.statement`.
