### ISSUE TITLE
SANITIZE_FIELD_NAMES and http-headers Filter

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#1924]
The next major release should include the following refinements to the `SANITIZE_FIELD_NAMES` and `http-filter`ing in order to bring us into full complicated with the spec.

Specifically, this includes

1. Remove `['pw','pass','connect.sid']` from the `SANITIZE_FIELD_NAMES` defaults
   (Update: Decision 2023-07-25 to **NOT** do this. Do not want a compat breakage to drop these.)
2. Conform to the java agent behavior of capturing cookies in `transaction.context.request.cookies` and blanking out `transaction.context.request.headers.cookies`. (Update: this was implemented recently in https://github.com/elastic/apm-agent-nodejs/pull/3322)
3. Redact/sanitize `transaction.context.request.cookies` per spec (Done. See https://github.com/elastic/apm-agent-nodejs/pull/3322)
4. Remove the individual redacting of the `set-cookie` http  header and values (Done. See https://github.com/elastic/apm-agent-nodejs/pull/3322)
5. Consider either removing the `http-headers` filter entirely or moving all `SANITIZE_FIELD_NAMES` logic into this filter. (Done. See https://github.com/elastic/apm-agent-nodejs/pull/3322)

**Comment by trentm** [comment]
See the "Update" and "Done" notes above.
