### ISSUE TITLE
Buffer/Binary Capturing Middlewares Results in Large Blob-y not useful Data Being Reported

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#1925]
If a user is using a body parsers module that captures a raw Buffer (such as [the Express raw body parser](http://expressjs.com/en/resources/middleware/body-parser.html#bodyparserrawoptions)) this can result in large blobs of binary data being reported via the agent.  This seems like a bug.

To fix this, we should

1. Refine the definition of `captureBody:true` to _not_ include binary data and
2. Instead, when `captureBody:true` and the agent encounters a raw buffer, it will capture the string `<Buffer>` to indicate there was binary data present. 

from @trentm 

```
if (haveBody) {
    if (!captureBody) {
        // Aside: I'm not sure why the agent calls this "REDACTED" here. If
        // the config is `captureBody: false`, then I would just leave
        // context.body = undefined.
        context.body = '[REDACTED]'
    } else if (Buffer.isBuffer(body)) {
        context.body = '<Buffer>'
    } else {
        ...
    }
}
```

**Comment by trentm** [comment]
@astorm Correct me if I'm wrong that this is now resolved.
