### ISSUE TITLE
Document how to tune the performance of the agent

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#193]
The agent configuration options provide several knobs which can be tuned to reduce memory usage, disk IO, CPU time etc.

While these are all documented individually, it would beneficial to have a central page in our documentation, that walks the reader through how to minimize the performance impact of the agent on the host application, by utilizing these configuration options.

**Comment by consense** [comment]
aside from forcing the agent to flush sooner I was unfortunately not able to determine how to reduce memory/cpu footprint of the agent.
See below chart for the impact we were seeing upon enabling the agent on a digitalocean 3gb/1cpu machine
![image](https://user-images.githubusercontent.com/2467245/35303482-652fc34e-0092-11e8-87ff-b5045ac6df32.png)

Looking forward to sampling in the 6.2 branch
