### ISSUE TITLE
[META 382] Zero-configuration support

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#1944]
Implement zero-configuration support for the agent as described in: https://github.com/elastic/apm/issues/382

SPEC issue: https://github.com/elastic/apm/issues/401

**Comment by trentm** [comment]
- [ ] handle the rare case for "service.name" discovery to not error out if the $CWD of the process is not inside the directory tree holding the package.json file. Instead we'd change it to fallback to some default "unknown nodejs service" string.
