### ISSUE TITLE
docs: update open tracing doc

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#1965]
Per this comment: https://github.com/elastic/apm-agent-nodejs-opentracing/pull/16#issuecomment-773189649

With the old OpenTracing APIs being (defacto) put out to pasture we should consider updating the OpenTracing doc that exists in this repository: https://www.elastic.co/guide/en/apm/agent/nodejs/current/opentracing.html

Specifically, 

1. Make a note of the difference between OpenTracing and OpenTelemetry 
2. Link to the general APM docs on OpenTelemetry: https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html

**Comment by trentm** [comment]
The OTel Bridge PR (#2641) added a deprecation note to the OpenTracing docs page a long wihle back.
