### ISSUE TITLE
TypeError: lastPrepareStackTrace is not a function

### ISSUE THREAD

**Issue by BataevDaniil** [elastic/apm-agent-nodejs#1980]
You have problem in dependency https://github.com/watson/error-callsites/issues/3
I do not use apm because it does not work with react

**Comment by trentm** [comment]
I'll take this. I'll have to get access to the error-callsites repo and npm package first.  https://github.com/watson/error-callsites/issues/5 opened for that.

**Comment by rtymchyk** [comment]
Can the use of this module be avoided? It's clearly not maintained and causing problems with the APM agent

**Comment by rtymchyk** [comment]
Thought I guess it's `stackman` that's the problem...

**Comment by trentm** [comment]
1. https://github.com/watson/error-callsites/issues/3 is fixed now. I'll have to wait for a hiccup on https://github.com/watson/error-callsites/issues/5 to get npm publish rights for a new version (ETA next week).
2. With #2094 the stackman dep has been dropped from this package, so I'll just have to update to the new error-callsites version when I'm able to publish that. I'll do a new agent release early next week with that.

**Comment by trentm** [comment]
error-callsites@2.0.4 has the fix

**Comment by trentm** [comment]
elastic-apm-node@3.16.0 has been published with a fix for this.

**Comment by BataevDaniil** [comment]
@trentm thanks
