### ISSUE TITLE
High CPU load when APM-SERVER is down

### ISSUE THREAD

**Issue by ggalihpp** [elastic/apm-agent-nodejs#1984]
**Describe the bug**

We try some testing on our production environment. And try to measure the apm-server configuration.
Everything run perfectly fine at first. But after a day and the request spikes, apm-server cannot receive any more request 
(503) Queue is full
this is expected and we need to bump the config. But what surprised us were the API went crazy and the CPU load going high

![apm-agent](https://user-images.githubusercontent.com/28330810/109100290-32054b80-7757-11eb-95e8-59783e8ed7ff.png)

from the picture, we can see that rest-api-2 has a high CPU load. And it has the APM enabled, while the other one not.
FYI at first, we enabled APM on both API. But disabled it, and the CPU load normal immediately

**To Reproduce**

Steps to reproduce the behavior: 
1. Run APM-SERVER
2.  Integrate APM-AGENT
3. Shutdown apm-server

**Expected behavior**

CPU load normal

**Environment (please complete the following information)**

- OS: LINUX
- Node.js version: v14.15.4
- APM Server version: 7.11.0
- Agent version: 3.11.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)

**Comment by trentm** [comment]
@ggalihpp Hello. Thanks for the bug report! As a first guess, I believe this is related to https://github.com/elastic/apm-nodejs-http-client/issues/136 that we are currently looking into.

**Comment by trentm** [comment]
@ggalihpp Sorry for the delay. [v3.14.0](https://www.elastic.co/guide/en/apm/agent/nodejs/current/release-notes-3.x.html#release-notes-3.14.0) of the agent was released yesterday that includes a fix for this. https://github.com/elastic/apm-nodejs-http-client/pull/144 was the relevant PR to the agent that should fix the issue.

**Comment by gauravsunstone** [comment]
Facing the same issue in 3.40.0

**Comment by trentm** [comment]
@gauravsunstone Thanks. Please open a new issue with as many details as you can provide, otherwise it will get lost in this closed issue.
