### ISSUE TITLE
exclude the HTTP span under an Elasticsearch span

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2000]
From discussion on today's apm-agent-nodejs call and from https://github.com/elastic/apm/pull/420 we think the HTTP span "under" an Elasticsearch (ES) span from instrumentation of the "elasticsearch" and "@elastic/elasticsearch" modules should be excluded. The ES span is an "exit" span, and arguably the HTTP request it makes is an implementation detail. As well, eliding that span would make breakdown metrics much more useful/realistic. (FWIW, it would also side-step the current issue with the HTTP span being a *sibling* of, rather than a child of, the ES span for the instrumentation of the newer "@elastic/elasticsearch" client.)

From memory (though might be nice to confirm), the Python agent excludes the HTTP span (via `leaf=True` in the code). I recall one other language agent optionally including the HTTP span, but I think it was off by default.

**Comment by dgieselaar** [comment]
How do we capture retries if the HTTP span is dropped?

**Comment by joshdover** [comment]
+1 on this for Kibana's usage. We'd like to start enabling our support team to use APM instrumentation to debug performance problems and I think this duplication creates confusing noise.

> How do we capture retries if the HTTP span is dropped?

Could we add a `context.http.attempts` field?

**Comment by trentm** [comment]
> How do we capture retries if the HTTP span is dropped?

I'll ask the APM group. I don't see any current apm-server intake fields, no ECS http fields that could easily hold this value.

**Comment by trentm** [comment]
Note to self: because a span synchronously created under a current span (e.g. the HTTP span under an ES span) currently isn't set as a *child* might complicate implementation of this. If we had the child relationship (as we eventually want), then the implementation could just be something like the Python agent's `span.leaf=true` and use that to avoid creating new span children.

**Comment by trentm** [comment]
Note that I haven't pursued the "how to track retries". We discussed it at an APM Agents call (2022-02-01). There isn't a currently suitable ECS field for this. I considered adding a span label for this, but it would be first case of any Node.js APM agent instrumentation adding span labels automatically -- I'm not sure if span labels should remain the domain of the user.

User code (e.g. Kibana code) should be able to add an [ES Client "response" handler](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/observability.html#_events) to add a label to the `apm.currentSpan` with the number of attempts.  Something like:

```js
client.on('response', (_err, result) => {
  // Obviously missing defensive guards here.
  apm.currentSpan.setLabel('attempts', result.meta.attempts, false)
})
```
