### ISSUE TITLE
Why lambda support is deprecated?

### ISSUE THREAD

**Issue by zhaoyi0113** [elastic/apm-agent-nodejs#2007]
**Is your feature request related to a problem? Please describe.**

I see lambda support is deprecated but no explanation about why? Is there any issue for the library deprecated to support lambda?

**Comment by trentm** [comment]
@zhaoyi0113 Thanks for the question. I'll answer with my understanding (though I might have some details wrong). The deprecation notice was added in #1511. Issue #827 gives details on how AWS Lambda support isn't working. Eventually the decision was made to generally revisit how Elastic APM Agents (including languages other than Node.js) implement their Lambda support, especially now given the AWS Lambda Extensions API. That effort is tracked at https://github.com/elastic/apm/issues/352 -- but currently there isn't a timeline for that work.

**Comment by zhaoyi0113** [comment]
@trentm thanks for your reply. This is what I was looking for.
