### ISSUE TITLE
Add support for @koa/router

### ISSUE THREAD

**Issue by erwinv** [elastic/apm-agent-nodejs#2010]
There is official support for [koa-router](https://github.com/ZijianHe/koa-router) but not [@koa/router](https://github.com/koajs/router). The former is more popular (more downloads in NPM trends), but the latter is actually a more recent fork, and a quick check of the `koa-router` shim shows that it can be used as-is with the `@koa/router` fork.

Re-use the `koa-router` shim for `@koa/router`.

This would also indirectly add support for other routers based on `@koa/router` such as [koa-joi-router](https://github.com/koajs/joi-router).

**Comment by astorm** [comment]
Thanks for the heads up @erwinv -- is this a PR you'd be interested in making, or are you just passing along information that might help us in the future? (either is appreciated!)

Also -- could you talk a little bit about what you mean when you say 

> and a quick check of the koa-router shim shows that it can be used as-is with the @koa/router fork.

What sort of check did you do? If it's "made a quick instrumentation module" would you be able to share that code?

**Comment by astorm** [comment]
@erwinv I did some more investigating into this today and (appologies for not realizing this earlier) -- we _do_ support `@koa/router`.  

At the risk of getting _too_ into the weeds, when we use an array like this in our list of instrumentation

https://github.com/elastic/apm-agent-nodejs/blob/c64a089e6d4a814f15c2f111850a9d36e771b39b/lib/instrumentation/index.js#L35

It's saying 

> Instrument the `koa-router` and `@koa/router` modules via the instrumentation in `lib/instrumentation/modules/koa-router.js` 

The `koa-router.js` file is used because `koa-router` is the first element of that array.

So, we _do_ support @koa/koa-router.  Are you seeing behavior that indicates we don't support it?  If so, could you share that behavior so we can better diagnose things?

**Comment by erwinv** [comment]
@astorm thanks for investigating. Sorry for assuming the APM agent did not support `@koa/router`.

I am currently investigating the absence of APM traces for one of our microservices. The service's page on the APM dashboard is empty (0 transactions and errors). The only available data are CPU usage and System memory usage (in the Metrics tab).

I thought it was because it uses an unsupported router library. It uses `koa-joi-router`, which, in turn, uses `@koa/router`. In hindsight, even with an unsupported router, it should still show transactions, though their path names will not be grouped.

I'll try to debug this today. Maybe reproduce it on a local Elastic stack Docker cluster. I will close this ticket, since the issue is no longer about `@koa/router`. Thanks again!

**Comment by erwinv** [comment]
@astorm Just an update: I have identified the root cause. It was simply the case of calling `apm.start` too late.

This particular service that had missing traces was written in TypeScript, and I think the developer unwittingly started the APM agent too late because TSLint (or ESLint) complains if you put code in the middle of imports. It prescribes putting import statements at the top-level, before any other code, e.g.:

```TypeScript
// index.ts
import apm from 'elastic-apm-node'
import App from './app'

if (process.env.ELASTIC_APM_ACTIVE === 'true') {
  apm.start(/*...*/)
}

App()
```

The `./app` import calls `require('koa')` and also imports the routes files, which, in turn, call `require('@koa/router')`. So by the time `apm.start` is called, the `koa` and `@koa/router` node modules were already imported and those codes have not received the instrumented versions of those node modules.

The fix is, of course, to call `apm.start` before the `./app` import, and if the linter complains, just change the `import` statement to `require` and make sure to put it at the very top:

```TypeScript
// index.ts
if (process.env.ELASTIC_APM_ACTIVE === 'true') {
  require('elastic-apm-node').start(/*...*/)
}

import App from './app'

App()
```
