### ISSUE TITLE
Service map not displaying the connection between two services.

### ISSUE THREAD

**Issue by JiaLiPassion** [elastic/apm-agent-nodejs#2014]
**Versions** 
Kibana: (if relevant) 7.11.1
APM Server: (if relevant) 7.11.1
Elasticsearch: (if relevant) 7.11.1

I am using Kibana/ElasticSearch/APM 7.11.1.
And I am not working on http server, so I am using nodejs agent to create the custom `transactions`. I have two services, `producer` and `consumer`.
The trace sequence is:
1. producer startTransaction `trace006`. 
2. producer startSpan `request222`.
3. producer send traceparent to consumder
4. consumer startTransaction `request224` with `childOf` traceparent from producer.
5. consumer startTransaction `request334` with `childOf` traceparent from producer.

And the timeline displayed correctly, 
<img width="1363" alt="Screen Shot 2021-03-24 at 11 52 52" src="https://user-images.githubusercontent.com/1442575/112252703-f0f24f80-8ca0-11eb-8990-6fe74068c6c2.png">
 , the relationship of `producer` and `consumer` can be displayed in the timeline graph.

But the service map didn't show the connections between the `producer` and the `consumer` services. Only two standalone service nodes.
<img width="839" alt="Screen Shot 2021-03-24 at 11 58 15" src="https://user-images.githubusercontent.com/1442575/112252728-f6e83080-8ca0-11eb-9794-147234dfd783.png">

I found another issue here https://discuss.elastic.co/t/service-map-not-linking-services/262096/4,
and I think the problem is the same.
I am writing some simulation nodejs app to generate transaction/span data. So is there any doc or code sample to set `span.destination` correctly?

Here is my code:

1. NodeJS app1 acts as `producer` service.

```
const agent =
       require('elastic-apm-node').start({'producer', serverUrl: 'http://localhost:8200'});
const startTime = Date.now();
const tran = createTransaction(producer, 'trace006', startTime);

const traceparent = producer.currentTraceparent;
const req1 =
    tran.startSpan('request222', 'custom', {startTime: startTime + 10});
req1.setDestinationContext(
    {service: {name: 'consumer', resource: 'db', type: req1.type}});
// use ipc communication channel to send the traceparent to another nodejs process.
sendTraceParentWithIPCToConsumer();
req1.end();
tran.end();
````

2. NodeJS app2 acts as `consumer` service.
```
const agent =
       require('elastic-apm-node').start({'consumer', serverUrl: 'http://localhost:8200'});
ipc.on('message', traceparent => {
  const startTime = Date.now();
  const req2 =
      agent.startTransaction('request224', {startTime, childOf: traceParent});
   req2.end(startTime + 100);
  const req3 =
      agent.startTransaction('request334', {startTime, childOf: traceParent});
  req3.end(startTime + 200);
});
```

So I am trying to use `req1.setDestinationContext(
    {service: {name: 'consumer', resource: 'consumer', type: req1.type}});` to set destionation, but not working...

I tried to set the `span.type` to `external`, now the link is displayed, but not `producer -> consumer service`, it is `producer -> consumer node`, where the `consumer` is the `resource` of the destination context.

<img width="760" alt="Screen Shot 2021-03-25 at 1 15 57" src="https://user-images.githubusercontent.com/1442575/112354482-14081800-8d10-11eb-9b13-cc8799dba915.png">

Is there any other settings or special code I need to do?

Thank you.

**Comment by JiaLiPassion** [comment]
Finally I observed the data of `span` and `transaction` of the normal `http request` and `express` from `nodejs agent`, also I checked the code from https://github.com/elastic/apm-agent-nodejs/blob/4b22bd084595da3a2a50171b23d67ae6b7c03ce0/lib/instrumentation/http-shared.js, now the link is working.

**Comment by trentm** [comment]
@JiaLiPassion I'm glad you figured it out. The docs for the APM Agent don't make it clear which are the relevant data for the service map when adding custom span/transactions.

**Comment by JiaLiPassion** [comment]
@trentm, thank you, I am using `request` and `express` and monkey-patch some APIs of `span/transaction` to make it work, if there are some doc or API to make agent API can work with service map more easier, that will be great.
