### ISSUE TITLE
TAV for AWS-SDK Strategy

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2020]
The `aws-sdk` package, which contains SDK code for _all_ of Amazon's services,  releases new versions often.  There are [875 in the 2.x branch](https://www.npmjs.com/package/aws-sdk?activeTab=versions).

We're going to need to long term strategy for deciding which versions get tested by the TAV runner.  Running all 875 versions in the 2.x branch doesn't seem sustainable, but the current SemVer range capabilities of the TAV runner means something like picking the last 10

      versions: '>=2.858 <3'

will grow over time and eventually become sustainable.  Something like

> We might want a new TAV feature to spot select versions to test... to be able to say "test the latest version, then the N releases before that, then perhaps a sampling of the ones before that in this same major".

Next steps are for us to determine our testing strategy. After that we'll need to expand the TAV runner or develop a test-local API that will allow us to skip tests in a way that's consistent with that strategy.

**Comment by trentm** [comment]
FWIW, the current strategy is to periodically update "versions: ..." sections of .tav.yml via "dev-utils/update-tav-versions.js" using config provided in an additional "update-versions: ..." config blog in the .tav.yml file.  Eventually it would be nice if `tav` itself supported this extra block, or supported those "update-versions: ..." fields directly.  /cc @david-luna

**Comment by david-luna** [comment]
`test-all-versions@6.1.0` includes this feature and the dependency and `.tav.yml` file have been updated in https://github.com/elastic/apm-agent-nodejs/pull/3871
