### ISSUE TITLE
High cocurrency Cpu High Load

### ISSUE THREAD

**Issue by swift1911** [elastic/apm-agent-nodejs#203]
I think that stackman https://github.com/watson/stackman/blob/23bc84459d42922b02c1686f1eba24b5e13bbee7/index.js#L201 have performance bug

here is my performance result:

[long_text_2018-01-23.txt](https://github.com/elastic/apm-agent-nodejs/files/1658325/long_text_2018-01-23.txt)

**Comment by watson** [comment]
Thank you for taking the time to look into this and to report it. I'll make sure this gets fixed ASAP.

**Comment by watson** [comment]
@swift1911 which version of Node.js are you using?

**Comment by watson** [comment]
Ah, never mind. I managed to reproduce the problem. That the regex doesn't scale when the source file becomes very large. Could it be that all your source code is bundled into a single file?

I'm working on a fix to speed this up for very large files.

**Comment by swift1911** [comment]
i use node 8.7.0

**Comment by swift1911** [comment]
my ssr-bundle.js size is  300kb-600kb

**Comment by watson** [comment]
This have been fixed in version 1.0.0
