### ISSUE TITLE
Capturing an error object with a field of type `Date` with value `Invalid Date` causes an error

### ISSUE THREAD

**Issue by nedyalkov** [elastic/apm-agent-nodejs#2030]
**Describe the bug**

If you try to capture an error object with a field of type `Date` with a value `Invalid Date`, the underlaying `stackman` library will throw an error `RangeError: Invalid time value`.

There is already logged bug there: https://github.com/watson/stackman/issues/17, but the bigger problem is totally valid errors like Mongoose CastError cannot be properly logged due to this issue.

**To Reproduce**

Steps to reproduce the behavior: 
1. Start an APM monitoring: `const apm = ElasticApm.start({...})`
2. Create an error object: `const err = new Error('Will fail')`
3. Add `Invalid Date` to it: `err.date = new Date('invalid')`
3. Capture the error: `apm.captureError(err)`
4. You'll see an `RangeError: Invalid time value` error in the logs

**Expected behavior**

The field should be either omitted or formatted as `Invalid Date` and not to fail.

**Environment (please complete the following information)**

- OS: OSX
- Node.js version: v14.15.0
- APM Server version: v7.11.1
- Agent version: 3.12.1

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Agent config options: 
<details>
    <summary>Click to expand</summary>

```
{   
    serviceName,
    serviceVersion,
    environment: env,
    serviceNodeName: host,
    logLevel: 'error',
    transactionSampleRate: 1,
    centralConfig: true,
    cloudProvider: 'aws',
    transactionIgnoreUrls: ['/status', '/i/system/status*'],
    active: currentConfig.applicationMonitoring,
    // auth options...
}
```
</details>

`package.json` dependencies:
<details>
    <summary>Click to expand</summary>

```
{
    "elastic-apm-node": "^3.12.1",
    // unrelated dependancies...
}
```
</details>

**Comment by trentm** [comment]
@nedyalkov Thanks for reporting this! And apologies for this getting missed for so long in our triaging.

I can repro with the current agent version:

```
% cat foo.js
/* eslint-disable */
const apm = require('./').start({
  logUncaughtExceptions: true
})
const err = new Error('Will fail')
err.date = new Date('invalid')
apm.captureError(err)

% node foo.js
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at attributesFromErr (/Users/trentm/el/apm-agent-nodejs/lib/errors.js:97:19)
    at Object.createAPMError (/Users/trentm/el/apm-agent-nodejs/lib/errors.js:195:21)
    at Immediate.<anonymous> (/Users/trentm/el/apm-agent-nodejs/lib/agent.js:541:12)
    at processImmediate (node:internal/timers:466:21)
{"log.level":"info","@timestamp":"2022-08-10T21:17:36.445Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"Sending error to Elastic APM: {\"id\":\"f24be2d1a069a0f95e189ba394699e20\"}"}
```

**Comment by trentm** [comment]
With the coming fix the error capture works, capturing an APM error object that looks like:

```
    {
        "error": {
            "id": "51e772b23cf661a6a0a370e9e15ff14a",
            "timestamp": 1660169216921000,
            "context": {
                "user": {},
                "tags": {},
                "custom": {}
            },
            "exception": {
                "message": "Will fail",
                "type": "Error",
                "handled": true,
                "attributes": {
                    "date": "Invalid Date"
                },
                "stacktrace": [
                    {
                        "filename": "err-attr-invalid-date.js",
                        "lineno": 5,
                        "function": "Object.<anonymous>",
                        "library_frame": false,
                        "abs_path": "/Users/trentm/el/apm-agent-nodejs6/err-attr-invalid-date.js",
                        "pre_context": [
                            "  logUncaughtExceptions: true",
                            "})"
                        ],
                        "context_line": "const err = new Error('Will fail')",
                        "post_context": [
                            "err.date = new Date('invalid')",
                            "apm.captureError(err)"
                        ]
                    },
...
```
