### ISSUE TITLE
"metadata requests did not finish, possible deadlock" log.error is slightly alarmist

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2065]
Cloud metadata collection in the agent can log this:

```
{"log.level":"error","@timestamp":"2021-04-29T04:56:27.104Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"metadata requests did not finish, possible deadlock"}
```

if either (a) the [CallbackCoordination](https://github.com/elastic/apm-agent-nodejs/blob/v3.14.0/lib/cloud-metadata/callback-coordination.js#L33-L44) for cloud metadata collection has a bug where it actually deadlocks (which won't actually deadlock or crash the node.js app/process, or (b) it just hit the 3s timeout given for cloud metadata collection.

The latter (b) is most likely. Kibana was hitting this in their tests recently, so that timeout can be hit -- presumably on a very CPU-busy process (like Kibana can be on startup).

That message, and log level, is a bit alarmist. Perhaps log.warn and mention the timeout case specifically. Possibly drop the work "deadlock".

**Comment by nicomabs** [comment]
Same issue here

**Comment by JojiePalahang** [comment]
Any workaround or permanent solution on this message

**Comment by trentm** [comment]
This message was mentioned in an SDH recently. The message was initially read as a likely cause of an observed issue, but actually was unrelated.
