### ISSUE TITLE
Align type, subtype and action for HTTP spans with SPEC

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#2075]
The Node.js agent uses different subtypes for http spans (e.g. http, https, http2).
As defined in the [corresponding SPEC](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-http.md#http-client-spans) http spans should use `external` for type and `http` for subtype.

**Comment by trentm** [comment]
Per discussion on the apm-agents call earlier this week, Felix suggested this need not be considered a breaking change. Should given Dale a heads up if/when near merging this to Kibana.

**Comment by trentm** [comment]
@AlexanderWert @felixbarny Should we look to add guidance to the spec on the "action" field? Currently, for outgoing http spans, Node.js is setting `action="http"`, Ruby is setting `action="GET|POST|..."`, and others are leaving it null (this per Alex's inconsistencies doc). I don't know what `action` is used for in the UI. I can ask around (in chat or one of the weeklies) if you think that is best.

**Comment by trentm** [comment]
Second question: How does a user know if a span is HTTP 1, 2 (or 3 when we have QUIC integration)? An example span from the Node.js agent tests:

```
{
  id: 'a5b4d2f6d911e11c',
  transaction_id: '7d9e35adc8deba0c',
  parent_id: '7d9e35adc8deba0c',
  trace_id: '85108ecdae4d8e6e8e5011f8d5b48b10',
  name: 'GET https://localhost:55588/sub',
  type: 'external',
  subtype: 'http2',
  action: null,
  timestamp: 1623281643740481,
  duration: 2.466,
  context: {
    db: undefined,
    http: {
      method: 'GET',
      status_code: 200,
      url: 'https://localhost:55588/sub'
    },
    tags: undefined,
    destination: { service: [Object], address: 'localhost', port: 55588 },
    message: undefined
  },
  stacktrace: undefined,
  sync: false,
  outcome: 'success',
  sample_rate: 1
}
```

This is likely a question for a separate issue. :)

**Comment by AlexanderWert** [comment]
> @AlexanderWert @felixbarny Should we look to add guidance to the spec on the "action" field? Currently, for outgoing http spans, Node.js is setting action="http" (actually action=null for http2), Ruby is setting action="GET|POST|...", and others are leaving it null (this per Alex's inconsistencies doc). I don't know what action is used for in the UI. I can ask around (in chat or one of the weeklies) if you think that is best.

IIRC the action is only used to show a corresponding badge on the span flyout in the UI (this one is from Ruby agent):
![image](https://user-images.githubusercontent.com/866830/121474685-b2795080-c9c4-11eb-926c-597861c5a52d.png)

I like the idea of setting the action to the HTTP method for HTTP spans and adding this to the spec. @felixbarny WDYT?

**Comment by felixbarny** [comment]
SGTM

**Comment by trentm** [comment]
A light challenge:  Is there much value in that "action" field at all?  Obviously it would be a larger issue/effort, but what utility would the user lose if we just dropped the "action" altogether?  #rhetorical

That said, for now we'll keep "action". I agree that using the HTTP verb is more useful than 'http' here.

Aside: Should that `subtype=http_rb` considered a Ruby agent inconsistency bug?

**Comment by AlexanderWert** [comment]
> Aside: Should that subtype=http_rb be considered a Ruby agent inconsistency bug?
Yes, but that is already be fixed in the newest Ruby agent.

**Comment by felixbarny** [comment]
> Is there much value in that "action" field at all?

That's definitely debatable. We don't use it in the UI aside from displaying it on the span level.
But in theory, someone could have built their own dashboards to get a graph per action, for example.
