### ISSUE TITLE
Add captureBody config option (replacing logBody)

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#208]
The `logBody` config option should be replaced with a `captureBody` option.

The `captureBody` config option should take a string that can have the following values: `errors`, `transactions`, `all`, and `off`.

- The default value should be `off`
- If the value is `errors`, the agent should include the HTTP request body for all errors that are sent to the APM Server
- If the value is `transactions`, the agent should include the HTTP request body for all transactions that are sent to the APM Server
- If the value is `all`, the agent should include the HTTP request body for both errors and transactions that are sent to the APM Server

**Comment by watson** [comment]
As pointed out by @beniwohli, the disabled value in the same config option in the Python agent is `none` instead of `off`. Though I personally like `off` better, I'm ok with changing this to align with the Python agent, if the Python agent doesn't change to use `off`. But if we start to go down this rabbit hole, we should also consider if `captureErrorLogStackTraces` should be changed as well since it uses `never` and `always` 😬

**Comment by beniwohli** [comment]
I don't actually check if the value is `'none'` anywhere, just if it's one of the other three, so changing it to `'off'` is simply a matter of documentation for me. Let's go with `'off'` 👍
