### ISSUE TITLE
Feature Request: span_min_duration

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2080]
The Java Agent provides [a `span_min_duration`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-span-min-duration) configuration value that allows for discarding of spans that don't meet a minimum threshold.  

We should investigate whether it's feasible to add this feature to the Node.js agent and, if feasible, implement it.

**Comment by bvader** [comment]
We have found `span_min_duration` to be a very valuable to help tune / reduce the "The Noise" collected by the agents. 

Specific Example that we used `span_min_duration` with the Java Agent to reduce 10-100s of millions 5-100us calls to Redis for CoreLogic. These calls just consumed massive amounts of telemetry, ingest capacity and storage and added little to no calue. The good thing if we actually had a slow Redis call it would show up as it would exceed the `span_min_duration`  (example we set to 1ms, some apps are even 2-5ms)

**Comment by trentm** [comment]
(Late follow-up to this.) This should now be handled by added support for these specs: https://github.com/elastic/apm/tree/main/specs/agents/handling-huge-traces

- v3.32.0 2022/04/27 Added support for span compression.
- v3.38.0 2022/08/11 Added support for `exitSpanMinDuration` ([spec](https://github.com/elastic/apm/blob/main/specs/agents/handling-huge-traces/tracing-spans-drop-fast-exit.md), [config var doc](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#exit-span-min-duration))
