### ISSUE TITLE
Capture Span Stack Traces off by Default

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2092]
This issue captures our intent to explore turning the `captureSpanStackTraces` configuration value off by default.

We should get some sanity perf. numbers to validate whether the overhead is low enough to justify this.

* * *

Proposal:

- [ ] Get a ballpark estimate of the perf impact of that `Error.captureStackTrace(obj, Span)` when `captureSpanStackTraces` is enabled.
- [ ] Argue for `captureSpanStackTraces` being false by default (possibly in the next major rev of the agent) if the perf impact is at all significant. (Paying CPU for span.stacktrace that one very rarely sees/uses is hard to justify).
- [ ] Update the performance tuning guide.

**Comment by trentm** [comment]
More discussion -- along with the `span_stack_trace_min_duration` (aka `spanFramesMinDuration`) config var -- here: https://github.com/elastic/apm/pull/585#pullrequestreview-857074810

**Comment by trentm** [comment]
The argument for why this change can be done in a minor version (i.e. is not a "breaking change") is here: https://github.com/elastic/apm/pull/585#issuecomment-1016688401

That thread also includes other relevant discussion.
