### ISSUE TITLE
Security vulnerability [moderate] in `hosted-git-info`

### ISSUE THREAD

**Issue by hsharif-rh** [elastic/apm-agent-nodejs#2099]
## Expected Behaviour
No security vulnerability related to Elastic APM.

## Current Behaviour
I'm seeing a moderate security vulnerability being flagged from `hosted-git-info` which is a dependency of `read-pkg-up`.

Additional info:
`moderate  │ Regular Expression Denial of Service`
`Package │ hosted-git-info`
`Patched in │ >=2.8.9 <3.0.0 || >=3.0.8`
`Path | elastic-apm-node > read-pkg-up > read-pkg > normalize-package-data > hosted-git-info`

## Possible Solution
Patch `hosted-git-info` dependency or a dependency further upstream.

## Steps to Reproduce
`npm audit` or `yarn audit`.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `elastic-apm-node --version` | 3.12.1 |
| `npm --version`  | 6.14.11 |
| `yarn --version` | 1.22.10 |
| `node --version` | 12.x |

| OS | Version |
| MacOS | Catalina |

**Comment by trentm** [comment]
@hsharif-rh Is this part of a larger project that has other dependencies?  My understanding is that the current dependency chain results in getting `hosted-git-info@2.8.9` which has the fix for this vulnerability.

Here is my failed attempt to reproduce with a fresh new project:

```
[8:54:51 trentm@pink:~/tmp (n:12)]
% node --version
v12.22.1
[8:54:54 trentm@pink:~/tmp (n:12)]
% npm --version
6.14.12
[8:54:57 trentm@pink:~/tmp (n:12)]
% mkdir n12
[8:55:00 trentm@pink:~/tmp (n:12)]
% cd n12
[8:55:02 trentm@pink:~/tmp/n12 (n:12)]
% npm init -y
Wrote to /Users/trentm/tmp/n12/package.json:

{
  "name": "n12",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


[8:55:07 trentm@pink:~/tmp/n12 (n:12)]
% npm install elastic-apm-node@3.12.1
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN n12@1.0.0 No description
npm WARN n12@1.0.0 No repository field.

+ elastic-apm-node@3.12.1
added 135 packages from 105 contributors and audited 135 packages in 5.334s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[8:55:18 trentm@pink:~/tmp/n12 (n:12)]
% npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 135 scanned packages
```


Are you able to share more details about the project (perhaps its "package.json" and/or "package-lock.json" and/or "yarn.lock") in which you are seeing this `npm audit` warning?  Thanks.

**Comment by trentm** [comment]
(Note this is the same as https://github.com/elastic/apm-agent-nodejs/pull/2098 that was recently opened -- and closed by me.)

**Comment by hsharif-rh** [comment]
@trentm thanks for the prompt response. I'll get some detailed info together soon, cheers!

**Comment by trentm** [comment]
> Path | elastic-apm-node > read-pkg-up > read-pkg > normalize-package-data > hosted-git-info

Currently this resolves for me as:

- elastic-apm-node@3.15.0 package.json has `"read-pkg-up": "^7.0.1",`
    - read-pkg-up@7.0.1 package.json has `"read-pkg": "^5.2.0",`
        - read-pkg@5.2.0 package.json has `"normalize-package-data": "^2.5.0",`
            - normalize-package-data@2.5.0 package.json has `"hosted-git-info": "^2.1.4",`
                - hosted-git-info@2.8.9

**Comment by hsharif-rh** [comment]
@trentm I ran `yarn audit` and I'm getting quite a few hits in various areas of our project. We are using `v3.12.1` of the APM library.

**Comment by hsharif-rh** [comment]
@trentm Hi mate, did you happen to get a chance to run the same process with `elastic-apm-node@3.12.1`?

**Comment by trentm** [comment]
> did you happen to get a chance to run the same process with `elastic-apm-node@3.12.1`?

@hsharif-rh I did. My [original comment attempting to repro](https://github.com/elastic/apm-agent-nodejs/issues/2099#issuecomment-854001421) used `npm install elastic-apm-node@3.12.1`.  I cannot repro with just a simple package.json whose *only* dependency is that version of elastic-apm-node.

```
% cat package.json
{
  "name": "n12",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "elastic-apm-node": "^3.12.1"
  }
}

% npm ls elastic-apm-node
n12@1.0.0 /Users/trentm/tmp/n12
└── elastic-apm-node@3.12.1

% npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 135 scanned packages

% node --version
v12.22.1

% npm --version
6.14.12
```

Possible issues:
1. Another one of your dependencies might be forcing an older version of `hosted-git-info`.  What does `npm ls hosted-git-info` and/or `yarn list --pattern hosted-git-info` show?
2. You might have an older version of `hosted-git-info` frozen in a "package-lock.json" or "yarn.lock" file?

**Comment by hsharif-rh** [comment]
Definitely could be the case with multiple versions of `hosted-git-info` existing in our `yarn.lock` file or even older versions of `elastic-apm-node`.

I'll do some digging next week and keep you in loop. Cheers for the prompt response!

**Comment by hsharif-rh** [comment]
All good, this is definitely coming from an earlier version in our lock file. Closing this, cheers!
