### ISSUE TITLE
elastic-apm-node seems to affect performance in our project

### ISSUE THREAD

**Issue by petermilan** [elastic/apm-agent-nodejs#2106]
In our project (API server powered by hapijs and graphql) we were just debugging some performance issues and we noticed weird readFile (visible using newrelic) happening during our requests. After we debugged this, we are under impression that it was happening in `elastic-apm-node"` module, as once we disabled the package in our project, the calls to readFile were not present in newrelic output and the performance of our requests was slightly improved. Any idea what could call the readFile so many times? Here is a screenshot from newrelic:
 
![image](https://user-images.githubusercontent.com/917147/121523767-dce40180-c9f6-11eb-8867-75af646b5dcc.png)

**Comment by trentm** [comment]
@petermilan Hi, thanks for reporting this! I'm sorry you are hitting a bad perf issue.

As a first guess, I was just working on a perf issue in elastic-apm-node (#2094) that hopefully could be a fix for this (part of that work included fixing a caching issue that could result in excessive `fs.readFile`).

1. A first thing to try, if you are able, is to set the agent's `captureSpanStackTraces` config setting to `false` (https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#capture-span-stack-traces); restart; then see if that immediately helps.

If so, then (a) we can dig more into why that might be and (b) I suspect updating to a new version of the agent (which we haven't released yet, but likely will today or early next week) will help you a lot here.

If **not**, then, if you are able, I'd like to see if we can get a profile of the running app to try to narrow it down.

**Comment by trentm** [comment]
@petermilan FYI: elastic-apm-node@3.16.0 has been published which includes a fix for that caching issue I mentioned. One thing you could try is upgrading to this version to see if that fixes the excessive `fs.readFile` issue you saw.

**Comment by trentm** [comment]
Closing for now. Please feel free to re-open this if you have more information that we can dig into. Thanks.

**Comment by petermilan** [comment]
Sorry for late reply, we managed to find time to test the issue for some short period of time, and looks like new version solved the perf issues

**Comment by trentm** [comment]
@petermilan That is great to hear. Thanks for getting back.
