### ISSUE TITLE
Trace Parent Header is not Propagated to Elasticsearch (in Kibana?)

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2116]
We've received reports that the Node.js agent is not propagating trace parent headers to elasticsearch

> Mikhail noted that the Node.js agent doesn’t propagate the trace parent header to Elasticsearch.

However -- the Node.js Agent _does_ propagate the trace parent header for requests made with the `elasticsearch` and `@elasticsearch/elasticsearch` modules, as well as any outgoing HTTP request made via the `http` or `https` modules (which most (but not all) Node.js request libraries are based on).  That happens here

https://github.com/elastic/apm-agent-nodejs/blob/7d6b2e992de0aceebf2e63a9c1fb369bb4126731/lib/instrumentation/http-shared.js#L160

Three questions for the Kibana team

1. Ideally, can you provide an **isolated** instance of the Node.js agent not propagating the trace parent header?

2. Is this request to elasticsearch handled by Node.js or is it a request being made directly by the browser/front-end? (in other words, is this a Node.js Agent problem or a Browser Agent problem?)

3. Is there a transaction active when the request is being made?

Number three is the sticky wicket here.  In order to add a trace parent header there will need to be a transaction active.  The Node.js agent will create transactions automatically when processing incoming HTTP requests, and we have an API for manually creating transactions.  If these requests to elasticsearch are happening outside of a transaction, a header will not be propagated. 

If we can get answers to the above three questions we'll be better situated to advise on what's going on.

**Comment by trentm** [comment]
@mshustov ^^

**Comment by mshustov** [comment]
@astorm I don't rule out that the problem is the way I tested. Here you can find a Kibana setup I used:
https://github.com/elastic/kibana/compare/master...mshustov:kibana-server-tracing-header?expand=1
I create a transaction in the Kibana server. To trigger it, you need to hit  `/core` endpoint with `curl -i -X GET http://127.0.0.1:5601/core`.

In the logs I can see:
```
SpanIds {
  'trace.id': '06359fe65b0caba6f05b89a4924cd5de',
  'span.id': 'fa2352da8eb62702'
}
```
but the outgoing request headers:
```
{
    'user-agent': 'elasticsearch-js/8.0.0-canary.13 (darwin 18.7.0-x64; Node.js v14.17.0)',
    'x-elastic-product-origin': 'kibana',
    'x-elastic-client-meta': 'es=8.0.0p,js=14.17.0,t=8.0.0p,hc=14.17.0'
}
```
In the agent verbose logs, I found messages that apm agent sends the transaction.
```
{"log.level":"debug","@timestamp":"2021-06-18T06:12:01.932Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"sending span {\"span\":\"fa2352da8eb62702\",\"parent\":\"e8e810ea9ffa6239\",\"trace\":\"06359fe65b0caba6f05b89a4924cd5de\",\"name\":\"GET localhost:9200/_cat/indices\",\"type\":\"external\"}"}
{"log.level":"debug","@timestamp":"2021-06-18T06:12:01.932Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"sending span {\"span\":\"af6807c2e9c106e6\",\"parent\":\"e8e810ea9ffa6239\",\"trace\":\"06359fe65b0caba6f05b89a4924cd5de\",\"name\":\"Elasticsearch: GET /_cat/indices\",\"type\":\"db\"}"}
```

I'm not sure how the `@elastic/elasticsearch` stores `event.meta.request.params.headers`. Maybe `apm-nodejs-agent` injects headers at a later stage?

**Comment by astorm** [comment]
Thanks for the repro @mshustov, this makes what you're seeing much clearer to me.

I took a look at the implementation of `@elastic/elasticsearch` and it does appear the headers returned in the response event are created/set earlier than the the Node.js agent's trace(parent|state) headers.  

Specifically, it looks like the headers included with the event/result for a response are set here

https://github.com/elastic/elasticsearch-js/blob/4933e3b9bec474511233f5a05819e493060a86e2/lib/Transport.js#L351

which is well before the `makeRequst` function gets called

https://github.com/elastic/elasticsearch-js/blob/4933e3b9bec474511233f5a05819e493060a86e2/lib/Transport.js#L416-L434

and, just to be thorough, when the Node.js Agent intercepts the request in order to add the `traceparent` header, we're working with a copy of this data.

https://github.com/elastic/apm-agent-nodejs/blob/a07eb3a6616d25bf91cb0cf4ce982d7c1af18be4/lib/instrumentation/http-shared.js#L138-L146

Also, FWIW, if we weren't setting a trace parent header here it would stop all sorts of features in the UI from working as expected (trace view, service maps, etc.).

I think we're set here so we're going to close this one out.  If there's more discussion to be had though don't hesitate to re-open and/or keep going!

**Comment by mshustov** [comment]
> which is well before the makeRequst function gets called

Alright, now I see. The `apm agent` wraps the `http.request` method to inject the trace headers.
It's a bit confusing, that `@elastic/elasticsearch` client doesn't provide the *actual* headers sent with an outbound request. @delvedor is it something we can fix on the `@elastic/elasticsearch` client level?

**Comment by trentm** [comment]
> is it something we can fix on the @elastic/elasticsearch client level?

@delvedor can, of course, override me, but I wouldn't think so.  There will always be handling underneath and outside the responsibility of the ES client in the HTTP client libraries and HTTP agent that control what headers are actually sent. For example node's http client and agent will potentially set Keep-Alive, Host, and Authorization depending on various options.   Perhaps the ES client docs could be clearer here? I'm not sure.

One technique that can be used to get what headers are actually being sent is to use node's built-in debug logging via `NODE_DEBUG=http`. For example: https://gist.github.com/trentm/34bc84e65095f4e3bca5255829f93040

**Comment by mshustov** [comment]
> There will always be handling underneath and outside the responsibility of the ES client in the HTTP client libraries and HTTP agent that control what headers are actually sent. 

`@elastic/elasticsearch` client is already coupled with `http`: for example,  `headers` leak into the ES client interface. From this point of view, it might be reasonable to have access to all the headers sent. Or don't have access to them at all, if we consider a network layer to be an implementation detail.

**Comment by astorm** [comment]
@mshustov @trentm I've opened a discussion over in the `@elastic/elasticsearch` repo to track the discussion on `@elastic/elasticsearch` and so it doesn't get lost down here in a closed issue.  https://github.com/elastic/elasticsearch-js/issues/1483
