### ISSUE TITLE
export AgentConfigOptions, Transaction, etc. from index.d.ts

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2118]
@mshustov asked:

> Is there a specific reason why this interface [`AgentConfigOptions`] is not exported? https://github.com/elastic/apm-agent-nodejs/blob/master/index.d.ts#L192
> Kibana has to work it around https://github.com/elastic/kibana/blob/4584a8b570402aa07832cf3e5b520e5d2cfa7166/packages/kbn-apm-config-loader/src/types.ts
> ...
> I think the agent could export all the public types: AgentConfigOptions, TransactionOptions, Transaction, Span, SpanOptions. that user interact with.

I don't believe there is a design reason to not export these types.

There might be a *practical* reason in the difference between [`export =`](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) and [`export default ...`](https://www.typescriptlang.org/docs/handbook/modules.html#default-exports). The agent current uses the former: https://github.com/elastic/apm-agent-nodejs/blob/a07eb3a6616d25bf91cb0cf4ce982d7c1af18be4/index.d.ts#L5
which, IIUC, is models the actual CommonJS export style: https://github.com/elastic/apm-agent-nodejs/blob/a07eb3a6616d25bf91cb0cf4ce982d7c1af18be4/index.js#L5

I don't have a solid enough experience with TypeScript to know if changing to this will have some unexpected issue:

```
export default agent
export interface AgentConfigOptions {
...
```

Experience from others is welcome.

**Comment by trentm** [comment]
Some guidance here on "DTS files": https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

**Comment by mshustov** [comment]
@trentm APM-RUM agent `d.ts` file https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum/src/index.d.ts

**Comment by trentm** [comment]
Notes (somewhat to self).

### option B: define everything in index.d.ts like we have now.

This seems to work, but I don't see a way to export "Agent" itself.

```typescript
declare interface Agent {
  start (options?: agent.AgentConfigOptions): Agent;
  isStarted (): boolean;
  // ...
}

declare const agent: Agent;
export = agent

// Re-export some public API types.
declare namespace agent {
  export interface AgentConfigOptions {
    abortedErrorThreshold?: string;
    active?: boolean;
    captureExceptions?: boolean;
    serviceName?: string;
    // ...
  }
  // ...
}
```

The state of using this type definition file is:

```typescript
import apm from '.' // 'elastic-apm-node'
// Or can also do this:
//   import type { AgentConfigOptions } from '.' // 'elastic-apm-node'

// Auto-complete in VS code works for these
apm.start({
  abortedErrorThreshold: '10s'
})
apm.isStarted()

// Can use the export AgentConfigOptions type now.
function getDefaultConfig(): apm.AgentConfigOptions {
  return {}
}

// This does NOT work.
// As noted above, I don't see a way to export `Agent`.
interface MyAgent extends apm.Agent {
}
```

**Comment by trentm** [comment]
So I am now favouring:

### option A: define in separate .d.ts files and re-export here.

```typescript
import Agent_, { AgentConfigOptions as AgentConfigOptions_ } from './lib/agent';

// The export is a singleton instance of the `Agent` class.
declare const agent: Agent_;
export = agent

// Re-export some public API types.
declare namespace agent {
  export type Agent = Agent_;
  export type AgentConfigOptions = AgentConfigOptions_;
  // ...
}
```

The use cases work:

```typescript
import apm from '.' // 'elastic-apm-node'
// Or can also do this:
//   import type { AgentConfigOptions } from '.' // 'elastic-apm-node'

// Auto-complete in VS code works for these
apm.start({
  abortedErrorThreshold: '10s'
})
apm.isStarted()

// Can use the export AgentConfigOptions type now.
function getDefaultConfig(): apm.AgentConfigOptions {
  return {}
}

// This does now WORKS.
interface MyAgent extends apm.Agent {
}
```

**Comment by mshustov** [comment]
@trentm tests the current implementation locally. In both VSCode and WebStorm, click on an exported type (`AgentConfigOptions`, for example), navigates a user to a place where it's re-exported https://github.com/elastic/apm-agent-nodejs/pull/2119/files#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R16
It's not the ideal Developer Experience. 
Cannot we declare and export types right from the root of `index.ts` file?
```typescript
// index.d.ts file
export {
  AgentConfigOptions,
  Transaction,
  TransactionOptions,
  Span,
  SpanOptions,
} from './lib/agent';
```

or declare them in `d.ts` file as described in the TS docs https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#reference-example?

> This seems to work, but I don't see a way to export "Agent" itself.

Doesn't it work out?
```typescript
import Agent_ from './agent.d.ts`
export default Agent_
```
Or `agent` is the singletone? Then we might need to use [InstanceType](https://www.typescriptlang.org/docs/handbook/utility-types.html#instancetypetype) helper.

**Comment by trentm** [comment]
> Or agent is the singletone? 

Yes the exported agent is a singleton. 

> > This seems to work, but I don't see a way to export "Agent" itself.

Now I'm no longer sure why/if this (exporting the "Agent" class/namespace/type) is a requirement. If so, I think this basically works:

```
interface Agent_ {
  start (options?: apm.AgentConfigOptions): Agent_
  isStarted (): boolean;
}

declare const apm: Agent_

declare namespace apm {
  export type Agent = Agent_

  export interface AgentConfigOptions {
    abortedErrorThreshold?: string;
    active?: boolean;
    captureExceptions?: boolean;
    serviceName?: string;
    // ...
  }

  // ...
}

export = apm
```

I.e. re-exporting `Agent_` as `Agent`. The down-side of this is the presence of `Agent_` (with the underscore) in type info, e.g.:

![Screen Shot 2021-08-16 at 5 58 39 PM](https://user-images.githubusercontent.com/46866/129647250-4da77f40-6a14-4908-b7d1-7b1f2f28c0f6.png)

**Comment by trentm** [comment]
For now let's assume exporting `apm.Agent` is *not* a requirement. I.e. we do not need to support this:

```typescript
import apm from '.' // 'elastic-apm-node'
// Or:
//   import type { Agent } from '.' // 'elastic-apm-node'

// Extending apm.Agent works.
interface MyAgent extends apm.Agent {
  foo (): boolean
}
let a: MyAgent
a.foo()
a.isStarted()
```

If later needed it can be done as in the previous comment.

**Comment by trentm** [comment]
Apparently this works to export `Agent` without having to use an alias:

```typescript
declare namespace apm {
  export interface Agent {
    start (options?: AgentConfigOptions): Agent;
    isStarted (): boolean;
  }
  export interface AgentConfigOptions {
    active?: boolean;
  }
}
declare const apm: apm.Agent;
export = apm
```

So I'm trying this.

**Comment by trentm** [comment]
@mshustov `elastic-apm-nodejs@3.21.0` has now been published with this index.d.ts improvement.
