### ISSUE TITLE
Clarify ignoreUrls / ignoreUserAgents in documentation

### ISSUE THREAD

**Issue by danieljuhl** [elastic/apm-agent-nodejs#212]
It is not clear if ignoring urls/user-agents only disables the transaction tracing or if any errors would also be ignored.

**Comment by watson** [comment]
Thanks for raising this issue.

It just stops the request from being instrumented - I.e. no transaction will be created for that request. Any error that happens during the request will still be sent to the APM Server.

I'll make sure to update the docs to make this more clear 😃

**Comment by TehNrd** [comment]
I realize this is old but I still find this documentation a bit confusing. The metadata object for a transaction contains the following data and if I wanted to match on a string value for the URL...

```
url.full        https://api.mysite.io:443/v1/utils/pause?duration=2500
url.original    /v1/utils/pause?duration=2500
url.path        /v1/utils/pause

```
...which exact string would it be? 

I assumed it would be `/v1/utils/pause` as that is what is shows up in the APM dashboard, but that does not appear to be the correct value.
