### ISSUE TITLE
[META 352] AWS Lambda support

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#2156]
Add support for AWS lambda as described in the meta issue: https://github.com/elastic/apm/issues/352

**Comment by astorm** [comment]
An initial To Do list for the Node.js Agent's Lambda support

- Determine the fate of instrumentation for context.success, context.fail, and context.done (no longer documented – should we keep these?)
- Handling async handler functions
- Include processing of tracestate header along with traceparent
- Collect data per the draft spec
- Create “metadata from env” fetcher
- Cold Start detector
- Solving the “Thawed execution environment but no APM Server Connection” errors

**Comment by trentm** [comment]
This depends on:

- [ ] https://github.com/elastic/apm-nodejs-http-client/issues/165
- [ ] https://github.com/elastic/apm-agent-nodejs/issues/2294
