### ISSUE TITLE
mongodb 4.0.x causes startup to hang/fail

### ISSUE THREAD

**Issue by stevenhair** [elastic/apm-agent-nodejs#2170]
**Describe the bug**

With mongodb 4.0.1 installed, application startup will either hang or fail.

**To Reproduce**

Steps to reproduce the behavior: 
1. Add elastic-apm-node to a project that uses mongodb 4 (or upgrade an existing one)
2. Start the application

**Expected behavior**

The application should start

**Environment (please complete the following information)**

- OS: CentOS 7/macOS 11.4
- Node.js version: 14.7.3
- APM Server version: N/A
- Agent version: 3.18.0

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [X] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    module.exports = {
      serverUrl: 'https://elastic-apm.mydomain.com/',
      secretToken: '...',
      environment: 'dev',
      captureBody: 'all',
      centralConfig: false,
      serviceName: 'MyService',
      active: true,
      logLevel: 'debug',
    };
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    "@nestjs/axios": "0.0.1",
    "@nestjs/common": "^8.0.4",
    "@nestjs/core": "^8.0.4",
    "@nestjs/platform-express": "^8.0.4",
    "@nestjs/schedule": "^1.0.0",
    "amqplib": "^0.8.0",
    "axios": "^0.21.1",
    "body-parser": "^1.18.2",
    "cookie-parser": "^1.4.5",
    "csv-parse": "^4.15.0",
    "date-fns": "^2.21.0",
    "elastic-apm-node": "^3.18.0",
    "express": "^4.16.2",
    "express-openapi-validator": "^4.12.15",
    "hs-fuzzy-dates": "1.0.1",
    "is-base64": "^1.1.0",
    "minimist": "^1.2.5",
    "moize": "^6.0.3",
    "mongodb": "^4.0.1",
    "pako": "^2.0.3",
    "queue-promise": "^2.2.1",
    "rascal": "^13.1.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "snowflake-sdk": "^1.5.3",
    "source-map-support": "^0.5.19",
    "ts-retry": "^2.3.4",
    "xml2js": "^0.4.23",
    "xmlbuilder": "^15.1.1"
    ```
  </details>

**Comment by astorm** [comment]
Thanks for reporting @stevenhair -- we were able to reproducing the crashing behavior, but not the hanging behavior.  It looks like the new mongo 4.0 version moved some cheese we rely on.  We've got a PR in flight to get this fixed over here: https://github.com/elastic/apm-agent-nodejs/issues/2170

Your issue didn't include a specific reproduction, but if you could test the branch from https://github.com/elastic/apm-agent-nodejs/issues/2170 to see if it clears up your problem that'd be a big help in validating our fix.  Otherwise, keep an eye on https://github.com/elastic/apm-agent-nodejs/issues/2170 landing and getting into the next release.

**Comment by stevenhair** [comment]
I just gave 14279590029c509a57f8d7ffdfcb855261aa2ad8 a try and it does indeed solve my issue. Thanks!

**Comment by astorm** [comment]
That's great to hear @stevenhair -- also kudos for finding the right commit when I liked to the wrong issue (that should have been https://github.com/elastic/apm-agent-nodejs/pull/2171 -- since corrected)

PRs been merged, and we're closing this one out.

**Comment by trentm** [comment]
@stevenhair elastic-apm-node@3.19.0 is now published with this fix.

**Comment by stevenhair** [comment]
@trentm thank you!
