### ISSUE TITLE
Dumb question: does this APM lib support OpenTelemetry?

### ISSUE THREAD

**Issue by JaneJeon** [elastic/apm-agent-nodejs#2183]
I noticed that on the documentation it only states compatibility with Open_Tracing_, which is not necessarily the same as Open_Telemetry_. I've even read this https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html and I'm still not entirely sure that this specific library pushes its traces in OTel format...

**Comment by astorm** [comment]
No such thing as a dumb question @JaneJeon -- especially when it comes to distinctions around OpenTracing, OpenTelemetry, and APM Agents.  Hopefully this will clear things up. 

1. Elastic's Node.js Agent pushes traces to APM Server in a custom format that predates both OpenTracing and OpenTelemetry

2. We were an early supporter of OpenTracing and [developed an open tracing bridge](https://www.elastic.co/guide/en/apm/agent/nodejs/current/opentracing.html)

3. Re: OpenTelemetry -- the Node.js Agent does not _currently_ support sending traces in the OpenTelemetry format.  We may consider this in a future release.

That doesn't mean you can't use OpenTelemetry with Elastic's Observability platform though!

What Elastic does support is the ability to _export_ data directly from an OpenTelemetry instrumented application to APM Server using the OTLP format. At a high level, you'll instrument your application using the OpenTelemetry libraries, and then configure an OpenTelemetry exporter to point at APM Server's OTLP endpoint.  

This means when you're using Elastic's Observability platform you can choose between instrumenting your application with Elastic's existing agents, the new OpenTelemetry instrumentation, or both!

I think that answers your question, so I'm going to close this out.  However, if I've missed the mark please don't hesitate to keep the conversation going.
