### ISSUE TITLE
warn on `errorMessageMaxLength` deprecated config option usage

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2314]
The `errorMessageMaxLength` option was deprecated by `longFieldMaxLength` in #2193. The option should be removed for the next major version.

Update (2023-07): Let's just warn with `process.emitWarning` (... or log.warn?)

**Comment by david-luna** [comment]
As discussed we will `log.warn`

**Comment by trentm** [comment]
This was done in https://github.com/elastic/apm-agent-nodejs/pull/3553 on the "dev/4.x" branch, which will be the active 4.x release branch soonish.
