### ISSUE TITLE
Import of the package types requires dependency installation

### ISSUE THREAD

**Issue by mshustov** [elastic/apm-agent-nodejs#2338]
**Describe the bug**

If I import any types from the package, the TypeScript compiler fails the type check since my project doesn't have `elastic-apm-node` dependencies installed.

**To Reproduce**

Steps to reproduce the behavior: 
1. install `v3.21.0`
2. Import any type from the package
3. Run type check
4. See errors:
```
12:27:36  ERROR Type check failed in packages/kbn-cli-dev-mode/tsconfig.json:
12:27:36  ERROR node_modules/elastic-apm-node/index.d.ts:4:43 - error TS7016: Could not find a declaration file for module 'pino'. '/dev/shm/workspace/parallel/14/kibana/node_modules/pino/pino.js' implicitly has an 'any' type.
12:27:36          Try `npm i --save-dev @types/pino` if it exists or add a new declaration (.d.ts) file containing `declare module 'pino';`
12:27:36  
12:27:36        4 import type { Logger as PinoLogger } from 'pino';
12:27:36                                                    ~~~~~~
12:27:36  
12:27:36        node_modules/elastic-apm-node/index.d.ts:5:31 - error TS7016: Could not find a declaration file for module 'connect'. '/dev/shm/workspace/parallel/14/kibana/node_modules/connect/index.js' implicitly has an 'any' type.
12:27:36          Try `npm i --save-dev @types/connect` if it exists or add a new declaration (.d.ts) file containing `declare module 'connect';`
12:27:36  
12:27:36        5 import type * as Connect from 'connect';
12:27:36                                        ~~~~~~~~~
12:27:36  
12:27:36        node_modules/elastic-apm-node/index.d.ts:6:33 - error TS2307: Cannot find module 'aws-lambda' or its corresponding type declarations.
12:27:36  
12:27:36        6 import type * as AwsLambda from 'aws-lambda';
12:27:36                                          ~~~~~~~~~~~~
12:27:36  
```

**Additional context**
It happens because the published APM agent package imports types from the 3rd party packages:
``` typescript
import type { Logger as PinoLogger } from 'pino';
import type * as Connect from 'connect';
import type * as AwsLambda from 'aws-lambda';
```

There are two options:
- Consumers of the `elastic-apm-node` types have to install `@types/...` for these packages in their project, which is PITA.
- `elastic-apm-node` includes the deps in the distributable, that seems to be the recommended way according to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html `For that reason, we used "dependencies" and not "devDependencies", because otherwise our consumers would have needed to manually install those packages.`

**Comment by trentm** [comment]
@mshustov Pretty sure this is a dupe of https://github.com/elastic/apm-agent-nodejs/issues/2331 for which we got a quick v3.21.1 release out yesterday. Are you able to try that?  There is still a requirement for TypeScript users to manually install `@types/node` themselves.

**Comment by mshustov** [comment]
@trentm yup, the update to `3.21.1` worked out
