### ISSUE TITLE
appName changed to serviceName - documentation not updated everywhere

### ISSUE THREAD

**Issue by StianOvrevage** [elastic/apm-agent-nodejs#237]
When updating APM-server and debugging I found out that appName was for some reason renamed to serviceName.

But, the docs are not updated everywhere:

https://www.elastic.co/guide/en/apm/get-started/current/install-and-run.html

**Comment by danieljuhl** [comment]
@watson would it also be possible to have a list of breaking changes? Especially for us, who used (and tested) the alpha/beta, so that an upgrade can be so smooth as possible, when upgrading both apm-server and multiple projects using the agent.

**Comment by watson** [comment]
@danieljuhl I've just created a PR with an upgrade guide - let me know what you think: #245

**Comment by danieljuhl** [comment]
@watson looking great. Will do our upgrade this weekend and let you know if something was missing :)
