### ISSUE TITLE
AWS instrumentations for SDK version 3

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#2376]
- [x] https://github.com/elastic/apm-agent-nodejs/issues/2955
- [x] https://github.com/elastic/apm-agent-nodejs/issues/2956
- [x] https://github.com/elastic/apm-agent-nodejs/issues/2957
- [x] https://github.com/elastic/apm-agent-nodejs/issues/2958

**Comment by david-luna** [comment]
https://github.com/elastic/apm-agent-nodejs/pull/3287 for S3

**Comment by david-luna** [comment]
#3486 for DynamoDB
