### ISSUE TITLE
empty tracestate header sometimes sent on outgoing http requests

### ISSUE THREAD

**Issue by PaulMougel** [elastic/apm-agent-nodejs#2405]
The library sometimes adds an empty `tracestate` header for outgoing HTTP requests.

Unfortunately, HTTP requests with a header set with an empty value are blocked by our destination server, where they are flagged as an HTTP Protocol violation. This API call, otherwise valid, is thus blocked because of the APM agent. We have been forced to pin the version of `apm-agent-nodejs@3.13.0`, which is a version that does not show this behavior.

I'm opening an issue following previous discussion in [this PR comment](https://github.com/elastic/apm-agent-nodejs/pull/2038#discussion_r730060651).

The `tracestate` header has no value and is sent over the wire as `tracestate:`. However, `traceparent` and `elastic-apm-traceparent` do have values.

**To Reproduce**
_work in progress_

**Expected behavior**

The `tracestate` HTTP header is not sent over the wire if it has no value.

**Environment (please complete the following information)**

- OS: `Debian GNU/Linux 9`
- Node.js version: `14.18.1`
- APM Server version: N/A
- Agent version: `apm-agent-nodejs@3.23.0`

**How are you starting the agent? (please tick one of the boxes)**
Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    captureSpanStackTraces: false,
    transactionMaxSpans: 200,
    transactionSampleRate: 0.5,
    metricsInterval: '1m',
    metricsLimit: 100,
    logger: <pinojs logger>
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    N/A
    ```
  </details>

**Comment by trentm** [comment]
Thanks for opening the issue. Sorry for the delay.
Here is my repro:

1. First, have a separate server that our example script will call. This is the server that will receive a request with the empty `tracestate`.  Mine is running at `http://localhost:8200`.

2. Run this script that starts an HTTP server listening at `http://localhost:3000` that will make an outgoing `GET http://localhost:8200/` when called.  Using an HTTP server will start an APM transaction that picks up a possible trace-context headers (`traceparent` and `tracestate`):

```js
// example-empty-tracestate.js

const apm = require('./').start({ // elastic-apm-node
  metricsInterval: '0s',
  centralConfig: false,
  cloudProvider: 'none',
  logUncaughtExceptions: true,
  useElasticTraceparentHeader: false,
  captureSpanStackTraces: false
})

const http = require('http')

const server = http.createServer(function (serverReq, serverRes) {
  http.get('http://localhost:8200/', function (res) {
    console.warn('XXX res: %s %s', res.statusCode, res.headers)
    res.resume()
    res.on('end', function () {
      console.warn('XXX done client request')
      serverRes.writeHead(200)
      serverRes.end()
    })
  })
})
server.listen(3000, function () {
  console.warn('XXX server listening at http://localhost:3000')
})
```

3. Start that server and make an HTTP request **that includes a valid traceparent**:

```
% node example-empty-tracestate.js
XXX server listening at http://localhost:3000
XXX res: 200 {
  date: 'Mon, 15 Nov 2021 23:49:32 GMT',
  connection: 'close',
  'content-length': '0'
}
XXX done client request
```

```
% curl -i http://localhost:3000/ -H 'traceparent:00-ffd94b597c5c451046258fbf33d446c3-ffbbfe97c361882b-01'
HTTP/1.1 200 OK
Date: Mon, 15 Nov 2021 23:49:32 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

The result is that the outgoing HTTP request from the example script is:

```
    GET / HTTP/1.1
    traceparent: 00-ffd94b597c5c451046258fbf33d446c3-0c132eaeaf22357f-01
    tracestate:
    host: localhost:8200
    connection: close
```

Per our [spec](https://github.com/elastic/apm/blob/master/specs/agents/tracing-distributed-tracing.md#tracestate):

> Note that we will currently only ever populate an es `tracestate` entry at the trace root.

By passing in a `traceparent` for the `GET http://localhost:3000/`, the transaction created by the script is *not* a trace root, so we don't set a tracestate value.  However, I suspect later code in the agent that is setting trace-context headers for outgoing requests is not checking for "falsey" values.

As to the *HTTP spec*, my read of the ABNF at https://datatracker.ietf.org/doc/html/rfc7230#section-3.2 is that an empty header value is explicitly allowed. However, this is about supporting picky proxies/servers that do not like empty header values.

**Comment by Marsup** [comment]
This is great! I thought it was a bug all along, I could have spent quite some time reproducing that one. I entirely agree with you that this isn't an APM issue, the problem is on the receiving end, they're on the verge of fixing it, but your patch will be most welcome. Thanks a lot for spending time on this.

**Comment by PaulMougel** [comment]
Hi @trentm. Thank you very much for the repro and commit.

This will 100% solve our issue with picky destination servers and will definitely help us a lot in the future by removing weird edge cases that are hard to debug.

Very much appreciated 🙏

**Comment by trentm** [comment]
elastic-apm-node@3.25.0 is published now with this change.

**Comment by PaulMougel** [comment]
Thanks!
