### ISSUE TITLE
Lambda: fill the HTTP context for API Gateway-triggered functions

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2419]
https://github.com/elastic/apm-agent-nodejs/pull/2194#discussion_r742328035

> Also the spec says:
>> The agent should use the information in the request and response objects to fill the HTTP context (context.request and context.response) fields in the same way it is done for HTTP transactions.
>Perhaps a separate issue to add `transaction.context.{request,response}` fields? We won't be able to re-use the `parsers.getContextFrom{Request,Response}()` functions that take core http objects.

**Comment by trentm** [comment]
Relevant spec section: https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-aws-lambda.md#api-gateway-v1--v2

**Comment by trentm** [comment]
See https://github.com/elastic/apm-agent-nodejs/issues/3000 that I think might just be handled by doing this one.
