### ISSUE TITLE
Increasing memory usage

### ISSUE THREAD

**Issue by rgallagher27** [elastic/apm-agent-nodejs#243]
We've been encountering a problem where the memory usage on our app servers increases steadily over time until they die when enabling APM.

We've tried multiple different options for reducing memory usage, including decreasing the `flushInterval` to 5, decreasing the `maxQueueSize` to 25 and decreasing the `transactionSampleRate` to 0.1 but all this has achieved is reducing the rate at which the memory usage increases at. 

I've attached a screenshot of our NewRelic monitoring of the memory usage. Each dip from ~3Gb is the instance failing and being restarted.

![screen shot 2018-02-15 at 10 21 08](https://user-images.githubusercontent.com/1388136/36253091-820125d6-123e-11e8-9069-80bc5647f914.png)

**Comment by Qard** [comment]
What modules are you using? Can you share what dependencies your app has and what versions they are? Some more detail about exactly what your app does might help too.

**Comment by rgallagher27** [comment]
Sure, this service is basically just for querying products in our Elasticsearch Database so performs queries and aggregations agains our ES cluster. 

The main dependencies we have are:

* Hapi (16.6.2)
* Elasticsearch (13.3.1)
* AWS sdk (2.97.0)
* Mongoose (4.9.8)
* Redis (2.8.0)

We also have other APM, logging dependencies:

* Newrelic (1.40.0)
* good (7.2.0)

**Comment by Qard** [comment]
Sorry for the delay, I'm still investigating this.

For now, you could also try setting `sourceLinesErrorAppFrames` and `sourceLinesErrorLibraryFrames` to `0`. Source code context lines are another potential source of excessive memory use. It shouldn't be leaky, but it might build up a bit in the reporting queue if there's a lot of activity happening in each request.

**Comment by Qard** [comment]
We released a new version recently which fixed a memory leak that was surfacing in mongoose, related to the promise microtask queue. Let me know if that fixes your problem. I'm closing this, but feel free to re-open it if you are still having problems. 😸
