### ISSUE TITLE
[META 545] Drop unsampled transactions when connected to APM Server 8.0+

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#2455]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F545)](https://github.com/elastic/apm/issues/545)

[![issue details](https://img.shields.io/endpoint?label=spec-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F552)](https://github.com/elastic/apm/issues/552)

Drop unsampled transactions when the agent is connected to an APM Server of version 8.0 or higher.

* * *

- [ ] Does APM server back to the [supported](https://www.elastic.co/guide/en/apm/guide/7.16/agent-server-compatibility.html) version 6.6 have this "version" in the JSON response body of "GET /"?

**Comment by trentm** [comment]
FYI: The java agent PR: https://github.com/elastic/apm-agent-java/pull/2329/files
If I read that correctly, it doesn't block processing on having gotten a first version value from the APM server... instead it defaults to saying "yes, this is possibly an older APM server that should recent unsampled transactions" up until it has a value.

https://github.com/elastic/apm-agent-java/blob/8e15859b583fab19c12aeef25be2fc8e11227d62/apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java might be useful for comparison.

**Comment by trentm** [comment]
The Python agent seems to do possibly the opposite:
- It will "GET /" from APM server lazily when the first batch of events is ready to send to APM Server (setting `client.server_version`). If there is some error the `client.server_version` is left `None`.
- Subsequent checks whether the server is `>= 8.0` will default to passing if `server_version` couldn't be set, or hasn't yet been set.


Q:
- [ ] Does APM server back to the [supported](https://www.elastic.co/guide/en/apm/guide/7.16/agent-server-compatibility.html) version 6.6 have this "version" in the JSON response body of "GET /"?

**Comment by trentm** [comment]
Spec ref: https://github.com/elastic/apm/blob/main/specs/agents/tracing-sampling.md#non-sampled-transactions
