### ISSUE TITLE
Error/warnings after upgrade

### ISSUE THREAD

**Issue by sibelius** [elastic/apm-agent-nodejs#2464]
**Describe the bug**

elastic-apm-node is reporting this:

```jsx
{"log.level":"error","@timestamp":"2021-11-23T18:01:49.668Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200"}
```

from version 3.22.0  to 3.24.0

**To Reproduce**

Update to 3.24.0

Steps to reproduce the behavior: 
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**

**Environment (please complete the following information)**

- OS: [e.g. Linux] mac
- Node.js version: node 16
- APM Server version: 3.24.0
- Agent version: 

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [x] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by trentm** [comment]
@sibelius I don't believe there was any change in versions 3.23.0 and 3.34.0 of the agent that would cause this. The error:

> APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200

indicates that there is no APM Server process listening at 127.0.0.1:8200. 

- What is the output of running `curl -i http://127.0.0.1:8200/` to see if there is an APM Server at that URL responding?
- Running the agent with trace logging (`ELASTIC_APM_LOG_LEVEL=trace node app.js`) might help provide some more detail.

**Comment by sibelius** [comment]
this was the error/warning before

{"log.level":"error","@timestamp":"2021-11-23T18:27:56.069Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"Elastic APM isn't correctly configured: serviceName \"@app/main\" contains invalid characters! (allowed: a-z, A-Z, 0-9, _, -, <space>)"}

**Comment by trentm** [comment]
> Elastic APM isn't correctly configured: serviceName "@app/main" contains invalid characters! 

Ah. *That* behaviour has changed in v3.24.0 of the agent.
Elastic APM trace reporting requires a [`serviceName`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#service-name) and it must only include these characters:

> Allowed characters: a-z, A-Z, 0-9, -, _, and space.

The "@" in "@app/main" is illegal.   
Typically for Node.js projects, the APM agent will use the "name" field from "package.json".
Version 3.24.0 of the APM agent included a change to normalize "@someOrg/somePackageName" to "someOrg-somePackageName" so that it satisfies the requirement for `serviceName`.

So what is happening is that the APM agent startup is getting farther along: It no longer fails with the illegal "@" in the `serviceName`.  The next thing needed is a [`serverUrl`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#server-url) configuration pointing to a running APM Server, to which the APM agent sends tracing data.

**Comment by sibelius** [comment]
the problem was that apm was just doing 1 warning 

and in the latest version if keep sending the error/warning 

![image](https://user-images.githubusercontent.com/2005841/143085884-36b5bf8f-4dab-46e2-871a-ea83d8757298.png)

**Comment by trentm** [comment]
Currently the agent is logging that error every time it attempts to speak to APM server and the connection fails. It talks to APM server roughly every 30s by default (per the `apiRequestTime` config var), plus occasional requests for central config (per the `centralConfig` config var).

Given that trouble communicating with APM Server can be intermittent (the APM server could go down for a while, come back up, go down, etc.), we can't change this to only log that error the first time it happens.  We could look into reducing the frequency of this error log message for consecutive failures.

Is there a reason your application is turning on the APM agent without an APM server to which to send trace data?

**Comment by sibelius** [comment]
this usually only happens on dev mode

right now we are adding `ELASTIC_APM_ACTIVE=false` to avoid this errors

**Comment by trentm** [comment]
If you have a dev mode (say for CI or tests) with no APM server, then `ELASTIC_APM_ACTIVE=false` is reasonable. Another option is the relatively recently added [`disableSend`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#disable-send) config var that tells the APM agent to work normally except that it never tries to talk to APM Server.

Note as well that the agent will pick up a local `elastic-apm-node.js` file for config as well, so you might be able to have something like:

```js
// elastic-apm-node.js
function isDevMode() {
   // ... return true if in dev-mode
}
module.exports = {
    disableSend: isDevMode()
}
```

**Comment by sibelius** [comment]
good enough for us

thanks for the info

**Comment by trentm** [comment]
No problem!
