### ISSUE TITLE
MongoDB instrumentation not working with MongoClient.connect static method

### ISSUE THREAD

**Issue by abreu-gyant** [elastic/apm-agent-nodejs#2467]
**Describe the bug**

MongoDB instrumentation is not working when the `MongoClient` is created through the static method. Also, when creating the `MongoClient` through the constructor it only works if `monitorCommands: true` is set in the client options.

**To Reproduce**

```javascript
import * as apm from 'elastic-apm-node';

apm.start({
  serviceName: 'MongoDB Test',
  serverUrl: 'http://localhost:8200/',
  logLevel: 'debug',
});

async function test() {
  const client = await MongoClient.connect('mongodb://localhost:27017/apm-test');
  const db = client.db();
  apm.startTransaction('test');
  const result = await db.listCollections().toArray();
  console.log(result);
  apm.endTransaction('end');
}

void test();
```

**Expected behavior**

APM spans of MongoDB should be logged.

**Environment (please complete the following information)**

- OS: macOS (11.3.1)
- Node.js version: v14.17.6
- APM Server version: 7.15.0
- Agent version: 3.24.0
- MongoDB: 4.2.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by trentm** [comment]
@abreu-gyant Thanks very much for the issue! I believe I will have a fix for both issues in https://github.com/elastic/apm-agent-nodejs/pull/2512
