### ISSUE TITLE
Look into removing EOL versions from the doc build

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-nodejs#2500]
Versions 2.x, 1.x, and 0.x are all end of life, yet still built to our documentation: https://www.elastic.co/guide/en/apm/agent/nodejs/index.html. This can cause problems around release time, for example, https://github.com/elastic/apm-agent-nodejs/pull/2499.

Let's look into either removing EOL versions from the doc build, or disabling link-checking in EOL versions (might not be possible).

**Comment by trentm** [comment]
@bmorelli25 I'm curious, what was done here, if anything?

**Comment by bmorelli25** [comment]
Nothing was done here. This is a won't/can't fix type of thing based on the following. Happy to discuss more.

* The doc build doesn't support selective link checking, so we can't disable link checking for EOL versions.
* The doc build _does_ allow us to remove branches from the build, but the number of internal links that need to be fixed to do this is not worth the effort.
* This problem should be mitigated now that the APM guide is where we'd like it to be. Better structure plus no Libbeat dependency means hardly any content restructuring/renaming in our current system. 
* This problem will be fixed by our new documentation system (by allowing us to stop link-checking older versions of the docs).

**Comment by trentm** [comment]
Thanks for the detailed answer.
