### ISSUE TITLE
MongoDB Profiling not working

### ISSUE THREAD

**Issue by kishoreacesurf** [elastic/apm-agent-nodejs#251]
### Expected behavior
MongoDB spans should be profiled
### Actual behavior
MongoDB spans are not showing up in logs
### Environment

- Operating system: 
- Node.js version: 
- APM Server version: 
- Agent version: 
- Agent start method:
  - [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
  - [ ] Requiring `elastic-apm-node/start` from within the source code
  - [ ] Starting node with `-r elastic-apm-node/start`
- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by watson** [comment]
@kishoreacesurf Thanks for opening the issue.

When you say "MongoDB spans are not showing up in logs", I expect you mean that you're not seeing them in Elasticsearch / Kibana, but that you are seeing the transactions correct?

A common issue that result in this is that you're requiring and starting the Node.js agent _after_ you have required your MongoDB module. It's important that the Node.js agent is the very first thing that is required and started. See our Troubleshooting guide for details: https://www.elastic.co/guide/en/apm/agent/nodejs/current/troubleshooting.html#missing-performance-metrics

**Comment by Qard** [comment]
This issue will be closed due to inactivity. If you feel it should be reopened, do not hesitate to comment on the issue.
