### ISSUE TITLE
mssql - support latest version of tedious

### ISSUE THREAD

**Issue by Tam2** [elastic/apm-agent-nodejs#2517]
**Describe the bug**

Currently Tedious is only supported up till version 9, Tedious is now at version 14, is it possible to to add support for up to version 14?

**Expected behavior**

Any version of tedious up till the latest should work

**Environment (please complete the following information)**

- OS: [e.g. Linux] Docker on Linux
- Node.js version: 16.13.1
- APM Server version: latest (cloud)
- Agent version: latest

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Did some investigation here - https://discuss.elastic.co/t/apm-missing-sql-span-nestjs-typeorm-sql-server/291221 

It seems like the request object has changed in the later versions, the sql statement is no longer available in `request.parametersByName` but is available in `request.sqlTextOrProcedure`

**Comment by trentm** [comment]
@Tam2  Thanks very much for the issue, especially for the investigation! Sorry for the delay in responding.

Some additional notes on adjustments that may be necessary for some of the major revs:
- From a quick look v13 and v14 likely will not break out instrumentation.
- 12.0.0 new min node is 12.x: https://github.com/tediousjs/tedious/releases/tag/v12.0.0
- 11.0.0 new min node is 10.x: https://github.com/tediousjs/tedious/releases/tag/v11.0.0
- 10.0.0 makes some changes to Connection.connect that might impact our instrumentation: https://github.com/tediousjs/tedious/releases/tag/v10.0.0
