### ISSUE TITLE
Override sampled state from traceparent header

### ISSUE THREAD

**Issue by spalger** [elastic/apm-agent-nodejs#2554]
**Is your feature request related to a problem? Please describe.**
I'm running a service using Google Cloud Run. Distributed tracing is a feature of cloud run if you use their tooling, and they automatically set a `traceparent` header for each request that comes into the service with a 0.1 trace sampling rate applied. APM sees this traceparent header and ignores the `transactionSampleRate` config I have provided and only samples transactions that Google Cloud Run deems "sampled". I'd really like to be able to control this behavior so that I can store APM transactions regardless of what Google Cloud Run deems noteworthy.

**Describe the solution you'd like**
I'd like a way to override the "sample" state that come from the `traceparent` header.

**Describe alternatives you've considered**
Wrapping the `server.emit()` method to delete the traceparent header before APM gets a chance to read it, requesting that Google Cloud Run allow customizing of the sample rate (which their docs explicitly state is not configurable)

**Comment by astorm** [comment]
great work tracking this one down @spalger, and thanks for reporting.  

Possibly of interest -- this isn't the first time a vendor's header has stomped on what we want to do -- if you're interested there's further reading [over here](https://github.com/elastic/apm/issues/286)

**Comment by trentm** [comment]
@spalger FYI: https://github.com/elastic/apm-agent-nodejs/pull/2555#issuecomment-1027208321
