### ISSUE TITLE
Memory leak in v3.28.0

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/apm-agent-nodejs#2569]
**Describe the bug**

High memory usage in v3.28.0, up to a point where the Node processes become unresponsive. Restarting reproduces.  
I just reverted to v3.27.0 and will observe charts for a few hours. I'll report here

In the screenshot below (from Kibana APM app itself), elastic-apm-node upgrade was merged on Feb. 9th at 3am (Paris time).This process is automatic. The app was restarted the same day at around 1pm

![screenshot-kibana-01 storcloud org-2022 02 10-09_24_27](https://user-images.githubusercontent.com/5468291/153368468-6c81dcd2-53a3-4fa2-bfae-43dd4398e2d1.png)

**To Reproduce**

Steps to reproduce the behavior: 
1. Upgrade a running application using elastic-apm-node v3.27.0 to v3.28.0

**Expected behavior**

Nothing special, APM keeps on collecting data as usual.

**Environment (please complete the following information)**

- OS: Ubuntu 18.04
- Node.js version: 16.13.0
- APM Server version: 7.13.3
- Agent version: 3.28.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options
*No options, we use all defaults*
- `package.json` dependencies:

 ```
    "@aws-sdk/client-s3": "3.50.0",
    "@elastic/ecs-winston-format": "1.3.1",
    "@elastic/elasticsearch": "7.17.0",
    "@fortawesome/fontawesome-free": "6.0.0",
    "angular": "1.8.2",
    "angular-animate": "1.8.2",
    "angular-aria": "1.8.2",
    "angular-chart.js": "1.1.1",
    "angular-file-saver": "1.1.3",
    "angular-i18n": "1.8.2",
    "angular-material": "1.2.4",
    "angular-material-data-table": "0.10.10",
    "angular-messages": "1.8.2",
    "angular-sanitize": "1.8.2",
    "angular-translate": "2.19.0",
    "angular-translate-loader-static-files": "2.19.0",
    "angular-ui-router": "1.0.30",
    "angulartics": "1.6.0",
    "angulartics-google-analytics": "0.5.0",
    "axios": "0.25.0",
    "basic-auth": "2.0.1",
    "body-parser": "1.19.1",
    "bull": "4.5.1",
    "bunyan-winston-adapter": "0.2.0",
    "chart.js": "2.9.4",
    "chartjs-plugin-annotation": "0.5.7",
    "chartjs-plugin-datalabels": "1.0.0",
    "cheerio": "1.0.0-rc.10",
    "cls-hooked": "4.2.2",
    "connect-flash": "0.1.1",
    "connect-multiparty": "2.2.0",
    "connect-redis": "6.1.1",
    "d3plus": "1.9.8",
    "dpkg-compare-versions": "1.0.1",
    "elastic-apm-node": "3.28.0",
    "email-templates": "8.0.8",
    "express": "4.17.2",
    "express-session": "1.17.2",
    "file-saver": "2.0.5",
    "form-data": "4.0.0",
    "google-palette": "1.1.0",
    "he": "1.2.0",
    "i18n-2": "0.7.3",
    "ioredis": "4.28.5",
    "jquery": "3.6.0",
    "js-yaml": "4.1.0",
    "jsonwebtoken": "8.5.1",
    "jstransformer-less": "2.3.0",
    "less": "4.1.2",
    "lodash": "4.17.21",
    "marked": "4.0.12",
    "method-override": "3.0.0",
    "mjml": "4.12.0",
    "moment": "2.29.1",
    "moment-duration-format": "2.3.2",
    "moment-timezone": "0.5.34",
    "mysql2": "2.3.3",
    "ng-file-upload": "12.2.13",
    "node-jose": "2.1.0",
    "node-stream-zip": "1.15.0",
    "nodemailer-stub": "1.2.2",
    "oidc-provider": "7.10.6",
    "openid-client": "5.1.3",
    "otplib": "12.0.1",
    "passport": "0.5.2",
    "passport-http": "0.3.0",
    "passport-jwt": "4.0.0",
    "passport-local": "1.0.0",
    "pug": "3.0.2",
    "puppeteer-core": "5.2.1",
    "qrcode": "1.5.0",
    "sequelize": "6.16.1",
    "sequelize-temporal": "1.0.8",
    "sha512crypt-node": "1.0.1",
    "svg-captcha": "1.4.0",
    "swagger-ui-express": "4.3.0",
    "tempy": "1.0.1",
    "umzug": "3.0.0",
    "uuid": "8.3.2",
    "winston": "3.5.1",
    "xlsx": "0.18.0",
    "zabbix-promise": "2.0.2"
```

**Comment by ddolcimascolo** [comment]
Side note, I see in the diff between 3.27.0 and 3.28.0 that you supported exit spans for ES (very nice BTW :pray:). Dunno of that's related or not, but we do use extended `@elastic/elasticsearch` `Client` and `Transport` classes.

1. We extend `Client` to register some event handler for logging and plug-in our custom `Tansport`

```
class Client extends elasticsearch.Client {

  constructor() {
    super({
      Transport // Our custom Transport class
    });

    this.registerEventLoggers();
  }

  registerEventLoggers() {
    this.on('request', (err, result) => {
      const { connection: { url }, attempts, request: { id, params: { method, path, querystring, body } } } = result.meta;

      logger.debug('elasticsearch/%s >> (%d) %s %s%s?%s %s', id, attempts, method, url, path, querystring, body, { err });
    });

    this.on('response', (err, result) => {
      const { statusCode, body, meta: { request: { id } } } = result;

      logger.debug('elasticsearch/%s << %d %j', id, statusCode, body, { err });
    });

    this.on('sniff', (err, result) => {
      const { meta: { request: { id }, sniff: { reason, hosts } } } = result;

      logger.info('elasticsearch/%s << Sniffing (%s) returned %j', id, reason, hosts, { err });
    });
  }

}
```

2. We extend `Transport` to override `request(params, options, callback)` to put some request options automatically and also unwrap the response body from the result object. This is what the legacy client was doing and we kept that when we upgraded to `@elastic/elasticsearch` client. Fun fact: this is what the client [will do by default in v8](https://github.com/elastic/elasticsearch-js/pull/1572/files#diff-27c04b11a66accdd7eed3c317e37723f21182c9f9d31848471f2f766c0f380c0R225) :)

```
class Transport extends elasticsearch.Transport {

  request(params, options, callback) {
    /**
     * For search requests we append ?timeout=xxx as a query parameter
     * This allows to transparently use a global configuration setting for all requests
     */
    if (/_search$/.test(params.path)) {
      _.defaultsDeep(params, {
        querystring: {
          timeout: `${config.ES_REQUEST_TIMEOUT}ms`
        }
      });
    }

    const result = super.request(params, options, callback);

    if (!callback && !(options && options.asStream)) {
      return result.then(({ body }) => body); // Unwraps body from the returned result, to emulate what the old ES client does
    }

    return result;
  }

}
```

**Comment by ddolcimascolo** [comment]
After reverting the lib to v3.27.0

![screenshot-kibana-01 storcloud org-2022 02 10-11_33_20](https://user-images.githubusercontent.com/5468291/153389281-1827470b-0824-4f69-9ef0-a49fc8868b6c.png)

**Comment by trentm** [comment]
@ddolcimascolo Thanks for reporting! Ugh, sorry about this. Yes, the best guess is probably the changes in the `@elastic/elasticsearch` instrumentation in commit 10f533e878f8b04781ab407a0ba9dc04909861a3 (#2557). The immediately preceding change is commit cff14650b3a5af12add139bc401fb2461a9b341d. 

1. I don't know how easy or disruptive it is for you to try, but a potentially interesting experiment would be to try with that preceding commit, but having this in your package.json:

```
  "elastic-apm-node": "elastic/apm-agent-nodejs#cff14650b3a5af12add139bc401fb2461a9b341d"
```

If that does *not* show the leak, then that almost certainly narrows it down to commit 10f533e8.

2. Getting a heap snapshot of the process with agent v3.28.0 when it is has leaked a lot of memory would help.

The way I've done this in the past is to add this signal handler to my node.js app:

```js
const path = require('path')
const fs = require('fs')
const v8 = require('v8')
console.warn(`"node ${path.basename(process.argv[1])}" is running as PID ${process.pid}: use 'kill -SIGUSR2 ${process.pid}' to create a heapsnapshot` )
process.on('SIGUSR2', function () {
  var stamp = new Date().toISOString().replace(/:/g, '-').split('.')[0]
  v8.getHeapSnapshot()
    .pipe(fs.createWriteStream(`leak-${stamp}.heapsnapshot`))
    .on('close', function () {
      console.warn(`Created leak-${stamp}.heapsnapshot`)
    })
})
```

- Then when the memory usage is high in the process, call `kill -SIGUSR2 PID` to tell it to generate the heap snapshot. Note that this'll pause the process while it makes that dump.
- The open Chrome, Developer Tools, "Memory" tab, "Load" to open the .heapsnapshot file.
- Generally I sort by "Retained Size" and then start clicking around to try to get context.

This will contain internal details about your app, so I understand if you cannot share the file. Or you could share it with me privately and I'd delete it after looking.


I'll get trying to reproduce this shortly.

**Comment by trentm** [comment]
@ddolcimascolo You can skip getting a heap dump. I understand the issue. I am just working through testing now.  I am embarrassed at my mistake that caused this.  Thanks for all the details!

**Comment by trentm** [comment]
elastic-apm-node@3.29.0 has been published with what I understand to be a fix for this.

**Comment by ddolcimascolo** [comment]
@trentm I can confirm that v3.29.0 fixes it. Thx again
