### ISSUE TITLE
Lambda: Layer ARN for Deploying an Agent

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2574]
If users want to use Elastic's AWS Lambda Extension with the Node.js Agent, they're currently required to manually include the agent source along side their application/service source and `require` it in their handler function.

We should build a Lambda Layer that includes an agent build and uses [a wrapper script](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html) to ensure the agent's loaded via the `-r` option.

This will be a two stage process.  

First, we'll need to create a build script that will package a released agent into an AWS layer, publish it to a region, and produce an ARN.  After users configure their function with this ARN they will have access to the Node.js agent via their service _and_ a wrapper script will be in place to ensure that the agent's preloaded with the `-r` option.

Second, once this script it built, it will need to be included in our agent release process.  This may mean one additional manual step, or may mean jenkins automation.  At the end of this step we'll have the ability to publish this layer to _all_ regions and produce a table of ARNs that users may choose from.

**Comment by trentm** [comment]
- We should (maybe "must") ensure that the right thing happens if a user uses this layer *and* also ships the apm agent in their function layer and manually `require('elastic-apm-node')`s for manual instrumentation or just because that's what they had laying around.
- I think we should consider adding a package-lock.json or similar to get closer to repeatable builds. That is separate work and shouldn't block this issue, though.

**Comment by astorm** [comment]
> We should (maybe "must") ensure that the right thing happens if a user uses this layer and also ships the apm agent in their function layer and manually require('elastic-apm-node')s for manual instrumentation or just because that's what they had laying around.

Good to call this out.

The layer works because the Amazon Node.js Lambda Runtime automatically sets the `NODE_OPTIONS` env variable to something like this

```
"NODE_PATH": "/opt/nodejs/node14/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task",
```

So in the case of someone having added the agent to their deployed Lambda source _and_ having added the layer, Node.js will prefer the version of the agent that's been added to the deployed lambda source (`/var/runtime/node_modules` above) over the layer's source (`/opt/nodejs/node_modules` above)

Talking naively, the right thing to do here seems to be to honor the Lambda path settings. While this could definitely get weird if there's two sources that are different versions in place, it could be equally weird to change these path settings and alter the overall behavior of the runtime. WDYT?

**Comment by trentm** [comment]
> Node.js will prefer the version of the agent that's been added to the deployed lambda source (`/var/runtime/node_modules` above) over the layer's source (`/opt/nodejs/node_modules` above)

`/opt/nodejs/node_modules` is first in the `NODE_PATH` you showed above. Doesn't that mean it will "win"?

Either way, it sounds like this case (having two `elastic-apm-node`s installed) might "just work".

* * *

Another potential concern. Does our installation of `elastic-apm-node` and, in particular, **its dependencies** in `/opt/nodejs/node_modules` potential impact the behaviour of the user's application? For example, can the user's app accidentally get the *agent's* `pino` dep instead of their own when doing `require('pino')`?

**Comment by astorm** [comment]
> /opt/nodejs/node_modules is first in the NODE_PATH you showed above. Doesn't that mean it will "win"?

_nod_ looks like I flip flopped those.  I've corrected the text.

> Another potential concern. Does our installation of elastic-apm-node and, in particular, its dependencies in /opt/nodejs/node_modules potential impact the behaviour of the user's application? For example, can the user's app accidentally get the agent's pino dep instead of their own when doing require('pino')?

I didn't test this but it does look like that will be case.  It appears that any module code distributed via a layer will have this behavior.

**Comment by trentm** [comment]
> Does our installation of elastic-apm-node and, in particular, its dependencies in /opt/nodejs/node_modules potential impact the behaviour of the user's application?

There used to be an option to `npm install` to have it use the "global layout" so that the install tree would look like:

```
.../node_modules/
    elastic-apm-node/
        node_modules/
            <all of elastic-apm-node's deps here>
```

I think that would solve the issue.

**Comment by trentm** [comment]
From `npm install --help`:

```
       The --global-style argument will cause npm to install the package into your local
       node_modules folder with the same layout it uses with the global node_modules folder.
       Only your direct dependencies will show in node_modules and everything they depend on
       will be flattened in their node_modules folders. This obviously will eliminate some
       deduping.
```

Seems to work:

```
% npm --version
6.14.15
% node --version
v12.22.6

% npm install --global-style elastic-apm-node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN s@1.0.0 No description
npm WARN s@1.0.0 No repository field.

+ elastic-apm-node@3.29.0
added 157 packages from 112 contributors and audited 157 packages in 7.052s

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


% ls node_modules
elastic-apm-node
% du -sh node_modules
 15M	node_modules
% ls node_modules/elastic-apm-node/node_modules
@babel                          hosted-git-info                 path-exists
@elastic                        http-headers                    path-parse
@types                          inherits                        pino
after-all-results               internal-slot                   pino-std-serializers
ajv                             is-arrayish                     process-warning
ansi-styles                     is-bigint                       pseudomap
async-cache                     is-boolean-object               punycode
...
```

So perhaps we just need to change the build script at https://github.com/elastic/observability-robots/issues/1053 to use:

```
...
npm install --global-style https://github.com/elastic/apm-agent-nodejs#${BRANCH_OR_TAG}
...
```

**Comment by astorm** [comment]
Sounds like the work for this is done in https://github.com/elastic/observability-robots/issues/1053.  

The final test will be out next real agent release.

**Comment by trentm** [comment]
> The final test will be out next real agent release.

Nope. Doesn't work. See https://github.com/elastic/apm-agent-nodejs/pull/2607#issuecomment-1064554597 for discussion.

**Comment by v1v** [comment]
https://github.com/elastic/apm-agent-nodejs/pull/2169 disabled tags.

if you enable back then it should work, though maybe it might be worth to enable tags from the latest tag onwards with the right regex

**Comment by v1v** [comment]
https://github.com/elastic/apm-agent-nodejs/releases/tag/v3.30.0 has been generated automatically by [this build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/v3.30.0/1/pipeline)

<img width="2062" alt="image" src="https://user-images.githubusercontent.com/2871786/158244409-a580e52e-3c78-4593-84b0-ab94316042af.png">

**Comment by astorm** [comment]
Everything appears to be working here.  We'll leave this issue open until the 3.31 release.  If 3.31 publishes correctly we'll consider this done and close the issue out. (cc @AlexanderWert)

**Comment by astorm** [comment]
Tagging 3.31 resulted in layer ARNs being successfully published. https://github.com/elastic/apm-agent-nodejs/releases Closing this out as done. Hat tip to @v1v and our other robot mechanics for getting this one working.
