### ISSUE TITLE
[META 605] Add span links for message tracing

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-nodejs#2593]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F605)](https://github.com/elastic/apm/issues/605)

[![issue details](https://img.shields.io/endpoint?label=spec-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F606)](https://github.com/elastic/apm/issues/606)

Summary of spec changes:

- If your agent instruments any of Azure Service Bus, JMS, Kafka, RabbitMQ, SQS, or SNS, then instrumentation for receiving messages or batches of messages "SHOULD":
    - Create a transaction (with trace-context from message metadata, if any) for the handling of each message, if possible.
    - Otherwise, when creating the transaction or span for the message or batch of messages, look for trace-context in metadata for up to 1000 messages and create a span link for each.
- If your agent supports AWS Lambda instrumentation, then in addition to the creation of span links, this spec change has a number of changes to the context captured for SQS and SNS-triggered invocations. (The special-casing of a message batch with a single message has been dropped.)

**Comment by trentm** [comment]
Here is the spec diff for this work: https://github.com/elastic/apm/pull/616/files

**Comment by trentm** [comment]
1. ^^ is for SQS instrumentation.
2. The (non-Lambda) SNS instrumentation in this agent only instruments the `sns.publish()` call, so there is no handling of message reception spans on which we might add span links automatically.
3. That leaves the changes to the SNS and SQS triggered lambda instrumentation to be done.
