### ISSUE TITLE
[META 619] Change default behavior for span compression and dropping of spans

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#2619]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F619)](https://github.com/elastic/apm/issues/619)

Spec change: https://github.com/elastic/apm/pull/611

This includes:
- [ ] Change default value for `span_compression_enabled` to `true`
- [ ] Change default value for `span_compression_same_kind_max_duration` to `0ms`

**Comment by trentm** [comment]
I'm guessing this'll just happen as part of https://github.com/elastic/apm-agent-nodejs/issues/2100

**Comment by trentm** [comment]
Added to the 8.3 milestone because I think Alan's impl of span compression in 8.3 will just do this automatically... because the Node.js APM agent impl came after this spec change.

**Comment by trentm** [comment]
Done in #2656 and #2623
(/cc @astorm)
