### ISSUE TITLE
Kubernetes attachment

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-nodejs#2622]
- [x] Publish a docker image that contains the agent distribution, similar to what the Java agent is already doing (see [build](https://github.com/elastic/apm-agent-java/blob/3187b4fbbf349041f95080e49b194848b1c33098/.ci/release/Jenkinsfile#L245-L257) and the [observability/apm-agent-java](https://container-library.elastic.co/r/observability/apm-agent-java) image in our Docker registry)
- [x] Integrate with the webhook in APM Server (https://github.com/elastic/apm-server/issues/7386) to copy the agent from the image to a volume via an init container and add environment variables to attach the agent.

**Comment by AlexanderWert** [comment]
Note: This can also be reused to support Elastic APM with [container-based AWS Lambda functions](https://github.com/elastic/apm-aws-lambda/issues/107).

**Comment by trentm** [comment]
For comparison, my (very naive) read of the "OTel Operator" is that it sets (or appends to) `NODE_OPTIONS=" --require /otel-auto-instrumentation/autoinstrumentation.js"`
https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/instrumentation/nodejs.go#L24-L27

**Comment by astorm** [comment]
Request made to productivity team for a published Dockerfile: https://github.com/elastic/observability-robots/issues/1229

I'm proceeding to making the adjustments to the mutating webhook to enable attachment.

**Comment by trentm** [comment]
see https://github.com/elastic/apm-agent-nodejs/pull/2742

**Comment by astorm** [comment]
Completed the minor changes needed to the mutating webhook, see https://github.com/elastic/apm-mutating-webhook/pull/31.  @trentm per last week's planning I decided to go absolute `NODE_OPTIONS` path and left out `NODE_PATH` for now.

**Comment by astorm** [comment]
Final task to finish this will be fore the Node.js Docker image to be listed as a _public_ docker image.  Right now it appears to require some sort of elastic auth to fetch. See: https://github.com/elastic/sre/issues/194

**Comment by trentm** [comment]
@astorm This can be closed now, right?
