### ISSUE TITLE
automate releases

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2625]
Work with the robots team to get automated releases.

The current release process is documented here: https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#releasing

#2585 added a "Release" stage for publishing Lambda Layers when a tag is pushed. 

- Is the release flow for the other agents based on a developer making/pushing a release tag? If not, what triggers an automatic release process?

**Comment by trentm** [comment]
This failed in `npm publish ...`:  /cc @pazone 

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/v3.33.0/1/pipeline

```
[2022-05-05T19:48:42.798Z] npm notice 
[2022-05-05T19:48:43.200Z] npm ERR! code E403
[2022-05-05T19:48:43.200Z] npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/elastic-apm-node - You do not have permission to publish "elastic-apm-node". Are you logged in as the correct user?
[2022-05-05T19:48:43.200Z] npm ERR! 403 In most cases, you or one of your dependencies are requesting
[2022-05-05T19:48:43.200Z] npm ERR! 403 a package version that is forbidden by your security policy.
```

**Comment by trentm** [comment]
I'm guessing this is because `elasticmachine` is not on the npm owner list (`npm owner ls elastic-apm-node`) for this package.

I'm curious if the jenkins tag build (https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/view/tags/job/v3.33.0/) can be safely re-run. Ideally each of the steps in the "Release" stage are idempotent.

**Comment by trentm** [comment]
I've added:

```
% npm owner add elasticmachine elastic-apm-node
...
npm notice INFO: User elasticmachine invited to package elastic-apm-node successfully.
+ elasticmachine (elastic-apm-node)
```

I'm not sure if someone needs to login to npm as elasticmachine an accept that invication.  @elastic/observablt-robots do you know?

**Comment by trentm** [comment]
(I've manually finished the 3.33.0 release, so re-running that particular job as a test won't be useful now.)

**Comment by v1v** [comment]
> I'm not sure if someone needs to login to npm as elasticmachine an accept that invitation. https://github.com/orgs/elastic/teams/observablt-robots do you know?

We tried the other day to invite the same user to one of our playground packages but unfortunately we were not able to do it as we didn't have access to the login anymore. So we might need to poke some people and see what's needed.

cc @pazone

**Comment by trentm** [comment]
>  is there a reason why this package lives out of elastic project in npm registry?

Historical. This package existed before `@elastic/` did -- and before npm supported namespaces.

**Comment by trentm** [comment]
# release v3.34.0

https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/view/tags/job/v3.34.0/

This is getting farther.

- There was a [hiccup](https://github.com/elastic/apm-agent-nodejs/pull/2724) with the "Dist" step that builds the Lambda layer, fixed now.
- The npm publish worked:

```
% npm info elastic-apm-node
elastic-apm-node@3.34.0 | BSD-2-Clause | deps: 32 | versions: 121
...
published 34 seconds ago by elasticmachine <infra-root+npm@elastic.co>
```

- The "Opbeans" step failed (I'm looking now).

**Comment by trentm** [comment]
A guess from earlier of a possible failure mode was:

> One possible failure will be if the `npm install ...` that the "Opbeans" stage does fails if the `npm publish` just before that needs some time on the npm server-side to update npm caches. We shall see.

and indeed the Opbeans stage of the release pipeline failed on what is probably this:

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/v3.34.0/2/pipeline

```
[2022-05-25T21:23:57.820Z] + CI=true npm install --ignore-scripts elastic-apm-node@3.34.0
[2022-05-25T21:23:59.440Z] npm ERR! code ETARGET
[2022-05-25T21:23:59.440Z] npm ERR! notarget No matching version found for elastic-apm-node@3.34.0.
[2022-05-25T21:23:59.440Z] npm ERR! notarget In most cases you or one of your dependencies are requesting
[2022-05-25T21:23:59.440Z] npm ERR! notarget a package version that doesn't exist.
```

### Options

1. Do the 'npm publish' step earlier in the pipeline and *hope* that the lambda layer publishing steps take enough time that the Opbeans stage will work then.
2. Add a spin loop at the start of the Opbeans stage process to retry the `npm install` if it gets an ETARGET with a timeout to account for being run soon after a publish.
3. Decouple the Opbeans stage from the APM agent release process. This was discussed as "an alternative" on https://github.com/elastic/opbeans-node/pull/148 recently.

I'm disinclined to (1) because "hope is not a strategy". In this case the strategy is a reliable release process. Releases are relatively infrequent, so if the process is flakey it is harder to fix.

Theoretically (2) would be straightforward to implement, but what should that timeout be? Granted the issue is old (from 2018) but user reports from https://github.com/npm/npm/issues/20574 suggest that the time for all npm servers to update could be an *hour* or more. That's too long to have as a timeout in a release process.

My preference would be to reconsider option (3). In https://github.com/elastic/opbeans-node/pull/148 the latest was:

> While decoupling the "agent release"-process and "opbeans update to latest agent and release"-process would be a good thing. That is too much work for now.

**Comment by trentm** [comment]
> My preference would be to reconsider option (3).

However, as was mentioned on https://github.com/elastic/opbeans-node/pull/148#issue-1183853607, I don't know of a way to have a dependabot-based process for updating opbeans-node to the latest elastic-apm-node **and ensure that a new git tag is created on opbeans-node.git**.

At the time @v1v suggested perhaps we could discuss the need for the tagging with the APM agents team: https://github.com/elastic/opbeans-node/pull/148#issuecomment-1085831183

Perhaps it is time to do that.

@v1v or other @elastic/observablt-robots, I'd welcome your input on the "Options" above to make the elastic-apm-node release pipeline reliable.

**Comment by trentm** [comment]
I've moved the remaining issue with the "Opbeans" stage to a separate issue to be clearer: https://github.com/elastic/apm-agent-nodejs/issues/2728
