### ISSUE TITLE
ELASTIC_APM_SERVICE_NAME env var for Node Lambda not working

### ISSUE THREAD

**Issue by RyanHealey1307** [elastic/apm-agent-nodejs#2628]
We have a test NodeJs lambda function using the following layers:
elastic-apm-extension-ver-0-0-4-x86_64 layer

I have set `ELASTIC_APM_SERVICE_NAME` environment variable to 'node-apm-enabled'.

However, within Elastic under APM we are seeing the original function name (as it is within AWS - we want change the service name in Elastic to remove the environment prefix by setting `ELASTIC_APM_SERVICE_NAME`), so we would expect the name of the service and service.name within the metadata of the transaction in APM to reflect the value set by the environment variable.

It is showing under APM as 'test1-node-apm-enabled' for the Service Name and for service.name in the transaction metadata.
So it still includes the environment prefix. As we have added `ELASTIC_APM_SERVICE_NAME` to the environment variables to change the service name, I would expect the name and service.name metadata to be updated to the new value.

Could you please advise how we would go about changing the service name to achieve our desired outcome?

Thanks

**Comment by AlexanderWert** [comment]
Same as https://github.com/elastic/apm-agent-java/issues/2557#issuecomment-1081731553:

This has been solved in Node.js agent agent versions >= 3.30.0.

Also feel free to try the Lambda layer deployment of the Node.js Agent with the `NODE_OPTIONS=-r elastic-apm-node/start.js` environment variable as [described in the docs](https://www.elastic.co/guide/en/apm/agent/nodejs/current/lambda.html)

**Comment by RyanHealey1307** [comment]
Ahhh my bad. Thank you!
