### ISSUE TITLE
[QUESTION] Can Write apm data to file?

### ISSUE THREAD

**Issue by exejutable** [elastic/apm-agent-nodejs#2633]
I read the documentation of apm agent in the elk page and i have a doubt/question

Is possible to collect the telemetry in json log files and  send it using `elastic-agent` to apm?

thanks, for the amazing package!

**Comment by trentm** [comment]
@exejutable Hi! I'm not exactly sure what you are asking. By `elastic-agent` are you referring to the (relatively new) "Elastic Agent" described at https://www.elastic.co/guide/en/fleet/current/fleet-overview.html ? The Elastic Agent is the new system by which Elastic users can deploy and manage our many integrations (like filebeat, metricbeat, etc.) and the APM *Server*.

Currently we are looking into adding support for the Elastic Agent to be able to automatically deploy *APM Agents* in cases where that is possible (e.g. in Kubernetes, and for APM agents which support instrumentation without changing user code, e.g. the Java and Node.js APM agents). However, that isn't current feature.

> Is possible to collect the telemetry in json log files and send it using elastic-agent to apm?

If I understand you correctly, I think the answer is: no, currently to collect *APM* data requires and APM Agent and those are not currently deployed via Elastic Agent.

**Comment by trentm** [comment]
Feel free to re-open this if you have follow-up questions or if I misunderstood you.
