### ISSUE TITLE
Cannot read property 'isStarted' of undefined

### ISSUE THREAD

**Issue by evenSosaAkido** [elastic/apm-agent-nodejs#2640]
When running the service in build mode I get this error: 

```
/app/api/node_modules/elastic-apm-node/lib/agent.js:209
         if (this.isStarted()) {
                  ^
       TypeError: Cannot read property 'isStarted' of undefined
           at Agent.start (/app/api/node_modules/elastic-apm-node/lib/agent.js:209:12)
           at Object.5380 (/app/api/build/server.js:1:61214)
           at r (/app/api/build/server.js:1:104471)
           at Object.6752 (/app/api/build/server.js:1:2007)
           at r (/app/api/build/server.js:1:104471)
           at Object.7728 (/app/api/build/server.js:1:72882)
           at r (/app/api/build/server.js:1:104471)
           at /app/api/build/server.js:1:104511
           at Object.<anonymous> (/app/api/build/server.js:1:104536)
           at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**To Reproduce**

1. Installed as "elastic-apm-node": "^3.13.0"
2. configured as 
```
import { start } from 'elastic-apm-node';
import { Agent } from 'elastic-apm-node/lib/agent';

const apm: Agent = start({
  // Run only if the server is specified on the env config.
  serverUrl: {my url},
  serviceName: {my app name},
});
```
4. run yarn build then yarn start
5. See error

**Expected behavior**

Yarn start should start without any errors

**Environment (please complete the following information)**

- OS: Mac OSX and node:12-alpine
- Node.js version: 12.14
- APM Server version: ^3.13.0

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [x ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by astorm** [comment]
Hey @evenSosaAkido, good to meet you.  I think I see the issue.  

We have a very specific way to start the agent with typescript.  You can [read about it here](https://www.elastic.co/guide/en/apm/agent/nodejs/current/es-modules.html), but specifically

1. You'll want to import the agent's special `start` module
2. You'll want to configure the agent using its environment variables instead of calling start directly
3. You'll want to invoke your node program with a `-r` flag that looks like this `-r elastic-apm-node/start`

Doing all this ensures that the agent both starts and is the first thing loaded in the compiled node source that you're actually running.  

In your code it looks like you're importing the `Agent`'s `start` method as a stand alone function.  This won't work -- `start` is intended to be used as a method on an instantiated agent object, not as a stand alone function.

Does the above information get you headed in the right direction? If there's a reason you can't use the above please let us know.

**Comment by evenSosaAkido** [comment]
@astorm first of all thanks for your quick response. I did your point number 1. and now it's working. Although I understand what you are saying I'm not sure I understand how it was working before. I had the same config for over a year and it just started failing today without changing libraries or any part near that code.

If you have an explanation would be great. But if not thanks a lot for your help anyways.

**Comment by astorm** [comment]
> I had the same config for over a year and it just started failing today without changing libraries or any part near that code. If you have an explanation would be great. But if not thanks a lot for your help anyways.

That's a good question @evenSosaAkido and, unfortunately, I don't have a great answer for it.  _Something_ had to have changed and the code, as written and compiled with stock typescript, just can't work.  

Do you happen to know where the  `const apm: Agent = start({...` code block came from?  The only thing I can think of is there was a typescript plugin, or something else in your compiler/builder tool-chain that fixed this but is hone now, but that's just speculating without enough evidence.

**Comment by astorm** [comment]
@evenSosaAkido I think I see what's going on here.  I'm guessing you, someone else, or some robot, has upgraded your TypeScript compiler to a version that's 4.4 or greater.  

Prior to this version, TypeScript would have compiled your source into something that looked like this

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const elastic_apm_node_1 = require("elastic-apm-node");
const apm = elastic_apm_node_1.start({
// Run only if the server is specified on the env config.
});
```

This calls `start` directly on the object returned by `require("elastic-apm-node");`, which is how it's intended to be used.  So this worked, although TypeScript wasn't honoring the letter of the law when it came to the code it generated. 

However, in more recent versions the TypeScript compiler will produce code that looks like this.

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const elastic_apm_node_1 = require("elastic-apm-node");
const apm = (0, elastic_apm_node_1.start)({
// Run only if the server is specified on the env config.
});
```

That is, the code ensures that the indirect import of the `start` function is honored by calling it like this

```
(0, elastic_apm_node_1.start)(...)
```

You can read more about this in the TypeScript release notes here: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#breaking-changes -- specifically the section named _More-Compliant Indirect Calls for Imported Functions_

We hope that helps -- and if you happen to know of other people using this code please let them know about the TypeScript changes!

**Comment by evenSosaAkido** [comment]
@astorm that actually makes a lot of sense thanks for digging into it

**Comment by akshaydhawle** [comment]
simply do the below steps  

code - 
import apm from 'elastic-apm-node';

if (!apm.isStarted()){

   apm.start({
        serviceName,
        secretToken,
        serverUrl,
       active,
   });
}

**Comment by loucadufault** [comment]
> In your code it looks like you're importing the Agent's start method as a stand alone function. This won't work -- start is intended to be used as a method on an instantiated agent object, not as a stand alone function.

Can we add this to https://www.elastic.co/guide/en/apm/agent/nodejs/current/starting-the-agent.html#start-gotchas ?
