### ISSUE TITLE
[META 634] a compression-eligible span must not be buffered on an already ended parent

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#2655]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/634

**Comment by trentm** [comment]
This one was already done in the in-progress span-compression work for the Node.js APM agent: https://github.com/elastic/apm-agent-nodejs/pull/2623/files#diff-04c91e574ac5eedc11a2f73394e4b7a3b13d3bc59d64b74ed2dd861d5f815599R361
