### ISSUE TITLE
Not supported by v18.0 of Node

### ISSUE THREAD

**Issue by Crawk95** [elastic/apm-agent-nodejs#2662]
elastic-apm-node - is not supported last version of node v18.0

**Comment by trentm** [comment]
@Crawk95  Thanks. We just recently updated "engines" in package.json on our main branch to support Node v18 (https://github.com/elastic/apm-agent-nodejs/pull/2652). We'll have a release out with that soon.

**Comment by trentm** [comment]
FYI: https://github.com/elastic/apm-agent-nodejs/pull/2663 is our PR for doing a new release.
