### ISSUE TITLE
Disconnected HTTP2 sessions cause a crash when reporting transactions

### ISSUE THREAD

**Issue by chinthakagodawita** [elastic/apm-agent-nodejs#2670]
**Describe the bug**

We're using the agent to instrument grpc calls. Since `@grpc/grpc-js` uses the internal Node HTTP/2 server, it's able to auto-instrument all incoming requests, we've added additional instrumentation information ourselves.

We've found that very intermittently, some requests are causing process crashes. We've had to disable APM as a result.

Error thrown:
```
Error [ERR_HTTP2_SOCKET_UNBOUND]: The socket has been disconnected from the Http2Session
    at new NodeError (node:internal/errors:371:5)
    at Object.get (node:internal/http2/core:867:17)
    at Object.getContextFromRequest (/opt/app/node_modules/elastic-apm-node/lib/parsers.js:24:32)
    at Transaction.toJSON (/opt/app/node_modules/elastic-apm-node/lib/instrumentation/transaction.js:206:41)
    at Transaction._encode (/opt/app/node_modules/elastic-apm-node/lib/instrumentation/transaction.js:237:15)
    at Instrumentation.addEndedTransaction (/opt/app/node_modules/elastic-apm-node/lib/instrumentation/index.js:315:63)
    at Transaction.end (/opt/app/node_modules/elastic-apm-node/lib/instrumentation/transaction.js:288:32)
    at ServerHttp2Stream.<anonymous> (/opt/app/node_modules/elastic-apm-node/lib/instrumentation/modules/http2.js:80:17)
    at ServerHttp2Stream.f (/opt/app/node_modules/once/once.js:25:25)
    at ServerHttp2Stream.onend (/opt/app/node_modules/end-of-stream/index.js:36:27)
    at /opt/app/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
    at AsyncHooksRunContextManager.with (/opt/app/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:49:17)
    at ServerHttp2Stream.wrapper (/opt/app/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
    at ServerHttp2Stream.emit (node:events:538:35)
    at ServerHttp2Stream.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I think a possible resolution here would be to surround this code in a `try/catch`: https://github.com/elastic/apm-agent-nodejs/blob/2f503a4011b63b4253bcfff8d9bb106c15c81c18/lib/parsers.js#L24-L28

**To Reproduce**
This is difficult to reproduce, I'd assume you could do something like the following:
- Start a HTTP/2 server
- Send a request and close the connection before you completely receive a response

**Expected behavior**

The APM agent should not throw an exception.

**Environment (please complete the following information)**

- OS: Linux (Debian)
- Node.js version: 16.14.2
- APM Server version: 7.17.0
- Agent version: 3.31.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] ~Requiring `elastic-apm-node/start` from within the source code~
- [ ] ~Starting node with `-r elastic-apm-node/start`~

**Additional context**

- Agent config options
  <details>
    <summary>Click to expand</summary>

    ```js
        const apmAgent = apm.start({
            active: apmEnabled,
            secretToken,
            serverUrl: config.elasticApm.serverUrl,
            environment: config.elasticApm.environment,
            serviceName: '[REDACTED]',
            transactionSampleRate: 0.2,
            serviceVersion: '[REDACTED]',
            /** Ignore metrics & health transactions */
            transactionIgnoreUrls: '[REDACTED]',
            /** Use the Kubernetes pod name as the node name, if available */
            serviceNodeName: process.env.KUBERNETES_POD_NAME,
            logLevel: 'off',
        });
    ```
  </details>
- `package.json` dependencies
  <details>
    <summary>Click to expand</summary>
	Only includes relevant packages

    ```json
        "dependencies": {
            "@grpc/grpc-js": "1.6.3",
            "@grpc/proto-loader": "0.6.9",
            "@protobuf-ts/runtime": "2.4.0",
            "@protobuf-ts/runtime-rpc": "2.4.0",
            "elastic-apm-node": "3.31.0",
        },
    ```
  </details>

**Comment by trentm** [comment]
Thanks for the issue, especially for the hints on how to reproduce.

I am able to repro with the following:

### play-http2-insecure-server.js

This runs an HTTP/2 server ... that fatally calls `stream.session.destroy()` before it ends the stream.

```js
const apm = require('./').start({ // elastic-apm-node
  serviceName: 'play-http2-insecure-server',
  metricsInterval: '0s',
  apiRequestTime: '3s',
  captureExceptions: false
})

const http2 = require('http2')

const server = http2.createServer()
server.on('error', console.error)
server.on('stream', (stream, headers) => {
  console.log('on stream: headers=', headers)
  stream.respond({
    'content-type': 'text/html; charset=utf-8',
    ':status': 200
  })
  // If, for some reason, the Http2Session is destroyed before the stream
  // ends ... then the APM agent's `http2` instrumentation needs to be
  // careful not to use the `stream.session.socket` proxy
  // (https://nodejs.org/api/http2.html#http2sessionsocket) because it can
  // throw `ERR_HTTP2_SOCKET_UNBOUND`:
  // https://github.com/nodejs/node/blob/v16.14.2/lib/internal/http2/core.js#L865-L867
  stream.session.destroy()
  stream.end('<h1>Hello World</h1>')
})

server.listen(1234)
```

### play-http2-client.js

This makes a simple HTTP/2 request to the above server. (I'm using a node.js client here instead of curl or a browser, because in real life *insecure* HTTP/2 servers aren't allowed.)

```js
const http2 = require('http2')
const sess = http2.connect('http://localhost:1234')
const {
  HTTP2_HEADER_PATH,
  HTTP2_HEADER_STATUS
} = http2.constants

const req = sess.request({ [HTTP2_HEADER_PATH]: '/' })
req.on('response', (headers) => {
  console.log('response headers:', headers[HTTP2_HEADER_STATUS])
})
req.setEncoding('utf8')
req.on('data', (chunk) => {
  console.log('data chunk:', chunk)
})
req.on('end', () => {
  console.log('req end')
  sess.close()
})
```

### the repro

Run the server:

```
% NODE_DEBUG=http2 node play-http2-insecure-server.js
```

and make a request:

```
% node play-http2-client.js
response headers: 200
req end
```

The server output is:

```
HTTP2 87722: Http2Session server: received a connection
HTTP2 87722: Http2Session server: setting up session handle
HTTP2 87722: Http2Session server: sending settings
HTTP2 87722: Http2Session server: submitting settings
HTTP2 87722: Http2Session server: created
(node:87722) Warning: Setting the NODE_DEBUG environment variable to 'http2' can expose sensitive data (such as passwords, tokens and authentication headers) in the resulting log.
(Use `node --trace-warnings ...` to show where the warning was created)
HTTP2 87722: Http2Stream 1 [Http2Session server]: headers received
on stream: headers= [Object: null prototype] {
  ':scheme': 'http',
  ':authority': 'localhost:1234',
  ':method': 'GET',
  ':path': '/',
  [Symbol(nodejs.http2.sensitiveHeaders)]: []
}
HTTP2 87722: Http2Stream 1 [Http2Session server]: initiating response
HTTP2 87722: Http2Session server: destroying
HTTP2 87722: Http2Session server: start closing/destroying undefined
HTTP2 87722: Http2Stream 1 [Http2Session server]: destroying stream
HTTP2 87722: Http2Session server: finishSessionClose
XXX getContextFromRequest: start
node:internal/http2/core:867
          throw new ERR_HTTP2_SOCKET_UNBOUND();
          ^

Error [ERR_HTTP2_SOCKET_UNBOUND]: The socket has been disconnected from the Http2Session
    at new NodeError (node:internal/errors:371:5)
    at Object.get (node:internal/http2/core:867:17)
    at Object.getContextFromRequest (/Users/trentm/el/apm-agent-nodejs8/lib/parsers.js:25:32)
    at Transaction.toJSON (/Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/transaction.js:202:41)
    at Transaction._encode (/Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/transaction.js:233:15)
    at Instrumentation.addEndedTransaction (/Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/index.js:320:63)
    at Transaction.end (/Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/transaction.js:284:32)
    at ServerHttp2Stream.<anonymous> (/Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/modules/http2.js:80:17)
    at ServerHttp2Stream.f (/Users/trentm/el/apm-agent-nodejs8/node_modules/once/once.js:25:25)
    at ServerHttp2Stream.onfinish (/Users/trentm/el/apm-agent-nodejs8/node_modules/end-of-stream/index.js:31:27)
    at /Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
    at AsyncHooksRunContextManager.with (/Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/run-context/BasicRunContextManager.js:49:17)
    at ServerHttp2Stream.wrapper (/Users/trentm/el/apm-agent-nodejs8/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
    at ServerHttp2Stream.emit (node:events:526:28)
    at finish (node:internal/streams/writable:754:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP2_SOCKET_UNBOUND'
}
```

**Comment by chinthakagodawita** [comment]
Thanks for the speedy fix @trentm!

**Comment by trentm** [comment]
I hope to get a release out in a day or two... just waiting for one other change.

**Comment by chinthakagodawita** [comment]
I can confirm that `3.33.0` has fixed things for us ❤️

**Comment by curtdept** [comment]
@trentm still a bug in here somewhere

![image](https://user-images.githubusercontent.com/23644717/167169453-67cc8e93-31fb-4812-8344-8fce733da31b.png)

**Comment by trentm** [comment]
@curtdept  That line, `http2.js:238`,

https://github.com/elastic/apm-agent-nodejs/blob/v3.33.0/lib/instrumentation/modules/http2.js#L238

is where the APM agent's http2 instrumentation is (a) attempting to create a span for an *outgoing* `http2.request()` call, but (b) doesn't create a span because the `http2.request()` call is not in the context of an APM transaction. One that line the APM agent is just calling the unwrapped function after determining it isn't going to capture any APM data.

I don't *think* it indicates that the APM agent's instrumentation is causing the issue.  I don't know that without more details, though.  I don't know how to start trying to reproduce.

It is probably best to open a separate issue, if you are willing, because this is a separate part of the instrumentation: wrapping outgoing HTTP/2 requests, rather than the wrapping of incoming HTTP/2 server requests.

**Comment by trentm** [comment]
> I don't _think_ it indicates that the APM agent's instrumentation is causing the issue.

There *is* a small block just above that line
https://github.com/elastic/apm-agent-nodejs/blob/v3.33.0/lib/instrumentation/modules/http2.js#L230-L236
where the APM agent might be tweaking `arguments[0]` to that `http2.request()` call (the headers, to propagate trace-context on the 'traceparent' header, etc.). Conceivably that could be an issue caused by the APM agent. I don't think that would lead to a "The session has been destroyed"-type error, however.

**Comment by curtdept** [comment]
@trentm in terms of repro (sorry I know same ticket). Seemed easiest to with aws-sdk v3 kinesis client which they recently switched to http2. After almost exactly an hour, connects are no longer made and I only get this session destroyed error. For testing purposes I could rip out elastic apm and let it run for an hour.

**Comment by trentm** [comment]
> For testing/isolation purposes I could rip out elastic apm and let it run for an hour.

That would definitely be a welcome test.

**Comment by curtdept** [comment]
> > For testing/isolation purposes I could rip out elastic apm and let it run for an hour.
> 
> That would definitely be a welcome test.

Running it now :) Will report back

**Comment by curtdept** [comment]
@trentm ya not the APM, still occurring with apm installed, aws-sdk issue thanks for looking into tit

**Comment by trentm** [comment]
Thanks very much for reporting back.

> looking into it.

I saw that slip. ;)
