### ISSUE TITLE
Version 3.32.0 regression database statement

### ISSUE THREAD

**Issue by descampsk** [elastic/apm-agent-nodejs#2671]
**Describe the bug**

With the new version 3.32.0 I don't see the database statement in the Kibana APM dashboard

![image](https://user-images.githubusercontent.com/22590202/166450113-ab9ec80f-6fe8-4504-8b6d-102540313ec6.png)

It seems also that the span is doubled : 

![image](https://user-images.githubusercontent.com/22590202/166450165-5be5b0fd-faeb-4568-8b3e-b2ad8e92c528.png)

With 3.31.0 I have the statement 

![image](https://user-images.githubusercontent.com/22590202/166449999-a6a49740-7c3c-4d78-b836-9dbfb2acd0e6.png)

**To Reproduce**

Upgrade to 3.32.0

**Expected behavior**

I should see the database statement in the APM Panel

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 14.18
- APM Server version: 8.1.2
- Agent version: 3.32.0

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [x] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

**Comment by descampsk** [comment]
I will try it today and will let you know.

**Comment by descampsk** [comment]
Ok if I disable `spanCompressionEnabled` to false, the DB Query is there.

But I think it should not be to true per default because it deletes all db statement which are one of the most usefull information in the APM

**Comment by astorm** [comment]
@descampsk Glad to hear turning off the new span compression feature got you back up and running -- appologies for the surprise new default.   I'll definitely pass on your feedback regarding defaults for this feature.  

Also, for what its worth -- if your span [had exceeded the max duration value](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#span-compression-exact-match-max-duration) it wouldn't have been compressed.  In other words even with span compression on you _should_ still get the full span, with SQL statements, for database queries that are running long.  

Leaving this open until I have a chance to fully reproduce the behavior @descampsk describes -- the second span confuses me a little bit and I want to make sure we fully understand what's happening here before I close this.

**Comment by ddolcimascolo** [comment]
Hi @astorm

I just found my DB statements disappeared too 🤗
But I like compression, we have a few N+1 queries use cases and those are a lot nicer as a single compressed span in Kibana!

Can you confirm that even with compressed spans the DB query should be there on individual spans? Or is it something that you can't support and we should disable compression is we want statements?

Thx,
David

**Comment by astorm** [comment]
@ddolcimascolo @descampskGood news -- I spent some quality time with the specs and our implementation and the loss of the `span.db.statement` field appears to be a bug in our implementation and not something inherent to compressed spans.  I've opened an issue with more information here:

https://github.com/elastic/apm-agent-nodejs/issues/2715

Until we land a fix for #2715 the best path forward is disable span compression.  Once a fix for #2715 lands you should get those useful queries back, even when compression is enabled.

**Comment by trentm** [comment]
elastic-apm-node@3.34.0 has been released and includes a fix for https://github.com/elastic/apm-agent-nodejs/issues/2715

**Comment by ddolcimascolo** [comment]
Thx!
