### ISSUE TITLE
Allow setting of result when ending transaction

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#272]
A common pattern today when working with custom transactions are:

```js
var trans = agent.startTransaction('name', 'type')
doSomeWork(function (err) {
  if (err) trans.result = 'error'
  trans.end()
})
```

It might prove useful to be able to pass a result to the `end` function, eg:

```js
var trans = agent.startTransaction('name', 'type')
doSomeWork(function (err) {
  trans.end(err && 'error')
})
```

**Comment by watson** [comment]
@elastic/apm-agent-devs do any of the other APM agents allow something similar?

**Comment by mikker** [comment]
Yes,

```ruby
ElasticAPM.transaction 'Name' do
  # ...
end.submit(200) # <-- result
```

**Comment by beniwohli** [comment]
Passing the result to `end_transaction()` is the only way to set the result in the Python agent

https://www.elastic.co/guide/en/apm/agent/python/2.x/api.html#client-api-end-transaction

**Comment by axw** [comment]
Sorry, missed this (wasn't on the list yet).

Not at the moment for Go. The Transaction.Done method accepts an optional duration and nothing else; you must set the Result field before calling Done.

**Comment by felixbarny** [comment]
Same for the Java agent, the result has to be set before.

**Comment by watson** [comment]
@axw @felixbarny would it make sense to allow for setting the result in the call to "end" in the Go and Java agents, or is this just down to the differences between what's expected/normal in these languages?

**Comment by axw** [comment]
> @axw @felixbarny would it make sense to allow for setting the result in the call to "end" in the Go and Java agents, or is this just down to the differences between what's expected/normal in these languages?

Maybe, it depends on how the Go API evolves. At the moment, the model structure is exposed to the instrumented code, but I'm thinking I might change that, so the instrumentation API can evolve independently of the model and intake API.

The OpenTracing Go API allows you to pass in "options" when finishing a span: https://godoc.org/github.com/opentracing/opentracing-go#Span. We could do something similar. I'm not sure if that's better than just setting it before ending the transaction, though. There's no optional arguments in Go, so it's not really any less verbose. It's a choice between:

```go
tx.Result = "error"
tx.Done()
```

vs.

```go
tx.DoneWithOptions(elasticapm.TransactionDoneOptions{
    Result: "error",
})
```

or maybe

```go
tx.Done(elasticapm.TransactionResultOption("error"))
```

**Comment by felixbarny** [comment]
Interestingly, in Java OpenTracing, there is no options when finishing a span: https://github.com/opentracing/opentracing-java/blob/3e270abc6d07315ff71fe09886a9cbe93ea221f4/opentracing-api/src/main/java/io/opentracing/Span.java#L151

In Java, there are also no optional arguments. You can only have overloaded methods, i.e. same method names with different params.

The [public Java API for transaction](https://github.com/elastic/apm-agent-java/blob/72080da3e776f80d82b5576b879b6de3c5690c27/apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java) currently does not support for adding the result, however I should clearly add this. The public API does not expose the model structure. That makes is much simpler to keep it backwards compatible. However, that means you can not set all properties the intake API offers with the public Java APM API. To set things like `Span.context.db.statement` you need to use the internal API, which does not make backwards compatibility guarantees. 

@axw is that what you meant with 
> At the moment, the model structure is exposed to the instrumented code, but I'm thinking I might change that, so the instrumentation API can evolve independently of the model and intake API.

@watson 
What's the advantage of setting the result in end as opposed to setting it before calling end?

**Comment by watson** [comment]
> What's the advantage of setting the result in end as opposed to setting it before calling end?

It might not be a benefit to Java or Go, as languages are different. But in Node.js it is purely for esthetics of writing less lines of code. The end result is the same (no pun intended).

**Comment by axw** [comment]
> @axw is that what you meant with

Yes, pretty much. There's no "internal API" in the Go agent, but you can set the model fields directly, and I suppose that's roughly equivalent. For the most part, you don't need to interact with it.

**Comment by mikker** [comment]
Somewhat relevant: https://github.com/elastic/kibana/issues/18707
Special `result` keywords will get special colors in the TPM graphs
