### ISSUE TITLE
missing HTTP spans randomly

### ISSUE THREAD

**Issue by agarwalarjun123** [elastic/apm-agent-nodejs#2729]
There are some HTTP spans missing randomly part of transactions.  It is captured in some transactions but are lost in some. 

**Steps to reproduce the behavior:**
1. Use this config
require('elastic-apm-node').start({
  serviceName: _.get(config, 'LOGGER.APM_SERVICE_NAME'),
  serverUrl: _.get(config, 'LOGGER.APM_BASE_URI'),
  captureBody: 'all',
  captureHeaders: true,
  active: (config.APP.NODE_ENV !== 'development')
});

**Expected behavior**

The agent should push all transaction spans part of a transaction.

**Environment (please complete the following information)**

- OS: Linux
- Node.js version:  14.19.3
- APM Server version: 7.15.2
- Agent version: 3.9.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>
        "elastic-apm-node": "3.9.0"
  </details>

**Comment by trentm** [comment]
Hello @agarwalarjun123. Thanks for the issue.

elastic-apm-node version 3.9.0 is [a very old release from a year and a half ago](https://www.elastic.co/guide/en/apm/agent/nodejs/current/release-notes-3.x.html#release-notes-3.9.0). Are you able to update to a more recent release to see if that makes a difference. We'll be able to help you better if you are running a version that is relatively newer.

Can you provide more details on your application and what types of spans (or transactions?) are missing? Is it spans for outgoing HTTP requests that are missing? If so, what code or package are you using to make HTTP requests? The APM agent instruments some, but not all, HTTP request packages.

Are you able to post a small code example that demonstrates the problem you are seeing? If not, that is okay. If it appears random, then I can understand that a small reproduction case would be difficult.

A trace log of what the agent is doing might help us determine if there is some reason the APM agent is dropping spans. You can do this by adding `logLevel: 'trace'` to your `require('elastic-apm-node').start({ ... })` start options.
