### ISSUE TITLE
add support for fastify@4

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2737]
Currently fastify v4 has RC pre-releases. Our TAV tests and supported-technologies doc page say we support fastify `>=1`. We should change that to be specific about the major versions support, and we should test and update for fastify v4 as necessary.

**Comment by trentm** [comment]
fastify@4 drops support for node v12 and, I believe, node v10 in this major version as well.

fastify@3's ".github/workflows/ci.yml" tests with `node-version: [10, 12, 14, 16, 17]` so supported node 10. Our fastify tests also happen to work with fastify@3 and node@8.6, it just wasn't tested.

**Comment by trentm** [comment]
fastify@4 requires node >=14.6.0 -- because it uses pino@8 which uses on-exit-leak-free@1 which requires https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry which came in node 14.6.0.

**Comment by karliell** [comment]
I wrote as 
```
fastify.listen({ port: 3000 }, (err) => { if (err) throw err }, () => {
    console.log("running on port 3000");
});
```
Or, 
```
fastify.listen({ port: 3000 },  () => {
    console.log("running on port 3000");
});
```
However, I still get this error:
```
(node:25269) [FSTDEP011] FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.
```

**Comment by trentm** [comment]
@karliell 

When I run this:

```js
const fastify = require('fastify')
const app = fastify()
app.get('/ping', (req, reply) => {
    reply.send('pong')
})
app.listen({ port: 3000 }, (err) => { if (err) throw err }, () => {
    console.log("running on port 3000");
});
```

I see that FSTDEP011 warning:

```
(node:73658) [FSTDEP011] FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.
```

However, when I run this:

```js
const fastify = require('fastify')
const app = fastify()
app.get('/ping', (req, reply) => {
    reply.send('pong')
})
app.listen({port: 3000}, () => {
    console.log("running on port 3000");
});
```

I do not see that deprecation warning.  I get the same behaviour whether or not the `elastic-apm-node` APM agent is being used.

Do you see different behaviour?  I'm using fastify@4.9.2 and elastic-apm-node@3.40.1.
