### ISSUE TITLE
Performance investigation

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-agent-nodejs#2745]
Investigate the performance of the node agent when used with Kibana.

As part of this issue, we have to decide what use cases we'll look into and what results we are targeting.

**Comment by trentm** [comment]
We'll get a new release out next week with the #2786 change.

A brief (obviously limited) tl;dr of this investigation was that the largest perf impact from the APM agent on Kibana was from the async-hook. Using AsyncLocalStorage instead showed a significant improvement. 

Flamegraphs of Kibana using the new agent (with some load) did not show obvious *large* next targets for perf improvement: traceparent/tracestate/TraceContext processing and Span & Transaction constructors and .end() time stuck out a bit, but not that much. Note that these flamegraphs were when running in `contextPropagationOnly=true` mode. The next time we timebox some time for perf, it would be good to explore with and without that mode.
