### ISSUE TITLE
add support for redis@4

### ISSUE THREAD

**Issue by jsDotx3** [elastic/apm-agent-nodejs#2751]
Version 4 came out 6 months ago and allows to improve asynchronicity. Is it possible to have the trace of the calls?

**Comment by trentm** [comment]
@jsDotx3 Thanks for the issue. We definitely plan to support this but haven't yet had a chance. Requests for it (like your issue) help prioritize it.   I'm closing this, because we have an issue for it already: https://github.com/elastic/apm-agent-nodejs/issues/2477
