### ISSUE TITLE
parallel async spans using promise.all leading to transaction terminating early

### ISSUE THREAD

**Issue by agarwalarjun123** [elastic/apm-agent-nodejs#2752]
**Describe the bug**

parallel http/mongodb async spans using promise.all leading to transaction terminating before the remaining spans completed.

**Expected behavior**

Transaction should be completed after all the async promises get resolved.

**Environment**

- OS: [e.g. Linux]
- Node.js version: 14
- APM Server version: 7.17.3
- Agent version: 3.35.0

**How are you starting the agent?**

- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options
serviceName: _.get(config, 'LOGGER.APM_SERVICE_NAME'),
  serverUrl: _.get(config, 'LOGGER.APM_BASE_URI'),
  captureBody: 'all',
  captureHeaders: true,
  active: (config.APP.NODE_ENV !== 'development'),
  logLevel: 'trace',

**Comment by trentm** [comment]
Hi @agarwalarjun123. Sorry for the delay in responding.

To answer, I'll need to make sure I understand what your code is doing. Is this about an HTTP server request handler that is making multiple MongoDB requests in a `Promise.all(...)` call and then only responding when that Promise.all is complete?

Are you able to show a small code example (or show a part of your HTTP request handler code) that demonstrates the issue?

**Comment by agarwalarjun123** [comment]
thanks for the help! this issue is resolved.
