### ISSUE TITLE
`await`able `apm.flush()`

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2857]
To use `apm.flush(callback)` effectively in an async function one has to resort to promisify'ing it like this:

```js
const { promisify } = require('util')
await promisify(apm.flush.bind(apm))().then(function (err) {
  ...
})
```

It would be helpful if `apm.flush()` could return a Promise if no callback is given, then it could be `await`d directly.

**Comment by alainrk** [comment]
I've tried to address this, let me know if it could be enough or if there's something I'm missing 😄
