### ISSUE TITLE
Change order in which config options overrule each other for all agents

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#287]
Currently the Node.js agent can be configured using a combination of environment variables, a config file, and in-line config options.

Right now config options set in a config file will overrule the same config options set in-line. Likewise, config options set using environment variables will overrule the same config options set in a config file.

It would make sense to align this order across all backend Elastic APM agents (currently Python, Ruby, Go, and Java). I'm leaving out the frontend JavaScript agent as I think the methods of configuration here are restricted to only in-line configuration.

It has been proposed to change the order to the following (higher overrule lower):

1. Environment variables
1. In-line configuration
1. Config file
1. Default values

Reason being that it should be easy for people deploying the application to overrule config options set by the developer in either the config file or in-line. It might also be a use-case that a config file is shared among different apps, so it should be possible to overwrite config options in-line. That's at least our suggestion.

But we'd love input on if this aligns with real world use-cases or if we missed something obvious 😃 

P.S. Changing this order should of course be considered a breaking change, so for the Node.js agent we'll have to bump the major for this to be changed.

/cc @elastic/apm-agent-devs

**Comment by Qard** [comment]
Personally, I think it makes more sense as it is now. I can imagine an ops team being delivered an app bundle, of some sort, and wanting to deploy that with their own custom config and being confused when in-app configs override what they are trying to do.

**Comment by axw** [comment]
I don't know about the in-app config, but I do think environment variables should trump everything else.

I'm not sure under what circumstances you would use in-app configuration. Any examples you can point to?

**Comment by watson** [comment]
@axw it's much easier to get up and running with in-app config as there's no external dependencies. Not sure if that's only a benefit in an interpreted language like JavaScript, or if it applies to Go and Java as well.

**Comment by watson** [comment]
@Qard wrote:

> Personally, I think it makes more sense as it is now. I can imagine an ops team being delivered an app bundle, of some sort, and wanting to deploy that with their own custom config and being confused when in-app configs override what they are trying to do.

When you say "I think it makes more sense as it is now", do you mean the suggested order or as in how the Node.js agent currently handles it? Your comment about ops makes me think you're referring to the suggested order and not the current behavior

**Comment by watson** [comment]
cc @roncohen

**Comment by Qard** [comment]
I meant having a config file override in-app configs seems more intuitive from an ops perspective. I can see a case for the other way though, having a basic config file to build apps from which you would override in code and then ops can just stick to environment variables to override the in-app configs.

**Comment by watson** [comment]
I can see that I made a mistake in the issue description. In the listed order it shows that in-line overrides the config file, but right after I write the opposite.

As Stephen points out there's something to be said for both orders though. So I'm not really sure what the best cause of action is here?

**Comment by watson** [comment]
I think it's more obvious to a first time user that they can overwrite their config file with in app config options. As long as we give ops people at least one way to overwrite everything (which we would do with ENV's trumping everything), then I think we're ok.

So unless there's still concerns, I'd say this is ready to implement 😃

**Comment by watson** [comment]
When dropping Node 4 support, consider if it's worth it to set the minimum supported Node 6 version to v6.5.0 as that has 99% support for ES2015, as opposed to only 95% for <6.5.0. The we don't need extra 4% for anything, there's no need for it.
