### ISSUE TITLE
Some transaction API are not documented in documentation and typescript definition

### ISSUE THREAD

**Issue by Holi0317** [elastic/apm-agent-nodejs#2885]
**Is your feature request related to a problem? Please describe.**

I was trying to set the traceparent of an existing transaction. Searching through the official docs yields me nothing but looking through the code I found something interesting:

1. `Transaction` class inherits `GenericSpan` https://github.com/elastic/apm-agent-nodejs/blob/ee08f45ded9701c0e9b71dcffe31eb19509fd6d8/lib/instrumentation/transaction.js#L29
2. `GenericSpan` provides `setParentSpan` method https://github.com/elastic/apm-agent-nodejs/blob/ee08f45ded9701c0e9b71dcffe31eb19509fd6d8/lib/instrumentation/generic-span.js#L201

I also noticed that the library is prefixing private fields with `_`, and the method I mentioned sounds like public to me. However, this method (and a lot of public methods in the library) is not documented anywhere in the docs or in `.d.ts` files.

Is there any reason to exclude these methods in the documentations? And is it safe to use these methods?

**Describe the solution you'd like**

Include documentation on public methods in official docs and `.d.ts` file.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by astorm** [comment]
@Holi0317  nice to meet you and thanks for writing/reporting in. 

> Is there any reason to exclude these methods in the documentations? And is it safe to use these methods?

That's a great question.  Our official supported API methods and objects are the ones you can find in [our API Reference](https://www.elastic.co/guide/en/apm/agent/nodejs/current/api.html). These are the methods that are considered safe to use and where we make a good faith effort to honor SemVer conventions.

Re: other methods -- any method not listed in the API docs is considered an internal implementation detail regardless of the state of its leading underscores or not. Re: safety -- these are method where we reserve the right to change how they behave without honoring SemVer conventions, and using them may have unintended side effects on how your traces show up in the UI. 

If there's a problem you're trying to solve and there a method that seems like it should be a part of the public API the best path forward is to open a new issue, describe the use case and request a public API method for it.
