### ISSUE TITLE
Adding custom logger is not working

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#289]
### Expected behavior

When using the [`logger`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#logger) config option it should be possible to overwrite the default logger.

### Actual behavior

The `logger` config option just seems to be ignored (as pointed out in https://github.com/elastic/apm-agent-nodejs/issues/232#issuecomment-375087000)

### Steps to reproduce

1. `npm install pino`
1. Create a file just containing this:
    ```js
    require('elastic-apm-node').start({
      logger: require('pino')()
    })
    ```
1. The output in the console should be some like this:
    ```
    {"level":50,"time":1521726287091,"msg":"Elastic APM isn't correctly configured: Missing serviceName","pid":7540,"hostname":"watson.local","v":1}
    ```
    But because the custom `logger` isn't picked up, it's just:
    ```
    Elastic APM isn't correctly configured: Missing serviceName
    ```

**Comment by coolboi567** [comment]
Can this logger configuration be used to save all the debug/info logs into a separate file?

**Comment by watson** [comment]
@coolboi567 No, you need to supply a custom logger for that purpose. In the future, could you please ask questions in our [Discuss forum](https://discuss.elastic.co/c/apm) or open a new issue?

**Comment by coolboi567** [comment]
@watson Sure would do from now on. Sorry for this but I saw that forum was not that active, and it took days before anyone reponds, that's why I choose to ask question in related issues like these.

**Comment by watson** [comment]
@coolboi567 We respond just as fast here as in the forums. It was probably just because it was during the Christmas holiday 😃
