### ISSUE TITLE
suppport @koa/router

### ISSUE THREAD

**Issue by sibelius** [elastic/apm-agent-nodejs#2899]
**Is your feature request related to a problem? Please describe.**
@koa/router is the same as koa-router

**Describe the solution you'd like**
add @koa/router inside instrumentation similar to koa-router

**Describe alternatives you've considered**
manually setting setDefaultTransactionName

**Additional context**
koa-router moved to scoped npm package name @koa/router

**Comment by trentm** [comment]
@sibelius I don't think https://github.com/elastic/apm-agent-nodejs/pull/2900 should be necessary. The intent of this line in the agent: https://github.com/elastic/apm-agent-nodejs/blob/a19cac444a08b76f03f450c16cde08e4fa461c8f/lib/instrumentation/index.js#L55 is that both `require('koa-router')` and `require('@koa/router')` are instrumented by https://github.com/elastic/apm-agent-nodejs/blob/main/lib/instrumentation/modules/koa-router.js and we are testing that with https://github.com/elastic/apm-agent-nodejs/blob/main/test/instrumentation/modules/koa-router/new-name.test.js

Was instrumentation of `@koa/router` not working in your experience?

**Comment by trentm** [comment]
> Was instrumentation of `@koa/router` not working in your experience?

Note that the APM agent currently doesn't yet support v11 or v12 of either `koa-router` or `@koa-router`. We have https://github.com/elastic/apm-agent-nodejs/issues/2811 open for that, currently.

**Comment by sibelius** [comment]
we are using @koa/router@12.0.0

what is the best way to "instrument" manually @koa/router until the support lands?

**Comment by sibelius** [comment]
I'm gonna close this issue for now

**Comment by trentm** [comment]
> if I remove the semver check it should work?

That will turn on the agent's instrumentation, but unfortunately something has changed in koa-router@11 that breaks the transaction name discovery in our instrumentation (#2811 shows the test failures). I hope to get #2811 prioritized for our next release cycle, but practically speaking it will still be at least a number of weeks before we get to it.

If you know the koa-router code and are willing to dig a bit, finding specifics on relevant changes in koa-router@11 that breaks how https://github.com/elastic/apm-agent-nodejs/blob/main/lib/instrumentation/modules/koa-router.js#L21-L48 works would probably help.
