### ISSUE TITLE
addFilter example outdated

### ISSUE THREAD

**Issue by Thetortuga** [elastic/apm-agent-nodejs#290]
Hi,

I am trying to use the addFilter feature to filter out some request.
The example in the doc seems to be outdated:

```js
apm.addFilter(function (payload) {
  if (payload.context.request && payload.context.request.headers) {
    // redact sensitive data
    payload.context.request.headers['x-secret'] = '[REDACTED]'
  }
  // remember to return the modified payload
  return payload
})
```
Indeed, `payload.context` does not exist. Instead, we could make something like that :
```js
apm.addFilter(function (payload) {
  payload.transactions.map((transaction) => {
    if (transaction.type === 'request' &&  transaction.context.request.headers) {
      transaction.context.request.headers['x-secret'] = '[REDACTED]'
    }
  })
  return payload
})
```

**Comment by watson** [comment]
Hi @Thetortuga 

Thanks for reporting this error. I think the best cause of action is to call the filter function once per transaction as the documentation describes. I haven't checked why/when this broke, but it's definitely the expected action.

I'll make sure this gets fixed ASAP.

**Comment by watson** [comment]
After discussing this with the team we dicided it would be a breaking change to fix the filter function to match the documentation (as people might already be relying on the broken behavior). Instead I've made a PR to change to docs to reflect the current behavior: #294 

We'll change the behavior of the filters in the next major version instead: #295
