### ISSUE TITLE
Support for KafkaJS publishers and consumers

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/apm-agent-nodejs#2905]
It would be great to have NodeJS agent support [KafkaJS](https://kafka.js.org/) publishers and consumers to create transactions and spans, as well as trace context propagation.

**Comment by astorm** [comment]
@michaelhyatt is there a specific Node.js kafka library you're interested in supporting? It looks like there's a few of them.

**Comment by michaelhyatt** [comment]
Yep, https://kafka.js.org/

**Comment by Gauravism2017** [comment]
Are there any progress/plans to support this library?

**Comment by trentm** [comment]
@Gauravism2017 No update on this currently. Comments/notes/reactions on this issue (like yours) will help decide if we can prioritize this work.
