### ISSUE TITLE
Add AWS ECS/Fargate to container-info Parsing

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2914]
**Is your feature request related to a problem? Please describe.**

We've identified a new pattern for pod UID strings. See [spec PR](https://github.com/elastic/apm/pull/678/files). 

**Describe the solution you'd like**

Update client parsing to include this new pattern.  Also, consider pulling `container-info` module into either the client or agent project.

**Comment by trentm** [comment]
When implementing this, we might also want to add testing based on the shared "json-specs/cgroup_parsing.json" added in https://github.com/elastic/apm/pull/686

**Comment by trentm** [comment]
That shared spec file is being sync'd in in https://github.com/elastic/apm-agent-nodejs/pull/2949

**Comment by trentm** [comment]
Re-opened. This is only resolved when we update to a new release of 'elastic-apm-http-client' with the above commit.
