### ISSUE TITLE
convention for marking internal API methods/attributes

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2926]
(This is a follow-up on the conversation started at https://github.com/elastic/apm-agent-nodejs/pull/2882#pullrequestreview-1106440168 about conventions for non-public methods/attributes in the APM agent code. Perhaps we can discuss here then, if appropriate, define/document some conventions in [CONTRIBUTING.md](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md) or [DEVELOPMENT.md](https://github.com/elastic/apm-agent-nodejs/blob/main/DEVELOPMENT.md).  Happy to write this in a separate form if that is more helpful.)

The APM agent public API provides user access to (mostly just three) classes: `Agent`, `Transaction`, `Span`. What is "public API" on these is defined in [index.d.ts](https://github.com/elastic/apm-agent-nodejs/blob/main/index.d.ts) and -- hopefully reasonably completely -- [documented here](https://www.elastic.co/guide/en/apm/agent/nodejs/current/api.html).

However, this is JavaScript, so attributes and methods other than those explicitly public ones are available to the user. For example, `agent._conf` and `span.setDbContext()` are available to the user that pokes around for them.

A potential issue here:
1. A user uses `span.setDbContext()` in their custom/manual instrumentation.  (This isn't unreasonable because there *aren't* any documented public APIs to set various kinds of span context.)
2. We later want to change the semantics of setting DB context in our instrumentation modules.
3. Any change we make could **break** the rare user using those APIs.

This isn't a large issue. It is mostly theoretical (i.e. there aren't any support issues on this).

## Proposal

I propose:

1. Any not-explicitly-public-for-the-user methods/attributes on `Agent`, `Transaction` and `Span` SHOULD be prefixed with a leading underscore to **hint** that it is non-public / internal.
2. We document the use of leading underscore as a convention to mean "this is internal to the APM agent code" in the API docs and in developer docs in "CONTRIBUTING.md".
3. If we remove a not-explicitly-public-but-not-prefixed-with-underscore-method -- e.g. removing `span.setDbContext()` -- then we SHOULD maintain a backward compatible accessor method until the next major version. That accessor SHOULD emit a warning message.

The goal is to make what is and isn't public-API-for-the-user be more self-explanatory. This assumes some familiarity in the user base with the leading underscore convention. I feel it is well-established in the [Python community via PEP 8](https://peps.python.org/pep-0008/#method-names-and-instance-variables). It is used in Node.js core, with some evidence in [writable._write(...)](https://nodejs.org/api/all.html#all_stream_writable_writechunk-encoding-callback) and other methods:

> The `writable._write()` method is prefixed with an underscore because it is internal to the class that defines it, and should never be called directly by user programs.

## Alternative options

- [Symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol). We could use a private symbol for each attribute. IMO, this isn't worth it. It adds a lot of syntax to make it slightly harder for user code to access internal fields.
- [Private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields). Generally [not available until node v14](https://node.green/#ES2022-features) and sometimes later. In some (current?) versions of v8, there have been perf concerns with private class fields as well.
- Separate public API classes. We could, for example, have separate `AgentAPI` (for the user to use) and `Agent` (used in internal agent code). I believe the Java APM agent has something like this. I think this would make for a clearer public API. However, it would be a large refactor. Given that the issue here isn't large and the likely long term API for APM is the OTel API, I don't think this would be worth the effort.

## A note on "public", "internal", etc.

I've been avoiding the terms "private" and "protected" as they evoke C++, Java, and TypeScript meanings. If we want to use C++ terminology, my intent with an underscore-prefixed method is that the method is "protected" and most or all other classes in the internal APM agent code are "friend" classes. For example, the following means that any internal APM agent code with access to a `Span` instance can call `span._setOutcomeFromSpanEnd(...)`. 

```js
class Span {
    _setOutcomeFromSpanEnd() { ... }
}
```

However, I think using the terminology "*internal* to the APM agent code" is closer to my intent. I'm not proposing anything to solve "this is private to just this class in the APM agent code".

**Comment by astorm** [comment]
Proposal seems reasonable -- just to restate it to make sure I understand 

- For "the world can rely on these to be stable" methods on the `Agent`, `Transaction`, and `Span` objects we won't use a leading underscore.  For every other method, we _will_ use a leading underscore to indicate _stay away, this is internal even though it's on a public API class/object_.  

- As we encounter methods and properties on these classes that don't adhere to this convention, we'll change them to be `_` leading but also leave a non-underscore but warning emitting method in place so we don't ruin people's day.

- Underscores should not be mistaken as a convention to indicate class based protection (Java, C#, etc.) -- it's strictly for internal/not-internal so we shouldn't sweat calling them as we would any other traditionally-public method when working on internal API features. 

Documenting this somewhere _does_ feel necessary -- as leading underscores are a convention but one with subtle different meanings across language/project communities. 

Question: What about classes/constructor-functions/objects we're using for internal feature implementations? Do we need/want a convention there? (my current thought would be no -- but happy to conform to one if others think it's necessary)

Looking at the alternative

- Symbols are clever but agree -- big PITA and sometimes make hard things harder or impossible

- Agree on private fields -- we live in land of land of "Node.js EOL is just a suggestion", so private fields aren't something we can/should support yet

- Separate API classes/objects also seems like a lot of mental overhead at this point in the agent's life.
