### ISSUE TITLE
Add simple benchmark test

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#293]
Add a simple benchmark test that can be run from the console to show the overhead of enabling the agent in an example application (test-case app).

The benchmark does not need to be able to run in CI which would require us to store the result somewhere to compare new runs with older runs.

Stretch goal:

- Make it easy to add more test-cases to cover more scenarios

Still pending (2019/04/09):
- [ ] Commit the code to the repo
- [ ] Submit the information to ES
- [ ] Create Kibana dashboard to check the data
- [ ] Create CI job to run the tests per PR (https://github.com/elastic/apm-agent-nodejs/issues/306)
- [ ] Blog post about performance and performance tuning

**Comment by watson** [comment]
The benchmarks currently live in this branch: https://github.com/watson/apm-agent-nodejs/commits/benchmark

Here's the diff: https://github.com/elastic/apm-agent-nodejs/compare/master...watson:benchmark

**Comment by saurabhnanda** [comment]
@watson are the benchmark results published anywhere?

**Comment by watson** [comment]
@saurabhnanda I'm not sure. Maybe @astorm knows
