### ISSUE TITLE
Option `opts.parent` for `Agent.prototype.captureError` is not present in types

### ISSUE THREAD

**Issue by sefiros1** [elastic/apm-agent-nodejs#2977]
**Describe the bug**

Option `opts.parent` for `Agent.prototype.captureError` is not present in the interface  `CaptureErrorOptions`(`./index.d.ts:311`).
In pure JS it's not a problem to pass 'parent' for error (transaction or span), but in TypeScript it's not so convenient.

**To Reproduce**

Steps to reproduce the behavior: 
1. Start agent
```js
const apmAgent = require('elastic-apm-node');
apmAgent.start();
```
3. Start transaction and end transaction
```js
const transaction = apmAgent.startTransaction('Name');
transaction.end();
```
4. Then call captureError
```js
apmAgent.captureError(new Error('some error'), { parent: transaction });
```

**Expected behavior**

TypeScript will compile code without any type assertion.

**Environment (please complete the following information)**

- OS: MacOS
- Node.js version: v16.17.1
- APM Server version: v8.4.2
- Agent version: v3.38.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by trentm** [comment]
Hi @sefiros1. Thanks for the issue!

The `parent` was added in https://github.com/elastic/apm-agent-nodejs/pull/2666. From that PR description:

> I have not documented this option in the user docs, nor added it to
> the TypeScript types because I don't expect it to be that used.
> 
> I'm happy to doc it and add it to types if people disagree. Or we can
> always add it later if there are external use cases.

:)   I am happy to get the `parent` option added to the docs and the TypeScript types.

**I would love to know more about your use case** that led you to looking for and finding the `parent` option. The `captureError()` API has a *lot* of options, so I would think you had to be fairly motivated to even find this option.  Is your use case about attaching errors to already ended and manually created transactions, as you showed in your reproduction steps?

**Comment by sefiros1** [comment]
Hi @trentm!

> **I would love to know more about your use case** that led you to looking for and finding the `parent` option. The `captureError()` API has a _lot_ of options, so I would think you had to be fairly motivated to even find this option. Is your use case about attaching errors to already ended and manually created transactions, as you showed in your reproduction steps?

I have several asynchronous tasks that run at the same time. I create a span for each task. In each of the tasks, an error may appear that needs to be linked to a specific span of this task.
Let me show you an example of the behavior I'm looking for:
```typescript
// Start agent
const apmAgent = require('elastic-apm-node');
apmAgent.start();
// Start root transaction
const transaction = apmAgent.startTransaction('Root transaction');
// Create array of tasks
const tasks = ['task1', 'task2']; // may be more than 2
// Create span for each task
const spans = tasks.map((task) => apmAgent.startSpan(task));
// Run async tasks
await Promise.all(tasks.map(async (task, i) => {
  // Get span of current task
  const span = spans[i];
  // Do some work
  // ...
  // Capture error if needed
  if (error) {
    apmAgent.captureError(error, { parent: span });
    span.setOutcome('failure');
    span.end();
    throw error;
  }
  span.end();
}))
transaction.end();
```

**Comment by trentm** [comment]
Thanks for the details. I have a couple comments on your example code.

Let me start by changing your example to this (so there isn't a top-level `await` so I can run it):

```js
// issue-2997.0.js
const apmAgent = require('elastic-apm-node')
apmAgent.start()

async function main () {
  const transaction = apmAgent.startTransaction('Root transaction')
  const tasks = ['task1', 'task2'] // may be more than 2
  const spans = tasks.map((task) => apmAgent.startSpan(task))
  await Promise.all(tasks.map(async (task, i) => {
    // Get span of current task
    const span = spans[i]

    // Do some work ...
    let error = null;

    if (error) {
      apmAgent.captureError(error, { parent: span })
      span.setOutcome('failure')
      span.end()
      throw error
    }
    span.end()
  }))
  transaction.end()
}

main()
```

If I run this, the parent/child relationships of the spans looks like this:

```
       transaction f4445f "Root transaction" (9.485ms, outcome=unknown)
       `- span 3d15e1 "task1" (0.893ms, sync)
         `- span 0f2130 "task2" (1.267ms, sync)
```

In other words, each "taskN" span is a child of "task(N-1)".  That is because (at least in the Elastic APM agent) `apmAgent.startSpan()` makes that created span the "current span" and another `.startSpan()` will be made a child of the current span.  So if you have 10 tasks, then it'll look like this:

```
       transaction ddde42 "Root transaction" (9.584ms, outcome=unknown)
       `- span 8f71b5 "task1" (1.796ms, sync)
         `- span 526ca5 "task2" (2.15ms, sync)
           `- span 301bca "task3" (2.083ms, sync)
             `- span 1ce692 "task4" (2.126ms, sync)
               `- span f74540 "task5" (2.08ms, sync)
                 `- span 83e7f5 "task6" (2.135ms, sync)
                   `- span 1f7379 "task7" (2.078ms, sync)
                     `- span 8c627c "task8" (2.063ms, sync)
                       `- span 7611f4 "task9" (2.002ms, sync)
                         `- span a0e60f "task10" (1.89ms, sync)
```

One way to avoid that is to only create the span inside the async task function, something like this:

```diff
--- issue-2997.0.js	2022-10-11 14:48:01.000000000 -0700
+++ issue-2997.1.js	2022-10-11 14:48:07.000000000 -0700
@@ -1,14 +1,13 @@
-// issue-2997.0.js
+// issue-2997.1.js
 const apmAgent = require('elastic-apm-node')
 apmAgent.start()

 async function main () {
   const transaction = apmAgent.startTransaction('Root transaction')
   const tasks = ['task1', 'task2'] // may be more than 2
-  const spans = tasks.map((task) => apmAgent.startSpan(task))
   await Promise.all(tasks.map(async (task, i) => {
     // Get span of current task
-    const span = spans[i]
+    const span = apmAgent.startSpan(task)

     // Do some work ...
     let error = null;
```

Then a given `span` is only "current" for that `async (task, i) => { ... }` function, and we get a trace that looks like:

```
       transaction 274a51 "Root transaction" (8.024ms, outcome=unknown)
       `- span 06a9ec "task1" (0.475ms, sync)
       `- span 357249 "task2" (0.166ms, sync)
```

The good news is that **this also solves the issue where using `parent` was needed.** We can now drop the `parent` option. The `captureError` will use the "current" span by default. Before, when `startSpan`s were all called ahead of time, the "current span" in each invocation of `async (task, i) => { ... }` was the span for the *last* task.

Here is a final version of the script that:
1. makes every second task error, so we can see error capture; and
2. puts the `transaction.end()` in a try-finally so we are sure it is called.

```js
// issue-2997.2.js
const apmAgent = require('elastic-apm-node')
apmAgent.start()

async function main () {
  const transaction = apmAgent.startTransaction('Root transaction')
  const tasks = ['task1', 'task2', 'task3', 'task4'] // may be more ...
  try {
    await Promise.all(tasks.map(async (task, i) => {
      // Get span of current task
      const span = apmAgent.startSpan(task)

      // Do some work ...
      let error = i % 2 ? new Error(`i=${i} boom`) : null

      if (error) {
        apmAgent.captureError(error)
        span.setOutcome('failure')
        span.end()
        throw error
      }
      span.end()
    }))
  } finally {
    transaction.end()
  }
}

main()
```

Running that results in a trace that will look like this:

```
       transaction 0bcad5 "Root transaction" (8.261ms, outcome=unknown)
       `- span 35c92a "task1" (0.419ms, sync)
       `- span 69a54a "task2" (0.411ms, sync, outcome=failure)
         `- error 5ef659 "i=1 boom"
       `- span 8020f2 "task3" (0.088ms, sync)
       `- span dcf9aa "task4" (0.101ms, sync, outcome=failure)
         `- error b0b6ed "i=3 boom"
```


All that said, I think it worthwhile to add `parent` to the TypeScript types. Thanks again for creating the issue.

**Comment by trentm** [comment]
elastic-apm-node@3.39.0 is release with this now.
