### ISSUE TITLE
`@apollo/server@4` support (the new apollo-server-express et al)

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2980]
`@apollo/server` will be the new home of `apollo-server-core` and `apollo-server-express` (and also, I imagine, the apollo server middleware for other frameworks like fastify and hapi).   The groundwork for this move was started about 8 months ago in https://github.com/apollographql/apollo-server/commit/e70c64557d0851c9bfd9f24b83d3569197a8581e, https://github.com/apollographql/apollo-server/commit/6ad3531545a142241cadd70974f7a6cc08ba35af and other commits.

`@apollo-server/4.0.0` was released on 2022-10-10. My guess is that the old package names will (eventually or now?) cease getting new releases and we should consider adding direct support for `@apollo-server` v4 for equivalent GraphQL instrumentation.

**Comment by diskra** [comment]
Any movement on this?

**Comment by trentm** [comment]
@diskra Nothing currently. I'll add it for consideration for our next planning round.

**Comment by diskra** [comment]
@trentm Thank you for the update! Can't wait to hear the outcome of your planning round 🤞🏽

**Comment by jmesimak** [comment]
I forked the apm agent and tried this. I'm still unsure how to properly test it but I am seeing the graphql option appear in our Kibana and it is reporting data.

`lib/instrumentation/modules/@apollo/server.js`
```javascript
const semver = require("semver")
const shimmer = require("../../shimmer")
const clone = require("shallow-clone-shim")

module.exports = function (apolloServerCore, agent, { enabled }) {
  if (!enabled) return apolloServerCore

  function wrapGraphQLRequest(orig) {
    return function wrappedRunHttpQuery() {
      var trans = agent._instrumentation.currTransaction()
      if (trans) trans._graphqlRoute = true
      return orig.apply(this, arguments)
    };
  }

  shimmer.wrap(apolloServerCore.ApolloServer.prototype, "executeHTTPGraphQLRequest", wrapGraphQLRequest)
  return apolloServerCore
};
```

**Comment by trentm** [comment]
@jmesimak Nice!

Would you like to start a draft PR and we could work through getting testing working together?  Basically remaining work here would be:

- Create a "test/instrumentation/modules/@apollo/server.test.js" test file. The name doesn't *have* to be that, but we've tended to have the module test files somewhat mirror the paths in "lib/...".   You could start by copying over the current "apollo-server-express.test.js" file, removing all the `test(...)` blocks except the first one, and adapting that to use `@apollo/server`.
- Do you know the min supported node version for `@apollo/server@4`? We'll need a guard in the test file so that we don't test it with older node (the APM agent supports back to node v8.6 currently).  "apollo-server-express.test.js" has a guard for this near its top already (search for "SKIP").
- Filling out that test file with some more cases.
- Adding an entry to ".tav.yml" to test versions of `@apollo/server` as they are released. We can sort that out later.
- Adding an entry to "docs/supported-technologies.asciidoc".


(Note to self: I think we could skip the direct inclusion of 'apollo-server-core' in our package.json, because it is imported indirectly by 'apollo-server-express' and it is the latter that we are testing.)

**Comment by diskra** [comment]
According to [Apollo's Docs](https://www.apollographql.com/docs/apollo-server/getting-started/) and [package.json](https://github.com/apollographql/apollo-server/blob/main/package.json) , 
 
"node": ">=14.16.0",
"npm": ">=8.5.0"

**Comment by jmesimak** [comment]
I'll give it a try and let's see what happens. Thanks for the detailed instructions!

**Comment by trentm** [comment]
Thanks.

I forgot to mention, when working on your test file, you don't need to run the whole test suite (`npm test`). Each test file should run independently: `node test/instrumentation/modules/@apollo/server.test.js`.

Also `npm run lint` (or `make check`) to run style/lint checks.
