### ISSUE TITLE
serverless-http support

### ISSUE THREAD

**Issue by kurigashvili-godaddy** [elastic/apm-agent-nodejs#3000]
**Is your feature request related to a problem? Please describe.**
I am using serverless-http + express with serverless framework. When I look into data recorded by APM a lot of information related to http request is missing. 

**Describe the solution you'd like**
Support serverless-http out of box (it does look like lib/instrumentation/http-shared.js does not initiate correctly with serverless-http).

**Describe alternatives you've considered**
Here is my workaround.
```js
const apm = require("elastic-apm-node");
const serverless = require("serverless-http");
const express = require("express");
const app = express();

// without adding this middleware, a lot of apm http request metadata is missing
app.use((req, res, next) => {
  const traceparent =
    req.headers.traceparent || req.headers["elastic-apm-traceparent"];
  const tracestate = req.headers.tracestate;
  const transaction = apm.startTransaction(null, "request", {
    childOf: traceparent,
    tracestate: tracestate,
  });
  // transaction by default has req and res undefined so no http metadata can be created
  
  transaction.req = req;
  transaction.res = res;
  res.on("finish", function () {
    transaction.end();
  });
  next();
});

app.get("/test/:id", (req, res) => {
  const { id } = req.params;
  res.json({ id });
});

module.exports.handler = serverless(app);
```

**Additional context**
## Current 

<img width="1174" alt="Screen Shot 2022-10-24 at 11 07 20 AM" src="https://user-images.githubusercontent.com/88911006/197602344-12dd0484-6c2e-4d9c-8361-049d03d8182a.png">

<img width="954" alt="Screen Shot 2022-10-24 at 11 48 40 AM" src="https://user-images.githubusercontent.com/88911006/197602897-6bd48752-3f84-4cf6-b63e-66c662b79bee.png">

## Expected

<img width="1193" alt="Screen Shot 2022-10-24 at 11 49 38 AM" src="https://user-images.githubusercontent.com/88911006/197602959-43538845-0671-432a-8b04-48d34459f2e2.png">

<img width="962" alt="Screen Shot 2022-10-24 at 11 49 53 AM" src="https://user-images.githubusercontent.com/88911006/197602975-2c2c9509-c13d-4b9c-8e7f-1e404ea33323.png">

<img width="1007" alt="Screen Shot 2022-10-24 at 11 50 05 AM" src="https://user-images.githubusercontent.com/88911006/197602994-b5ecabb0-01cb-4396-9f8a-c38ab372c653.png">

**Comment by trentm** [comment]
Hi, thanks for the report. I think this will be handled by https://github.com/elastic/apm-agent-nodejs/issues/2419
We could either close this one and have you follow that issue, or keep this one open and sanity check again when we implement it.

**Comment by kurigashvili-godaddy** [comment]
Closing as duplicate of https://github.com/elastic/apm-agent-nodejs/issues/2419
