### ISSUE TITLE
[META 709] Add/simplify ES cluster name capture

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#3002]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/709

**Comment by trentm** [comment]
This was already done as part of #2882
- code: https://github.com/elastic/apm-agent-nodejs/pull/2882/files#diff-8b8cdefabed92970b05a687c766e3c51678ea17686b219d93ff63043f40a6538
- test: https://github.com/elastic/apm-agent-nodejs/pull/2882/files#diff-10308c7e3f70ee314a2e4a92b9e4b795ed5c680c2d101fac452d08f86a148b87
