### ISSUE TITLE
APM Server transport error: error fetching APM Server version: timeout 

### ISSUE THREAD

**Issue by rimiti** [elastic/apm-agent-nodejs#3016]
Hello,

We just created our first deployment on the latest Elastic version (8.x) on cloud.elastic.co in order to the APM into our NodeJS api as describe into the example.

**Version used:**
"elastic-apm-node": "3.40.0"

### Context

When we put :

```
require('elastic-apm-node').start({
  serviceName: 'api',
  secretToken: 'OUR_SECRET',
  serverUrl: 'https://38f0802942b3467ba00732e4bbf128f6.apm.eu-west-1.aws.cloud.es.io:443',
  environment: 'local',
});
```

### Error

We are getting error :

```
api | {"log.level":"warn","@timestamp":"2022-11-04T11:51:10.577Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"cloud metadata requests timed out, using default values instead"}
api | {"log.level":"error","@timestamp":"2022-11-04T11:51:10.587Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error: error fetching APM Server version: timeout (30000ms) fetching APM Server version"}
api | {"log.level":"error","@timestamp":"2022-11-04T11:51:10.590Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error (ERR_SOCKET_TIMEOUT): Socket timeout"}
```

Do you know why are we getting this timeout?

PS: We dont have any firewall rules or network blockers.

Thanks a lot,

**Comment by rimiti** [comment]
**Resolved:**

Nodejs agent seems not working with latest Elastic version.
We deployed a new stack on v7 and it works great...

**Comment by trentm** [comment]
@rimiti This should definitely work. I'm sorry it wasn't working immediately for you. I'm not sure what the issue was with your original 8.x deployment.

You've deleted it now:

```
% curl -i https://38f0802942b3467ba00732e4bbf128f6.apm.eu-west-1.aws.cloud.es.io:443
HTTP/2 410
content-type: application/json; charset=UTF-8
x-cloud-request-id: Yltq5UDlQ3iLVQjhypZB-w
x-found-handling-cluster: 38f0802942b3467ba00732e4bbf128f6
content-length: 43
date: Fri, 04 Nov 2022 17:14:12 GMT

{"ok":false,"message":"Deleted resource."}
```

so we can't debug it anymore.
If you do go back to trying 8.x and hit a similar problem, we can try to debug it.

**Comment by rimiti** [comment]
Thank you @trentm for your investigation but before creating the issue I did the same curl but it wasn't returning a JSON response.

Absolutely agreed about the "weird" case. 

>I will reopen the case if the problem come back when I will migrate the deployment to v8.x.

Thanks a lot,
