### ISSUE TITLE
[META 724] Collect information on the agent activation method

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#3039]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/724
- Spec issue: https://github.com/elastic/apm/issues/725

**Comment by trentm** [comment]
I'm proposing these names for various install/start methods:

| Install/start method                                | `agent.installation.method`          | Notes |
| --------------------------------------------------- | ------------------------------------ | ----- |
| `require('elastic-apm-node').start(...)`            | "require-and-start"                  | |
| `require('elastic-apm-node/start')`                 | "require-start"                      | |
| `require('elastic-apm-node/start-next')`            | "require-start-next"                 | This should go away when Next.js instrumentation is GA. |
| `import 'elastic-apm-node/start.js'`                | "import-start"                       | This is fringe given the agent doesn't currently support ESM. |
| `import apm from 'elastic-apm-node'; apm.start()`   | "import-and-start"                   | Ditto. |
| Using [AWS Lambda Layer][]                          | "preload-require-start-lambda-layer" | |
| Via [APM Attacher][]                                | "preload-require-start-apm-attacher" | |
| `node -r elastic-apm-node/start ...`                | "preload-require-start"              | Fallback if not one of the specialize "preload-*" cases above. |
| `NODE_OPTIONS='-r elastic-apm-node/start' node ...` | "preload-require-start-envvar"       | Fallback for any other `NODE_OPTIONS` usage. |

[AWS Lambda Layer]: https://www.elastic.co/guide/en/apm/agent/nodejs/current/lambda.html
[APM Attacher]: https://www.elastic.co/guide/en/apm/attacher/current/apm-attacher.html

**Comment by trentm** [comment]
### take 2

| Install/start method                       | `agent.installation.method` | Notes |
| ------------------------------------------ | --------------------------- | ----- |
| `require('elastic-apm-node').start(...)`, `require('elastic-apm-node/start')` | "require" | |
| `import 'elastic-apm-node/start.js'`, `import apm from 'elastic-apm-node'; apm.start()` | "import" | Could help understand need and priority for ESM support. |
| Using [AWS Lambda Layer][]                 | "aws-lambda-layer" | `NODE_OPTIONS` pointing to "/opt/nodejs/node_modules/elastic-apm-node" |
| Via [APM Attacher][]                       | "k8s-attacher" | `NODE_OPTIONS` pointing to "/elastic/apm/agent/elastic-apm-node" |
| `NODE_OPTIONS='-r elastic-apm-node/start'` | "env-attach" | Fallback for any other `NODE_OPTIONS` usage. |
| `node -r elastic-apm-node/start ...`       | "preload" | Or perhaps "cli-attach"? |

[AWS Lambda Layer]: https://www.elastic.co/guide/en/apm/agent/nodejs/current/lambda.html
[APM Attacher]: https://www.elastic.co/guide/en/apm/attacher/current/apm-attacher.html
