### ISSUE TITLE
Option opts.tracestate for Agent.prototype.startTransaction is not present in types

### ISSUE THREAD

**Issue by sefiros1** [elastic/apm-agent-nodejs#3061]
**Describe the bug**

Option `opts.tracestate` for `Agent.prototype.startTransaction` is not present in the interface Agent(`./index.d.ts:61`).
In pure JS it's not a problem to pass 'tracestate' for new transaction, but in TypeScript it's not so convenient.

My case:
I want to add apm trace support for my custom queue service (like rabbit or kafka). I've already added traceparent support and I need to use tracestate if producers are using `transactionSampleRate < 1`.

**To Reproduce**

Steps to reproduce the behavior: 
1. Start agent
```ts
const apmAgent = require('elastic-apm-node');
apmAgent.start();
```
2. Start transaction with tracestate
```ts
apmAgent.startTransaction('Name', { tracestate });
```

3. See error
```
Argument of type '{ tracestate: string; }' is not assignable to parameter of type 'TransactionOptions'.
Object literal may only specify known properties, and 'tracestate' does not exist in type 'TransactionOptions'.
```

**Expected behavior**

TypeScript will compile code without any type assertion.

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 16.18.1
- APM Server version: v8.4.2
- Agent version: v3.38.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by trentm** [comment]
@sefiros1 Thanks. I'm working on fixing that here: https://github.com/elastic/apm-agent-nodejs/pull/3063
