### ISSUE TITLE
Drop support for Node 4

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-nodejs#308]
As Node.js v4 reaches EOL (currently in maintenance) and a new LTS is released we will drop support for Node 4 allowing us to use language features available after Node 4

The following should be done when upgrading:

- [x] Bump read-pkg-up dependency to newer version
- [x] Bump wait-on dev-dependency to newer version
- [x] Drop support for Node 9

**Comment by watson** [comment]
@alvarolobato FYI: I just updated the title and description of this issue to use the word "drop" instead of "deprecate" as the latter can mean that we still support it, but just warn people that the next version will no longer support it. Using the word "drop" is less ambiguous IMO 😃

**Comment by watson** [comment]
When dropping Node 4 support, consider if it's worth it to set the minimum supported Node 6 version to v6.5.0 as that has 99% support for ES2015, as opposed to only 95% for <6.5.0. The we don't need extra 4% for anything, there's no need for it.

**Comment by Qard** [comment]
The remaining 4% is fairly obscure, so it's not really that important.

**Comment by watson** [comment]
Support for Node 4 (and 9) have been removed from the `api-v2` branch, so I'll close this issue now.
