### ISSUE TITLE
[META 745] Implement Azure Functions metadata detection

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#3089]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/745

**Comment by trentm** [comment]
I have some follow-up questions on the Azure Functions metadata collection here: https://github.com/elastic/apm/pull/712#pullrequestreview-1254115253

This is based on the gherkin spec file that was added later in that PR.

**Comment by trentm** [comment]
My questions are answered well-enough. I think the changes in #3071 handle this.
