### ISSUE TITLE
Instrument CPU and memory usage

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#309]
Collect the following metrics:

- CPU usage (user + system)
- Memory usage (allocated heap + heap in use + rss + external)

There's a lot of other interesting metrics we could collect, but to get the ball rolling this is a nice start that will still give a lot of value.

Note that the APM Server currently does not support this. For now this is just a tracking issue. Once we start the work we'll update this issue.

**Comment by alvarolobato** [comment]
This will be implemented in the general Metrics issue we are working on soon: https://github.com/elastic/apm-agent-nodejs/issues/422
