### ISSUE TITLE
[META 753] Support Partial Transaction for AWS Lambda

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#3136]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/753

**Comment by trentm** [comment]
See this coming lambda extension change: https://github.com/elastic/apm-aws-lambda/pull/384
We should work with and without an extension supporting that.

**Comment by trentm** [comment]
FWIW, here is the Python PR adding this support: https://github.com/elastic/apm-agent-python/issues/1734

**Comment by trentm** [comment]
![Screenshot 2023-04-21 at 12 59 50 PM](https://user-images.githubusercontent.com/46866/233724915-c5572212-0262-4697-af55-a46c9eae2335.png)

Here is an example of the coming PR for this showing how a timed-out lambda invocation now gets a reported (failed) transaction.
