### ISSUE TITLE
Add Node nightly to CI

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-nodejs#316]
We need to create a CI job that can test against last Node nightly to be able to know the problems ahead of the next release.

**Comment by watson** [comment]
We should consider if it's better to just test release candidates. I was just thinking that the nightlies might have too many bugs unrelated to our instrumentation, which in turn will take up too much of our time, whereas the release candidates should come less frequent only leading up to a release and are more stable.

On the other hand, finding the bug early might be nice, which the nightlies will allow.
