### ISSUE TITLE
[META 773] Service environment correlation

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#3195]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/773

**Comment by trentm** [comment]
This is implemented in the ecs-logging-nodejs packages now: `@elastic/ecs-morgan-format@1.4.0`, `@elastic/ecs-pino-format@1.4.0`, `@elastic/ecs-winston-format@1.4.0`
