### ISSUE TITLE
Fastify wont capture body - fix proposed

### ISSUE THREAD

**Issue by ddoice** [elastic/apm-agent-nodejs#3217]
**Fastify**

When instrumenting a fastify server the `captureBody` option wont work, it seems that the function `getContextFromRequest`  is not able to recover the body.

**To Reproduce**

1. Start the fastify server
3. Then call some endpoint (tried both with and without error)
4. Check kibana APM module and look for that transaction

![image](https://user-images.githubusercontent.com/14946058/227586973-7d85c852-5c62-4aa1-b3fc-35043cc6f6d0.png)

**Expected behavior**

To have the body available in the transaction.

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 18.14.2
- APM Server version: 7.6.1
- Agent version: 3.43.0
- Fastify version 4.13.0

**How are you starting the agent? (please tick one of the boxes)**

- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Agent config options: 
<details>
  <summary>Click to expand</summary>

```
    serverUrl: 'http://localhost:8200',
    logLevel: 'trace',
    verifyServerCert: false,
    captureBody: 'all',
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
    "@fastify/sensible": "5.2.0",
    "@fastify/swagger": "8.3.1",
    "@fastify/swagger-ui": "1.5.0",
    "@prisma/client": "4.10.1",
    "@types/pg": "8.6.6",
    "elastic-apm-node": "^3.43.0",
    "fastify": "4.13.0",
    "fastify-plugin": "4.5.0",
    "fluent-json-schema": "4.1.0",
    "pg": "8.10.0"
```
</details>

**Comment by trentm** [comment]
@ddoice Thanks very much for the issue and the patch and my apologies for taking so long to respond. There was an old PR to do almost exactly this that had languished (partly my fault). https://github.com/elastic/apm-agent-nodejs/pull/2681   I think that will solve the issue for you.  I am hoping to get that PR merged very soon.  I'll update this issue when that is done.
