### ISSUE TITLE
Set-Cookie header is redacted, but Cookie header is not

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-agent-nodejs#3273]
From the [spec](https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-http.md#http-transactions):

> Captured request and response headers, cookies, and form bodies MUST be sanitised (i.e. secrets removed) according to data sanitization rules.

However, this only happens for the `Set-Cookie` header, not the `Cookie` header, which seems to be a violation of the spec.

**Comment by david-luna** [comment]
Hi @dgieselaar 

Thanks for filling the issue. I've checked how the filter works adding this small change on the test file for filters
```
diff --git a/examples/trace-http.js b/examples/trace-http.js
index f9fbb524..ee7e9dab 100755
--- a/examples/trace-http.js
+++ b/examples/trace-http.js
@@ -43,7 +43,8 @@ const server = http.createServer(function onRequest (req, res) {
         res.writeHead(200, {
           server: 'example-trace-http',
           'content-type': 'text/plain',
-          'content-length': Buffer.byteLength(resBody)
+          'content-length': Buffer.byteLength(resBody),
+          'set-cookie': [ 'password=test', 'foo=bar']
         })
         res.end(resBody)
       })
@@ -56,7 +57,8 @@ server.listen(3000, function () {
   //
   // Note that this there is no current "transaction" here, so this HTTP
   // request is not captured by APM. See "trace-http-request.js" for more.
-  const clientReq = http.request('http://localhost:3000/', function (clientRes) {
+  const options = { headers: { accept: '*/*', cookie: 'password=test;foo=bar' } }
+  const clientReq = http.request('http://localhost:3000/', options, function (clientRes) {
     console.log('client response: %s %s', clientRes.statusCode, clientRes.headers)
```

Running `./examples/trace-http.js` example we get a transaction with this shape

```
{
    "transaction": {
        "name": "GET /",
        "type": "request",
        "result": "HTTP 2xx",
        "id": "d5233c52c314d102",
        "trace_id": "d93fb3d7a8b54b9e862851473bc309c8",
        "duration": 17922.716,
        "timestamp": 1683125345650013,
        "sampled": true,
        "context": {
            "user": {},
            "tags": {},
            "custom": {},
            "service": {},
            "cloud": {},
            "message": {},
            "request": {
                "http_version": "1.1",
                "method": "GET",
                "url": {
                    "raw": "/",
                    "protocol": "http:",
                    "hostname": "localhost",
                    "port": "3000",
                    "pathname": "/",
                    "full": "http://localhost:3000/"
                },
                "headers": {
                    "accept": "*/*",
                    "cookie": "password=[REDACTED]; foo=bar",
                    "host": "localhost:3000",
                    "connection": "close"
                },
                "socket": {
                    "remote_address": "::1"
                }
            },
            "response": {
                "status_code": 200,
                "headers": {
                    "server": "example-trace-http",
                    "content-type": "text/plain",
                    "content-length": "4",
                    "set-cookie": "[REDACTED]",
                    "date": "Wed, 03 May 2023 14:49:23 GMT",
                    "connection": "close"
                }
            }
        },
        "span_count": {
            "started": 1
        },
        "outcome": "success",
        "sample_rate": 1
    }
}
}
```

The request cookie string is checked and keys that match the [sanitization field names](https://github.com/elastic/apm/blob/main/specs/agents/sanitization.md#sanitize_field_names-configuration) get their values redacted. In this case the `password` is redacted but not `foo`. If there is no key matching the field names you will see the full content of the cookie.

Set-cookie response header is completely redacted.

Did you expect to have the cookie completely redacted as well? If not could you provide a scenario/sample and a version to try to reproduce the issue?

**Comment by dgieselaar** [comment]
@david-luna I think so, see https://elastic.slack.com/archives/C5M02D1GE/p1681668055146329?thread_ts=1681637379.980439&cid=C5M02D1GE (internal) for context.

**Comment by david-luna** [comment]
Digest to have context here.

There was some wording on [this discussion](https://github.com/elastic/apm/pull/378/files#r537287895) that did not make it to the spec. Agents do implement redacting of the cookies but not exactly the same way
- Java agent add a `cookies` property and redacts it, it also removes the cookie header ([see](https://github.com/elastic/apm-agent-java/blob/4409da32aafb27608d2a195a8d9c97a85452a70f/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/SanitizingWebProcessor.java))
- Python Agent add the property and keeps the cookie, both redacted ([see](https://github.com/elastic/apm-agent-python/blob/dceda6681be6c159f02f4a7fcc7bf77f4c86cf64/tests/processors/tests.py#L207))

Need to check other agents.

Currently the nodejs agent is redacting the sensitive parts of the cookie but not creating the `cookies` property which may lead to think is not redacting them.

**Comment by trentm** [comment]
To make sure I understand exactly, the current state is as follows.
Given this request/response:

```
GET / HTTP/1.1
Host: ...
Cookie: foo=bar; password=12345; secret=12345

HTTP/1.1 200 OK
Date: Fri, 05 May 2023 20:35:52 GMT
Connection: close
Set-Cookie: spam=eggs; sometoken=12345
```

The APM agents currently result in the following transaction fields

## nodejs

```json
{
    "transaction": {
        "context": {
            "request": {
                "headers": {
                    "host": "...",
                    "cookie": "foo=bar; password=[REDACTED]; secret=[REDACTED]"
                }
            },
            "response": {
                "headers": {
                    "date": "...",
                    "connection": "...",
                    "set-cookie": "[REDACTED]"
                }
            }
        }
    }
}
```


## python

```json
{
    "transaction": {
        "context": {
            "request": {
                "headers": {
                    "host": "...",
                    "cookie": "foo=bar; password=[REDACTED]; secret=[REDACTED]"
                },
                "cookies": {
                    "foo": "bar",
                    "password": "[REDACTED]",
                    "secret": "[REDACTED]"
                }
            },
            "response": {
                "headers": {
                    "date": "...",
                    "connection": "...",
                    "set-cookie": "[REDACTED]"
                }
            }
        }
    }
}
```

## java

```json
{
    "transaction": {
        "context": {
            "request": {
                "headers": {
                    "host": "...",
                },
                "cookies": {
                    "foo": "bar",
                    "password": "[REDACTED]",
                    "secret": "[REDACTED]"
                }
            },
            "response": {
                "headers": {
                    "date": "...",
                    "connection": "...",
                    "set-cookie": "[REDACTED]"
                }
            }
        }
    }
}
```

## others ...

**Comment by david-luna** [comment]
Indeed is what you understood. I've checked other agents (liker ruby) and they also create the `context.request.cookies` map to redact individually each cookie based on `sanitizeFieldNames` configuration.

The approach on the PR is to create the same map and redact the cookie header completely so we do not duplicate data. The consumer of the agent can make use of `sanitizeFieldNames` or `captureHeaders` to control how much data is sent.
