### ISSUE TITLE
rewrite 'disableInstrumentations' test in config.test.js to not need so much special casing

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#3303]
The

```js
test('disableInstrumentations', function (t) {
```

test in "test/config.test.js" requires a lot of special casing to exclude modules that don't even import in older node versions. This is an annoying and relatively frequent maintenance paper cut. It is obtuse for new prospective contributors of newer module instrumentations.

This test should be refactored to do some basic sanity tests, but otherwise not feel it has to cover every module that is instrumented.

**Comment by david-luna** [comment]
@trentm may this is already covered in https://github.com/elastic/apm-agent-nodejs/pull/3658 ?

**Comment by trentm** [comment]
> @trentm maybe this is already covered in #3658 ?

Yes, thanks.  https://github.com/elastic/apm-agent-nodejs/pull/3658#discussion_r1349388994 gives my reasoning for having dropped this test.
