### ISSUE TITLE
[META 793] Report FQDN for `detected_hostname`

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#3310]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/793
- Spec issue: https://github.com/elastic/apm/issues/794

The spec PR: https://github.com/elastic/apm/pull/805

**Comment by trentm** [comment]
If/when doing this, we should consider finding doing the `detected_hostname` update for the Node.js agent as well, to conform to https://github.com/elastic/apm/blob/main/specs/agents/metadata.md#hostname (spec PR/discussion: https://github.com/elastic/apm/pull/517)
