### ISSUE TITLE
Deprecate filterHttpHeaders configuration

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3320]
Once #3273 is resolved [filterHttpHeaders config](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#filter-http-headers) will become redundant since the agent will be capable of filtering/redacting headers (and cookies as well) by the proper set up of [captureHeaders](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#capture-headers) and [sanitizeFieldNames](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#sanitize-field-names).

We can proceed to deprecate `filterHttpHeaders`. Since this is considered a breaking change we should plan it for the next major release.

**Comment by trentm** [comment]
@david-luna We could deprecate it when #3273 is done -- i.e. just document it as deprecated -- and then *remove* the config var in the next major.
