### ISSUE TITLE
Remove `filterHttpHeaders` config option

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3332]
The agent is no longer using `filterHttpHeaders` config option to redact cookies. This [pull request](https://github.com/elastic/apm-agent-nodejs/issues/3320) changed the data format to place the cookies inside `context.request.cookies` map which is accepted by the intake API.

With that change now `sanitizeFieldNames` options is in charge of redacting the cookies and there is no use for `filterHttpHeaders` which is already marked as deprecared.

We should then remove the config option

**Comment by trentm** [comment]
Notes: perhaps add "deprecated" note in index.d.ts for this option as well.

**Comment by trentm** [comment]
Closed by https://github.com/elastic/apm-agent-nodejs/pull/3539 on "dev/4.x" branch, which will be the 4.x active branch soonish.
