### ISSUE TITLE
Update debug log output to not add line breaks

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#335]
When logging objects with multiple properties, the current logger will split the objects over multiple lines. This is often the case when the log level is set to `debug`. The old debug mode didn't do this.

Example of line split:

![image](https://user-images.githubusercontent.com/10602/39815645-fabd42ca-5398-11e8-93c3-66bc2aa386cf.png)

**Comment by watson** [comment]
Btw, the reason I think line splits are an issue is that many log collectors expects each line to be a single log entry.

**Comment by trentm** [comment]
Obsolete with move to pino logger.
