### ISSUE TITLE
CommonJS & ESM for tests

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3391]
Some of the agent dependencies are moving to ESM exclusively and this presents a new challenge for testing their version using `TAV`. In [this dependabot PR](https://github.com/elastic/apm-agent-nodejs/pull/3385) which updates `got` we faced 2 problems
- exports property of the package does not have `package.json` in it so we are not allowed to require it
- we need to use dynamic imports

So we should find an alternative to `require` to read `package.json` files and also a way for the test to know when to use require or dynamic imports (if there is no single way of doing it)

Note: better to wait until #1952 is completed

**Comment by trentm** [comment]
Specifically for `got` note https://github.com/elastic/apm-agent-nodejs/blob/16ed4d514f9c9ff07741d8f4dd97669e4d0ce832/.tav.yml#L14-L17

```js
# Testing 'got' was initially added to test an issue in its usage of
# mimic-response@1.0.0. However, this test case serves to sanity test 'got'
# usage with the agent. Got@12 is pure ESM, so cannot currently be tested with
# the current test script.
```


For the "get the version from package.json" error (if I understand it correctly), we have `safeGetPackageVersion` in `_utils.js`:

```js
// "Safely" get the version of the given package, if possible. Otherwise return
// null.
//
// Here "safely" means avoiding `require("$packageName/package.json")` because
// that can fail if the package uses an old form of "exports"
// (e.g. https://github.com/elastic/apm-agent-nodejs/issues/2350).
function safeGetPackageVersion (packageName) {
```

**Comment by david-luna** [comment]
> So we should find an alternative to require to read package.json files and also a way for the test to know when to use require or dynamic imports (if there is no single way of doing it)

#1952 is done so now:
- we can use `runTestFixtures` function to tests for CJS and ESM packages
- we also have `safeGetPackageVersion` to get the package info

we can close this issue
