### ISSUE TITLE
how to search by custom labels on kibana apm transactions?

### ISSUE THREAD

**Issue by sibelius** [elastic/apm-agent-nodejs#3395]
**Is your feature request related to a problem? Please describe.**
I've add some custom labels on 

`apm.setLabel('operationName', request.body.operationName);`

I'd like to search inside kibana apm services transactions

![image](https://github.com/elastic/apm-agent-nodejs/assets/2005841/ff220d48-41fa-4b41-b492-84e52b13c27e)

![image](https://github.com/elastic/apm-agent-nodejs/assets/2005841/88691dc7-bdcb-4843-bd5d-bba9b928cd67)

I can only search them inside kibana discover

`labels.operationName: 'my operation name"`

**Describe the solution you'd like**
Improve the documentation to make it clear how to search and index custom labels

**Describe alternatives you've considered**
Only using kibana discover for now, but searching directly on kibana apm services transactions would be better

**Additional context**
We are using latest apm server, kibana and elastic search

**Comment by trentm** [comment]
Hi @sibelius, I just tried with my v8.6.2 Elastic deployment and it seemed to work for me. Here is what I did:

1. I have a script that creates an HTTP server and sends a request to it: either `GET /` or `GET /ping`. The HTTP server will add a label (`subpath=ping`) if it was `GET /ping`.

```js
const apm = require('../').start({ // elastic-apm-node
  serviceName: 'example-trace-http',
  useElasticTraceparentHeader: false,
  usePathAsTransactionName: true
})

const http = require('http')

const server = http.createServer(function onRequest (req, res) {
  console.log('incoming request: %s %s %s', req.method, req.url, req.headers)
  if (req.url === '/ping') {
    apm.setLabel('subpath', 'ping')
  }
  req.resume()
  req.on('end', function () {
    const resBody = 'pong'
    res.writeHead(200, {
      server: 'example-trace-http',
      'content-type': 'text/plain',
      'content-length': Buffer.byteLength(resBody)
    })
    res.end(resBody)
  })
})

server.listen(3000, function () {
  const path = (Math.random() < 0.5 ? '/' : '/ping')
  const clientReq = http.request('http://localhost:3000' + path, function (clientRes) {
    console.log('client response: %s %s', clientRes.statusCode, clientRes.headers)
    const chunks = []
    clientRes.on('data', function (chunk) {
      chunks.push(chunk)
    })
    clientRes.on('end', function () {
      const body = chunks.join('')
      console.log('client response body: %j', body)
      server.close()
    })
  })
  clientReq.end()
})
```

2. I set `ELASTIC_APM_SERVER_URL` and auth appropriately and called it a number of times.

3. In the Kibana APM app the transactions page shows both transaction groups:

![Screenshot 2023-05-31 at 8 56 53 AM](https://github.com/elastic/apm-agent-nodejs/assets/46866/7c8c93d9-b8be-4853-9f06-bf64e5c6d5e5)

5. And I can filter on `labels.subpath: ping`:

![Screenshot 2023-05-31 at 8 57 48 AM](https://github.com/elastic/apm-agent-nodejs/assets/46866/945e25d7-8b96-4e75-b75e-2de76839549a)

**Comment by sibelius** [comment]
is there some "delay" to indexing on apm ?

**Comment by trentm** [comment]
> is there some "delay" to indexing on apm ?

No, or at least it should be very small.   There *is* a delay of up to 10s ([configurable](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#api-request-time) before the APM agent will send tracing data on to APM server.

**Comment by trentm** [comment]
> `apm.setLabel('jobData', JSON.stringify(job.data));`
> 
> JSON.stringify could be a problem?

`JSON.stringify` results in a string, so the *type* should be fine.



> can we also increase the limit of label value ?

Unfortunately, no. Label names and values are limited to 1024 characters and that isn't configurable.

**Comment by sibelius** [comment]
is there any guide to manually index? or manually test the indexed data?

**Comment by trentm** [comment]
I may be misunderstanding you, but the APM data is queryable in "Discover" in Kibana, so you can go look at the exact collected data.

**Comment by sibelius** [comment]
tks, I'm gonna close and reopen if needed
