### ISSUE TITLE
Start supporting `response.writableEnded` in transaction's context

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3428]
According to [nodejs docs](https://nodejs.org/api/http.html#responsefinished) `response.finished` property is deprecated since: v13.4.0, v12.16.0. There is another property recommended by the docs named `writableEnded`. Agent is relying on this property to fill the `transaction.contex.response.finished` field.

Although latest version v20.3.0 still supports it agent should anticipate the removal of that property and use the new one when needed. So some expression like the one below may be enough

```javascript
context.finshed = res.finished || res.writableEnded
```

**Comment by thesixpathguy** [comment]
Hi @david-luna, I am interested to work on the issue. Can you please assign it to me?
