### ISSUE TITLE
Update package.json engines with node 10

### ISSUE THREAD

**Issue by dicarlo2** [elastic/apm-agent-nodejs#343]
It seems that node 10 is supported by apm, albeit with broken tracing (https://github.com/nodejs/node/issues/20516). Still, can we get the package.json updated to have node 10 as an engine? We don't use the automatic tracing functionality and would like to move to node 10 without having to use `--ignore-engines` with `yarn`.

**Comment by watson** [comment]
Good point. I've made a PR to address it: #345

**Comment by watson** [comment]
This have now been fixed in v1.5.4
