### ISSUE TITLE
[META 811] Fix reporting of `system.process.cgroup.memory.mem.limit.bytes` when limit not set

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#3450]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/811
- Spec issue: https://github.com/elastic/apm/issues/812

**Comment by trentm** [comment]
We'd perhaps first need to support the `system.process.cgroup.*` metrics at all. (E.g. the Python docs: https://www.elastic.co/guide/en/apm/agent/python/current/metrics.html#cpu-memory-cgroup-metricset).

**Comment by gregkalapos** [comment]
This is (somewhat of a) dupl. of https://github.com/elastic/apm-agent-nodejs/issues/3452. Closing this in favor of https://github.com/elastic/apm-agent-nodejs/issues/3452
