### ISSUE TITLE
`@aws-sdk/client-s3` test failures with recent 3.363.0 version

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#3454]
`TAV=@aws-sdk/client-s3` tests started failing today with the recently released (today) 3.363.0 version.

```
% npm info @aws-sdk/client-s3 time
...
  '3.359.0': '2023-06-23T19:22:05.591Z',
  '3.360.0': '2023-06-26T19:23:11.014Z',
  '3.6.4': '2023-06-26T22:58:32.310Z',
  '3.362.0': '2023-06-28T19:26:17.649Z',
  '3.363.0': '2023-06-29T20:23:50.756Z'
}
```

https://github.com/elastic/apm-agent-nodejs/actions/runs/5416261226
https://github.com/elastic/apm-agent-nodejs/actions/runs/5416261226/jobs/9845765429#step:3:344
https://github.com/elastic/apm-agent-nodejs/actions/runs/5416261226/jobs/9845769982#step:3:135

Those are failures in node v14 and node v16.  The equiv for node v18 and v20 passed.
I wonder if there was some breakage just for older node versions.

They both failed with:

```
 node_tests_1  | -- required packages ["@aws-sdk/client-s3@3.363.0"]
node_tests_1  | -- installing ["@aws-sdk/client-s3@3.363.0"]
node_tests_1  | -- running test "node test/instrumentation/modules/@aws-sdk/client-s3.test.js" with @aws-sdk/client-s3
node_tests_1  | /app/test/instrumentation/modules/@aws-sdk/client-s3.test.js:276
node_tests_1  |       t.equal(errors[0].parent_id, failingSpanId, 'error is a child of the failing span from getObjNonExistantObject')
node_tests_1  |                         ^
node_tests_1  | 
node_tests_1  | TypeError: Cannot read properties of undefined (reading 'parent_id')
node_tests_1  |     at Object.checkApmServer (/app/test/instrumentation/modules/@aws-sdk/client-s3.test.js:276:25)
node_tests_1  |     at done (/app/test/_utils.js:331:26)
node_tests_1  |     at ChildProcess.exithandler (node:child_process:394:7)
node_tests_1  |     at ChildProcess.emit (node:events:513:28)
node_tests_1  |     at maybeClose (node:internal/child_process:1100:16)
node_tests_1  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by trentm** [comment]
Changelog: https://github.com/aws/aws-sdk-js-v3/blob/main/CHANGELOG.md#33630-2023-06-29

This entry seems a potential candidate:

```
clients: use migrated [@smithy](https://github.com/smithy) packages (https://github.com/aws/aws-sdk-js-v3/issues/4873) ([d036e2e](https://github.com/aws/aws-sdk-js-v3/commit/d036e2e43cd33cfd497871f97dde907c3078b2fd))
```

**Comment by AndKiel** [comment]
I'm not sure if directly related to your test failures but the upgrade of elastic-apm-node from 3.45.0 to 3.47.0 broke S3 interactions like generating pre-signed URLs, throwing:

```
Cannot read properties of undefined (reading 'hostname')
at (node_modules/elastic-apm-node/lib/instrumentation/modules/@aws-sdk/client-s3.js:155)
```

Using client-s3 version 3.332.0.

**Comment by trentm** [comment]
@AndKiel Thanks for reporting! I've opened https://github.com/elastic/apm-agent-nodejs/issues/3464 because I'm pretty sure this is a separate issue. I asked there if you could show some code that is hitting this, to help me repro.
