### ISSUE TITLE
Trying to hide Next.JS `/.next` request path but it still appears as `/_next`

### ISSUE THREAD

**Issue by khteh** [elastic/apm-agent-nodejs#3463]
**Describe the bug**
I try to hide transaction path `/.next` Next.JS distribution folder using
```
  transactionIgnoreUrls: [
    '/health/*',
    '/_next/*',
    '/robots.txt'
  ],
```
OR:
```
  ignoreUrls: [
    /^\/health\//i,
    /^\/[._]+next\//i,
    /^\/robots.txt/
  ],  
```
but it appear as `/_next/*` in the Kibana APM page. How can I hide it? Thanks.

**To Reproduce**

Steps to reproduce the behavior: 
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**

**Environment (please complete the following information)**

- OS: [e.g. Linux] Ubuntu
- Node.js version: 20.2
- APM Server version: 8.8.0
- Agent version: 3.45.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Agent config options: 
<details>
  <summary>Click to expand</summary>

```
replace this line with your agent config options
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
replace this line with your dependencies section from package.json
```
</details>

**Comment by david-luna** [comment]
Hi @khteh 

Elastic APM agent cannot instrument Nextjs apps by calling `agent.start()` and need to be done in a different way

There is [documentation](https://www.elastic.co/guide/en/apm/agent/nodejs/current/nextjs.html) explaining how to instrument Nextjs. As a summary you
- should use the 3rd option of instrumentation `-r elastic-apm-node/start-next.js`
- need to have a file named `elastic-apm-node.js` at the root of the project to set the configuration

I've created a [repo](https://github.com/david-luna/elastic-nodejs-agent-nextjs) for testing purposes. You can have a look at this particular [commit](https://github.com/david-luna/elastic-nodejs-agent-nextjs/commit/edcbcc04cd1bc22c76b5d0135afc3ce3747120a3) which adds instrumentation with the configuration you gave which works :)

**Comment by khteh** [comment]
It's not a entirely Next.JS but it involves Express and SPDY: https://github.com/elastic/apm-agent-nodejs/issues/3413

**Comment by khteh** [comment]
This is NOT fixed. Why is this closed?
