### ISSUE TITLE
attempt update to elastic-apm-node@4 in Kibana

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#3556]
Kibana uses elastic-apm-node and is in TypeScript. Attempting to PR to update Kibana to v4 would be a good exercise to get a feel for the impact of the breaking changes that we *do* have. If it is too painful, then we might reconsider some of the changes.

**Comment by trentm** [comment]
David's start at this is here: https://github.com/elastic/kibana/pull/165483

**Comment by david-luna** [comment]
PR https://github.com/elastic/kibana/pull/165483 merged last week. We can close this issue
