### ISSUE TITLE
Custom error properties not shown

### ISSUE THREAD

**Issue by AdriVanHoudt** [elastic/apm-agent-nodejs#358]
**Describe the bug**
Opbeat used to copy over error properties to custom or at least show the extra properties in the extra tab.
Now they are being logged under `error.exception.attributes` but not shown in the custom tab on the errors page in Kibana.
Is there a way to get this functionality back? This is super useful info when fixing errors.

**To Reproduce**
```
const error = new Error('oops');
error.usefulExtraProp = 'all the data';
apm.captureError(error);
```

**Expected behavior**
see top

**Environment (please complete the following information)**
- OS: mac (any)
- Node.js version: 8
- APM Server version: don't know
- Agent version: 1.5.4

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by AdriVanHoudt** [comment]
I can manually copy over the properties from `payload.exception.attributes` to `payload.context.custom` in a filter but that feels hacky :D

**Comment by AdriVanHoudt** [comment]
Ok I did just 
```js
if (item.exception && item.exception.attributes) {
    item.context.custom = item.exception.attributes;
}
```
was less hacky then predicted :D

**Comment by watson** [comment]
Yeah, I agree it would make a lot of sense to show this data. I'm glad you found a workaround for now, but I'll make sure to raise this with the UI team so we can look into what can be done.

cc @elastic/apm-ui

**Comment by alvarolobato** [comment]
@elastic/apm-ui can you have a look at this request?, please.

**Comment by sqren** [comment]
@alvarolobato Let's discuss it at the next APM weekly, and prioritise it there.

**Comment by formgeist** [comment]
I've opened a design issue to add this to the Kibana APM UI https://github.com/elastic/kibana/issues/20664 to add the `attributes` object to the page, so we should be able to bring this in soon.
