### ISSUE TITLE
Default logger doesn't support %o

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#368]
Since switching from using the [debug](https://www.npmjs.com/package/debug) module to output debug information to using the normal logger, we have issues rendering logs correctly on versions of Node.js older than v8.4.0 (as this was the version that added support for `%o` and `%O`).

This is only a cosmetic issue though - but it would be nice if we could find a way around it.

Here's an example of a log entry in Node.js 8.4.0+

```
adding transaction to queue { id: '03b82970-7b0b-4886-a945-2fee2c2bacb0' }
```

In Node.js 6 and below the above log entry instead looks like this:

```
adding transaction to queue %o { id: '12c87952-70da-494b-9aec-113525b24ac5' }
```

**Comment by trentm** [comment]
Min supported node is v8.6.0 now. As well, we've moved to a pino logger.
