### ISSUE TITLE
FetchError sometimes when using elastic-apm-node

### ISSUE THREAD

**Issue by sibelius** [elastic/apm-agent-nodejs#3696]
**Describe the bug**

When enabling apm auto instrumentation with node-fetch@2.6.7

```
FetchError: request to https://webiste.com/api failed, at ClientRequest. <anonymous> (/usr/src/app/server.js:75:829901)
  at /usr/src/app/node_modules/elastic-apm-node/lib/instrumentation/ run-context/AbstractRunContextManager. js:95:49
at AsyncLocalStorage. run (node: async_hooks:346:14)
at AsyncLocalStorageRunContextManager.with /usr/src/app/node_modules/elastic-apm-node/Lib/instrumentation/run-context/AsyncLocalStorageRunContextManager. js:57:36)
at ClientRequest. wrapper /usr/src/app/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:23)
at ClientRequest.emit (node:events:523:35)
at at
ClientRequest.emit (node: domain:489:12)
ClientRequest. wrappedEmit [as
emit] (/usr/src/app/node_modules/elastic-apm-node/lib/instrumentation/http-shared.js:278:21)
at
TLSSocket.socketErrorListener (node:_http_client:495:9)
at
TLSSocket. emit (node:events:511:28)
at
TLSSocket.emit (node:domain: 489:12)
at at
emitErrorNT (node: internal/streams/destroy: 151:8)
emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node: internal/process/task_queues:82:21)
```

**To Reproduce**

Enable apm auto instrumentation with node-fetch@2.6.7

elastic-apm-node@3.49.0

Steps to reproduce the behavior: 
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**

**Environment (please complete the following information)**

- OS: [e.g. Linux] linux
- Node.js version: node 20
- APM Server version: elastic-apm-node@3.49.0
- Agent version: 7.17.0

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [x] Starting node with `-r elastic-apm-node/start`

**Additional context**

Agent config options: 
<details>
  <summary>Click to expand</summary>

```
replace this line with your agent config options
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
replace this line with your dependencies section from package.json
```
</details>

**Comment by david-luna** [comment]
Hi @sibelius 

I've setup a small script to try to reproduce the issue with the versions of `node-fetch` and `elastic-apm-node` you specified but I . This is the code snippet

```js
const http = require('http');
const fetch = require('node-fetch');

const server = http.createServer(function (req, res) {
  req.resume();

  req.on('end', function () {
    fetch('https://website.com/api')
      .then(res => res.text())
      .then(body => {
        res.writeHead(200, {
          server: 'example-trace-node-fetch',
          'content-type': 'text/plain',
          'content-length': Buffer.byteLength(body),
        });
        res.end(body);
      })
      .catch(err => {
        res.writeHead(500, {
          server: 'example-trace-node-fetch',
          'content-type': 'text/plain',
          'content-length': Buffer.byteLength(err.message),
        });
        res.end(err.message);
      });
  });
});

server.listen(3000);
```

Are you passing any other options than the URL to `node-fetch`? could you provide a small snippet for reproduction?
Worth to mention latest version is v4.1.0. Yo may want to update

**Comment by sibelius** [comment]
I think this is a bug on node-fetch or maybe node HTTP itself,  or some problem with DNS

tks
