### ISSUE TITLE
Does the "Sending error to Elastic APM: %o'" message need to be INFO level?

### ISSUE THREAD

**Issue by pmuellr** [elastic/apm-agent-nodejs#3748]
This message has been showing up in Kibana logs for a while now, and is fairly noisy.

https://github.com/elastic/apm-agent-nodejs/blob/5930659c01aee75348b31ec48d1d762fccfe43fc/lib/agent.js#L729

Checking some serverless overview logs, over 1 hr I see 488K messages, 64K of which are that message - 13%.

Should this be changed to debug?  Or via some other mechanism only shown when explicitly desired?

**Comment by amd032** [comment]
I was thinking about exactly the same thing last week.
It would be great to have it on debug level.

**Comment by trentm** [comment]
I agree that this can be changed to "debug" level.
