### ISSUE TITLE
ESM instrumentation/hooking fails with Node.js v18.19.0

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3784]
Out CI stated failing recently in the `test` action only for node v18 on a specific test script `tests/instrumentation/fixtures/use-knex-pg.mjs`.
https://github.com/elastic/apm-agent-nodejs/actions/runs/7161350478/job/19496836227

The error reveals that the script is ran twice and a racing condition occurs when creating the database in `postgres`. The reason behind this double load seem to be a backport (from v20) of the loading process of modules.
https://github.com/nodejs/node/pull/44710

We can reproduce with a small project
```
// package.json
{
  "name": "iitm-double-load",
  "version": "1.0.0",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "import-in-the-middle": "^1.5.0"
  }
}
```
```
// file index.mjs
import { isMainThread } from 'worker_threads';

console.log('index module is loaded!!!', isMainThread);
```

You can see the module is loaded in the main and also in a worker thread
```bash
NODE_OPTIONS="--experimental-loader=import-in-the-middle/hook.mjs" NODE_NO_WARNINGS=1 node ./index.mjs
index module is loaded!!! false
index module is loaded!!! true
```

**Comment by trentm** [comment]
workaround in ^^
The correct fix is an update of IITM with a fix.

**Comment by trentm** [comment]
IITM v1.6.0 was *just* released to fix this:
```
 '1.6.0': '2023-12-11T17:01:48.278Z'
```

So I guess we could have just waited an hour. :)

**Comment by david-luna** [comment]
IITM fix in https://github.com/DataDog/import-in-the-middle/pull/44
