### ISSUE TITLE
Agent environment not set correctly from NODE_ENV in 4.3.0

### ISSUE THREAD

**Issue by SergioPRAyscom** [elastic/apm-agent-nodejs#3807]
**Describe the bug**

After updating from elastic-apm-node v4.1.0 to v4.3.0, the APM environment in production is set to "development".

**To Reproduce**

1. Set NODE_ENV to "production" or start the application with this variable set.
3. Then print the value of NODE_ENV and check that it is "production".
2. Then initialize the agent using agent.start(), and print the value of the agent environment calling agent.getServiceEnvironment(), it is "development".
3. Now if we instead use agent.start({ environment: process.env.NODE_ENV }), and then call agent.getServiceEnvironment(), we get "production".

**Expected behavior**

The default environment value for the agent is the value of NODE_ENV, so the expected result in step 2 should be "production".
https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#environment

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 18
- APM Server version: not applicable
- Agent version: 4.3.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Agent config options:
<details>
  <summary>Click to expand</summary>

```
ELASTIC_APM_SERVICE_NAME=xxxx
ELASTIC_APM_SERVER_URL=xxxx
ELASTIC_APM_ACTIVE=true
ELASTIC_APM_LOG_UNCAUGHT_EXCEPTIONS=true

{
  logLevel: process.env.NODE_ENV === 'development' ? 'info' : 'off',
  useElasticTraceparentHeader: true
}
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
    "elastic-apm-node": "^4.0.0",
```
</details>

**Comment by trentm** [comment]
Just from the description, it sounds like this could have been introduced in v4.2.0: https://www.elastic.co/guide/en/apm/agent/nodejs/4.x/release-notes-4.x.html#release-notes-4.2.0

I'll start looking.

**Comment by trentm** [comment]
I can repro. 

I don't think it was the https://github.com/elastic/apm-agent-nodejs/pull/3679 change that was in 4.2.0, however.


This was broken in v4.2.0 by https://github.com/elastic/apm-agent-nodejs/issues/3807. 
Repro:

```
% cat badenv.example.js
var apm = require('./').start({
  serviceName: 'badenv',
  logLevel: 'warn'
});
console.log('XXX environment:', apm._conf.environment);

% NODE_ENV=yo node badenv.example.js
XXX environment: development
```

That should output `XXX environment: yo`.

My guess is that the config refactor in that change made it so `apm._conf.environment` was always defined (using 'development' as a default). It used to be that it was undefined after initially setting `apm._conf`, then the `process.env.NODE_ENV` default was applied **in the apm-client**:

```
% rg NODE_ENV
lib/apm-client/http-apm-client/README.md
59:- `environment` - Environment name (default: `process.env.NODE_ENV || 'development'`)

lib/apm-client/http-apm-client/index.js
256:    this._conf.environment = process.env.NODE_ENV || 'development';
```

If that's the case, then one option is to:
- move that default handling using `process.env.NODE_ENV` up into "config/schema.js"
- *remove* the `NODE_ENV` usage in lib/apm-client/...

PR coming.

**Comment by trentm** [comment]
@SergioPRAyscom Thanks for the issue!
