### ISSUE TITLE
Memory usage reported incorrectly in k8s pod

### ISSUE THREAD

**Issue by birladeanuadrian** [elastic/apm-agent-nodejs#3854]
**Describe the bug**
The `system.process.memory.usage` is reported incorrectly when apm runs inside a process in a k8s pod. The pod is limited to 250MB of memory, but reported memory is 11GB. This is because the memory is retrieved from the files `/proc/meminfo` and `/proc/self/stat`. A better way to retrieve memory statistics is from `/sys/fs/cgroup/memory/memory.usage_in_bytes`. It might be a possibility to add a configuration to apm so that it reads statistics either from `/proc` or from `/sys/fs/cgroup/memory`.

**To Reproduce**

1. Deploy an application with apm enabled from code in a k8s pod with a sidecar inside an on-premises cluster 
2. Check statistics and see memory usage

**Expected behavior**
Memory usage is 50MB, not 11GB.

**Environment (please complete the following information)**

- OS: debian bulleseye-slim
- Node.js version: 18, 20
- APM Server version: 7.17.2
- Agent version: 4.3.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

**Comment by trentm** [comment]
Hi @birladeanuadrian. Thanks for the issue.



> The `system.process.memory.usage`

Do you mean `system.process.memory.rss.bytes` (https://www.elastic.co/guide/en/apm/agent/nodejs/current/metrics.html#metric-system.process.memory.rss.bytes) or perhaps `system.process.memory.size`? The Node.js APM agent doesn't report a metric named `system.process.memory.usage`.

* * *

Using `/sys/fs/cgroup/memory` might require some defensiveness. Testing in a `kind` k8s cluster on macOS there isn't such a dir:

```
~ # ls /sys/fs/cgroup/memory
ls: /sys/fs/cgroup/memory: No such file or directory
~ # ls /sys/fs/cgroup
cgroup.controllers        cpu.stat                  hugetlb.2MB.rsvd.max      memory.reclaim
cgroup.events             cpu.weight                io.bfq.weight             memory.stat
cgroup.freeze             cpu.weight.nice           io.latency                memory.swap.current
cgroup.kill               cpuset.cpus               io.max                    memory.swap.events
cgroup.max.depth          cpuset.cpus.effective     io.stat                   memory.swap.high
cgroup.max.descendants    cpuset.cpus.partition     memory.current            memory.swap.max
cgroup.procs              cpuset.mems               memory.events             pids.current
cgroup.stat               cpuset.mems.effective     memory.events.local       pids.events
cgroup.subtree_control    hugetlb.2MB.current       memory.high               pids.max
cgroup.threads            hugetlb.2MB.events        memory.low                pids.peak
cgroup.type               hugetlb.2MB.events.local  memory.max                rdma.current
cpu.idle                  hugetlb.2MB.max           memory.min                rdma.max
cpu.max                   hugetlb.2MB.numa_stat     memory.oom.group
cpu.max.burst             hugetlb.2MB.rsvd.current  memory.peak
```

I found https://github.com/docker/for-mac/issues/6118 but I haven't read through it. I see mention of cgroupsv1 vs cgroupsv2, but I'm not sure if that is a relevant difference.

Do you happen to know of an authoritative reference for `/sys/fs/cgroup/memory`?

I found https://stackoverflow.com/questions/50865763/memory-usage-discrepancy-cgroup-memory-usage-in-bytes-vs-rss-inside-docker-con as well that seems to discuss the differences in various ways to get memory info. I haven't read through this yet, either.

**Comment by trentm** [comment]
Ah... our APM agents already have a spec for report cgroup memory metrics: https://github.com/elastic/apm/blob/main/specs/agents/metrics.md#cgroup-metrics

And we have this (sadly languishing) issue to implement those in this agent: https://github.com/elastic/apm-agent-nodejs/issues/1813

So I believe this issue is effectively a duplicate (and vote for) #1813.

**Comment by trentm** [comment]
I'll resolve this as a duplicate, and I've made a node to discuss adding #1813 to upcoming planning.
