### ISSUE TITLE
error.exception.message not truncated

### ISSUE THREAD

**Issue by MartinKolarik** [elastic/apm-agent-nodejs#390]
**Describe the bug**
Not sure if this is by design but `error.exception.message` is not truncated which creates problems when it's too long (e.g. [knex](https://knexjs.org/) includes the whole SQL query in the message).

**Expected behavior**
I'd expect it to be truncated like other fields.

**Environment (please complete the following information)**
- OS: Linux
- Node.js version: 8
- APM Server version: 6.2.4
- Agent version: 1.6.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by watson** [comment]
`error.exception.message` isn't a keyword field, so that's why we don't need to truncate it. What kind of issues are you seeing?

**Comment by MartinKolarik** [comment]
It is displayed in the APM Errors dashboard which doesn't work very well when the message is a few megabytes of text. I guess it could be solved on the Kibana side though, by displaying only the first N characters.

**Comment by jalvz** [comment]
my 2c:
If we only had the dashboards, I'd say truncate in apm-server. But some users might chose a different output (eg Kafka) and/or they might want to consumer the data differently, and they might not want us to  truncate too aggressively.
 So I think we should truncate in apm-server to something reasonable from a data processing perspective (a few Mbs is reasonable I think, but not a few Gbs) *and* truncate it further in the UI to something reasonable for displaying.

**Comment by roncohen** [comment]
I agree with @jalvz. I would make the default truncation even shorter (2kb for example) in order to try to conserve disk/memory resources if you have a long message in a frequently happening error. It's important that the limits be configurable though.

**Comment by MartinKolarik** [comment]
I think "length" is fine, it means bytes everywhere in JS unless explicitly stated otherwise.

**Comment by watson** [comment]
This has now been released in version 1.8.0 of the Node.js Agent.

By default error messages will be truncated to 2048 bytes, but you can control the max length using [`errorMessageMaxLength`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#error-message-max-length)

**Comment by MartinKolarik** [comment]
It is still going to be truncated further in the UI, right?

**Comment by watson** [comment]
I've opened an issue in the APM Server repo (as that's where the dashboards live)  to make sure this gets fixed: https://github.com/elastic/apm-server/issues/1021
