### ISSUE TITLE
TAV failing for `tedious@15.1.3`

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3926]
`tedious@15.1.3` is using a feature not supported in Node v14. 

```
node_tests-1  | -- installing ["tedious@15.1.3"]
node_tests-1  | -- running test "node test/instrumentation/modules/tedious.test.js" with tedious (env: {})
node_tests-1  | /app/node_modules/@azure/core-rest-pipeline/dist/commonjs/policies/multipartPolicy.js:99
node_tests-1  |             boundary ??= parsedBoundary;
node_tests-1  |                      ^^^
node_tests-1  | 
node_tests-1  | SyntaxError: Unexpected token '??='
node_tests-1  |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
node_tests-1  |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
node_tests-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
node_tests-1  |     at Module.load (internal/modules/cjs/loader.js:979:32)
```

Ref: https://github.com/elastic/apm-agent-nodejs/actions/runs/8354734062/job/22868580858#step:3:364

**Comment by david-luna** [comment]
```bash
npm info tedious time

...
  '15.1.1': '2022-11-01T14:49:39.714Z',
  '15.1.2': '2022-11-09T13:13:18.399Z',
  '15.1.3': '2023-02-12T23:20:33.835Z',
  '16.0.0': '2023-04-07T20:42:21.850Z',
  '16.1.0': '2023-05-07T16:50:04.608Z',
...
```

it's weird that didn't fail before

**Comment by trentm** [comment]
Tedious v15 has this:

```
$ cat node_modules/tedious/package.json
...
  "engines": {
    "node": ">=14"
  },
...
  "dependencies": {
    "@azure/identity": "^2.0.4",
    "@azure/keyvault-keys": "^4.4.0",
```

`@azure/core-rest-pipeline` is a transitive dep of both of those azure packages.
The failure started for us as of @azure/core-rest-pipeline@1.5.0 (released '2024-03-13T23:11:24.832Z'):

```
% npm install @azure/core-rest-pipeline@1.15.0
% rg -g "*" '\?\?='
...
node_modules/@azure/core-rest-pipeline/dist/commonjs/policies/multipartPolicy.js
99:            boundary ??= parsedBoundary;
```

I believe that `??=` syntax was in the core-rest-pipeline source code in earlier versions -- added in `commit 1691bef2d0 - [core] core-rest-pipeline multipartPolicy (#27487) (4 months ago)` -- but wasn't in the released build until https://github.com/Azure/azure-sdk-for-js/pull/26238, which was first released in v1.15.0.

I'd say `@azure/identity@2.x` is no longer maintained (the current major is 4.x, the last 2.x release was `'2.1.0': '2022-07-09T03:42:35.373Z'`). As of that core-rest-pipeline@1.15.0 the `"engines": { "node": ">=12.0.0" },` suggestion is broken.

It looks like some (many? all?) `@azure/...` npm packages are dropping support for older Node.js versions without bumping major versions. And they have range deps on other `@azure/...` deps that do it... so there is no longer-term way to use a `@azure/...` package as a dependency that is safe against dropping Node.js versions without using a package-lock to forever pin transitive deps.

**Comment by trentm** [comment]
This same breakage happens to tedious@13 and tedious@14 as well.
Effectively those tedious versions are all now `node >=16` -- and might be `node >=18` now or at some point, given that many of the `@azure/...` packages now have `"engines": {"node": ">=18"},`

**Comment by trentm** [comment]
I would think this would break tedious@12 as well, because it deps on the same version of azure/core-rest-pipeline:

```
└─┬ tedious@12.3.0
  ├─┬ @azure/identity@1.5.2
  │ ├─┬ @azure/core-client@1.9.1
  │ │ └── @azure/core-rest-pipeline@1.15.1 deduped
  │ └── @azure/core-rest-pipeline@1.15.1
  └─┬ @azure/keyvault-keys@4.8.0
    ├─┬ @azure/core-http-compat@2.1.1
    │ └── @azure/core-rest-pipeline@1.15.1 deduped
    └── @azure/core-rest-pipeline@1.15.1 deduped
```

However the tests are passing with node v14 for it. I'm not sure why.
I guess tedious@12 and/or azure/identity **v1** do not hit that code path.

In *general* I would say that all versions of tedious going back to tedious@11 -- when a dep on `@azure/identity` was added -- now cannot be relied upon to work with node <18... and perhaps that keeps moving up as newer versions of `@azure/...` packages drop support for Node.js versions without a major version bump.
