### ISSUE TITLE
Any plans to support hyper-express please?

### ISSUE THREAD

**Issue by zurmokeeper** [elastic/apm-agent-nodejs#4040]
Any plans to support hyper-express please?

**Comment by trentm** [comment]
@zurmokeeper Thanks for the issue. Currently, no, we don't have plans to add direct instrumentation for hyper-express.

One option might be to consider using our (currently in alpha) OpenTelemetry-based APM agent -- https://github.com/elastic/elastic-otel-node/tree/main/packages/opentelemetry-node -- and look into writing your own OpenTelemetry instrumentation for hyper-express.  However, granted that writing your own OpenTelemetry instrumentattion would be a significant learning curve.

**Comment by zurmokeeper** [comment]
@trentm Thanks for the reply, I'll try to see if I can get elastic-apm-node to support hyper-express directly first?

**Comment by trentm** [comment]
> I'll try to see if I can get elastic-apm-node to support hyper-express directly first?

Yes, it should be possible, so you could try that.

**Comment by trentm** [comment]
Closing, as I think the question is answered.
