### ISSUE TITLE
"active" config not being respected when the agent is started with -r or top level import

### ISSUE THREAD

**Issue by csnate** [elastic/apm-agent-nodejs#4112]
**Describe the bug**

The [active](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#active) config value is not being respected when it's set to "false" if I start the agent with the [require start module](https://www.elastic.co/guide/en/apm/agent/nodejs/current/starting-the-agent.html#start-option-require-start-module) or the [-r opt](https://www.elastic.co/guide/en/apm/agent/nodejs/current/starting-the-agent.html#start-option-node-require-opt) and I use the [agent config file](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuring-the-agent.html#agent-configuration-file) to load the configuration. All of the other options are correctly being used (data is getting to the apm server, service name and environment are set, etc.) but if I set `active: false`, Elastic APM is still recording data.

If I use the [require and start](https://www.elastic.co/guide/en/apm/agent/nodejs/current/starting-the-agent.html#start-option-require-and-start) way to start the agent, then it looks like the `active` flag is working as expected.

**To Reproduce**

1. Use this config
elastic-apm-node.js
```
module.exports = {
  active: false,
  serverUrl: "https://apm.my-server.com",
  serviceName: "my-service"
  environment: "development"
};
```
2. Then call `node -r elastic-apm-node/start.js app.js`
3. Then do some actions that would send data to Elastic APM
4. See that data is still getting reported to Elastic APM

**Expected behavior**

No data is sent to Elastic APM when `active: false` when started with "require start module" or "-r opt"

**Environment (please complete the following information)**

- OS: Linux Alpine/Docker
- Node.js version: 20.15.0
- APM Server version: 8.10.2
- Agent version: 4.7.0 or 8.10.2 if you mean the Elastic Server Agent?

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [X] Requiring `elastic-apm-node/start` from within the source code
- [X] Starting node with `-r elastic-apm-node/start`

**Additional context**

Agent config options: 
<details>
  <summary>Click to expand</summary>

```
{
  active: false,
  serverUrl: "https://apm.my-server.com",
  serviceName: "my-service"
  environment: "development"
}
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
"elastic-apm-node": "4.7.0"
```
</details>

**Comment by csnate** [comment]
I think I've found the issue - https://github.com/elastic/apm-agent-nodejs/blob/main/lib/config/schema.js#L879

1. Before this [line 862](https://github.com/elastic/apm-agent-nodejs/blob/main/lib/config/schema.js#L862) the options are read in from the file, so `fileOpts['active'] = false;`
2. Line 879, the check isn't going to pass because `fileOpts[def.name]` would evaluate to false, and then `def.fileValue` does not get set to `false`
3. Then when [the Config is constructed](https://github.com/elastic/apm-agent-nodejs/blob/main/lib/config/config.js#L131-L137), the default value for `active` will "win out" since it is set and the `fileOpts.active` value is not set.
4. Also, the reason it DOES work when passing the config into `apm.start({...})` is because that config object gets assigned to Config after the defaults, so the value would be `active: false` correctly.

The fix would be to change that check on line 879 to be `typeof fileOpts[def.name] !== "undefined"`. Wouldn't hurt to do the same thing on line 876 in case an environment variable was set to false as well.

If I get some time next week I can fork and submit a PR

**Comment by csnate** [comment]
can anyone look at the PR? It's pretty straightforward

**Comment by david-luna** [comment]
@csnate thanks for the elaborated issue report and the PR. I've already added my feedback in it :)
