### ISSUE TITLE
get span "type": "ext.http.http"    req.body  and res.body

### ISSUE THREAD

**Issue by wanglong167** [elastic/apm-agent-nodejs#414]
get span "type": "ext.http.http"    req.body  and res.body

**Comment by watson** [comment]
Thanks for opening an issue 😃

Do you want the request and response body to be stored on spans of type `ext.http.http`?

**Comment by wanglong167** [comment]
@watson  Yes or you can customize span additional data

**Comment by wanglong167** [comment]
implementation  Zipkin Features

**Comment by watson** [comment]
Ok, makes sense 😃 

What do you mean with "implementation Zipkin Features"?

**Comment by wanglong167** [comment]
Can the next version be added?

**Comment by wanglong167** [comment]
Whether other redis can also add execution commands
For example span.setReqContext({statement: redisreq, type: 'rediscmd-req'})
span.setResContext({statement: redisres, type: 'rediscmd-res'})

**Comment by wanglong167** [comment]
@watson

**Comment by watson** [comment]
I unfortunately don't know when this can be added. There's current no support for something like this in the APM Server API, but we're looking into adding more meta data to spans in general and this feature will fall right into the that category.

**Comment by watson** [comment]
Since version 2.1.0 of the agent it has been possible to [add tags to spans](https://www.elastic.co/guide/en/apm/agent/nodejs/current/span-api.html#span-set-tag). I'll close this issue now
