### ISSUE TITLE
Custom AsyncHooks code for Node.js 11+?

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#416]
We can simplify our code a little when this commit is included in a release (probably in Node.js 11.0.0): https://github.com/nodejs/node/pull/20894

The hooks added in [lib/instrumentation/async-hooks.js](https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/async-hooks.js) can be simplified as shown below if we don't need to worry about the `TIMERWRAP` type:

```diff
   function init (asyncId, type, triggerAsyncId, resource) {
-    // We don't care about the TIMERWRAP, as it will only init once for each
-    // timer that shares the timeout value. Instead we rely on the Timeout
-    // type, which will init for each scheduled timer.
-    if (type === 'TIMERWRAP') return
-
     transactions.set(asyncId, ins.currentTransaction)
   }

   function destroy (asyncId) {
-    if (!transactions.has(asyncId)) return // in case type === TIMERWRAP
     transactions.delete(asyncId)
   }
```

**Comment by Qard** [comment]
We'll need to continue to use those to support older versions of Node.js, so we can't do anything with this for a really, really long time. Node.js 10 LTS doesn't reach end-of-life until April 2021. Should we just close this?

**Comment by watson** [comment]
What I meant with this was that we could have an alternative code path to use two different `init` and `destroy` functions depending on the Node.js version. That would hopefully make the code a tiny, tiny bit more performant on Node.js 11+

**Comment by Qard** [comment]
I think the native <-> js barrier hop would have vastly more impact on the execution time than an `if (condition) return`. 🤔

**Comment by trentm** [comment]
Given we are using AsyncLocalStorage rather than the async_hooks.createHook for context tracking in recent-enough node versions:

```js
const nodeSupportsAsyncLocalStorage = semver.satisfies(process.versions.node, '>=14.5 || ^12.19.0')
```

I think we can close this issue.
