### ISSUE TITLE
[META 882] Check classic and OTel agents against serverless

### ISSUE THREAD

**Issue by obltmachine** [elastic/apm-agent-nodejs#4167]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/882
- Spec issue: https://github.com/elastic/apm/issues/883

**Comment by trentm** [comment]
Note: the equiv issue for the OTel distro/agent is https://github.com/elastic/elastic-otel-node/issues/305

**Comment by trentm** [comment]
I tested a simple example script against a serverless deployment

```
cd apm-agent-nodejs
npm ci
cd examples/

export ELASTIC_APM_SERVER_URL="...REDACTED serverless endpoint URL..."
OTEL_EXPORTER_OTLP_HEADERS="Authorization=ApiKey a1Q0REDACTEDdLdjJGZw=="' \
    node trace-undici.js
```

It worked:

![Screenshot 2024-07-30 at 12 46 17 PM](https://github.com/user-attachments/assets/1fd200c0-b05c-48c0-b86b-69a842e394e2)
