### ISSUE TITLE
Should we continue to list Node.js 8.2.0+ support as experimental?

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#424]
The `async_hooks` module in Node core is still marked as experimental, but we use it instead of patching Node core when running Node.js version 8.2.0 or higher (though it was technically available in v8.1.0?!?).

Though it's marked as experimental it will not write a warning to stderr or stdout when required (as all other experimental modules does). This is because APM vendors simply have no other option than to use this module to get fully functional context propagation across async boundaries.

We do however still warn about this on our [compatibility page](https://www.elastic.co/guide/en/apm/agent/nodejs/current/compatibility.html):

![image](https://user-images.githubusercontent.com/10602/42080245-54c71f78-7b82-11e8-88c3-e89af2fa37b4.png)

There is however no known stability issues related to using Async Hooks. The only downside is a larger overhead, especially when making heavy use of async/await. So maybe our warning is a bit too much and should be toned down?

**Comment by Qard** [comment]
Well, there's been discussion about rewriting it deprecate the use of the destroy hook. It is, as yet, a bit unknown if that will result in significant changes. I'm therefore a little bit wary of removing the experimental notice.

**Comment by watson** [comment]
Hmmm that's true. But on the other hand, Node version 8 is LTS and it just seems odd that we don't officially support an LTS release. As far as I know the other APM vendors that do use Async Hooks do it without showing any warnings about it. At least from [what I've been able to find](https://blog.newrelic.com/2017/11/08/node-8-async-await-support/).

**Comment by alvarolobato** [comment]
We are going to reword the note, removing the "experimental" situation of the support, but keeping the warning about the possible changes to Async Hooks by node.js

**Comment by bmorelli25** [comment]
Looks like the solution @alvarolobato proposed on July 17 was never implemented. Are we still on board with this? If so, I can make the change.

**Comment by alvarolobato** [comment]
@bmorelli25 Yes, that's the case. Thanks
