### ISSUE TITLE
Self Signed Certificate in certificate chain error when installing apm agent for node

### ISSUE THREAD

**Issue by hemant-elastic** [elastic/apm-agent-nodejs#439]
Getting the below with npm 6.1.0, node 10.6.0
**npm install elastic-apm-node --save**
_npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://registry.npmjs.org/elastic-apm-node failed, reason: self-signed certificate in certificate chain_

Workaround: This fixes it -> npm config set strict-ssl false

**Comment by watson** [comment]
This seems to either be an issue with your network or with npm it self.

After some googling it looks like [one explanation](https://stapp.space/fight-with-2/) is that you're behind a corporate proxy that is terminating the ssl connection.

I would strongly recommend however not having strict ssl verification off permanently as it leaves you open to Man In The Middle attacks.

To just switch off strict ssl for a single command, you can prefix the command with `npm_config_strict-ssl=false`, eg:

```sh
npm_config_strict-ssl=false npm install elastic-apm-node --save
```

I'll close this issue for now, but if you feel it hasn't been answered satisfactory, feel free to reopen 😺
