### ISSUE TITLE
Aggregated transactions on APM dashboard when using express.Router

### ISSUE THREAD

**Issue by drefined** [elastic/apm-agent-nodejs#443]
Similar routes will be aggregated into same group of transactions on the APM dashboard view when using express.Router aka "mini-app"s only when the application is minified.

For example:
catRoutes and dogRoutes have a router.get('/', ...);

app.use('/cats', catRoutes);
app.use('/dogs', dogRoutes);

After requesting /cats/ and /dogs/, the APM dashboard will display "GET /" which includes both transactions with the proper urls displayed in the transaction sample.

I believe the expected behavior should display "GET /cats/" and "GET /dogs" separately.

- OS: Linux
- Node.js version: 8.11.3
- APM Server version: 6.3.1
- Agent version: 1.8.2
- I am calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)

**Comment by watson** [comment]
Yes, we do support nested routes in Express. So I think they should show up as you expect. I'll have a look and see why they are not.

**Comment by drefined** [comment]
@watson It does work before I bundle it up for production. I'm using webpack's UglifyJsPlugin and including the source map.

**Comment by watson** [comment]
@drefined do you mind sharing your webpack config and the command you use to run webpack?

**Comment by drefined** [comment]
webpack --display-error-details --config webpack/server.config.js

server.config.js:
```
const path = require('path');
const webpack = require('webpack');
const webpackNodeExternals = require('webpack-node-externals');

module.exports = {
    target: 'node',
    node: {
        __dirname: true,
    },
    devtool: 'source-map',
    context: path.resolve(__dirname, '..'),
    entry: {
        server: [
            'babel-polyfill',
            './app.js',
        ],
    },
    output: {
        path: './',
        filename: 'server.js',
    },
    externals: [webpackNodeExternals()],
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    cacheDirectory: true,
                    presets: ['env'],
                }
            },
        ],
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            parallel: true,
            cache: true,
            ie8: false,
            safari10: false,
            compress: {
                comparisons: false,
                drop_console: false,
            },
            output: {
                beautify: false,
                comments: false,
            },
        }),
    ],
};
```

**Comment by p-j** [comment]
Hi, if I may share something that may or may not be related, we just figured out that some of our endpoints didn't show up on our dashboards.

We had routes define like so:
```js
const express = require('express')
const router = express.Router()
router.get('/path', (req, res, next) => {
```
this one wasn't showing up, we changed the definition to
```js
const express = require('express')
const router = express.Router()
router.route('/path').get((req, res, next) => {
```
and this one is showing up.

It seems the problem affected only `.get('/path', callback)` definitions as `.post('/path', callback)` where handled correctly.

For consistency sake we updated all our definitions to `router.route('/path').<method>` and all is good now.

**Comment by Qard** [comment]
Just investigating this a bit. It seems sub routers _can_ be mounted in parameterized paths but don't actually receive the parameters from the parent.

```js
router.get('/:bar', (req, res) => {
  console.log(req.params) // includes 'bar' but not 'foo'
  res.end('done')
})
app.use('/:foo', router)
```

What we _could_ do is use `req.baseUrl + req.route.path` to build the full name. The base would be the filled in fragment, rather than the token form. ie: in a request to `/:a/:b` as `/foo/bar`, the result would be `/foo/:b`. Does that seem like a good enough approach, given that the nested parameterization doesn't appear to be a properly supported feature?

**Comment by watson** [comment]
> The base would be the filled in fragment, rather than the token form

That could leave to an explosion of unique transaction names, so I'd advice against it. We already have a pretty complicated set of hooks into the Express router, so I think it should be possible to hack together something that preserved the original route on a temporary property similar to `baseUrl` until we needed it.

**Comment by Qard** [comment]
That gets complicated with router nesting, and probably unnecessary, since there's not really any _practical_ reason to use tokenized paths in the parent router since it won't be passed into the child router in any way. 🤔

**Comment by watson** [comment]
So you're suggesting that we draw a line in the sand so to speak and just use the `baseUrl` because it's essentially a "misuse" of how to configure routes? I guess we could do that - and if we don't hear any negative feedback we can assume users are ok with it?

**Comment by Qard** [comment]
Yeah, that was my thinking. We can take the more complicated route though too, if you prefer. It would just take some more state management to make that possible.

**Comment by watson** [comment]
@roncohen as this is related to grouping, I would just like to hear your 2 cents on this. Should we go with the easy solution that in some edge cases might resolve in way to many groups, or should we put in more time to find a proper way to resolve the name of the parent route (eg `'/users/:id' + '/foo'` vs `'/users/42' + '/foo'`)

**Comment by roncohen** [comment]
I suggest we start with the simple solution.

**Comment by Qard** [comment]
This seems to only apply to express 4.0 through 4.5. Express 4.6+ already works fine.

**Comment by watson** [comment]
The fix for this have now been released in version 2.6.0

**Comment by descampsk** [comment]
Hello,
I don't know if I have to open a new issue but when i use routers, I don't have the parent name in the transaction name.
For example : 

```
#app.js 
var app = require('express')()  
var users = require('./users)  
app.use('/users', users)  
```

and 

```
#users.js    
let router = Router()
router.route('/:id').get(getUserById)
```

The transaction name is GET /:id/ instead GET /users/:id.

Do you know what i'm doing wrong ?

I use : 
- express 4.17.1
- elastic-apm-node 2.11.5

Thank you very much !

**Comment by watson** [comment]
@descampsk please open a new issue, then I'll be happy to look into it 😃

**Comment by descampsk** [comment]
Ok I do that. Thanks

**Comment by panand13** [comment]
i am using swagger for defining API endpoints and i see same issue of unknown  endpoint, can some help me on this?
