### ISSUE TITLE
Drop support for inline config options?

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#453]
Today it's possible to configure the agent either using environment variables, a config file or inline config options, the latter of which are passed to the start function:

```js
require('elastic-apm-node').start({
  // inline config options
})
```

If it wasn't for the inline config options, the user would not have to call `start()` explicitly. It also adds a potential delay between requiring the agent and configuring it. This means that it's possible to get a hold of the agent in an un/half-configured state, eg:

```js
const agent = require('elastic-apm-node')

// The agent isn't fully configured at this point

agent.start({...})
```

This means that we have to gracefully handle situations where users interact with parts of the agent that isn't ment to do anything before it's started. By eliminating the use of inline config options, users would just have to start the agent by doing this:

```js
require('elastic-apm-node')
```

But they would then be required to either create a config file or configure the agent using environment variables. So it's a bit less user-friendly for people just trying out the agent for the first time.

**Comment by watson** [comment]
@Qard @roncohen what do you think about this?

I'm not necessarily for this my self, but I would like to hear your point of view.

**Comment by trentm** [comment]
This is pretty old and I'm not (personally, naively) convinced. Closing for now. We can re-open if someone is keen on it again.
