### ISSUE TITLE
mysql is not instrumented but mongodb is

### ISSUE THREAD

**Issue by AJCStriker** [elastic/apm-agent-nodejs#459]
**Describe the bug**
The MySQL module instrumentation appears to be defective as the MongoDB instrumentation delivers results into Kibana but the MySQL module cannot be seen.

**To Reproduce**
1. Install the APM on Node in the normal way
2. Use Express and have a handler execute both SQL and Mongo
3. Observe SQL is not instrumented and Mongo is

**Expected behavior**

**Environment (please complete the following information)**
- OS: Mac OS X
- Node.js version: 9.2.0
- APM Server version: 6.3.1 
- Agent version: 1.8.3

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**
Debugging the apm-agent library appears to show that .buildSpan is not working inside the MySQL instrumentation as the currentTransaction is not defined causing the check inside buildSpan to fail.

Mongo operating in the same transaction is able to function correctly with buildSpan being able to find a transaction.

Any help in resolving this issue would be appreciated.

**Comment by Qard** [comment]
That sounds like a context loss issue. Are you using anything else in the request? In particular, is there anything between the mongodb and mysql calls in the control flow of the request? Things that do queuing-like behaviour have the potential to cause context loss.

**Comment by Qard** [comment]
Closing as stale. If you have anything further to add, just leave a comment and I'll happily re-open.
