### ISSUE TITLE
Move configuration docs to separate page

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#473]
Today the different config options are listed together with the API docs. This makes them hard to navigate to as the right hand menu doesn't show the headlines in that depth. If we had a separate configurations page it would render more nicely. I also think that it would be more logical to link to instead of having it buried under the `apm.start()` docs.

**Comment by watson** [comment]
We need to check with the website team if we can do redirects easily from the old to the new documentation before implementing it

**Comment by watson** [comment]
@dedemorton do we have any process of redirecting anchor links in our doc pages? We're considering moving a whole group of headlines to it's own new page.

**Comment by dedemorton** [comment]
@watson We **cannot** redirect from anchored sections, like https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-start.

To set up redirects from one _page_ to another, we create a request in the website repo (here's [an example](https://github.com/elastic/website-www.elastic.co/issues/2915)).
