### ISSUE TITLE
Thoughts about module version restrictions and looking ahead

### ISSUE THREAD

**Issue by Qard** [elastic/apm-agent-nodejs#514]
So we currently have a module range escape hatch at the top of each instrumentation file and test file. This prevents the instrumentation from being applied on versions we have not yet tested support for.

What if we could configure that range externally somehow? Regular installs of the module would have the instrumentation limited to the versions we specifically support but we could have CI test against modules _ahead_ of our current range to spot breaking changes before we look at supporting them. It might also be worth considering if there's an advantage to testing against master of those modules.

**Comment by watson** [comment]
If CI ran the tests in the mode that allowed future versions, how would we then get notified that they pass and that we should update the version guard? Today I use the failing build from Greenkeeper as a reminder that we need to test and then update the allowed version range.

**Comment by Qard** [comment]
The greenkeeper approach is okay. I'm just thinking that leaves is with a short blank spot between when a x.0.0 version is released and when we get around to testing and releasing instrumentation for it. If we could spot breaking changes before the release, perhaps we could have instrumentation ready _before_ release? Just a thought.

As for how to notify, we can get emails from Travis about it, right?

**Comment by watson** [comment]
Summary of call:

### Running package version outside our official supported range

We should make it possible to overwrite the supported version range by using some form of config option.

The most minimal implementation would be a "loose mode" that would just remove the upper limit of all version ranges. A more detailed implementation however would allow users to change specific version ranges one by one, but that might not be important to support.

### Specify supported version ranges in a central location

If possible it would be nice if we could keep the supported package versions in a central file that was used to both generate the `compatibility.asciidoc` book, served as the source for the ranges in the `.tav.yml` file, and for was used as the source for the version check that happens inside `lib/instrumentation/modules/*`.

**Comment by Qard** [comment]
And for test escape hatches too. ;)

**Comment by alvarolobato** [comment]
We've reached an agreement on this one and will create an implementation issue.

**Comment by watson** [comment]
@Qard what should we call the config option to allow the unsupported versions of a package to be instrumented? I've not been able to come up with a meaningful short name. So fra the "best" I have is:

```
ELASTIC_APM_INSTRUMENT_UNSUPPORTED_VERSIONS=mssql,redis
```

**Comment by Qard** [comment]
Sounds like a reasonable name to me. I can't think of anything better off-hand. 🤷‍♂️

**Comment by watson** [comment]
Created #745 to implement this
