### ISSUE TITLE
Elastic APM caught unhandled exception: start_1.default is not a function using hapi 16.1

### ISSUE THREAD

**Issue by dhruv2204** [elastic/apm-agent-nodejs#518]
**Elastic APM caught unhandled exception: start_1.default is not a function**
I am using Hapi v16.1 with latest apm node agent. When calling the `start()` function, agent breaks with unhandled exception. 
After enabling logger, i can see that code is breaking after `shimming hapi.Server.prototype.initialize`
This is the error: `Elastic APM caught unhandled exception: start_1.default is not a function`
I am using `server.ext('onPreHandler', somefunction);` before starting hapi server. The hapi module in elastic-apm-node lib has some checks for hapi v>17, which checks for connection and `onPreAuth`
`onPreResponse`. Can this be of any problem?

**Expected behavior**
Using environment variables to set serviceName and apm-server host.

**Environment (please complete the following information)**
- OS: macOS for dev and Linux in production (tried on both)
- Node.js version: v10.5.0
- APM Server version: 6.3.2
- Agent version: 1.11.0

**How are you starting the agent? (please tick one of the boxes)**
- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [x] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**
Using with typescript.
`import apm from 'elastic-apm-node/start';`
`apm();`

- Agent config options
  <details>
    <summary>Click to expand</summary>

    ```
    export ELASTIC_APM_SERVICE_NAME=xyzserver
    export ELASTIC_APM_SERVER_URL=http://externalmachineip:8200
    export ELASTIC_APM_LOG_LEVEL=debug
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    "axios": "^0.17.1",
    "babel-runtime": "^6.26.0",
    "csx": "^8.5.0",
    "elastic-apm-node": "^1.11.0",
    "good": "^7.1.0",
    "good-console": "^6.2.0",
    "good-file": "^6.0.1",
    "good-squeeze": "^5.0.1",
    "hapi": "^16.1.0",
    "inert": "^4.1.0",
    "ioredis": "^3.2.2",
    "jsdom": "^11.5.1",
    "mobx": "^3.4.1",
    "mobx-react": "^4.3.5",
    "module-alias": "^2.0.3",
    "mz": "^2.7.0",
    "preact": "^8.2.7",
    "preact-compat": "^3.17.0",
    "promise-polyfill": "^6.1.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-facebook-login": "^3.0.1",
    "react-gpt": "^1.1.1",
    "react-router-dom": "^4.0.0",
    "typestyle": "^1.5.1",
    "uuid": "^3.2.1"
    ```
  </details>

**Comment by watson** [comment]
We support hapi v9.0.0 and above (see our [compatibility documentation](https://www.elastic.co/guide/en/apm/agent/nodejs/current/compatibility.html) for details).

I can see that you require `elastic-apm-node/start` but then try to call the returned value as a function. This is the problem. If you require `elastic-apm-node/start`, the returned value is the agent object and not the start function. The agent will at this point already be started and you don't need to manually start it. If you remove the `apm()` line it should be fixed 😃 

Bonus: You can even just start Node.js with the `-r elastic-apm-node/start` command line flag. This will take care of starting the agent for you without having to add it to your source code.

**Comment by watson** [comment]
Please let me know if you can get it working 😃

**Comment by dhruv2204** [comment]
Cool. Thanks. 
This did the trick. `-r elastic-apm-node/start`
Just one question, what if the apm-server is not reachable or is down. This should not crash the deployment in any way right?

**Comment by watson** [comment]
If the APM Server is not reachable, the agent will just log an error message using its logger. The data that it was attempting to send to the APM Server will be dropped (to not consume memory) and everything continues as normal.
