### ISSUE TITLE
API Schema tests are failing

### ISSUE THREAD

**Issue by Qard** [elastic/apm-agent-nodejs#519]
Seems like the schema files in the apm-server repo moved, so now our schema tests are failing.

**Comment by watson** [comment]
Seems like nothing changed. [A new file was added though](https://github.com/elastic/apm-agent-python/pull/270). Can it be related to that?

**Comment by Qard** [comment]
Yeah, I considered it, but it's not that. It seems like it might not even run the bash script, for some reason. 🤔
