### ISSUE TITLE
Implement duration config suffixes

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-nodejs#545]
For duration configs (e.g. ELASTIC_APM_API_REQUEST_TIME), we will support time units like 1ms, 1s, 1m. For pre-v2 config, we should allow suffixes, but also continue to allow no suffix and assume the previous unit (e.g. "ms" for min span duration). For v2+ config, we should require suffixes.

**Comment by watson** [comment]
Here's the options that are durations

Config option | Release | Default
--------------|---------|---------
`abortedErrorThreshold` | 1.x | 25s
`apiRequestTime` | 2.x | 10s
`flushInterval` | 1.x | 10s
`serverTimeout` | 1.x | 30s

We need to decide what should happen in 2.x when a suffix isn't given:

1. Should we ignore the given config value, output a warning, and fall back to the default value?
1. Should we throw an error?
