### ISSUE TITLE
Default value for transactionMaxSpans

### ISSUE THREAD

**Issue by simllll** [elastic/apm-agent-nodejs#555]
**Problem**
I have some long running transactions I track with APM. There are a lot of automatically collected spans, which caused memory issues in my application. This was pretty hard to track down, due to the reason that this somehow only happened on my production environment (more data, longer runnign processes). 

**Solution**
Therefore I suggest setting a default value for transactionMaxSpans. E.g. 30 should be enough for most use cases.

**Comment by Qard** [comment]
That would be a breaking change, but might be worth considering for v2.

@watson What are your thoughts on this?

**Comment by watson** [comment]
Actually all the other Elastic APM agents set the default value to `500`, so we should actually align with that.

It's a mistake that we haven't done so, and so you could consider this a bug. If we were to set this to a very small number (e.g. 30), I agree it might trip up some users and should be considered a breaking changes. But if we set it to 500, I thiiiink it's ok to do it in a patch release. But if someone disagrees I'm open to make it breaking.

**Comment by Qard** [comment]
Ah, I would accept it not being a breaking change, in that case. 👍

**Comment by watson** [comment]
The new default value of 500 will be part of our next release 😃

**Comment by simllll** [comment]
Greats thanks for the quick fix!
