### ISSUE TITLE
Increase maxQueueSize default to 500

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#563]
Currently the default is 100. All the other Elastic APM agents have set the default to 500 which might be a bit more reasonable.

Pros:
- Fewer HTTP requests to the APM Server

Cons:
- Larger HTTP bodies and longer JSON stringify times

**Comment by watson** [comment]
@Qard do you think we should do this?

**Comment by Qard** [comment]
Isn't it going away soon, with v2? Should we bother with it?

**Comment by Qard** [comment]
Yeah, if we get a spare moment between other things we could do it. Probably doesn't need to be very high-priority though.

**Comment by alvarolobato** [comment]
Agreed that this is going away in V2, not going to change it at this point.
