### ISSUE TITLE
Make apm.captureError() return error uuid

### ISSUE THREAD

**Issue by lenartbezek** [elastic/apm-agent-nodejs#573]
**The problem**
We pass uuids of internal errors through our client API, so that clients can trace and report them back to us. Because there is currently no way of getting the uuid that the agent assigns to errors, we have to add a tag with another uuid, that we can also pass with the error response.

**Preferred solution**
Having `apm.captureError()` return the assigned uuid through callback or directly.

**Alternatives considered**
Using tags with a different uuid.

**Comment by watson** [comment]
Great idea 😃 Yes it would make a great addition to expose the uuid in some way.

I think it's best to expose it via the callback as you also suggested and not hijack the return value. That way the function will remain easy to promisify if you want.

**Comment by lenartbezek** [comment]
The callback has a different purpose though; it is called after errors are successfully sent to APM. It doesn't seem right to have the application wait for the agent to finish sending errors just to get the uuid.

Perhaps a better solution is to just supply your own uuid through `opts` argument of `apm.captureError()`? Very trivial to implement as well.

**Comment by watson** [comment]
That might work as well - as long as it follows the format that we expect. Today that's uuid v4

**Comment by Qard** [comment]
That's changing in v2 though, and will be stricter, because of the need to inherit from the transaction context.

**Comment by watson** [comment]
Will the error id also change? I thought it was only transaction/span ids...

**Comment by Qard** [comment]
Good question. My PR currently replaces the id everywhere with id and traceId from the trace context, which has a different format. 🤔

**Comment by Qard** [comment]
Looks like the error id _does_ change. https://github.com/elastic/apm-server/blob/v2/docs/spec/errors/v2_error.json#L12

**Comment by watson** [comment]
This feature have been added and will be released in the next version soon. The callback will be called with the id as the 2nd argument.

**Comment by watson** [comment]
@lenartbezek this have now been released in v1.14.0
