### ISSUE TITLE
WebSocket instrumentation can't be disabled

### ISSUE THREAD

**Issue by chris-erickson** [elastic/apm-agent-nodejs#593]
**Describe the bug**
I updated the config to exclude WebSockets (`ws`) and it continues to appear in metrics.  We run puppeteer which uses WebSockets to communicate with the headless browser.

**To Reproduce**
1. Use code that utilizes websockets

**Expected behavior**
WebSockets should not emit spans when disabled.

**Environment (please complete the following information)**
- OS: node8:slim docker (Debian Jessie)
- Node.js version: 8.12.0
- APM Server version: Latest in AWS
- Agent version: 1.12.0

**How are you starting the agent? (please tick one of the boxes)**
- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [x] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**
Changes made in elastic/apm-agent-nodejs#353 never made it into the `ws` module.

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    module.exports = {
        serviceName: 'something',
        serverUrl: 'http://ourserver.com',
        disableInstrumentations: ['ws'],
        ignoreUrls: [
            '/health',
            /^\/css\//i,
            /^\/images\//i,
        ],
        active:
            process.env.NODE_ENV === 'production'
            && !(process.env.APM_DISABLED === 'true'),
    };
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    "aws-sdk": "2.313.0",
    "config": "2.0.1",
    "elastic-apm-node": "1.12.0",
    "joi": "13.6.0",
    "journalize": "2.0.0",
    "koa": "2.5.3",
    "koa-bodyparser": "4.2.1",
    "koa-response-time": "2.0.0",
    "koa-router": "7.4.0",
    "koa-static": "5.0.0",
    "lodash": "4.17.10",
    "nunjucks": "3.1.3",
    "nunjucks-moment-timezone-filter": "^1.0.1",
    "puppeteer": "1.8.0",
    "puppeteer-cluster": "0.11.2",
    "uuid": "3.3.2"
    ```
  </details>

**Comment by watson** [comment]
Thanks for reporting this issue. A fix will be included in the next version of the agent

**Comment by chris-erickson** [comment]
Amazing, thank you.
