### ISSUE TITLE
Consider adding `context.app.language` object

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#6]
The APM Server intake API [supports](https://github.com/elastic/apm-server/blob/5b5a89a0f348f991394dca5efe796abed725a080/docs/data/intake-api/generated/error/payload.json#L12-L15) a sending up language information:

```json
"language": {
  "name": "ecmascript",
  "version": "8"
}
```

Question is what we should put as `name` and `version`?

I guess it makes most sense to log the version of ECMAScript used, but question is how we extract this information from a Node process

**Comment by AdriVanHoudt** [comment]
You can basically hardcode it to the node version no? (see http://node.green/) 
You can also get to the v8 version with `process.versions.v8` but not sure if that helps.
Might be worth taking the harmony flag into account.

**Comment by watson** [comment]
Good point with the harmony flag. Theres unfortunately a lot of variables here. You're probably right that we have to hardcode most of this

**Comment by vanjacosic** [comment]
Update on this: 
When/if the `language.version` field is made optional, `language.name` can be implemented simply as `javascript` for now. See issue: https://github.com/elastic/apm-server/issues/247

We also talked about making the `language.name` field user configurable, so @watson should keep that in mind when implementing.
