### ISSUE TITLE
Investigate failing `tav` test on Jenkins

### ISSUE THREAD

**Issue by simitt** [elastic/apm-agent-nodejs#61]
Investigate failing `tav` tests on Jenkins.

```
                 -- running test "node test/instrumentation/modules/mysql/pool-release-1.js" with mysql
14:50:33 module.js:491
14:50:33     throw err;
14:50:33     ^
14:50:33 
14:50:33 Error: Cannot find module 'bignumber.js'
14:50:33     at Function.Module._resolveFilename (module.js:489:15)
14:50:33     at Function.Module._load (module.js:439:25)
14:50:33     at Function.Module._load (/app/node_modules/require-in-the-middle/index.js:22:24)
```

**Comment by watson** [comment]
This is an issue with the version of npm that ships with Node.js 8. If we downgrade it to npm version 4 and it will work. We would have the same issue on Travis if we didn't do this:

https://github.com/elastic/apm-agent-nodejs/blob/605219a1afcafa60bfc93e4b45e3d1611392f1c0/.travis.yml#L18-L23
