### ISSUE TITLE
instrumentation of apollo-server-*

### ISSUE THREAD

**Issue by danieljuhl** [elastic/apm-agent-nodejs#641]
When using `express-graphql` requests/transactions are grouped by query/mutation name, but this is not the case when using `apollo-server-express`, where transactions is simply grouped by the route.

It would be nice if transactions through `apollo-server-*` was grouped by query/mutation name.

I'm happy to help, but a little guidance on where to start would be nice.

**Comment by Qard** [comment]
It's probably just a matter of hooking into the http server handler it uses internally. You can see how `express-graphql` does it here: https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/express-graphql.js

Note that all the server has to do is mark on the transaction that it's a graphql route. The `graphql` instrumentation itself will set the transaction name automatically, if it sees that it is in a graphql transaction: https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/graphql.js#L118-L125

**Comment by danieljuhl** [comment]
@Qard Just created a PR (and working on getting all tests green). It looks like apollo-server-* doesn't play well with node v4, so I have not included testing for the module on node v4.

**Comment by watson** [comment]
Support for `apollo-server-express` will be released in the next version

**Comment by watson** [comment]
This how now been released i v1.14.0

**Comment by levanvunam** [comment]
Sorry but I can't manage to make the apm works with apollo-server-express. I'm using:
nodejs 10.07.00 
apollo-server: "^2.9.7",
apollo-server-express: "^2.9.7"
elastic-apm-node: "^3.1.0",

I can receive the data from the graphql project but it's all unknown route and no grouping
![image](https://user-images.githubusercontent.com/12594238/68975500-5f620a80-082e-11ea-95fe-e69e8a919a22.png)

Thank you

**Comment by axw** [comment]
@levanvunam please create a new post on https://discuss.elastic.co/c/apm. If you provide debug logs there, following https://www.elastic.co/guide/en/apm/agent/nodejs/current/troubleshooting.html#debug-mode, you may have a better chance of someone being able to spot the issue.

**Comment by levanvunam** [comment]
Thank you
I will create other thread
