### ISSUE TITLE
Proxy issue: unable to send the error to elastic server

### ISSUE THREAD

**Issue by vajnorcan** [elastic/apm-agent-nodejs#655]
I'd like to ask a simple question, how can I resolve the 
```Error: connect ECONNREFUSED <elasticserver>:<port>```

Yes, I'm behind the corporate proxy. 
All the other requests (outside the network) work ok.

Is there any chance to setup the proxy for the elastic server requests? What library is the elastic apm node using ? 
Thank you

**Comment by vajnorcan** [comment]
sorry, perhaps I wasn't clear enough, I'm trying to do a simple ```.captureError(..)``` but that ends with the error I've mentioned above. I've tried all the valid proxies and double checked the server and the port, but still no luck... Thank you

**Comment by watson** [comment]
I'm sorry if I'm misunderstanding the issue, but according to the issue description, it sounds like you've configured the agent to send data to Elasticsearch. Is that correctly understood?

If so, that's the problem. Sending data directly to Elasticsearch is not supported. Instead the agent should be configured to send data to an APM Server that you need to run separately from your Elasticsearch cluster.

**Comment by watson** [comment]
Ah hang on, I have probably misunderstood. When you write "elastic server", I guess you mean Elastic APM Server?

**Comment by vajnorcan** [comment]
Yep, that one :)) Look for me it's a new stack and all I've been told is the server and port to which they are logging from Python related scripts. I've developed a server in nodejs though and they wanted me to implement the logging that will send the messages to the Elastic APM Server (apparently). sorry for the confusion, I might get the terms wrong!

**Comment by watson** [comment]
Ah ok 😅 To answer one of your original questions: The Node agent uses the normal `http` and `https` modules from node core to communicate with the APM Server.

**Comment by vajnorcan** [comment]
great. will muck around those then thought I've tried all the possible combinations. these corporate proxies are nasty things for developers

**Comment by watson** [comment]
🤔 I think it should work fine across proxies though. The agent will simply take the `serverUrl` config option and append `/v1/errors` as the path.

The request it self is performed here:

https://github.com/elastic/apm-nodejs-http-client/blob/aced47e8d039aad27be4feca62457cda32d7c484/index.js#L58-L64
