### ISSUE TITLE
Only flush if the error being sent is an uncaught exception

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#686]
When a regular error is given `agent.captureError()`, there's no need to flush the queue. Just send it as any other event.

**Comment by trentm** [comment]
Note that after #2094 goes in, here is a patch to do this:

```diff
diff --git a/lib/agent.js b/lib/agent.js
index 1b7b7350..59b18473 100644
--- a/lib/agent.js
+++ b/lib/agent.js
@@ -457,11 +457,17 @@ Agent.prototype.captureError = function (err, opts, cb) {
       if (agent._transport) {
         agent.logger.info('Sending error to Elastic APM: %o', { id })
         agent._transport.sendError(apmError, function () {
-          agent.flush(function (flushErr) {
+          if (handled) {
             if (cb) {
-              cb(flushErr, id)
+              cb(null, id)
             }
-          })
+          } else {
+            agent.flush(function (flushErr) {
+              if (cb) {
+                cb(flushErr, id)
+              }
+            })
+          }
         })
       } else if (cb) {
         // TODO: Swallow this error just as it's done in agent.flush()?
```

## perf impact

Here is a *quick* look at perf impact. The scenario was running `node --prof ... pathosapp.js err` which is simple Express app with the root `/` endpoint basically doing `next(new Error('oof'))` and loadgen'ing that up to 500 req/s via `hey -c 50 -q 10 -z 60s http://localhost:3000/`.

### before

```
Latency distribution:
  10% in 0.0050 secs
  25% in 0.0090 secs
  50% in 0.0155 secs
  75% in 0.0218 secs
  90% in 0.0260 secs
  95% in 0.0286 secs
  99% in 0.0443 secs
```

#### after

```
Latency distribution:
  10% in 0.0046 secs
  25% in 0.0085 secs
  50% in 0.0146 secs
  75% in 0.0207 secs
  90% in 0.0249 secs
  95% in 0.0279 secs
  99% in 0.0429 sec
```

So there is some noticeable improvement in latency there, but should be validated with a bit more testing. In theory it should also improve efficiency in communication with APM server if the app is erroring with any appreciable rate.
