### ISSUE TITLE
Support for Fastify

### ISSUE THREAD

**Issue by KidkArolis** [elastic/apm-agent-nodejs#690]
I'm trying to use elastic-apm-node with https://www.fastify.io/ and it's showing up in Kibana as:

```
GET unknown route
```

Would be nice if the route was extracted correctly.

**Comment by watson** [comment]
We don't have support for Fastify yet. But it's coming very soon. If you're interested in following it closer, check out this PR: #594 

If you want to have better transaction names with Fastify before this PR lands, I recommend our documentation for how to instrument a custom framework - specifically the route naming section:
https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-stack.html#custom-stack-route-naming

You case by the way see a list of our supported frameworks here: https://www.elastic.co/guide/en/apm/agent/nodejs/current/supported-technologies.html#compatibility-frameworks

**Comment by vecernik** [comment]
+1

**Comment by watson** [comment]
Support for Fastify have just been released in version 2.6.0 of the agent. See more info here: https://www.elastic.co/guide/en/apm/agent/nodejs/current/fastify.html
