### ISSUE TITLE
Split span type into 3 fields: Type, Subtype and Action

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#713]
Implement support for this API change: https://github.com/elastic/apm-server/pull/1618

This involves changing this API:

```js
agent.startSpan([name][, type])
```

To this:

```js
agent.startSpan([name][, type][, subType][, action])
```

If the function is called with only 2 arguments, it's assumed that `type` is of the old dot-separated format `type.subtype.action`. In that case the agent should split on `.` and fill `type`, `subType` and `action` accordingly.

We should also add a new `span.setType(type[, subType][, action])` function. If the type is set via `span.type = '...'` it's assumed that it's in the old dot-separate format and should automatically be split like if `agent.startSpan()` is called only with the `name` and `type` argument.

**Comment by Qard** [comment]
What should the behavior be when only `type` is given, but it's not three segments long? Is that considered valid? If so, how do we handle that?

Some possibilities are:
- fill left-to-right
- fill right-to-left
- first is type, last is action, middle is subtype

In these scenarios, `foo` could be any of:
- `type: foo, subtype: undefined, action: undefined` <- left-to-right or type first, action last, subtype middle
- `type: undefined, subtype: undefined, action: foo` <- right-to-left

And `foo.bar` could be any of:
- `type: foo, subtype: bar, action: undefined` <- left-to-right
- `type: undefined, subtype: foo, action: bar` <- right-to-left
- `type: foo, subtype: undefined, action: bar` <- type first, action last, subtype middle

**Comment by watson** [comment]
I would expect left-to-right
