### ISSUE TITLE
[Feature request] use http2 to post agent data and add support for envoy

### ISSUE THREAD

**Issue by swift1911** [elastic/apm-agent-nodejs#717]
**Is your feature request related to a problem? Please describe.**
In huge Transactions,Use http2 to post agent data is higher performance 
Support Service Mesh gateway like Envoy.

**Describe the solution you'd like**
support http2 post agent data in node10, http2 api is stable
Add an option just like ServerName,and then add ServerName to http 1/2 headers Host/authority value like : 

curl -XPOST 'http://[ServerUrl]' -H 'Host: apm-server' -d 'xxx'
curl --http2   -XPOST 'http://[ServerUrl]' -H ':authority: apm-server' -d 'xxx'

**Comment by watson** [comment]
We currently use a single streaming long running HTTP/1.1 request, so I don't think changing to HTTP/2 would be a benefit in terms of performance.

To properly support HTTP/2, we would have to add HTTP/2 support to the APM Server intake API first, as it currently only supports HTTP/1.1.

If you don't mind, I'll close this issue for now. Feel free to open another issue on the [APM Server repo](https://github.com/elastic/apm-server) if you feel that you would still benefit from HTTP/2 support. Then we can continue the discussion there 😃
