### ISSUE TITLE
captureError() should accept tags in metadata

### ISSUE THREAD

**Issue by MartinKolarik** [elastic/apm-agent-nodejs#718]
**Is your feature request related to a problem? Please describe.**
If an error happens outside of a transaction, there is no way to add tags, because `setTag()` is a no-op in that case and `captureError()` supports passing additional `context` and `user` data, but not `tags`.

**Describe the solution you'd like**
```
captureError(error, {
    tags: {} // works the same way as .addTags()
})
```

**Comment by watson** [comment]
Turns out this is already possible the way it's described here, we just forgot to document it. I've created an issue to update the documentation: #932
