### ISSUE TITLE
GraphQL module throws error when it should return Promise.resolve

### ISSUE THREAD

**Issue by dpoetzschke** [elastic/apm-agent-nodejs#746]
**Describe the bug**
On our project we ran into the problem, that elastic-apm-node would break the working integration of graphql in our app.
Instead of returning a Promise.resolve() with an error object graphql() will throw an error when used with elastic-apm-node.

**To Reproduce**
1. query is wrong, not like fieldname is wrong but an additional ")" is entered
2. Then call graphql()

**Expected behavior**
GraphQL should still return a Promise.resolve() with an errors Object

**Environment (please complete the following information)**
- OS: OSX, Docker (Alpine image) and GKE
- Node.js version: 10.14.0
- APM Server version:  -
- Agent version:2.0.1

I am opening a PR that has been working for us.

**Comment by alvarolobato** [comment]
Fixed in https://github.com/elastic/apm-agent-nodejs/pull/747

**Comment by watson** [comment]
Fixed as part of v2.0.6
