### ISSUE TITLE
Document commit message guidelines

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#755]
The commit messages in this project should follow the [Conventional Commits spec](https://www.conventionalcommits.org/).

We have a linter that [validates](https://github.com/elastic/apm-agent-nodejs/blob/61bb1de189c65e632b3169e1909105812b63c7d3/package.json#L10) this, but our [CONTRIBUTING.md](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md) file doesn't document this, which makes it harder to contribute.

To validate your new commit message locally, run:

```
npm run lint-commit
```

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-agent-nodejs/pull/1541.
