### ISSUE TITLE
Restructure Configuration docs

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#758]
It would probably make sense to move the Configuration page above the Agent API page:

![image](https://user-images.githubusercontent.com/10602/50177284-e5659080-0301-11e9-80b8-e832595f9161.png)

The [Configuration page](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html) should also be updated to better stand on its own. It seems a little out of context currently - as it technically also is as it has been moved from being a sub-section under `apm.start()` - I.e. it doesn't currently say that you can pass the options to the `start()` function.

**Comment by bmorelli25** [comment]
Let's chat about this when you're back from vacation. To me, it seems like the Agent API needs to come first as it explains `apm.start()`. Perhaps we could nest configuration under Agent API?

**Comment by watson** [comment]
Nesting would work as well. The reason why I suggested to move it above `Agent API` was because that users normally would be interested in configuration first before wanting to learn more about the Agent API. But both works for me.

**Comment by bmorelli25** [comment]
Ahh yeah that's a good point. Let me play around with the text and see what I can come up with! I'll open a PR at some point this week and we can go from there
