### ISSUE TITLE
how to get the CPU and Memory usage of the server hosts the app living in

### ISSUE THREAD

**Issue by gedennis** [elastic/apm-agent-nodejs#76]
So excited to meet the fantastic tools!!  And I can catch the metrics of http requests. However I am still confused  how to catch the CPU and Memory usage of the agents hosts. Is there some way to get it?

**Comment by watson** [comment]
Hi @gedennis
We recommend that you use our [Metricbeat](https://www.elastic.co/products/beats/metricbeat) product for that 😃 Would that work?

**Comment by gedennis** [comment]
@watson Thx 4 ur answer, watson。That is a nice way to gather the metirc  by Metricbeat。 But I want to monitor the CPU and Memory by the application。 Does the apm-agent-nodejs support it ? or some way to walk around?

**Comment by watson** [comment]
@gedennis Got it. There unfortunately isn't much you can do your self about this right now as the Elastic APM protocol doesn't support it. But it is something we have discussed adding. Let's keep this issue open and I'll update it with the progress.

**Comment by gedennis** [comment]
@watson cannot wait for that feature !!!

**Comment by watson** [comment]
We've come a little further with the planning, so I now feel safe creating an issue keep track of this feature: #309

I'll close this issue.
