### ISSUE TITLE
Restructure how method signatures are documented

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#760]
Currently API method signatures are documented in several different ways throughout the agent documentation. We should go over it and align them all in a common format.

**Comment by bmorelli25** [comment]
This is a duplicate of https://github.com/elastic/apm-agent-nodejs/issues/925, which was closed in the following PRs:

* docs: add info about when API's were added #1000
* docs: fix 'added in' for span API docs #1397
* [docs] Standardize API reference #975
