### ISSUE TITLE
Custom transaction type for incoming GraphQL requests

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#765]
If we detect an incoming GraphQL request, we'll change the name of the transaction from say `POST /graphql` to `<query> (/graphql)` where `<query>` is the name of the GraphQL query. Example: `hello (/graphql)`.

We should consider changing the transaction type to `graphql` as well instead if the default `request`.

Update: We decided we want to do this

**Comment by sibelius** [comment]
this makes sense, as each query should be considered a different POST type

I think this is what apollo engine does

you can aggregate queries based on their name

**Comment by dobesv** [comment]
For me, at least, the APM node agent is already doing this.

**Comment by watson** [comment]
@dobesv do you mean that it sets the transaction name to the GraphQL query, or do you mean that it changes the transaction type to `graphql`?

**Comment by dobesv** [comment]
It shows it in the list of requests with the operation name:

![image](https://user-images.githubusercontent.com/327833/50787628-c9537000-126b-11e9-98a3-7fceea6ecdb8.png)

And in the timeline it breaks things out by top-level resolver:

![image](https://user-images.githubusercontent.com/327833/50787662-e25c2100-126b-11e9-86f4-096534ad3375.png)

**Comment by watson** [comment]
We only show the transaction type indirectly via the tab just below the query bar - called "Requests" in this screenshot:

![image](https://user-images.githubusercontent.com/10602/50791864-5c6bc480-12c3-11e9-80ad-2179a23eef50.png)

The tab "Requests" shows all transactions with the type "request", but if we changed the transactions created for GraphQL requests to have the type `graphql`, it would create a tab next to this one called "Graphql".

That would allow you to view the graphs and transactions for GraphQL requests separately from the graphs and transactions for non-GraphQL requests.

It would also allow you to make custom queries and dashboards targeted only GraphQL transactions.

**Comment by sibelius** [comment]
where in the code can we modify to support this?

**Comment by watson** [comment]
@sibelius inside this if-statement:

https://github.com/elastic/apm-agent-nodejs/blob/fe8ff8ac6c71a6a21ba7e0dd787e570e6655f498/lib/instrumentation/modules/graphql.js#L120-L127

If I recall correctly you just need to:

```js
trans.type = 'graphql'
```

**Comment by Qard** [comment]
Closed by #1245.
