### ISSUE TITLE
High Memory issue at version 2.6.0

### ISSUE THREAD

**Issue by ambika93** [elastic/apm-agent-nodejs#772]
Team,
I'm using 2.0.6 version. After activating apm on service, memory increases gradually. At start of service memory is around 2 GB, which increases to 8 GB after 3 days and so on.

I'm using all default configurations.
Node dependency as below:
"aerospike": "3.0.2",
"async": "^2.6.0",
"bitset.js": "~4.0.1",
"body-parser": "^1.14.1",
"commander": "^2.9.0",
"ejs": "^2.3.4",
"express": "~4.9.6",
"kafka-node": "^2.6.1",
"lodash": "~3.10.1",
"moment": "~2.10.6",
"morgan": "~1.3.2",
"mysql": "^2.10.2",
"newrelic": "~1.29.0",
"node-uuid": "^1.4.7",
"nodemailer": "0.7.1",
"on-finished": "~2.3.0",
"q": "^1.4.1",
"redis": "^2.4.2",
"request": "^2.69.0"
I'm using new relic but it is disabled currently.

**Comment by watson** [comment]
When you say that new relic is disabled, in what way do you mean? Are you still requiring the `newrelic` module or is it just in your dependencies but not required?

**Comment by ambika93** [comment]
It's just a dependency.

**Comment by watson** [comment]
Thanks 👍 

Are you able to reproduce the problem in a small test-application that you can share with us? It would help us a lot in debugging the problem.

**Comment by ambika93** [comment]
@watson I'll try to reproduce issue on small test application. For now, I'm sharing memory graph.
![memoryincrease](https://user-images.githubusercontent.com/24220092/50966210-498f0500-14fa-11e9-96b5-05523a39a79f.png)

**Comment by ambika93** [comment]
@watson I've taken heapdump at my service. And i found issue with async hooks. I'm using node 8.12.0. I disabled asyncHooks and testing. I will update same.

**Comment by watson** [comment]
@ambika93 Did you get a chance to upgrade to a newer version of Node.js to see if the issue went away?

**Comment by watson** [comment]
Closing for now due to lack of activity. Feel free to leave a comment if you want this to be reopened.
