### ISSUE TITLE
Transaction name is `${method} unknown route` in Koa

### ISSUE THREAD

**Issue by posquit0** [elastic/apm-agent-nodejs#781]
**Describe the bug**
Kibana APM UI shows all transaction name as `${method} unknown route`. I think it should be `${method} ${path}`. How should I fix?

**To Reproduce**
No configuration. Imported on the top of main script file.

**Expected behavior**
 I think it should be `${method} ${path}`.

**Environment (please complete the following information)**
- OS: Ubuntu 16.04 LTS
- Node.js version: 10.15.0
- APM Server version: 6.5.4
- Agent version: 2.1.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by watson** [comment]
We use the "unknown route" name when we can't integrate with the router that you use, and you don't manually call [`agent.setTransactionName()`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-set-transaction-name).

As listed on the [Supported Technologies page](https://www.elastic.co/guide/en/apm/agent/nodejs/current/supported-technologies.html#compatibility-frameworks), we only support `koa-router` for detecting Koa routes.

Which router do you use with Koa?

**Comment by posquit0** [comment]
Yes, I read almost documentations. I'm usi g `koa-router` latest version.

**Comment by watson** [comment]
One possibility could be that you're requiring the `koa-router` module prior to calling `start()` on the APM agent. This would mean that the agent isn't started in time to hook into the router (which need to happen when it's required).

If you start up your application with the environment variable `ELASTIC_APM_LOG_LEVEL=trace` it will output how it's configured and which modules it registers. If it doesn't list the `koa-router` among those, it means that it didn't detect it, which most likely means that it was required before `start()` was called.

Can you check that?

**Comment by posquit0** [comment]
Thanks to your reply. My application's main file is `index.js`. This file calls `apm.start()` the first.

I found this issue is same with #782 . When I start with a command `node app` in the laptop terminal, it works well. Transaction had an expected name. SQL and Redis queries were collected.

However, when I built docker image based on `node:10.15.0-alpine`, it doesn't work as expected. Transaction had an unknown name. No collected SQL and Redis queries.

I don't know the reason yet.

**Comment by watson** [comment]
Are you using any sort of compilation step with for instance Babel or TypeScript that might mean that the code running in production is different from the code running locally?

**Comment by posquit0** [comment]
This is my `Dockerfile`. I think there is no difference. When I run the docker container in local, there is the same issue.

```dockerfile
### BASE
FROM node:10.15.0-alpine AS base
# Set the working directory
WORKDIR /app
# Copy project specification and dependencies lock files
COPY package.json yarn.lock ./


### DEPENDENCIES
FROM base AS dependencies
# Install dependencies for `node-gyp`
RUN apk --no-cache add --virtual builds-deps build-base python
# Configure NPM for private repositories
ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
# Install Node.js dependencies (only production)
RUN yarn --production
# Delete the NPM token
RUN rm -f .npmrc


### RELEASE
FROM base AS release
# Copy production dependencies
COPY --from=dependencies ./node_modules ./node_modules
# Copy app sources
COPY . .
# Expose application port
EXPOSE 7061
# In production environment
ENV NODE_ENV production
# Run
CMD [ "node", "app" ]
```

**Comment by watson** [comment]
I assume the `app` in the `node app` command refers to an `app.js` file located in the root of your project? My current hypothesis is that this file somehow starts the app differently when `NODE_ENV` is set to `production`. This seems to be the primary difference.

Would it be possible to share that file here?

**Comment by posquit0** [comment]
I have a directory `app/` and there is a main file `app/index.js` which I said above.

When I started `ELASTIC_APM_LOG_LEVEL=trace NODE_ENV=production node app`
```bash
adding hook to Node.js module loader
shimming http@10.15.0 module
shimming http.Server.prototype.emit function
shimming http.request function
shimming http.ServerResponse.prototype.writeHead function
shimming bluebird@3.5.3 module
shimming bluebird.prototype functions: [ '_then', '_addCallbacks' ]
shimming bluebird.config
shimming generic-pool@3.4.2 module
shimming generic-pool.PriorityQueue.prototype.enqueue
shimming mysql2@1.6.4 module
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
shimming koa-router@7.4.0 module
shimming koa-router prototype.match function
shimming https@10.15.0 module
shimming https.Server.prototype.emit function
shimming https.request function
```
when I started `docker run --rm -it -e ELASTIC_APM_LOG_LEVEL=trace -p 7061:7061 app` after building `docker build --force-rm -t app --build-arg NPM_TOKEN=${NPM_TOKEN}`:
```bash
adding hook to Node.js module loader
shimming http@10.15.0 module
shimming http.Server.prototype.emit function
shimming http.request function
shimming http.ServerResponse.prototype.writeHead function
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
shimming https@10.15.0 module
shimming https.Server.prototype.emit function
shimming https.request function
```

**Comment by posquit0** [comment]
This is a part of `app/index.js`. I still have no solution.

```node
#!/usr/bin/env node

'use strict';

// Load APM on production environment
const apm = require('elastic-apm-node');
// Start Elastic APM
apm.start({
  // Ignore requests to certain URLs from being instrumented
  ignoreUrls: [
    '/',
    '/spec'
  ],
  // Only activate the agent if it's running in production and apm server is set
  active: process.env.NODE_ENV === 'production' && !!process.env.ELASTIC_APM_SERVER_URL
});

const Koa = require('koa');
const bodyParser = require('koa-bodyparser');
const cors = require('@koa/cors');
const logging = require('@kasa/koa-logging');
const requestId = require('@kasa/koa-request-id');
const apmMiddleware = require('./middlewares/apm');
const responseHandler = require('./middlewares/responseHandler');
const logger = require('./logger');
const router = require('./routes');


const app = new Koa();
```

**Comment by watson** [comment]
This is very odd. Thanks for sharing the details. It seems like it never detects the call to `require` for any of the user-land modules. Only node core modules are detected. But I can't think of why this would be yet.

**Comment by watson** [comment]
I've prepared a version of the agent that shows more debug info that might help us figure out what goes on. You can install it by replacing the version number for the `elastic-apm-node` package in package.json with this one: `watson/apm-agent-nodejs#debug2` and run `npm install` again.

Then when you run the app, run it with the environment variable `DEBUG=require-in-the-middle`

**Comment by posquit0** [comment]
Thanks. I followed your guideline and made the result as [gist](https://gist.github.com/posquit0/ec7e2fbef6304c0a5a4ccfe8679c5b3d). `local.log` is from local terminal, `docker.log` is from running docker image.

Almost process is same, but `docker.log` has no `calling require hook` and `shimming` for `mysql2` and `koa-router`.

**Comment by watson** [comment]
Hmm or maybe I'm wrong about the `node_modules/node_modules`. Maybe it just looks like that because of another bug. Could you verify if that double nested `node_modules` folder exists inside the Docker image?

**Comment by watson** [comment]
Ah, I figured it out! I'm now able to recreate this locally.

In a temp directory, you can recreated it by doing the following:

```
mkdir node_modules
npm install koa-router watson/apm-agent-nodejs#debug2
cp -r node_modules tmp-node_modules
mv tmp-node_modules node_modules/node_modules
DEBUG=* node test.js
```

Where `test.js` contains the following:

```js
require('elastic-apm-node').start({serviceName: 'test'})
require('koa-router')
```

This will nest the `node_modules` folder inside it self which will trip up our algorithm.

**Comment by posquit0** [comment]
Wow! You're right. I found `./node_modules/node_modules` nested directory. After fixing `Dockerfile`, it works well. Thanks a lot! 👍

**Comment by sibelius** [comment]
I have a similar problem in our monorepo

@watson I've tried to install this version watson/apm-agent-nodejs#debug2

is there a way to debug require in the middle somehow?

**Comment by watson** [comment]
@sibelius the `require-in-the-middle` module uses the [`debug`](https://www.npmjs.com/package/debug) module for outputting debug info. So if you use the environment variable `DEBUG` you can get it to output debug information:

```
DEBUG=require-in-the-middle
```

**Comment by sibelius** [comment]
can we also suppport `@koa/router `, I think it is the same package, just new name
