### ISSUE TITLE
Node.js 0.12 CI issues

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#8]
Our dependency tests for Node.js v0.12 fail quite often on Travis CI.

The failure is always the same:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)
```
*https://travis-ci.org/elastic/apm-agent-nodejs/jobs/268019944*

It happens when the [test-all-versions](https://github.com/watson/test-all-versions) module tries to install a dependency for testing, i.e. before the actual test runs. This leads me to believe that it's the TCP connection to the npm registry that fails.

If we run the tests with [longjohn](https://github.com/mattinsler/longjohn) in an attempt to get a more meaningful stack trace, it looks like this (which isn't much help):

```
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)
---------------------------------------------
    at fireErrorCallbacks (net.js:458:15)
    at TLSSocket.Socket._destroy (net.js:497:3)
    at TCP.onread (net.js:561:17)
```
*https://travis-ci.org/elastic/apm-agent-nodejs/jobs/266829144*

I haven't been able to recreate this issue locally and I think it's related to the specific Linux or machine setup Travis is using for these tests combined with Node.js v0.12. I don't remember seeing these failures until after we switched on `sudo: required` in the .travis.yml file (was `sudo: false` previously).

I can't find any place where we or a dependency don't listen for the `error` event and this only happens in Node.js v0.12. This leads me to believe that it might actually be a bug in Node it self.

Possible options to solve this:
- Continue looking for the error to see if it's in user-land and fix it (maybe get some other eyes on this)
- Setup Travis to allow failures on Node.js 0.12 (I don't like this approach, as it would mean errors could sneak into our 0.12 support without us realising it)
- Don't test dependencies on Node.js 0.12 (we would still run the regular tests on Node.js 0.12 and we haven't seen this issue in these)
- Stop supporting Node.js 0.10 and Node.js 0.12 all together (these versions are no longer maintained or supported by the Node.js Foundation)
- Find a way to re-run the tests in Node.js 0.12 up to say 10 times until they pass
- Switch back to `sudo: false` (this might make the tests run at about half speed because the containerized setup on Travis isn't as fast)
- Stop using Travis all together and move all tests to the Elastic Jenkins cluster (and hope that Jenkins doesn't have the same issue as Travis)

**Comment by ruflin** [comment]
As a short term solution I would suggest to go with `Setup Travis to allow failures on Node.js 0.12` combine it with not supporting these versions especially from a commercial perspective as they are EOL. Not supporting does not mean we should not keep running the tests with it. Still having the tests around allows us to see when we actually introduce features which break on these versions. We also have test for OS in beats we do not commercial support and they are quite often red, but for us it's a best effort to keep it compatible.

**Comment by watson** [comment]
I'm a little afraid of allowing the tests to fail as that essentially would mean that we could start introducing bugs without knowing it. We wouldn't be able to remember to go and check every time the tests failed if it was because of Travis or because of a bug we introduced. 

If we stopped supporting 0.10 and 0.12, I would prefer to clean up the code to get rid of the pre v3 specific code. That would make the tests break right away in which case there isn't any reason to keep testing them.

But I actually forgot to add another possible solution: Stop using Travis and move the tests to the Elastic Jenkins cluster (I've updated the list above with this now).

**Comment by ruflin** [comment]
@watson In case removing 0.10 and 0.12 means you can clean up/simplify the code, I would probably remove the code. Are there strong reasons people have to stay on 0.10 or 0.12?

**Comment by watson** [comment]
@ruflin people still on 0.10 or 0.12 are only there because they haven't taken the time to upgrade yet. Unless they have some really obscure old binary dependencies that only work with those versions, I don't see any reason for them to stay expect that they don't want to touch an app that's running fine. There is some breaking changes, so they might need to make changes to their code if they use any of the [affected api's](https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4).

**Comment by watson** [comment]
Closing as support for Node.js <4 have been dropped. See #65
