### ISSUE TITLE
Not working v6.2.0

### ISSUE THREAD

**Issue by posquit0** [elastic/apm-agent-nodejs#813]
**Describe the bug**
APM agent always fail when agent send the transaction data. The error message says "context.request.url.port should be string or null"
```
I[#] S[#/allOf/0] allOf failed
I[#/context/request/url/port]
S[#/allOf/0/properties/context/properties/request/properties/url/properties/port/type] expected string or null, but got number
```

**To Reproduce**
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**
It works with `v2.1.0`

**Environment (please complete the following information)**
- OS: OS X
- Node.js version: 10.15.0
- APM Server version: 6.5.4
- Agent version: 2.2.0
- Koa version: 2.6.2
- Koa Router version: 7.4.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by watson** [comment]
Thanks for reporting. I'll make sure to release a fix right away

**Comment by watson** [comment]
Fixed in v2.2.1 that has just been released

**Comment by posquit0** [comment]
Thanks!

**Comment by watson** [comment]
I'll look into why this wasn't caught by our integration tests. It obviously shouldn't have slipped through.

**Comment by watson** [comment]
Note to self: It seems we'll allow port to be a number in APM Server 7.0.0: https://github.com/elastic/apm-server/pull/1813
