### ISSUE TITLE
APM Server transport error (400): Unexpected APM Server response APM Server accepted 0 events in the last request Error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "metricset#"   I[#] S[#/allOf/0] allOf failed

### ISSUE THREAD

**Issue by gate3** [elastic/apm-agent-nodejs#830]
**Describe the bug**
APM works well when running my app without docker but once i start the app in docker I get an error:

```javascript
APM Server transport error (400): Unexpected APM Server response
APM Server accepted 0 events in the last request
Error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "metricset#"
  I[#] S[#/allOf/0] allOf failed
    I[#/samples/system.process.cpu.total.norm.pct/value] S[#/allOf/0/properties/samples/patternProperties/%5E%5B%5E%2A%22%5D%2A$/properties/value/type] expected number, but got null
  Document: {"metricset":{"timestamp":1548853260277000,"tags":{"hostname":"96d3f45afe38","env":"development"},"samples":{"system.cpu.total.norm.pct":{"value":null},"system.memory.total":{"value":2096164864},"system.memory.actual.free":{"value":1151217664},"system.process.cpu.total.norm.pct":{"value":null},"system.process.memory.size":{"value":1100959744},"system.process.memory.rss.bytes":{"value":190550016}}}}
```

**To Reproduce**
1. Use this config '
const apmConfig = {
    serviceName: process.env.APP_NAME,
    serverUrl: process.env.APM_SERVER,
    secretToken: process.env.APM_TOKEN,
    logLevel: 'info',
}
'
2. Then call '
const apmObject = require('elastic-apm-node').start(apmConfig);
'
3. Then do ''

APM Server transport error (400): Unexpected APM Server response
APM Server accepted 0 events in the last request
Error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "metricset#"
  I[#] S[#/allOf/0] allOf failed
    I[#/samples/system.process.cpu.total.norm.pct/value] S[#/allOf/0/properties/samples/patternProperties/%5E%5B%5E%2A%22%5D%2A$/properties/value/type] expected number, but got null
  Document: {"metricset":{"timestamp":1548853260277000,"tags":{"hostname":"96d3f45afe38","env":"development"},"samples":{"system.cpu.total.norm.pct":{"value":null},"system.memory.total":{"value":2096164864},"system.memory.actual.free":{"value":1151217664},"system.process.cpu.total.norm.pct":{"value":null},"system.process.memory.size":{"value":1100959744},"system.process.memory.rss.bytes":{"value":190550016}}}}

**Expected behavior**
Expect the apm to work well with docker as it works without me using it 

**Environment (please complete the following information)**
- OS: Mac Osx
- Node.js version: v10.11.0
- APM Server version: 
- Agent version: 2.5.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by Qard** [comment]
It looks like the apm server your docker container is sending to needs an update.

**Comment by Guik** [comment]
Same issue. 

I'm using up to date alpha version official image:
docker.elastic.co/apm/apm-server:7.0.0-alpha2
docker.elastic.co/elasticsearch/elasticsearch:7.0.0-alpha2

Is apm-agent-nodejs compatible with alpha2 ?

**Comment by pbouda** [comment]
I get the exact same error, with version 2.6.0. I am using the images:

docker.elastic.co/apm/apm-server:6.6.2
docker.elastic.co/elasticsearch/elasticsearch:6.6.2

I am not really sure how to debug this, otherwise I would send more info...

**Comment by pbouda** [comment]
Btw, I am on Windows... Maybe a similar fix as above could be applied here...?

https://github.com/elastic/apm-agent-nodejs/blob/master/lib/metrics/platforms/generic/system-cpu.js#L35
