### ISSUE TITLE
50 percent depreciation in API performace while Using APM agent 

### ISSUE THREAD

**Issue by akki005** [elastic/apm-agent-nodejs#831]
Hi,

We are recently in a process of adding Elastic APM. But after Performance testing of API with APM agent throughput of API is reduced by 50%.

Throughput before adding APM agent - 15200/sec 
Throughput after adding APM agent - 8100/sec

APM-Agent configuration : 

```
  logLevel: 'info',
  serverTimeout: "10s",
  captureExceptions: true,
  sourceLinesErrorAppFrames: 5,
  sourceLinesErrorLibraryFrames: 0,
  captureErrorLogStackTraces: "messages",
  captureSpanStackTraces: false,
  stackTraceLimit: 15,
  transactionSampleRate:1,
  captureBody:false,
  instrument:true,
  disableInstrumentations:["redis","mysql"],
  transactionMaxSpans:50,
  apiRequestTime:"10s",
  apiRequestSize:"750kb"
```

We tried using different configurations but there wasn't much improvement in throughput.

Tried lowering `transactionSampleRate` ,`apiRequestTime` and `apiRequestSize`  but insignificant improvement.

Do we need to tune apm-server configurations?
Is there anything else need to be tuned in APM agent?

Please let me know if you need more info on this.

Thanks

**Comment by Qard** [comment]
Have you seen the [performance tuning](https://www.elastic.co/guide/en/apm/agent/nodejs/current/performance-tuning.html) guide? A transactionSampleRate of 1 is _definitely_ going to have a significant performance impact in a high-traffic environment. That should be tuned down significantly, depending on your scale. Stack traces and source lines also contribute significantly to the performance impact, so you can try turning those down/off.

May I ask what modules you are using in your app, and their versions? It would help to just copy/paste the contents of the dependencies block in your `package.json`.

**Comment by akki005** [comment]
@Qard Thanks for your time. 
As i have mentioned we tried lowering `transactionSampleRate` to 10%. but there was insignificant improvement. Next i will try  disabling **stack traces**.

dependencies in `package.json` :
```
{
    "async": "^1.4.2",
    "bunyan": "^1.5.1",
    "command-line-args": "^3.0.5",
    "couchbase": "^2.6.2",
    "cron": "^1.2.1",
    "debug": "^4.1.1",
    "elastic-apm-node": "^2.1.0",
    "elasticsearch": "^15.1.1",
    "ioredis": "^3.1.1",
    "joi": "^6.10.1",
    "lodash": "^4.0.0",
    "moment": "^2.10.6",
    "mysql": "^2.13.0",
    "pixl-xml": "^1.0.13",
    "redis": "^2.6.2",
    "redis-notifier": "^1.0.0",
    "request": "^2.79.0"
}
```
we are suing a [custom stack](https://www.elastic.co/guide/en/apm/agent/nodejs/0.x/custom-stack.html), so followed the instruction as provided on docs.

Thanks

**Comment by akki005** [comment]
I have moved this query to  [elastic discussion forum](https://discuss.elastic.co/t/50-percent-depreciation-in-api-performace-while-using-apm-agent/166509). so closing this.

**Comment by Qard** [comment]
10% of that amount of load is still 800 traces per second. That's _a lot_ of traces. Try 1% or less.
