### ISSUE TITLE
Transactions don't show SQL traces

### ISSUE THREAD

**Issue by airstofather** [elastic/apm-agent-nodejs#839]
**Describe the bug**
When looking at a transaction sample by clicking on a distribution bucket, we can only see the requests in the timeline, but we cannot see the Postgres queries. Also when clicking on a request in the timeline, the trace always points in the promise library, no matter what request we're looking at. Sample of trace:

```
node_modules/follow-redirects/index.js in RedirectableRequest._performRequest at line 186
node_modules/follow-redirects/index.js in RedirectableRequest at line 69
node_modules/follow-redirects/index.js in wrappedProtocol.request at line 363
node_modules/axios/lib/adapters/http.js in dispatchHttpRequest at line 141
in Promise
node_modules/axios/lib/adapters/http.js in httpAdapter at line 18
node_modules/axios/lib/core/dispatchRequest.js in dispatchRequest at line 59
in <anonymous>
internal/process/next_tick.js in _tickCallback at line 189
```

**Environment (please complete the following information)**
- OS: Ubuntu 18.04
- Docker version 17.03.3-ce, build e19b718
- Node.js version: v8.15.0
- APM Server version: 6.6.0
- Agent version: 2.5.0
- Sequelize version: 4.39.0
- pg version: 7.4.3

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Our ruby agent doesn't have this issue, thus we believe it's the node js agent (not the server).

**Comment by airstofather** [comment]
It was a misconfiguration issue which became obvious when added the ELASTIC_APM_LOG_LEVEL=true flag

**Comment by jamesmhaley** [comment]
Could you let us know what the misconfiguration was? Having the same problem.

**Comment by enigram** [comment]
@jamesmhaley I can't remember to be honest and I feel ashamed now for not including more details with my previous answer. Have you cranked up the verbosity level? Can you share the logs, maybe it will ring a bell.
