### ISSUE TITLE
Improve metrics docs

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#855]
The [metrics docs](https://www.elastic.co/guide/en/apm/agent/nodejs/current/metrics.html) are currently split over multiple html pages. It would make it easier to read if the sub-headlines were floated so that they all appeared on a single html page.

**Comment by watson** [comment]
I don't think we need to add http redirects as they have only been online for a were short while. So I don't expect anybody to be linking to them yet 🤞 cc @bmorelli25

**Comment by bmorelli25** [comment]
Yup, I agree. Pretty easy fix, will get this done when I save some down time.
