### ISSUE TITLE
Consider extracting metrics collection

### ISSUE THREAD

**Issue by rmdm** [elastic/apm-agent-nodejs#856]
Hi! I'm currently working on an alternative node.js agent https://github.com/rmdm/elastic-opentracing (I've started it mostly because I need more control on when and what to initialize and instrument). I'm going to add metrics collection support to it and as official module has already implemented it, I'd like to avoid reinventing the wheel and somehow to reuse it if possible. I'm not sure on the way in which it should be done though, wheter it should go with `elastic-apm-http-client` or in its own module, if at all. So I'd like to hear you thoughts on that :)

Btw, do you mind if I publish it under the `elastic-opentracing` name on npm?

**Comment by watson** [comment]
> Consider extracting metrics collection

Good idea. We already have this on the roadmap, but I don't know exactly when it will be released.

> I've started it mostly because I need more control on when and what to initialize and instrument.

We actually have an open issue to allow you to use the agent without auto-insturmentation: #627. This would then apply to [our OpenTracing bridge](https://github.com/elastic/apm-agent-nodejs-opentracing) as well. I assume this is what you're looking for?

ICYMI: You can already today use the [`disableInstrumentations`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#disable-instrumentations) config option to disable all automatic instrumentation. But it's not that easy to use for this purpose as there's no way to specify everything. Instead you have to specify a list of each module.

> I'm not sure on the way in which it should be done though, wheter it should go with `elastic-apm-http-client` or in its own module, if at all. So I'd like to hear you thoughts on that :)

If you make your own agent that doesn't inherit from this agent, I strongly recommend that you depend on `elastic-apm-http-client` for communication with the APM Server. This module takes care of a lot of the hard work keeping about keeping state, streaming data with a low overhead etc.

But as mentioned above, I actually think your specific use-case is better implemented as a config option in this agent.

> Btw, do you mind if I publish it under the `elastic-opentracing` name on npm?

I think it would be easily confused with our official OpenTracing bridge: `elastic-apm-node-opentracing`. So I would prefer if we could avoid it 😄

**Comment by rmdm** [comment]
Thanks for the thorough response.

> We actually have an open issue to allow you to use the agent without auto-insturmentation: #627. This would then apply to [our OpenTracing bridge](https://github.com/elastic/apm-agent-nodejs-opentracing) as well. I assume this is what you're looking for?

Maybe. Autoinstrumentation is only half of my concerns, and is the least important one. Intitialization is. I really don't like that any of my deps rule the way I organize things. At the same time, if the separation means that this strong 'require-it-first' requirement fades away, then yes, it is what I'm looking for.

> You can already today use the [`disableInstrumentations`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#disable-instrumentations) config option to disable all automatic instrumentation. But it's not that easy to use for this purpose as there's no way to specify everything. Instead you have to specify a list of each module.

Yeah, not the most convenient one to disable everything)

> If you make your own agent that doesn't inherit from this agent, I strongly recommend that you depend on `elastic-apm-http-client` for communication with the APM Server. This module takes care of a lot of the hard work keeping about keeping state, streaming data with a low overhead etc.

I've probably not put it well. I'm already using `elastic-apm-http-client` in my agent, and it works just fine) I meant that I'm not sure how to properly extract metrics collection from the official one and whether it should go with `elastic-apm-http-client` or as a separate module. In any case, I'm ready to help with such extraction if needed)

For now, thinking about all that, I just came up with a bit dirty hackish idea: to add official module as a dep and require metrics from it, like this:
```javascript
const Metrics = require('apm-agent-nodejs/lib/metrics')
```
hope it is legal)

> I think it would be easily confused with our official OpenTracing bridge: `elastic-apm-node-opentracing`. So I would prefer if we could avoid it smile

Ouch, ok, I'll try to come up with something different... :thinking:

**Comment by watson** [comment]
Would you be ok with doing context propagation manually? Today the agent keeps track of which transaction is the active transaction, so that at any time when you start a new span, that span will be associated with the active transaction. This can be a bit tricky to do unless you manually pass around a context object to containing the active transaction to all the places in your code where you want to start a new span.

**Comment by rmdm** [comment]
From the usage perspective I also expect my agent to be OpenTracing compatible, so that I can just switch specific implementation in my app root. So, yes, it is ok and expected for me to propagate context manually, if that context is a SpanContext in OT terms. Regarding possible mechanisms of the propagation, it is even possible to not pollute your business code with tracing-related code with just enough abstractions, as you know) Though, I'm not sure on enough)

**Comment by watson** [comment]
Ok great. It sounds to me like your use-case would be solved if we just added a config option to disable all automatic instrumentation and context propagation in the agent. That actually shouldn't be that hard to add. That way you could just use our OpenTracing support out of the box and get exactly what you're talking about.

That being said, we will of course still extract the metrics code into a separate module. But that's unrelated to this.

**Comment by rmdm** [comment]
Does that mean that with the option it is not anymore required to initialize the agent as the first thing in my app?

I'd be happy to contribute that, but I've looked through the code, and while the disabling instrumentation entirely seems pretty staightforward ([and looks like kinda already there](https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/index.js#L67)), the context propagation in the agent is blurry to me. So, I'll probably leave it to you :smile: For now I'm going to use my own implementation, and as it supports OpenTracing API it should not be hard to switch to the officially supported one when the time comes :smile:

**Comment by watson** [comment]
Correct. The only reason why it's a requirement to start the agent as the first thing in the app is so that it can hook into the `require` loader so that it can inject the code for automatic context propagation and so that in can inject the code for automatic instrumentation. Once those things are no longer a requirement, it can be started at any time.

I'll open an issue for adding this feature.

**Comment by rmdm** [comment]
Ok, Thank you for the discussion, I beleive I get even several options to go with. Closing this then.

**Comment by watson** [comment]
For reference, I've created two new issues to allow for this: #858 + #859
