### ISSUE TITLE
Custom Application Metrics

### ISSUE THREAD

**Issue by conord33** [elastic/apm-agent-nodejs#867]
I have just started using elastic stack for logs, tracing, and metrics. So far it has been working great! Nice work! 

It looks like the only thing missing so far is custom metrics... It looks like the apm-server now supports custom metrics, as well as the golang-agent. I am currently using the golang-agent to track some custom metrics and it works well.

Do you have an idea of when the node-agent will support custom metrics? It would be great to track things like user sign ups with it.

**Comment by Qard** [comment]
We don't have a specific timeline for it yet. We should be getting to it soon though.

**Comment by conord33** [comment]
Cool, I will keep an eye out for it 👍

**Comment by Qard** [comment]
I'll leave this open for now and update here when it gets released.

**Comment by conord33** [comment]
Thanks I appreciate it! 🙌

**Comment by conord33** [comment]
Any updates on this? 😀

**Comment by watson** [comment]
Yes, we're just putting the final touches on it an plan to release it this week or early next week. It was scheduled for the end of last week but got delayed as we found some issues related to CPU metrics on Linux

**Comment by conord33** [comment]
awesome! i look forward to using with it 👍

**Comment by watson** [comment]
Oh, actually. I got was too quick writing my reply. What I was referring to was what we internally call custom metrics. But it's basically language-specific metrics like Node.js Event Loop delay, Active Handles etc. But the release will not include an API for users to supply their own custom metrics like user-signup etc. Sorry about the confusion 😅

**Comment by conord33** [comment]
bummer... any idea when user defined metrics will be added?

**Comment by watson** [comment]
I don't know unfortunately - sorry for the false hope

**Comment by RenaudGelai** [comment]
> It looks like the only thing missing so far is custom metrics... It looks like the apm-server now supports custom metrics, as well as the golang-agent. I am currently using the golang-agent to track some custom metrics and it works well.

Hello, i'm interested in these "custom metrics" or "user-defined metrics". Is there an api documentation somewhere ? 

We currently have custom metrics, but our teams are uploading them through periodic logs that are then parsed and we'd like to make it more straightforward.

We are on version 7.0

Thanks in advance for your reply.

Best regards.

**Comment by sivachandran** [comment]
@conord33 I'm want to send custom metric to APM from golang app. Can you point me to a sample/documentation as you've already done?

Thanks in advance.

**Comment by conord33** [comment]
@sivachandran we use the prometheus exporter and wrap that with the elastic apm exporter.

```golang
import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"go.elastic.co/apm"
	"go.elastic.co/apm/module/apmprometheus"
)

...

apm.DefaultTracer.RegisterMetricsGatherer(
	apmprometheus.Wrap(prometheus.DefaultGatherer),
)

...
```

Our actual metrics get defined using this lib.

```golang
import "github.com/prometheus/client_golang/prometheus/promauto"

var (
	count prometheus.Counter
)

func init() {
	blockCount = promauto.NewCounter(
		prometheus.CounterOpts{
			Namespace: "nmspace",
			Subsystem: "subname",
			Name:      "count",
			Help:      "counts stuff",
		},
	)
}
```

Hope this helps!

**Comment by sivachandran** [comment]
Thanks @conord33.

**Comment by JoHuang** [comment]
I would like to monitor some custom number from node.js app. Still no way via `apm-agent-nodejs` ?
Or is there any to modify current system-only metrics? I can contribute if the path is clear.
thanks

**Comment by JoHuang** [comment]
Hi, I forked and add one public API for custom metrics, not sure if it's the direction to go or not.
https://github.com/JoHuang/apm-agent-nodejs/tree/custom-metrics

it looks like:
```
        apm.registerCustomMetric(
            "ws.connections",
            () => wss.clients.size
        );
```

And it will add a custom field `custom.ws.connections` to every build-in metrics data point.
FYI

@conord33 
Do you know what format does the custom metrics being sent? Are the metrics values included in system metrics data? Is there any official format for this?
Will APM page in Kibana automatically show your custom metrics, thanks

**Comment by axw** [comment]
@JoHuang that looks pretty good to me. I'd add an optional parameter for passing in labels, and I would also suggest not adding the "custom." prefix, so it could be used to bridge other metrics APIs without modifying names. You could of course still add it in your application code.

The metrics are sent with this format: https://www.elastic.co/guide/en/apm/server/current/metricset-api.html. e.g. something like this:

```json
{
    "metricset": {
        "tags": {"label_name": "label_value"},
        "samples": {
            "ws.connections": {
                "value": 123.0
            }
        }
    }
}
```

Metrics are stored in Elasticsearch like shown at https://www.elastic.co/guide/en/apm/server/current/metricset-indices.html. In the document you would have a field like `"ws.connections": 123.0`.

> Are the metrics values included in system metrics data?

Metrics with the same set of labels may be grouped together. If you don't label your metrics, they could end up in the same "metricset" sent to the APM Server, and in the same document in Elasticsearch.

> Will APM page in Kibana automatically show your custom metrics, thanks

Not at the moment. For now you'll need to create a separate dashboard, or use [Metrics Explorer](https://www.elastic.co/guide/en/kibana/current/metrics-explorer.html).

**Comment by JoHuang** [comment]
@axw Thanks for review. I'm a little bit confused, and would like to confirm :

> If you don't label your metrics, they could end up in the same "metricset" sent to the APM Server, and in the same document in Elasticsearch.

So document count won't increase to keep overhead as low as possible. If I add labels to the custom metrics, the metrics doc will be separated from apm build-in system metrics doc. Is that correct?

The "labels" you mentioned means the "dimensions" param in this function?
https://yaorg.github.io/node-measured/SelfReportingMetricsRegistry.html#getOrCreateGauge__anchor

> I'd add an optional parameter for passing in labels, and I would also suggest not adding the "custom." prefix, so it could be used to bridge other metrics APIs without modifying names.

To be sent within build-in metrics data, and not to have conflicts of document fields, I added "custom" prefix. Putting custom name in the 1st level of field in apm-defined doc does not feel right.
However, "custom" might be still possibly used by official team in the future anyway :p

The implement detail should be consistent to other language SDK, is there any official plan or official implement for this?

If I would like to send a PR for this, what's the next step should I do?
Thanks

**Comment by axw** [comment]
> So document count won't increase to keep overhead as low as possible. If I add labels to the custom metrics, the metrics doc will be separated from apm build-in system metrics doc. Is that correct?

That's correct.

> The "labels" you mentioned means the "dimensions" param in this function?

Yes. We call them labels in Elasticsearch/Elastic APM, so best to call it that in the API. Measured reporting is just an implementation detail.

> To be sent within build-in metrics data, and not to have conflicts of document fields, I added "custom" prefix. Putting custom name in the 1st level of field in apm-defined doc does not feel right.
However, "custom" might be still possibly used by official team in the future anyway :p

Fair point, but you could still have name collisions with multiple callers of `registerCustomMetric`. The built-in metrics are documented.

> The implement detail should be consistent to other language SDK, is there any official plan or official implement for this?
>
>
> If I would like to send a PR for this, what's the next step should I do?

Unfortunately there is no plan still, which is why there hasn't been much feedback so far. I think what you've done is consistent with long term goals, so I'd suggest going ahead and creating a PR following the [contributing guide](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md).

I think we should call this API experimental for now, to give a bit of flexibility to change or rename it without it being considered a breaking change.
