### ISSUE TITLE
express instrumentation causes "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by rodneyrehm** [elastic/apm-agent-nodejs#869]
**Describe the bug**

In an `express@4.16.4` application I would *occasionally* get the following error after adding `elastic-apm-node@2.5.1` into the mix:

```
RangeError: Maximum call stack size exceeded
    at arguments.(anonymous function) (…/node_modules/elastic-apm-node/lib/instrumentation/modules/express.js:1:1)
    at arguments.(anonymous function) (…/node_modules/elastic-apm-node/lib/instrumentation/modules/express.js:94:33)
    at arguments.(anonymous function) (…/node_modules/elastic-apm-node/lib/instrumentation/modules/express.js:94:33)
    […]
```

The instrumentation code assumes that `router.use()` would only ever take 2 arguments, so the instrumentation code [inserts itself as the third argument](https://github.com/elastic/apm-agent-nodejs/blob/6fb5c43e004fbd9160e8607c6bc1b18dbb7164a1/lib/instrumentation/modules/express.js#L49
). But [Router.use()](https://expressjs.com/en/4x/api.html#router.use) is variadic, accepting larger handler chains. This problem does not appear with [`app.use()`](https://expressjs.com/en/4x/api.html#app.use) being handed multiple handlers.

I was able to work around the issue by refactoring my code from

```js
const router = express.Router()
router.use('/path-alpha', sharedHandler, alphaHandler)
router.use('/path-bravo', sharedHandler, bravoHandler)
```

to

```js
const router = express.Router()
router.use(sharedHandler)
router.use('/path-alpha', alphaHandler)
router.use('/path-bravo', bravoHandler)
```

**Comment by watson** [comment]
Thanks for reporting this issue. I've not been able to reproduce the issue using the code you shared. Could you share a little more information about how often it occurs and if there's certain criterias that need to be present?

**Comment by rodneyrehm** [comment]
Hey @watson! I've tried building a reduced test case but failed. I tried a couple of combinations with modules (e.g. Sentry) and custom middlewares - but no luck. I'm closing this issue for lack of info and would reopen in the unlikely case of enlightenment.
