### ISSUE TITLE
socket.io long polling reported as "unknown route"

### ISSUE THREAD

**Issue by kesla** [elastic/apm-agent-nodejs#880]
**Describe the bug**
We're using socket.io and the long polling is reported as "unknown route" and since is's long polling it'll take up a ton of "impact".

<img width="1229" alt="screenshot 2019-02-27 at 17 53 58" src="https://user-images.githubusercontent.com/74128/53508974-24ab1d00-3abb-11e9-9524-b8fc281422c2.png">

**To Reproduce**
1. Install express & socket.io
2. Run the server

**Expected behavior**

Preferred here I think would be to simply ignore these requests until we've got #593 

**Environment (please complete the following information)**
- OS: Linux
- Node.js version: 10.11.0
- APM Server version: 6.6.1
- Agent version: 2.5.1

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by watson** [comment]
You should be able to use the [`ignoreUrls`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#ignore-urls) config option to filter this out. Would that work?

**Comment by kesla** [comment]
@walterra ooops, yes that should work! Sorry, totally missed it in the options. Will test tomorrow and report back!

**Comment by kesla** [comment]
That worked perfectly. Sorry about that.
