### ISSUE TITLE
Agent is running before the start function is called.

### ISSUE THREAD

**Issue by allanchau** [elastic/apm-agent-nodejs#887]
**Describe the bug**
I have a customised start function (example has been simplified)
```javascript
'use strict';

const apm = require('elastic-apm-node');

const start = () => {

    if (process.env.ELASTIC_APM_ACTIVE !== 'false') {

        apm.start();

    }

    return apm;

};

module.exports = { start };
```

I use kubernetes and from what I understand all environment variables have to be strings and should be converted in the app if you want it in a different format (boolean etc).

To get around this I specifically check for `process.env.ELASTIC_APM_ACTIVE !== 'false'` and don't call the start method.

The problem is even though the start method isn't called, apm will still log an error to the server.
```
logging error 3a397735-9dde-4f45-9b5e-212e88197336 with Elastic APM
```

**To Reproduce**
1. Create a file that returns APM.
2. Require the file, but don't call the start method.
3. Throw an error, it should be logged to the APM server.

**Expected behavior**
The agent should not start and a log `Elastic APM agent is inactive due to configuration` should appear during start up.

**Environment (please complete the following information)**
- OS: Alpine 3.4
- Node.js version: v6.11.0
- APM Server version: 🤷‍♂️ current cloud version
- Agent version: 1.8.2

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    "elastic-apm-node": "1.8.2",
    ```
  </details>

**Comment by watson** [comment]
Though the agent logs `logging error [...]`, it's actually not sending the error to the APM Server when it's not started. So you don't need to worry about that. This has been changed in version 2.x of the agent so that it now only logs this message in case it's actually sending the error.

You actually don't need to guard against calling `start()` as long as you have set the environment variable `ELASTIC_APM_ACTIVE=false`. The agent will automatically understand that the value of this environment variable should be parsed as a boolean and so it will not start the agent when it sees the string `"false"`.

**Comment by allanchau** [comment]
@watson Thanks, do you know why `Elastic APM agent is inactive due to configuration` isn't being logged though?

**Comment by watson** [comment]
It should. I've just tested it out with version 1.8.2 locally and I get the expected log message. Could it be because of your log level?

**Comment by watson** [comment]
@allanchau Did you get any time to look into this any further?

**Comment by allanchau** [comment]
@watson Hey sorry for the late reply. The log level is set to `debug`, but I've tried the other ones.
I've confirmed the environment variable is correctly set within the container too.

Are there any other variables that could be messing with the agent? `NODE_ENV=production|development` doesn't seem to make a difference either.

**Comment by watson** [comment]
If run your app with the environment variables `DEBUG=true ELASTIC_APM_LOG_LEVEL=debug`, it should output a lot of information in the beginning about how it the agent is configured. Do you mind posting that output here? (make sure to redact any sensitive information like the `secretToken` etc)

**Comment by watson** [comment]
FYI: In the new version of the agent this was simplified/changed so that you now just have to set `ELASTIC_APM_LOG_LEVEL=trace` in order to log the debug output that we need.

**Comment by watson** [comment]
Closing for now due to lack of activity. If it should be reopened, just leave a comment :)
