### ISSUE TITLE
Expose API to serialize the trace context

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#890]
Because of [this discussion](https://discuss.elastic.co/t/apm-trace-elastic-query/170472) I realized that we haven't exposed an API to serialize the trace context on the native agent (only on the OpenTracing bridge). We need that functionality.

**Comment by watson** [comment]
For inspiration, the OpenTracing API uses the concept of extract and inject for serialization and de-serialization respectively. The OT serialization looks like this:

```js
var clientSpan = ...;
...
// Inject clientSpan into a text carrier.
var headersCarrier = {}
Tracer.inject(clientSpan.context(), Tracer.FORMAT_HTTP_HEADERS, headersCarrier)
// Incorporate the textCarrier into the outbound HTTP request header map.
Object.assign(outboundHTTPReq.headers, headersCarrier)
// ... send the httpReq
```

And the de-serialization like this:

```js
// Use the inbound HTTP request's headers as a text map carrier.
var headersCarrier = inboundHTTPReq.headers
var wireCtx = Tracer.extract(Tracer.FORMAT_HTTP_HEADERS, headersCarrier)
var serverSpan = Tracer.startSpan('...', { childOf: wireCtx })
```

With respect to the HTTP format, this means that the user doesn't need to know about the name of the HTTP header. When it comes to a binary or just pure text format this doesn't have any particular benefit over just a simple function that returns or takes a string or buffer that contains the serialized trace context.

**Comment by balanza** [comment]
Strictly about serialisation, I'd implement it as a method in the `Transaction`'s prototype, let's name it `serialize()` for instance. Then I'd define a method in the agent, dealing with bad cases (ex: no `currentTransaction`) and gracefully returning `undefined`. Something like:

```
var wireCtx = agent.currentTransactionSerialized;
// or
var wireCtx = agent.traceContext;
```
Regarding the example provided, I agree it might be useful an interfaced similar to the one proposed by OpenTracing. Nevertheless, as APM already covers a lot of common-use modules and cases, I guess it would be on the User to develop its own `inject`/`extract` implementation, which would be based on the peculiar needs of the carrier being used. For that, the above proposal would still serve the purpose.

Or am I missing the point?
