### ISSUE TITLE
AWS Lambda Context Issue

### ISSUE THREAD

**Issue by blakeembrey** [elastic/apm-agent-nodejs#909]
**Describe the bug**

AWS Lambda APM copies `context` properties onto a new object. When using `context.callbackWaitsForEmptyEventLoop`, which is a setter function, it doesn't do anything on this object because it was copied as a regular boolean property.

**To Reproduce**

1. Create a lambda function that keeps the event loop open (e.g. a database connection)
2. Wrap in `apm.lambda()`
3. Try to set `context.callbackWaitsForEmptyEventLoop = false` and see the lambda function timeout

**Expected behavior**

**Environment (please complete the following information)**
- OS: AWS Lambda
- Node.js version: 8.x
- Agent version: 2.6.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

This combined with https://github.com/elastic/apm-nodejs-http-client/issues/46 made for a long day trying to integrate Elastic APM. Let me know if there's anything I can do to make a speedy bugfix! Happy to submit effective PRs - I believe this one should just be mutating `context.{success,fail}` directly.

**Comment by Qard** [comment]
Yeah, I'm thinking I agree here that just mutating the context might be the best route. I'll take a look at this soon. Just flying today. ✈️

**Comment by watson** [comment]
A fix for this just landed in master and will part of the next release

**Comment by watson** [comment]
This was just released in v2.7.0
