### ISSUE TITLE
Document missing captureError options

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#932]
The `options` that can be given to the `captureError` function are not all documented.

Currently only the following options are [documented](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-capture-error):

- `timestamp`
- `message`
- `user`
- `custom`

The following are not:

- `request`
- `response`
- `handled`
- `tags`

**Comment by jiangzm** [comment]
Why tags are not documented

**Comment by watson** [comment]
We just forgot
