### ISSUE TITLE
Transaction name is incorrect when request processing has an error exception

### ISSUE THREAD

**Issue by jiangzm** [elastic/apm-agent-nodejs#935]
**Describe the bug**
In the use of the express framework, the transaction default name is inaccurate when processing requests with exceptions, so what is seen in the kibana system is part of the real path or route.

**To Reproduce**
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**

**Environment (please complete the following information)**
- OS: macOS 10.14.3
- Node.js version: 10.15.3
- APM Server version: 6.6.2
- Agent version: ^2.6.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**
example code.
```javascript
const apm = require('elastic-apm-node').start({
  serviceName: "apm-log",
  serviceVersion: "1.0",
  serverUrl: 'http://localhost:8200'
})

const express = require('express')
const route = module.exports = new express.Router()

route.get('/orders/:id', function (req, res) {
  throw new Error("foo")
})
route.get('/products/:id', function (req, res) {
  res.send('bar')
})

const app = express()
app.use('/api', route)
```

When processing a request normally, the currentTransaction name is `“GET /api/products/:id”`.
When processing a request exception, the currentTransaction name is `“GET /products/:id”`.

**Comment by jiangzm** [comment]
[layer.js `#97`](https://github.com/expressjs/express/blob/master/lib/router/layer.js#L97) handler code in `express` fx:
```javascript
Layer.prototype.handle_request = function handle(req, res, next) {
  var fn = this.handle;

  if (fn.length > 3) {
    // not a standard request handler
    return next();
  }

  try {
    fn(req, res, next);
  } catch (err) {
    next(err);
  }
};
```
Executing this code  `'next(err)'` will pop the last executed route path.

[express.js`#50`](https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/express.js#L50) warp code in `apm-agent-nodejs`：
```javascript
if (!layer.route && layerPath && typeof next === 'function') {
    safePush(req, symbols.expressMountStack, layerPath)
    arguments[2] = function () {
        req[symbols.expressMountStack].pop()
        return next.apply(this, arguments)
    }
}
```

**Comment by watson** [comment]
Thanks for raising this issue and creating a PR to fix it ☺️
