### ISSUE TITLE
Don't publish Jenkinsfile to npm

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#941]
I just saw that we have a `Jenkinsfile` in the root of the repo which means that it's published together with the module to npm every time we release a new version. I somehow missed that when #801 was landed. This obviously wasn't the intention and there's two ways we can fix this:

1. Move it to the `test` directory
1. Add it to `.npmignore`

@kuisathaverat If possible I'd like to move it to the `test` directory to keep the root a little cleaner. Would this be possible? I assume somewhere this file is referenced and I need to update those references. Could you point me in the right direction?

**Comment by kuisathaverat** [comment]
the .travis.yml file is in the .npmignore, I do not like to move the Jenkinsfile to test folder, it is weird. On my pending tasks, there is one to unify the CI files structure for all projects, the candidate option it is to put all the CI stuff inside a folder named ".ci" on the root of the project.

If we move the location of the Jenkinsfile we'd have to update also the project in the infra repo, so we ha cannot change the location until this change is done. We can keep 2 copies of the Jenkinsfile meanwhile to not break the CI.

I prefer to move the Jenkinsfile to a ".ci" folder, but I can live with the other two options ;)

**Comment by watson** [comment]
Yeah I can see it looks a little inconsistent that I wanted to move `Jenkinsfile` to the test directory while we still have the `.travis.yml` file etc in the root. I guess it's just because `Jenkinsfile` isn't a dot-file, so it's more noisy.

I don't think it's weird to have it in the test directory though. It's only used for testing after all. We already have quite a few test scripts and Jenkins config files in there already. But having a custom `.ci` directory and moving everything Jenkins related in there would also be ok.

If we're going to do that, I'm ok with just adding it to `.npmignore` for now so we don't have to move it twice 👍
