### ISSUE TITLE
Logger is not initialized before usage

### ISSUE THREAD

**Issue by blakeembrey** [elastic/apm-agent-nodejs#955]
**Describe the bug**

When running in AWS Lambda with webpack, the dynamic requires are returning numbers. This, in turn, is causing an attempt to call `this._agent.logger`. Unfortunately, the logger is unavailable and this crashes the request.

**To Reproduce**

1. Webpack bundle a simple import, e.g. with https://github.com/zeit/ncc
2. Import APM agent
3. See crash

**Expected behavior**

Doesn't crash.

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Node.js version:
- APM Server version:
- Agent version:

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by blakeembrey** [comment]
![image](https://user-images.githubusercontent.com/1088987/55119774-6c1fcb80-50b0-11e9-8b9f-9679791a43db.png)

**Comment by blakeembrey** [comment]
Some easy fixes:

1. Avoid `require.resolve` here since it returns a number in webpack, use `require` directly
2. Avoid erroring on a number
3. Initialize the logger before instrumentation

**Comment by watson** [comment]
Oh, it's definitely an error on our part trying to use the logger before it's initialized - this should be fixed regardless of any Webpack issues. I hadn't considered how Webpack changes the `require` behavior and so we should probably make Webpack part of our test suite so this doesn't happen again.

We'll take a look at your PR's and see how we can best fix this - Thanks for taking the time to fix this 👍

**Comment by watson** [comment]
I found a reference to the number being returned by `require.resolve` in Webpack here:
https://webpack.js.org/api/module-methods/#requireresolve

![image](https://user-images.githubusercontent.com/10602/55143150-6e306b80-513e-11e9-9dfe-ff37ada40765.png)

**Comment by watson** [comment]
I did some early testing with the two PR's you made and it seems like while it stops complaining, it somehow doesn't instrument the application any more 🤔 It's most likely related to how we're patching the require function that just doesn't work with Webpack

**Comment by blakeembrey** [comment]
@watson Oh yeah, FWIW it has never worked for me. I’m 99% sure it’s because you try to read the `package.json` which won’t exist. This is purely so I can use the APM client again, I’m tracing everything manually.
