### ISSUE TITLE
Custom RITM Instrumentation

### ISSUE THREAD

**Issue by dvisztempacct** [elastic/apm-agent-nodejs#959]
**Is your feature request related to a problem? Please describe.**
Supporting abstract instrumentation capability for packages or use cases which are currently unsupported in mainline `apm-agent-nodejs`.

**Describe the solution you'd like**
I'd like access to the "dangerous" capability of hooking into the abstract instrumentation capability already implemented in `apm-agent-nodejs` on top of `require-in-the-middle`

**Describe alternatives you've considered**
One alternative I'd like to avoid is adding non-abstract instrumentation code (custom transactions and spans) to my services.

**Additional context**
We use `grpc-node` (see issue #300) which in the most general case IIUC poses some design hurdles (if/how to support streaming) that may understandably delay (perhaps indefinitely) support in mainline `apm-agent-nodejs`.

In practice, 99% of my RPCs hide the streaming/callback interface of `grpc-node` and provide a Promise-returning interface instead, which is a type of interface that ought to be straightforward to wrap for APM.

One of the biggest selling points for any performance instrumentation solution IMHO is abstraction and decoupling: I really don't want to see the code in my service or ask others to maintain the code to support it. I also believe that more monitoring capabilities will allow us to anticipate problems but conversely more code = more problems.

Thanks in advance for any feedback on this issue!

**Comment by watson** [comment]
I think you're in luck, we just released version 2.7.0 of the agent with a new API to add custom instrumentations. See the [`agent.addPatch()`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-add-patch) api documentation for details.

Would that do what you're looking for?

**Comment by dvisztempacct** [comment]
@watson Yes this will do very nicely! This also solves the problem of obtaining a reference to the agent, which was another issue I had with custom instrumentation code!

Issue closed!
