### ISSUE TITLE
Change DEBUG=true to logLevel: 'trace'

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#961]
To output the agent config today, you have to both set the config `logLevel: 'debug'` (or `'trace'`) and the environment variable `DEBUG=true`. It would be easier if you just had to set `logLevel: 'trace'`.

The reason why we went with the `DEBUG` environment variable originally was that it was easy to detect, so that [the entire code block](https://github.com/elastic/apm-agent-nodejs/blob/e1026382d8c6987137c00ffda83eb4e1acf292e6/lib/agent.js#L138-L161) could be skipped if it wasn't needed. But it's just too complicated of an API. Instead the if-statement should just check if `logLevel === 'trace'`

**Comment by curtisjohnson1** [comment]
Hi - I'll pick this one up
