### ISSUE TITLE
The "test/agent.js" test is taking longer to complete than expected

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#964]
After the last test have finished running, the test just hangs and waits for something to happen before it finally exists a short while later. It means that we're probably not cleaning up something that we should be cleaning up.

**Comment by watson** [comment]
jenkins, run tests please

**Comment by trentm** [comment]
I don't have a reference, but I believe we fixed this a while back.

```
% time node test/agent.test.js
...
node test/agent.test.js  0.72s user 0.10s system 27% cpu 2.937 total
```

There is no hang/delay on completion now.
