### ISSUE TITLE
Instrument the @elastic/elasticsearch module

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#968]
The new Elasticsearch client has been moved to the `@elastic` npm namespace, so its name is now `@elastic/elasticsearch`.

This is a complete rewrite of the client and I therefore assume the old instrumentation code doesn't work with it. So this is essentially a new instrumentation.

**Comment by gingerwizard** [comment]
Kibana has now been instrumented using the node APM agent. Currently, Kibana uses a mixture of the old and new ES client but is migrating to this new `@elastic/elasticsearch` module.

The ES performance team are looking to use Kibana's instrumentation data to capture the requests made to Elasticsearch - see https://github.com/elastic/rally-internal-tracks/issues/21. Without this auto-instrumentation, we will need to instrument Kibana ourselves as the _search and _async_search endpoints (the primary ones of interest) are already using this new client.
