### ISSUE TITLE
Integrating with Kafka-Node and similar Kafka clients

### ISSUE THREAD

**Issue by boriskogan81** [elastic/apm-agent-nodejs#979]
Part of our system relies on Kafka for message queues. I would like to be able to continue tracing transactions as they pass through Kafka via various producers and consumers, creating spans along the way. We are setting up kafka-node, which is a fairly common package, like this:

```
const kafka = require('kafka-node'),
    HighLevelProducer = kafka.HighLevelProducer,
    ConsumerGroup = kafka.ConsumerGroup,
    client = new kafka.KafkaClient({kafkaHost: kafkaConfig.kafkaHost}),
    producer = new HighLevelProducer(client),
    consumer = new ConsumerGroup(
        {
            kafkaHost: kafkaConfig.kafkaHost,
            groupId: kafkaConfig.groupId,
            fromOffset: 'earliest',
        },
        'os-events-raw'
    ),
    appEventsConsumer = new ConsumerGroup(
        {
            kafkaHost: kafkaConfig.kafkaHost,
            groupId: kafkaConfig.groupId,
            fromOffset: 'earliest',
        },
        'app-events'
    ),
    osEventsConsumer = new ConsumerGroup(
        {
            kafkaHost: kafkaConfig.kafkaHost,
            groupId: kafkaConfig.groupId,
            fromOffset: 'earliest',
        },
        'os-events'
    ),
    smcEventsConsumer = new ConsumerGroup(
        {
            kafkaHost: kafkaConfig.kafkaHost,
            groupId: kafkaConfig.groupId,
            fromOffset: 'earliest',
        },
        'smc-events'
    );
```
events get handled like this:
```
consumer.on('message', (kafkaMessage) => {
    let message =null;
    try {
        message = JSON.parse(kafkaMessage.value);
    } catch (e) {
        logger.error('failure parsing kafka message',{e,message})
        return;
    }
    if (!message) {
        logger.error('message is empty',{kafkaMessage})
        return;
    }

    let eventTransform = rawOsEventTransform(message);
    if (!eventTransform) {
        logger.error('XML parse error',{message})
        return;
    }

    producer.send([{
        topic: 'os-events',
        messages: [eventTransform]
    }], (err, data) => {
        if (err) {
            logger.error('kafka error', {err});
        }
    });
});
```

So, as you can see, a typical case is a consumer taking messages from a topic, transforming them and producing them to another topic. 

If there is an example of how we can log this using the APM agent, then great. If not, I'd like to be able to do so.

**Comment by Qard** [comment]
So there's two parts to this:

- Transaction linking is required between the two services, so you will need to pass along the traceparent header. This can be injected into HTTP headers, or it can be passed along in another way as long as you have a way to retrieve it on the other end. There's a PR open now to make that available publicly here: https://github.com/elastic/apm-agent-nodejs/pull/969
- The job processor will need to use the custom transactions interface to manually create a transaction when that message handler starts. See: https://www.elastic.co/guide/en/apm/agent/nodejs/1.x/custom-transactions.html

**Comment by boriskogan81** [comment]
Do I understand correctly that until the first part is complete (meaning, the APM is updated,) I can't do the second part?

Could you maybe show me an example of starting a transaction on an HTTP route (Express or similar,) continuing it in a produced Kafka message, then in a received Kafka message?

**Comment by Qard** [comment]
You _can_ do it now, but using a private API that may change in the future, so you'll want to switch to the official API as soon as that is available.

```js
const context = (agent.currentSpan || agent.currentTransaction || {})._context
const traceparent = context && context.toString()
```

Then pass along the `traceparent` value with your job data. On the other end, just start a new transaction somewhere like this:

```js
const trans = apm.startTransaction(name, type, traceparent)
// do some stuff
trans.end()
```

**Comment by boriskogan81** [comment]
Sorry, but is a transaction not started with the original span?

Meaning, I understood that for instance I have a front end app that hits an HTTP backend with a request. This starts a transaction. The backend sends a message to Kafka. A producer reads the message, continues the transaction with a new span, sends an HTTP request to another service which continues the transaction with yet another span, etc. 

No?

**Comment by Qard** [comment]
Oh, yes. Forgot we changed that recently. 😅 

Anyway, a "transaction" is local to the service. A "trace" is the thing that spans across services, and that is stitched together automatically out of transactions that are created with those `traceparent` links. You will need to create a transaction in your job processor to enable capturing of spans within the lifetime and asynchronous call-graph of that transaction.

**Comment by watson** [comment]
FYI: The API for getting the `traceparent` is now public and has just landed in v2.9.0:

3 new getters have been added from which you can get the `traceparent` string:

- `agent.currentTraceparent`
- `span.traceparent`
- `transaction.traceparent`

**Comment by boriskogan81** [comment]
NICE.

Webstorm isn't recognizing agent.currentTraceparent, but let's push it and see what it does.

**Comment by watson** [comment]
Oh, that's probably because we didn't update the TypeScript `.d.ts` file. That's a mistake. I'll make sure to fix it ASAP. Thanks for letting us know

**Comment by watson** [comment]
I've created a PR to update the types: #1001

**Comment by watson** [comment]
@boriskogan81 we just released v2.10.0 which should fix your Webstorm issues

**Comment by boriskogan81** [comment]
Thanks.

Sincerely,

Baruch

**Comment by watson** [comment]
@boriskogan81 Did this solve your question?

**Comment by boriskogan81** [comment]
Yes, thank you!

Sincerely,

Baruch
