### ISSUE TITLE
Distributed Trace Coverage in Custom Transactions Documentation

### ISSUE THREAD

**Issue by dvisztempacct** [elastic/apm-agent-nodejs#991]
The docs for custom transactions don't cover distributed tracing.

https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-transactions.html

This is perhaps already covered by one of the checkboxes in closed issue  elastic/apm-agent-nodejs#421

**Comment by watson** [comment]
Good point. As you know, we're missing an important part of the public API to allow for this to be used easily in user-land: #969 - We'll merge that in this week and that should allow us to properly make good documentation for it.

Thanks again for raising this issue 😃

**Comment by watson** [comment]
FYI: The `traceparent` API is now public and released in v2.9.0, so you can call `agent.currentTraceparent` (or `span.traceparent` or `transaction.traceparent`) to get the `traceparent` string

**Comment by watson** [comment]
I think this issue is still relevant... there are some things that we could document better, especially in the custom transactions section as you said. I'll open this again so we don't forget.

**Comment by bmorelli25** [comment]
A distributed tracing guide, including RUM correlation and custom DT via the Agent's API was added in https://github.com/elastic/apm-agent-nodejs/pull/1650. Here's a [link to the docs](https://www.elastic.co/guide/en/apm/agent/nodejs/current/distributed-tracing.html).
